"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import Icon from "../Icon";
import AppDialog from "../AppDialog";
const tok=()=>localStorage.getItem("marbo3a_token")||sessionStorage.getItem("marbo3a_token")||"";
async function api(path,options={}){const t=tok(),headers={...(options.headers||{}),...(t?{authorization:`Bearer ${t}`}:{})};if(options.body)headers["content-type"]="application/json";const r=await fetch(path,{...options,headers,credentials:"same-origin",cache:"no-store"}),d=await r.json().catch(()=>({}));if(r.status===401){window.dispatchEvent(new CustomEvent("marbo3a:session-revoked",{detail:{reason:"unauthorized"}}));throw new Error("UNAUTHORIZED")}if(!r.ok)throw new Error(d.error||"REQUEST_FAILED");return d}
const actionLabel=a=>({resolve:"حل البلاغ",dismiss:"رفض البلاغ",warn:"تنبيه المستخدم",freeze:"تجميد الحساب",ban:"حظر الحساب",remove_content:"إزالة المحتوى"}[a]||a);
const human=e=>({ADMIN_ONLY:"هذه الصفحة للأدمن فقط",UNAUTHORIZED:"انتهت جلسة الدخول",SELF_ROLE_CHANGE_FORBIDDEN:"ما تقدرش تغير صلاحيتك من نفس الجلسة",LAST_ADMIN:"لا يمكن إزالة آخر أدمن",CANNOT_MODERATE_ADMIN:"لا يمكن تطبيق الإجراء على أدمن",REPORT_TARGET_HAS_NO_USER:"البلاغ هذا مش مربوط بحساب يمكن معاقبته",ROLE_CHANGE_FAILED:"تعذر تغيير الصلاحية",MODERATION_ACTION_FAILED:"تعذر تطبيق إجراء الإشراف"}[e]||e||"تعذر تنفيذ الطلب");
export default function AdminCenter(){const[tab,setTab]=useState("overview"),[stats,setStats]=useState(null),[users,setUsers]=useState([]),[rooms,setRooms]=useState([]),[reports,setReports]=useState([]),[broadcasts,setBroadcasts]=useState([]),[logs,setLogs]=useState([]),[moderation,setModeration]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[q,setQ]=useState(""),[dialog,setDialog]=useState(null),[reason,setReason]=useState("");const[broadcast,setBroadcast]=useState({message:"",kind:"info",durationMs:5000,persistSeconds:0,sound:false,actionLabel:"",actionUrl:""});
 const cards=useMemo(()=>stats?[["متصلون الآن",stats.onlineUsers],["الزوار الآن",stats.onlineVisitors],["زوار اليوم",stats.visitorsToday],["المسجلون",stats.registeredUsers],["نشطون 24س",stats.activeUsers24h],["جدد اليوم",stats.newUsersToday],["الغرف",stats.rooms],["غرف نشطة",stats.activeRooms24h],["الرسائل",stats.messages],["أخطاء اليوم",stats.errorsToday],["مجمّدون",stats.frozen],["محظورون",stats.banned]]:[],[stats]);
 async function loadStats(){setStats((await api("/api/admin/stats")).stats)}async function loadUsers(){setUsers((await api(`/api/admin/users?q=${encodeURIComponent(q.trim())}`)).users||[])}async function loadRooms(){setRooms((await api("/api/admin/rooms")).rooms||[])}async function loadReports(){setReports((await api("/api/admin/reports")).reports||[])}async function loadBroadcasts(){setBroadcasts((await api("/api/admin/broadcasts")).broadcasts||[])}async function loadLogs(){const p=new URLSearchParams({limit:"120"});if(q.trim())p.set("q",q.trim());setLogs((await api(`/api/admin/logs?${p}`)).logs||[])}async function loadModeration(){setModeration((await api("/api/admin/moderation/actions")).actions||[])}
 async function refresh(){setBusy(true);setError("");try{await loadStats();if(tab==="users")await loadUsers();if(tab==="rooms")await loadRooms();if(tab==="reports")await loadReports();if(tab==="broadcast")await loadBroadcasts();if(tab==="logs")await loadLogs();if(tab==="moderation")await loadModeration()}catch(e){setError(human(e.message))}finally{setBusy(false)}}
 useEffect(()=>{if(!tok()){location.replace("/");return}refresh()},[tab]);
 function askUser(user,status){setReason("");setDialog({kind:"user",user,status})}async function applyUser(){const{user,status}=dialog;try{await api(`/api/admin/users/${user.id}/status`,{method:"PATCH",body:JSON.stringify({status,reason})});setDialog(null);await Promise.all([loadUsers(),loadStats()])}catch(e){setError(human(e.message))}}
 function askRole(user){setDialog({kind:"role",user,role:user.role||"user"})}async function applyRole(){try{await api(`/api/admin/users/${dialog.user.id}/role`,{method:"PATCH",body:JSON.stringify({role:dialog.role})});setDialog(null);await loadUsers()}catch(e){setError(human(e.message))}}
 async function deleteRoom(){try{await api(`/api/admin/rooms/${dialog.room.id}`,{method:"DELETE"});setDialog(null);await Promise.all([loadRooms(),loadStats()])}catch(e){setError(human(e.message))}}
 function askReport(report,action){setReason("");setDialog({kind:"report",report,action})}async function applyReport(){try{await api(`/api/admin/reports/${dialog.report.id}/action`,{method:"POST",body:JSON.stringify({action:dialog.action,reason})});setDialog(null);setReason("");await Promise.all([loadReports(),loadStats(),loadModeration().catch(()=>{})])}catch(e){setError(human(e.message))}}
 async function sendBroadcast(e){e.preventDefault();if(!broadcast.message.trim())return;setBusy(true);try{await api("/api/admin/broadcasts",{method:"POST",body:JSON.stringify(broadcast)});setBroadcast(v=>({...v,message:"",actionLabel:"",actionUrl:""}));await loadBroadcasts()}catch(e){setError(human(e.message))}finally{setBusy(false)}}
 return <main className="debug-admin-page admin-route-page" dir="rtl"><header><div><small>ADMIN CENTER</small><h1>مركز إدارة مربوعة</h1><p>الحسابات والغرف والبلاغات والبث والمراقبة من مكان واحد.</p></div><Link href="/home">الرجوع لمربوعة</Link></header><nav className="admin-tabs" aria-label="أقسام الإدارة">{[["overview","الرئيسية"],["users","الحسابات"],["rooms","الغرف"],["reports","البلاغات"],["moderation","الإجراءات"],["broadcast","البث"],["logs","Audit"]].map(([k,l])=><button key={k} className={tab===k?"active":""} onClick={()=>{setQ("");setTab(k)}}>{l}</button>)}</nav>{error&&<div className="debug-error" role="alert">{error}</div>}{busy&&<div className="admin-note" aria-live="polite">جاري تحديث البيانات...</div>}
 {tab==="overview"&&<><section className="debug-summary admin-route-stats">{cards.map(([l,v])=><div key={l}><b>{Number(v||0).toLocaleString("en-US")}</b><span>{l}</span></div>)}</section><section className="admin-route-actions"><Link href="/admin/debug"><Icon name="settings"/><b>الديباق</b><span>جلسات التشخيص والأخطاء</span></Link><Link href="/admin/readiness"><Icon name="check"/><b>الجاهزية</b><span>فحص V1 والخدمات</span></Link><Link href="/admin/system"><Icon name="settings"/><b>النظام</b><span>حالة البنية والخدمات</span></Link></section></>}
 {tab==="users"&&<><div className="admin-toolbar users-toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="اسم، بريد أو @username"/><button onClick={loadUsers}>بحث</button></div><div className="admin-user-list">{users.map(u=><article className="admin-user-card" key={u.id}><div className="admin-user-main"><div className="admin-user-avatar">{u.display_name?.[0]||"م"}</div><div><b>{u.display_name}</b><span>@{u.username} • {u.email}</span><small>{u.last_seen_at?`آخر ظهور ${new Date(u.last_seen_at).toLocaleString("ar-LY")}`:"لا يوجد نشاط مسجل"}</small></div></div><div className="admin-user-actions"><span className={`status-pill ${u.account_status}`}>{u.role==="admin"?"ADMIN":u.role==="moderator"?"MODERATOR":u.account_status}</span><button onClick={()=>askRole(u)}>الصلاحية</button>{u.role!=="admin"&&<><button onClick={()=>askUser(u,"active")}>تفعيل</button><button className="warn" onClick={()=>askUser(u,"frozen")}>تجميد</button><button className="danger" onClick={()=>askUser(u,"banned")}>حظر</button></>}</div></article>)}</div></>}
 {tab==="rooms"&&<div className="admin-room-list">{rooms.map(r=><article key={r.id}><div><b>{r.name}</b><span>{r.members_count||0} عضو • {r.owner_username?`@${r.owner_username}`:"النظام"}</span><small>{r.description}</small></div><button className="danger" onClick={()=>setDialog({kind:"room",room:r})}>حذف الغرفة</button></article>)}</div>}
 {tab==="reports"&&<div className="feature-list">{reports.map(r=><article key={r.id}><b>بلاغ #{r.id} • {r.reason}</b><span>المبلغ: @{r.reporter_username||"unknown"} • {r.target_type} #{r.target_id}</span><p>{r.details}</p><small>{new Date(r.created_at).toLocaleString("ar-LY")} • {r.status}{r.resolution_action?` • ${actionLabel(r.resolution_action)}`:""}</small>{r.resolution_note&&<p className="admin-note">{r.resolution_note}</p>}{r.status==="open"&&<div className="feature-actions"><button onClick={()=>askReport(r,"resolve")}>حل</button><button onClick={()=>askReport(r,"warn")}>تنبيه</button><button className="warn" onClick={()=>askReport(r,"freeze")}>تجميد</button><button className="danger" onClick={()=>askReport(r,"ban")}>حظر</button>{["post","comment","message","direct_message","room"].includes(r.target_type)&&<button className="danger" onClick={()=>askReport(r,"remove_content")}>إزالة المحتوى</button>}<button onClick={()=>askReport(r,"dismiss")}>رفض البلاغ</button></div>}</article>)}{!reports.length&&<article>ما فيش بلاغات.</article>}</div>}
 {tab==="moderation"&&<div className="admin-log-list">{moderation.map(m=><article className="admin-log" key={m.id}><div className="admin-log-top"><span>{actionLabel(m.action)}</span><b>{m.target_type} #{m.target_id}</b><time>{new Date(m.created_at).toLocaleString("ar-LY")}</time></div><strong>{m.reason||"بدون ملاحظة"}</strong><div className="admin-log-meta"><span>بواسطة @{m.admin_username||"admin"}</span>{m.report_id&&<span>بلاغ #{m.report_id}</span>}</div></article>)}{!moderation.length&&<article className="admin-note">ما فيش إجراءات إشراف مسجلة حتى الآن.</article>}</div>}
 {tab==="broadcast"&&<><form className="broadcast-form" onSubmit={sendBroadcast}><label>الرسالة<textarea value={broadcast.message} onChange={e=>setBroadcast(v=>({...v,message:e.target.value}))} maxLength={500} required/></label><div className="broadcast-grid"><label>النوع<select value={broadcast.kind} onChange={e=>setBroadcast(v=>({...v,kind:e.target.value}))}><option value="info">معلومة</option><option value="normal">عادية</option><option value="alert">تنبيه</option><option value="warning">تحذير</option><option value="announcement">إعلان</option></select></label><label>مدة الظهور<select value={broadcast.durationMs} onChange={e=>setBroadcast(v=>({...v,durationMs:Number(e.target.value)}))}><option value="3000">3 ثوان</option><option value="5000">5 ثوان</option><option value="10000">10 ثوان</option><option value="30000">30 ثانية</option></select></label><label>يبقى للقادمين<select value={broadcast.persistSeconds} onChange={e=>setBroadcast(v=>({...v,persistSeconds:Number(e.target.value)}))}><option value="0">لا</option><option value="300">5 دقائق</option><option value="1800">30 دقيقة</option><option value="3600">ساعة</option></select></label></div><label className="check-row"><input type="checkbox" checked={broadcast.sound} onChange={e=>setBroadcast(v=>({...v,sound:e.target.checked}))}/> صوت خفيف</label><div className="broadcast-grid"><label>نص زر اختياري<input value={broadcast.actionLabel} onChange={e=>setBroadcast(v=>({...v,actionLabel:e.target.value}))}/></label><label>الرابط اختياري<input value={broadcast.actionUrl} onChange={e=>setBroadcast(v=>({...v,actionUrl:e.target.value}))}/></label></div><button disabled={busy}>إرسال للجميع</button></form><div className="admin-log-list">{broadcasts.slice(0,20).map(b=><article className="admin-log" key={b.id}><div className="admin-log-top"><span>{b.kind}</span><time>{new Date(b.created_at).toLocaleString("ar-LY")}</time></div><strong>{b.message}</strong><div className="admin-log-meta"><span>وصول مباشر {b.delivered_count||0}</span></div></article>)}</div></>}
 {tab==="logs"&&<><div className="admin-toolbar users-toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="بحث في السجل"/><button onClick={loadLogs}>بحث</button></div><div className="admin-log-list">{logs.map(l=><article className={`admin-log ${String(l.level||"").toLowerCase()}`} key={l.id}><div className="admin-log-top"><span>{l.level}</span><b>{l.category}</b><time>{new Date(l.created_at).toLocaleString("ar-LY")}</time></div><strong>{l.action}</strong><div className="admin-log-meta">{l.username&&<span>@{l.username}</span>}{l.status_code&&<span>HTTP {l.status_code}</span>}</div></article>)}</div></>}
 {dialog?.kind==="user"&&<AppDialog open title={dialog.status==="active"?"تفعيل الحساب":dialog.status==="banned"?"حظر الحساب":"تجميد الحساب"} description={`@${dialog.user.username}`} danger={dialog.status!=="active"} confirmLabel="تأكيد" onClose={()=>setDialog(null)} onConfirm={applyUser}><textarea className="dialog-textarea" value={reason} onChange={e=>setReason(e.target.value)} maxLength={300} placeholder="السبب (اختياري)"/></AppDialog>}
 {dialog?.kind==="role"&&<AppDialog open title="تغيير صلاحية الحساب" description={`@${dialog.user.username}`} confirmLabel="حفظ الصلاحية" onClose={()=>setDialog(null)} onConfirm={applyRole}><label className="dialog-field">الصلاحية<select value={dialog.role} onChange={e=>setDialog(x=>({...x,role:e.target.value}))}><option value="user">مستخدم</option><option value="moderator">مشرف</option><option value="admin">أدمن</option></select></label></AppDialog>}
 {dialog?.kind==="report"&&<AppDialog open title={actionLabel(dialog.action)} description={`بلاغ #${dialog.report.id} • ${dialog.report.target_type} #${dialog.report.target_id}`} danger={["freeze","ban","remove_content"].includes(dialog.action)} confirmLabel="تنفيذ الإجراء" onClose={()=>setDialog(null)} onConfirm={applyReport}><textarea className="dialog-textarea" value={reason} onChange={e=>setReason(e.target.value)} maxLength={500} placeholder="سبب القرار / ملاحظة للإجراء"/></AppDialog>}
 {dialog?.kind==="room"&&<AppDialog open danger title="حذف الغرفة؟" description={`سيتم حذف «${dialog.room.name}» ورسائلها.`} confirmLabel="حذف نهائي" onClose={()=>setDialog(null)} onConfirm={deleteRoom}/>}</main>}
