"use client";
import {useEffect,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import Icon from "../../Icon";
import {liveApi,liveErrorText} from "../live-api";

export default function NewLivePage(){
 const router=useRouter(),videoRef=useRef(null),streamRef=useRef(null),pcs=useRef(new Map()),signalSince=useRef(0),pollRef=useRef(null),signalRef=useRef(null),heartbeatRef=useRef(null),[live,setLive]=useState(null),[title,setTitle]=useState(""),[status,setStatus]=useState(""),[starting,setStarting]=useState(false),[viewers,setViewers]=useState([]),[messages,setMessages]=useState([]),[message,setMessage]=useState(""),[cameraOn,setCameraOn]=useState(true),[micOn,setMicOn]=useState(true),[facing,setFacing]=useState("user");
 function stopMedia(){for(const pc of pcs.current.values())try{pc.close()}catch{}pcs.current.clear();for(const tr of streamRef.current?.getTracks?.()||[])try{tr.stop()}catch{}streamRef.current=null}
 async function openMedia(mode=facing){stopMedia();const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:mode}},audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});streamRef.current=s;if(videoRef.current)videoRef.current.srcObject=s;setCameraOn(true);setMicOn(true);return s}
 useEffect(()=>()=>{clearInterval(pollRef.current);clearInterval(signalRef.current);clearInterval(heartbeatRef.current);stopMedia()},[]);
 async function sendSignal(recipientId,kind,payload){if(!live)return;try{await liveApi(`/api/live/${live.id}/signals`,{method:"POST",body:JSON.stringify({recipientId,kind,payload})})}catch(e){if(e.message!=="VIEWER_GONE")setStatus(liveErrorText(e))}}
 async function ensurePeer(viewer){if(!live||pcs.current.has(Number(viewer.user_id)))return;const id=Number(viewer.user_id),pc=new RTCPeerConnection({iceServers:live.iceServers||[]});pcs.current.set(id,pc);for(const track of streamRef.current?.getTracks?.()||[])pc.addTrack(track,streamRef.current);pc.onicecandidate=e=>e.candidate&&sendSignal(id,"ice",e.candidate.toJSON());pc.onconnectionstatechange=()=>{if(["failed","closed","disconnected"].includes(pc.connectionState)&&!viewers.some(v=>Number(v.user_id)===id)){try{pc.close()}catch{}pcs.current.delete(id)}};try{const offer=await pc.createOffer();await pc.setLocalDescription(offer);await sendSignal(id,"offer",pc.localDescription)}catch{try{pc.close()}catch{}pcs.current.delete(id)}}
 async function pollViewers(){if(!live)return;try{const d=await liveApi(`/api/live/${live.id}/viewers`),next=d.viewers||[];setViewers(next);const active=new Set(next.map(v=>Number(v.user_id)));for(const [id,pc] of pcs.current){if(!active.has(Number(id))){try{pc.close()}catch{}pcs.current.delete(id)}}for(const v of next)await ensurePeer(v)}catch(e){if(e.status===410)return endLive(false);setStatus(liveErrorText(e))}}
 async function pollSignals(){if(!live)return;try{const d=await liveApi(`/api/live/${live.id}/signals?since=${signalSince.current}`);for(const s of d.signals||[]){signalSince.current=Math.max(signalSince.current,Number(s.id)||0);const pc=pcs.current.get(Number(s.sender_id));if(!pc)continue;if(s.kind==="answer"){if(pc.signalingState!=="closed")await pc.setRemoteDescription(s.payload)}else if(s.kind==="ice"){try{await pc.addIceCandidate(s.payload)}catch{}}}}catch(e){if(e.status===410)return;setStatus(liveErrorText(e))}}
 async function pollMeta(){if(!live)return;try{const d=await liveApi(`/api/live/${live.id}`);setMessages(d.messages||[])}catch{}}
 async function start(){if(starting||live)return;setStarting(true);setStatus("بنفتحوا الكاميرا...");try{await openMedia();const d=await liveApi("/api/live",{method:"POST",body:JSON.stringify({title:title.trim()})});const enriched={...d.live,iceServers:(await liveApi(`/api/live/${d.live.id}`)).iceServers||[]};setLive(enriched);setStatus("أنت لايف توا 🔴");setTimeout(()=>{pollRef.current=setInterval(()=>{pollViewers();pollMeta()},1600);signalRef.current=setInterval(pollSignals,700);heartbeatRef.current=setInterval(()=>liveApi(`/api/live/${enriched.id}/heartbeat`,{method:"POST"}).catch(()=>{}),7000)},200)}catch(e){stopMedia();setStatus(e?.name==="NotAllowedError"?"لازم تسمح للكاميرا والمايك باش تفتح لايف.":liveErrorText(e))}finally{setStarting(false)}}
 async function endLive(goBack=true){clearInterval(pollRef.current);clearInterval(signalRef.current);clearInterval(heartbeatRef.current);if(live)try{await liveApi(`/api/live/${live.id}/end`,{method:"POST"})}catch{}stopMedia();setLive(null);setViewers([]);setStatus("اللايف تسكّر، والفيديو ما تخزّنش.");if(goBack)setTimeout(()=>router.push("/live"),500)}
 function toggleTrack(kind){const track=streamRef.current?.getTracks?.().find(t=>t.kind===kind);if(!track)return;track.enabled=!track.enabled;if(kind==="video")setCameraOn(track.enabled);else setMicOn(track.enabled)}
 async function flip(){if(!live)return;const next=facing==="user"?"environment":"user";setFacing(next);try{const old=streamRef.current,oldVideo=old?.getVideoTracks?.()[0];const temp=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:next}},audio:false}),newVideo=temp.getVideoTracks()[0];for(const pc of pcs.current.values()){const sender=pc.getSenders().find(x=>x.track?.kind==="video");if(sender)await sender.replaceTrack(newVideo)}if(oldVideo)oldVideo.stop();if(old){const audio=old.getAudioTracks()[0];streamRef.current=new MediaStream([newVideo,...(audio?[audio]:[])]);if(videoRef.current)videoRef.current.srcObject=streamRef.current}setCameraOn(true)}catch{setStatus("ما قدرناش نقلبوا الكاميرا توا")}}
 async function sendMessage(e){e.preventDefault();if(!live||!message.trim())return;try{await liveApi(`/api/live/${live.id}/messages`,{method:"POST",body:JSON.stringify({body:message.trim()})});setMessage("");await pollMeta()}catch(e){setStatus(liveErrorText(e))}}
 async function react(emoji){if(!live)return;try{await liveApi(`/api/live/${live.id}/reactions`,{method:"POST",body:JSON.stringify({reaction:emoji})})}catch{}}
 return <main className="live-studio-page" dir="rtl"><section className="live-studio"><div className="live-video-stage"><video ref={videoRef} autoPlay muted playsInline className={facing==="user"?"mirror":""}/>{live?<><div className="live-studio-top"><b><i/> LIVE</b><span><Icon name="users"/>{viewers.length}</span></div><div className="live-floating-reactions">{["❤️","🔥","👏","😂","👍"].map(x=><button type="button" key={x} onClick={()=>react(x)}>{x}</button>)}</div></>:<div className="live-prep"><Icon name="video"/><h1>افتح لايف</h1><p>الكاميرا والصوت يطلعوا للناس مباشرة، ومجرد ما تسكّر اللايف الفيديو ما يتخزّنش.</p><input value={title} onChange={e=>setTitle(e.target.value)} maxLength={90} placeholder="شن عنوان اللايف؟"/><button disabled={starting} type="button" onClick={start}>{starting?"لحظة...":"ابدأ لايف"}</button></div>}</div>{live&&<aside className="live-studio-chat"><header><div><b>{live.title}</b><small>{viewers.length} يتفرجوا توا</small></div><button type="button" onClick={()=>endLive(true)}>إنهاء</button></header><div className="live-chat-stream">{messages.map(m=><p key={m.id}><b>{m.display_name||m.username}</b><span>{m.body}</span></p>)}</div><form onSubmit={sendMessage}><input value={message} onChange={e=>setMessage(e.target.value)} maxLength={500} placeholder="اكتب في الشات..."/><button aria-label="ابعث"><Icon name="send"/></button></form></aside>} {live&&<div className="live-studio-controls"><button type="button" className={!micOn?"off":""} onClick={()=>toggleTrack("audio")}><Icon name="mic"/><span>{micOn?"المايك":"مقفول"}</span></button><button type="button" className={!cameraOn?"off":""} onClick={()=>toggleTrack("video")}><Icon name="video"/><span>{cameraOn?"الكاميرا":"مقفولة"}</span></button><button type="button" onClick={flip}><Icon name="refresh"/><span>اقلب</span></button><button type="button" className="end" onClick={()=>endLive(true)}><Icon name="close"/><span>سكّر</span></button></div>}{status&&<div className="live-studio-status">{status}</div>}</section></main>
}
