"use client";
import {useEffect,useState} from "react";
import Icon from "../Icon";
import MediaGallery from "../MediaGallery";
import PublicRoomRail from "../PublicRoomRail";
import {fetchJson} from "../request";
import "./guest-explore.css";

async function publicApi(path,options={}){return fetchJson(path,{...options,cache:"no-store",credentials:"same-origin"},10000)}
const media=p=>Array.isArray(p?.media)&&p.media.length?p.media:(p?.image_url?[{url:p.image_url,type:"image"}]:[]);
const compact=n=>{const v=Math.max(0,Number(n)||0);return v>=1_000_000?`${(v/1_000_000).toFixed(v>=10_000_000?0:1)}م`:v>=10_000?`${(v/1_000).toFixed(v>=100_000?0:1)}ألف`:v.toLocaleString("ar-LY")};
const features=[["image","منشورات عامة","آخر المنشورات العامة من مجتمع مربوعة"],["video","اللايفات","شوف شن صاير مباشر توا داخل مربوعة"],["hash","غرف وصوت مباشر","ادخل الغرف العامة كزائر واسمع الصوت"],["users","أصحاب ومجتمع","اكتشف الحسابات العامة والناس الموجودين"],["message","رسائل وتفاعل","التسجيل يفتح لك الرسائل والتعليقات والتفاعل"],["map","خريطة مربوعة","بعد التسجيل تقدر تستعمل مزايا الموقع والخصوصية"],["video","تلفزيون مربوعة","التلفزيون متاح للحسابات المسجلة داخل مربوعة"]];

export default function ExplorePage(){
 const[posts,setPosts]=useState([]),[stats,setStats]=useState(null),[audience,setAudience]=useState({totalVisitors:0,onlineNow:0,trackingStartedAt:null}),[lives,setLives]=useState([]),[guest,setGuest]=useState(null),[next,setNext]=useState(null),[feedSeed,setFeedSeed]=useState(null),[loading,setLoading]=useState(true),[more,setMore]=useState(false),[error,setError]=useState(""),[gate,setGate]=useState("");
 async function ensureGuest(){try{const d=await publicApi("/api/public/guest/session",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({path:"/explore"})});setGuest(d.guest||null)}catch{}}
 async function loadAudience(){try{const d=await publicApi("/api/public/site-stats");if(d?.ok)setAudience({totalVisitors:Number(d.totalVisitors||0),onlineNow:Number(d.onlineNow||0),trackingStartedAt:d.trackingStartedAt||null})}catch{}}
 async function loadLives(){try{const d=await publicApi("/api/public/live");setLives(d.lives||[])}catch{setLives([])}}
 async function load(cursor=0,{quiet=false}={}){if(cursor)setMore(true);else if(!quiet)setLoading(true);try{const seedPart=feedSeed?`&seed=${feedSeed}`:"",d=await publicApi(`/api/public/feed?limit=15${cursor?`&cursor=${cursor}`:""}${seedPart}`);if(d.seed&&!feedSeed)setFeedSeed(d.seed);setPosts(p=>cursor?[...p,...(d.posts||[])]:d.posts||[]);setNext(d.nextCursor||null);if(!cursor){const s=await publicApi("/api/public/stats").catch(()=>({stats:null}));setStats(s.stats||null)}setError("")}catch(e){if(!quiet)setError(e?.message==="REQUEST_TIMEOUT"?"الاتصال تأخر شوية. اضغط وجرب مرة ثانية.":"تعذر تحميل محتوى مربوعة الآن")}finally{setLoading(false);setMore(false)}}
 useEffect(()=>{ensureGuest();load();loadAudience();loadLives();const refresh=()=>{if(document.visibilityState!=="visible")return;loadAudience();loadLives();load(0,{quiet:true})};const timer=setInterval(refresh,12000),visible=()=>document.visibilityState==="visible"&&refresh();document.addEventListener("visibilitychange",visible);publicApi("/api/public/guest/activity",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type:"pageview",path:"/explore",source:"guest_explore"})}).catch(()=>{});return()=>{clearInterval(timer);document.removeEventListener("visibilitychange",visible)}},[]);
 function requireAccount(action){setGate(action);try{sessionStorage.setItem("marbo3a_return_to","/home")}catch{}publicApi("/api/public/guest/activity",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type:"register_prompt",path:"/explore",source:action})}).catch(()=>{})}
 return <main className="guest-explore-page guest-live-sync" dir="rtl"><header className="guest-explore-header"><a href="/explore" className="guest-brand"><img src="/brand/official/marbo3a-mark.png" alt=""/><span><b>مربوعة</b><small>{guest?.label||"تصفح كزائر"}</small></span></a><div className="guest-audience-stats" aria-label="إحصائيات مربوعة"><span><Icon name="users"/><b>{compact(audience.totalVisitors)}</b><small>زائر مسجل</small></span><span><i/><b>{compact(audience.onlineNow)}</b><small>متصل</small></span></div><div><a href="/?next=%2Fhome" className="guest-login">دخول</a><a href="/?next=%2Fhome#register" className="guest-register">سجل الآن</a></div></header><section className="guest-explore-hero"><div><small>شن صاير توا في مربوعة</small><h1>تصفح مربوعة وهي حية، مش نسخة قديمة</h1><p>المنشورات، اللايفات، الغرف والنشاط يتحدثوا تلقائيًا. لما تبي تشارك أو تراسل أو تدخل مزايا خاصة، وقتها سجل.</p></div><Icon name="sparkles"/></section>
 <section className="guest-now-strip"><div><span className="guest-now-dot"/><b>{compact(audience.onlineNow)}</b><small>متصل توا</small></div><div><Icon name="video"/><b>{lives.length}</b><small>لايف شغال</small></div><div><Icon name="hash"/><b>{Number(stats?.publicRooms||0)}</b><small>غرفة عامة</small></div><button type="button" onClick={()=>load(0)}><Icon name="refresh"/> تحديث</button></section>
 {lives.length>0&&<section className="guest-live-section"><header className="guest-section-title"><small>مباشر توا</small><h2>لايفات شغالة في مربوعة</h2></header><div className="guest-live-track">{lives.map(l=><article key={l.id}><span className="guest-live-avatar">{l.avatar_url?<img src={l.avatar_url} alt=""/>:<b>{String(l.display_name||"م")[0]}</b>}<i>LIVE</i></span><div><b>{l.title||`${l.display_name} لايف توا`}</b><small>{l.display_name} · {Number(l.viewers_count||0)} يتفرجوا</small></div><button type="button" onClick={()=>requireAccount("مشاهدة اللايف")}>شوف اللايف</button></article>)}</div></section>}
 {stats&&<section className="guest-public-stats"><div><b>{Number(stats.users||0).toLocaleString("en-US")}</b><small>حساب نشط</small></div><div><b>{Number(stats.posts||0).toLocaleString("en-US")}</b><small>منشور</small></div><div><b>{Number(stats.publicRooms||0).toLocaleString("en-US")}</b><small>غرفة عامة</small></div></section>}
 <PublicRoomRail guestOnly title="الغرف العامة الشغالة"/><section className="guest-feature-overview"><header><small>واجهة مربوعة الحالية</small><h2>شن تقدر تشوف وتكتشف</h2></header><div>{features.map(([icon,title,body])=><article key={title}><span><Icon name={icon}/></span><b>{title}</b><p>{body}</p></article>)}</div></section><section className="guest-feed"><header className="guest-section-title"><small>يتحدث تلقائيًا</small><h2>آخر المنشورات العامة</h2></header>{error&&<button type="button" className="guest-error" onClick={()=>load()}>{error} — إعادة المحاولة</button>}{loading&&<div className="guest-loading">جاري تحميل مربوعة...</div>}{posts.map(p=><article className={`guest-post ${p.sponsored?"guest-post-sponsored":""}`} key={`${p.sponsored?"s":"p"}-${p.sponsored_id||p.id}`}>{p.sponsored&&<div className="sponsored-ribbon"><Icon name="sparkles" size={14}/><b>{p.sponsored_label||"مموّل"}</b><span>إعلان داخل مربوعة</span></div>}<header><a href={`/u/${p.username}`} className="guest-post-user">{p.avatar_url?<img src={p.avatar_url} alt=""/>:<span>{p.display_name?.[0]||"م"}</span>}<div><b>{p.display_name}</b><small><bdi dir="ltr">@{p.username}</bdi> · {new Date(p.created_at).toLocaleDateString("ar-LY")}</small></div></a></header>{p.body&&<p className="guest-post-body">{p.body}</p>}{p.location_label&&<div className="guest-post-location"><Icon name="map"/>{p.location_label}</div>}<MediaGallery items={media(p)} alt="وسائط المنشور"/><div className="guest-post-stats"><span>{p.likes_count||0} تفاعل</span><span>{p.comments_count||0} تعليق</span></div><div className="guest-post-actions"><button onClick={()=>requireAccount("الإعجاب بالمنشور")}><Icon name="heart"/> إعجاب</button><button onClick={()=>requireAccount("التعليق على المنشور")}><Icon name="message"/> تعليق</button><button onClick={()=>requireAccount("التفاعل داخل مربوعة")}><Icon name="share"/> مشاركة</button></div></article>)}{!loading&&!posts.length&&!error&&<div className="guest-empty"><Icon name="sparkles"/><h2>ما فيش منشورات عامة توا</h2></div>}{next&&<button className="guest-more" disabled={more} onClick={()=>load(next)}>{more?"جاري التحميل...":"منشورات أكثر"}</button>}</section><aside className="guest-join-banner"><div><b>تبي تشارك بدل المشاهدة؟</b><small>الحساب يفتح لك الرسائل والتفاعل واللايف والتلفزيون.</small></div><a href="/?next=%2Fhome#register">سجل الآن</a></aside>{gate&&<div className="guest-gate-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setGate("")}><section className="guest-gate" role="dialog" aria-modal="true"><div className="guest-gate-icon"><Icon name="lock"/></div><h2>شارك في مربوعة</h2><p>باش تقدر على {gate} لازم يكون عندك حساب. التصفح العام يبقى متاح بدون تسجيل.</p><a className="primary" href="/?next=%2Fhome#register">سجل الآن</a><a href="/?next=%2Fhome">عندي حساب</a><button onClick={()=>setGate("")}>كمل كزائر</button></section></div>}</main>}
