import {pool,requireAuth,clean,emitUser,redis} from "../runtime.mjs";

const REACTIONS=new Set(["like","love","laugh","wow","sad","angry"]);
const REACTION_TEXT={like:"إعجاب",love:"أحببت",laugh:"أضحكني",wow:"واو",sad:"أحزنني",angry:"أغضبني"};

const validId=v=>Number.isSafeInteger(Number(v))&&Number(v)>0;
const seedOf=v=>{const n=Number(v);return Number.isFinite(n)?Math.abs(Math.trunc(n))%2147483000:Math.floor(Math.random()*2147483000)};
async function friends(a,b){return Boolean((await pool.query(`SELECT 1 FROM friendships WHERE status='accepted' AND ((requester_id=$1 AND addressee_id=$2) OR (requester_id=$2 AND addressee_id=$1)) LIMIT 1`,[a,b])).rows[0])}
async function blocked(a,b){return Boolean((await pool.query(`SELECT 1 FROM user_blocks WHERE (blocker_id=$1 AND blocked_id=$2) OR (blocker_id=$2 AND blocked_id=$1) LIMIT 1`,[a,b])).rows[0])}
async function mutual(a,b){return Number((await pool.query(`WITH a1 AS(SELECT CASE WHEN requester_id=$1 THEN addressee_id ELSE requester_id END id FROM friendships WHERE status='accepted' AND(requester_id=$1 OR addressee_id=$1)),b1 AS(SELECT CASE WHEN requester_id=$2 THEN addressee_id ELSE requester_id END id FROM friendships WHERE status='accepted' AND(requester_id=$2 OR addressee_id=$2))SELECT COUNT(*)::int n FROM a1 JOIN b1 USING(id)`,[a,b])).rows[0]?.n||0)}
async function allowed(rule,viewer,target){if(String(viewer)===String(target)||rule==="everyone")return true;if(rule==="nobody")return false;if(await friends(viewer,target))return true;return rule==="friends_of_friends"&&(await mutual(viewer,target))>0}
async function relation(viewer,target){if(String(viewer)===String(target))return"self";const r=(await pool.query(`SELECT requester_id,status FROM friendships WHERE ((requester_id=$1 AND addressee_id=$2) OR (requester_id=$2 AND addressee_id=$1)) ORDER BY id DESC LIMIT 1`,[viewer,target])).rows[0];if(!r)return"none";if(r.status==="accepted")return"friend";if(r.status==="pending")return String(r.requester_id)===String(viewer)?"outgoing":"incoming";return"none"}
const postSql=`SELECT p.id,p.body,p.image_url,p.location_label,p.created_at,p.updated_at,u.id user_id,u.username,u.display_name,u.gender,u.avatar_url,COALESCE(pp.who_can_see_posts,'everyone') privacy_rule,(SELECT COUNT(*)::int FROM post_likes l WHERE l.post_id=p.id) likes_count,(SELECT COUNT(*)::int FROM post_comments c WHERE c.post_id=p.id AND c.deleted_at IS NULL) comments_count,EXISTS(SELECT 1 FROM post_likes ml WHERE ml.post_id=p.id AND ml.user_id=$1) liked,COALESCE((SELECT jsonb_agg(jsonb_build_object('url',pm.url,'type',pm.media_type,'position',pm.position) ORDER BY pm.position,pm.id) FROM post_media pm WHERE pm.post_id=p.id),CASE WHEN p.image_url IS NOT NULL AND p.image_url<>'' THEN jsonb_build_array(jsonb_build_object('url',p.image_url,'type','image','position',0)) ELSE '[]'::jsonb END) media FROM posts p JOIN users u ON u.id=p.user_id LEFT JOIN profile_privacy pp ON pp.user_id=u.id WHERE p.deleted_at IS NULL`;
async function filterVisible(rows,viewer){const out=[];for(const row of rows){if(await allowed(row.privacy_rule,viewer,row.user_id)){delete row.privacy_rule;row.relation=await relation(viewer,row.user_id);out.push(row)}}return out}

async function notify(userId,actor,type,title,body,refId){if(!userId||Number(userId)===Number(actor?.id))return;try{const row=(await pool.query(`INSERT INTO notifications(user_id,actor_id,type,title,body,ref_id) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,user_id,actor_id,type,title,body,ref_id,read_at,created_at`,[userId,actor?.id||null,type,title,body||"",refId||null])).rows[0];emitUser(userId,"notification:new",{...row,actor_username:actor?.username||null,actor_name:actor?.display_name||null,actor_avatar:actor?.avatar_url||null})}catch{}}

function reactionSummary(rows){const out={like:0,love:0,laugh:0,wow:0,sad:0,angry:0};for(const r of rows||[])if(out[r.reaction]!==undefined)out[r.reaction]+=Number(r.count||1);return out}

async function rankedFeed(viewerId,{seed,offset=0,limit=15,publicOnly=false}={}){
  const take=Math.min(120,Math.max(limit*6,30));
  const params=publicOnly?[seed,offset,take]:[viewerId,seed,offset,take];
  const viewerExpr=publicOnly?"NULL::bigint":"$1::bigint";
  const seedExpr=publicOnly?"$1::int":"$2::int";
  const offsetExpr=publicOnly?"$2::int":"$3::int";
  const takeExpr=publicOnly?"$3::int":"$4::int";
  const privacyWhere=publicOnly?`AND COALESCE(pp.who_can_see_posts,'everyone')='everyone'`:"";
  const blockWhere=publicOnly?"":`AND NOT EXISTS(SELECT 1 FROM user_blocks b WHERE (b.blocker_id=$1 AND b.blocked_id=p.user_id) OR (b.blocked_id=$1 AND b.blocker_id=p.user_id))`;
  const friendshipScore=publicOnly?"0":`CASE WHEN p.user_id=$1 THEN 26 WHEN EXISTS(SELECT 1 FROM friendships f WHERE f.status='accepted' AND ((f.requester_id=$1 AND f.addressee_id=p.user_id) OR (f.addressee_id=$1 AND f.requester_id=p.user_id))) THEN 16 ELSE 0 END`;
  const sql=`SELECT p.id,p.body,p.image_url,p.location_label,p.created_at,p.updated_at,u.id user_id,u.username,u.display_name,u.gender,u.avatar_url,
    COALESCE(pp.who_can_see_posts,'everyone') privacy_rule,
    (SELECT COUNT(*)::int FROM post_reactions r WHERE r.post_id=p.id) likes_count,
    (SELECT COUNT(*)::int FROM post_comments c WHERE c.post_id=p.id AND c.deleted_at IS NULL) comments_count,
    ${publicOnly?"FALSE":`EXISTS(SELECT 1 FROM post_reactions mr WHERE mr.post_id=p.id AND mr.user_id=${viewerExpr})`} liked,
    ${publicOnly?"NULL::text":`(SELECT reaction FROM post_reactions mr WHERE mr.post_id=p.id AND mr.user_id=${viewerExpr} LIMIT 1)`} my_reaction,
    COALESCE((SELECT jsonb_object_agg(q.reaction,q.n) FROM (SELECT reaction,COUNT(*)::int n FROM post_reactions r WHERE r.post_id=p.id GROUP BY reaction) q),'{}'::jsonb) reaction_summary,
    COALESCE((SELECT jsonb_agg(jsonb_build_object('url',pm.url,'type',pm.media_type,'position',pm.position) ORDER BY pm.position,pm.id) FROM post_media pm WHERE pm.post_id=p.id),CASE WHEN p.image_url IS NOT NULL AND p.image_url<>'' THEN jsonb_build_array(jsonb_build_object('url',p.image_url,'type','image','position',0)) ELSE '[]'::jsonb END) media,
    ((${friendshipScore}) +
      (SELECT COUNT(*) FROM post_reactions r WHERE r.post_id=p.id)*3.0 +
      (SELECT COUNT(*) FROM post_comments c WHERE c.post_id=p.id AND c.deleted_at IS NULL)*4.0 +
      GREATEST(0,120-(EXTRACT(EPOCH FROM (NOW()-p.created_at))/3600))*0.13 +
      (((hashtext(p.id::text||':'||${seedExpr}::text)::bigint+2147483648)%1000)/1000.0)*6.0
    )::numeric rank_score
  FROM posts p JOIN users u ON u.id=p.user_id LEFT JOIN profile_privacy pp ON pp.user_id=p.user_id
  WHERE p.deleted_at IS NULL AND u.account_status='active' ${privacyWhere} ${blockWhere}
    AND NOT EXISTS(SELECT 1 FROM sponsored_posts sp WHERE sp.post_id=p.id AND sp.active=TRUE AND (sp.starts_at IS NULL OR sp.starts_at<=NOW()) AND (sp.ends_at IS NULL OR sp.ends_at>NOW()))
  ORDER BY rank_score DESC,p.id DESC OFFSET ${offsetExpr} LIMIT ${takeExpr}`;
  const candidates=(await pool.query(sql,params)).rows;
  const selected=[];let consumed=0;
  for(let i=0;i<candidates.length&&selected.length<limit;i++){
    const row=candidates[i];consumed=i+1;
    if(publicOnly||await allowed(row.privacy_rule,viewerId,row.user_id)){
      delete row.privacy_rule;row.relation=publicOnly?"none":await relation(viewerId,row.user_id);row.sponsored=false;selected.push(row);
    }
  }
  return{posts:selected,nextOffset:candidates.length===take&&consumed?offset+consumed:null};
}

async function sponsoredFeed(viewerId,{seed,limit=4,publicOnly=false}={}){
  const params=publicOnly?[seed,limit]:[viewerId,seed,limit];
  const viewerExpr=publicOnly?"NULL::bigint":"$1::bigint",seedExpr=publicOnly?"$1::int":"$2::int",limitExpr=publicOnly?"$2::int":"$3::int";
  const privacyWhere=publicOnly?`AND COALESCE(pp.who_can_see_posts,'everyone')='everyone'`:"";
  const blockWhere=publicOnly?"":`AND NOT EXISTS(SELECT 1 FROM user_blocks b WHERE (b.blocker_id=$1 AND b.blocked_id=p.user_id) OR (b.blocked_id=$1 AND b.blocker_id=p.user_id))`;
  const rows=(await pool.query(`SELECT sp.id sponsored_id,sp.label sponsored_label,sp.destination_url,sp.cta_label,p.id,p.body,p.image_url,p.location_label,p.created_at,p.updated_at,u.id user_id,u.username,u.display_name,u.gender,u.avatar_url,COALESCE(pp.who_can_see_posts,'everyone') privacy_rule,
    (SELECT COUNT(*)::int FROM post_reactions r WHERE r.post_id=p.id) likes_count,
    (SELECT COUNT(*)::int FROM post_comments c WHERE c.post_id=p.id AND c.deleted_at IS NULL) comments_count,
    ${publicOnly?"FALSE":`EXISTS(SELECT 1 FROM post_reactions mr WHERE mr.post_id=p.id AND mr.user_id=${viewerExpr})`} liked,
    ${publicOnly?"NULL::text":`(SELECT reaction FROM post_reactions mr WHERE mr.post_id=p.id AND mr.user_id=${viewerExpr} LIMIT 1)`} my_reaction,
    COALESCE((SELECT jsonb_object_agg(q.reaction,q.n) FROM (SELECT reaction,COUNT(*)::int n FROM post_reactions r WHERE r.post_id=p.id GROUP BY reaction) q),'{}'::jsonb) reaction_summary,
    COALESCE((SELECT jsonb_agg(jsonb_build_object('url',pm.url,'type',pm.media_type,'position',pm.position) ORDER BY pm.position,pm.id) FROM post_media pm WHERE pm.post_id=p.id),CASE WHEN p.image_url IS NOT NULL AND p.image_url<>'' THEN jsonb_build_array(jsonb_build_object('url',p.image_url,'type','image','position',0)) ELSE '[]'::jsonb END) media
  FROM sponsored_posts sp JOIN posts p ON p.id=sp.post_id JOIN users u ON u.id=p.user_id LEFT JOIN profile_privacy pp ON pp.user_id=p.user_id
  WHERE sp.active=TRUE AND p.deleted_at IS NULL AND u.account_status='active' AND (sp.starts_at IS NULL OR sp.starts_at<=NOW()) AND (sp.ends_at IS NULL OR sp.ends_at>NOW()) ${privacyWhere} ${blockWhere}
  ORDER BY sp.weight DESC,((hashtext(sp.id::text||':'||${seedExpr}::text)::bigint+2147483648)%1000) DESC LIMIT ${limitExpr}` ,params)).rows;
  const out=[];for(const row of rows){if(publicOnly||await allowed(row.privacy_rule,viewerId,row.user_id)){delete row.privacy_rule;row.relation=publicOnly?"none":await relation(viewerId,row.user_id);row.sponsored=true;out.push(row)}}return out;
}
function interleaveSponsored(organic,ads){if(!ads.length)return organic;const out=[];let ai=0;for(let i=0;i<organic.length;i++){out.push(organic[i]);if((i+1)%4===0&&ai<ads.length)out.push(ads[ai++])}return out}

async function commentRows(postId,viewerId){
  const rows=(await pool.query(`SELECT c.id,c.post_id,c.user_id,c.parent_comment_id,c.body,c.created_at,c.edited_at,c.edited_at AS updated_at,u.username,u.display_name,u.gender,u.avatar_url,
    COALESCE((SELECT jsonb_object_agg(q.reaction,q.n) FROM (SELECT reaction,COUNT(*)::int n FROM comment_reactions r WHERE r.comment_id=c.id GROUP BY reaction) q),'{}'::jsonb) reaction_summary,
    (SELECT reaction FROM comment_reactions r WHERE r.comment_id=c.id AND r.user_id=$2 LIMIT 1) my_reaction,
    (SELECT COUNT(*)::int FROM comment_reactions r WHERE r.comment_id=c.id) reactions_count
  FROM post_comments c JOIN users u ON u.id=c.user_id WHERE c.post_id=$1 AND c.deleted_at IS NULL ORDER BY c.id ASC LIMIT 500`,[postId,viewerId])).rows;
  const roots=[],map=new Map();for(const row of rows){row.replies=[];map.set(Number(row.id),row)}for(const row of rows){if(row.parent_comment_id&&map.has(Number(row.parent_comment_id)))map.get(Number(row.parent_comment_id)).replies.push(row);else roots.push(row)}return roots;
}
async function commentById(commentId,viewerId){return(await pool.query(`SELECT c.id,c.post_id,c.user_id,c.parent_comment_id,c.body,c.created_at,c.edited_at,c.edited_at AS updated_at,u.username,u.display_name,u.gender,u.avatar_url,'{}'::jsonb reaction_summary,NULL::text my_reaction,0::int reactions_count FROM post_comments c JOIN users u ON u.id=c.user_id WHERE c.id=$1 AND c.deleted_at IS NULL`,[commentId])).rows[0]||null}

export function registerCoreFeed(app){
    app.get("/api/feed",async(req,res)=>{try{const u=await requireAuth(req,res);if(!u)return;const limit=Math.min(30,Math.max(5,Number(req.query.limit)||15)),offset=Math.max(0,Number(req.query.cursor)||0),seed=seedOf(req.query.seed);const organic=await rankedFeed(u.id,{seed,offset,limit}),ads=await sponsoredFeed(u.id,{seed,limit:Math.ceil(limit/4)});res.json({ok:true,posts:interleaveSponsored(organic.posts,ads),nextCursor:organic.nextOffset,seed,ranking:"smart-v1"})}catch(e){console.error("R1 smart feed",e);res.status(500).json({ok:false,error:"FEED_LOAD_FAILED"})}});
    app.get("/api/public/feed",async(req,res)=>{try{const limit=Math.min(30,Math.max(5,Number(req.query.limit)||15)),offset=Math.max(0,Number(req.query.cursor)||0),seed=seedOf(req.query.seed);const organic=await rankedFeed(null,{seed,offset,limit,publicOnly:true}),ads=await sponsoredFeed(null,{seed,limit:Math.ceil(limit/4),publicOnly:true});res.json({ok:true,posts:interleaveSponsored(organic.posts,ads),nextCursor:organic.nextOffset,seed,ranking:"smart-v1"})}catch(e){console.error("R1 public smart feed",e);res.status(500).json({ok:false,error:"PUBLIC_FEED_FAILED"})}});

    app.get("/api/feed/:id/reactions",async(req,res)=>{try{const u=await requireAuth(req,res);if(!u)return;const postId=Number(req.params.id);if(!validId(postId))return res.status(400).json({ok:false,error:"INVALID_POST"});const rows=(await pool.query(`SELECT r.user_id,r.reaction,r.updated_at,x.username,x.display_name,x.gender,x.avatar_url FROM post_reactions r JOIN users x ON x.id=r.user_id WHERE r.post_id=$1 ORDER BY r.updated_at DESC LIMIT 500`,[postId])).rows,summary=reactionSummary(rows);res.json({ok:true,total:rows.length,summary,myReaction:rows.find(x=>Number(x.user_id)===Number(u.id))?.reaction||null,reactions:rows})}catch(e){res.status(500).json({ok:false,error:"REACTIONS_LOAD_FAILED"})}});
    app.put("/api/feed/:id/reaction",async(req,res)=>{try{const u=await requireAuth(req,res);if(!u)return;const postId=Number(req.params.id),reaction=req.body?.reaction==null?null:String(req.body.reaction);if(!validId(postId))return res.status(400).json({ok:false,error:"INVALID_POST"});if(reaction&&!REACTIONS.has(reaction))return res.status(400).json({ok:false,error:"INVALID_REACTION"});const post=(await pool.query(`SELECT id,user_id FROM posts WHERE id=$1 AND deleted_at IS NULL`,[postId])).rows[0];if(!post)return res.status(404).json({ok:false,error:"POST_NOT_FOUND"});if(reaction){await pool.query(`INSERT INTO post_reactions(post_id,user_id,reaction) VALUES($1,$2,$3) ON CONFLICT(post_id,user_id) DO UPDATE SET reaction=EXCLUDED.reaction,updated_at=NOW()`,[postId,u.id,reaction]);await pool.query(`INSERT INTO post_likes(post_id,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING`,[postId,u.id]);await pool.query(`DELETE FROM notifications WHERE user_id=$1 AND actor_id=$2 AND type='post_reaction' AND ref_id=$3`,[post.user_id,u.id,postId]).catch(()=>{});await notify(post.user_id,u,"post_reaction",`${u.display_name||u.username} ${REACTION_TEXT[reaction]} منشورك`,REACTION_TEXT[reaction],postId)}else{await pool.query(`DELETE FROM post_reactions WHERE post_id=$1 AND user_id=$2`,[postId,u.id]);await pool.query(`DELETE FROM post_likes WHERE post_id=$1 AND user_id=$2`,[postId,u.id]);await pool.query(`DELETE FROM notifications WHERE user_id=$1 AND actor_id=$2 AND type='post_reaction' AND ref_id=$3`,[post.user_id,u.id,postId]).catch(()=>{})}const rows=(await pool.query(`SELECT reaction,COUNT(*)::int count FROM post_reactions WHERE post_id=$1 GROUP BY reaction`,[postId])).rows,summary=reactionSummary(rows);res.json({ok:true,reaction,total:Object.values(summary).reduce((a,b)=>a+b,0),summary})}catch(e){console.error("R1 post reaction",e);res.status(500).json({ok:false,error:"REACTION_FAILED"})}});

    app.get("/api/feed/:id/comments",async(req,res)=>{try{const u=await requireAuth(req,res);if(!u)return;const postId=Number(req.params.id);if(!validId(postId))return res.status(400).json({ok:false,error:"INVALID_POST"});res.json({ok:true,comments:await commentRows(postId,u.id)})}catch(e){console.error("R1 comments",e);res.status(500).json({ok:false,error:"COMMENTS_LOAD_FAILED"})}});
    app.get("/api/feed/:id/comments/preview",async(req,res)=>{try{const u=await requireAuth(req,res);if(!u)return;const postId=Number(req.params.id);if(!validId(postId))return res.status(400).json({ok:false,error:"INVALID_POST"});const roots=await commentRows(postId,u.id);res.json({ok:true,comments:roots.slice(-2)})}catch(e){res.status(500).json({ok:false,error:"COMMENTS_LOAD_FAILED"})}});
    app.post("/api/feed/:id/comments",async(req,res)=>{try{const u=await requireAuth(req,res);if(!u)return;const postId=Number(req.params.id),body=clean(req.body?.body,1000),parentId=req.body?.parentCommentId==null?null:Number(req.body.parentCommentId);if(!validId(postId))return res.status(400).json({ok:false,error:"INVALID_POST"});if(!body)return res.status(400).json({ok:false,error:"EMPTY_COMMENT"});const post=(await pool.query(`SELECT id,user_id FROM posts WHERE id=$1 AND deleted_at IS NULL`,[postId])).rows[0];if(!post)return res.status(404).json({ok:false,error:"POST_NOT_FOUND"});let parent=null;if(parentId){parent=(await pool.query(`SELECT id,user_id,parent_comment_id FROM post_comments WHERE id=$1 AND post_id=$2 AND deleted_at IS NULL`,[parentId,postId])).rows[0];if(!parent)return res.status(404).json({ok:false,error:"PARENT_COMMENT_NOT_FOUND"});if(parent.parent_comment_id)return res.status(400).json({ok:false,error:"REPLY_DEPTH_LIMIT"})}const row=(await pool.query(`INSERT INTO post_comments(post_id,user_id,parent_comment_id,body) VALUES($1,$2,$3,$4) RETURNING id`,[postId,u.id,parent?.id||null,body])).rows[0],comment=await commentById(row.id,u.id);await notify(parent?.user_id||post.user_id,u,parent?"comment_reply":"post_comment",parent?`${u.display_name||u.username} رد على تعليقك`:`${u.display_name||u.username} علّق على منشورك`,body.slice(0,120),postId);res.status(201).json({ok:true,comment})}catch(e){console.error("R1 comment create",e);res.status(500).json({ok:false,error:"COMMENT_CREATE_FAILED"})}});
    app.get("/api/feed/:postId/comments/:commentId/reactions",async(req,res)=>{try{const u=await requireAuth(req,res);if(!u)return;const cid=Number(req.params.commentId);if(!validId(cid))return res.status(400).json({ok:false,error:"INVALID_COMMENT"});const rows=(await pool.query(`SELECT r.user_id,r.reaction,r.updated_at,u.username,u.display_name,u.gender,u.avatar_url FROM comment_reactions r JOIN users u ON u.id=r.user_id WHERE r.comment_id=$1 ORDER BY r.updated_at DESC LIMIT 500`,[cid])).rows,summary=reactionSummary(rows);res.json({ok:true,total:rows.length,summary,myReaction:rows.find(x=>Number(x.user_id)===Number(u.id))?.reaction||null,reactions:rows})}catch(e){res.status(500).json({ok:false,error:"COMMENT_REACTIONS_LOAD_FAILED"})}});
    app.put("/api/feed/:postId/comments/:commentId/reaction",async(req,res)=>{try{const u=await requireAuth(req,res);if(!u)return;const postId=Number(req.params.postId),cid=Number(req.params.commentId),reaction=req.body?.reaction==null?null:String(req.body.reaction);if(!validId(postId)||!validId(cid))return res.status(400).json({ok:false,error:"INVALID_COMMENT"});if(reaction&&!REACTIONS.has(reaction))return res.status(400).json({ok:false,error:"INVALID_REACTION"});const c=(await pool.query(`SELECT id,user_id FROM post_comments WHERE id=$1 AND post_id=$2 AND deleted_at IS NULL`,[cid,postId])).rows[0];if(!c)return res.status(404).json({ok:false,error:"COMMENT_NOT_FOUND"});if(reaction){await pool.query(`INSERT INTO comment_reactions(comment_id,user_id,reaction) VALUES($1,$2,$3) ON CONFLICT(comment_id,user_id) DO UPDATE SET reaction=EXCLUDED.reaction,updated_at=NOW()`,[cid,u.id,reaction]);await notify(c.user_id,u,"comment_reaction",`${u.display_name||u.username} تفاعل مع تعليقك`,REACTION_TEXT[reaction],postId)}else await pool.query(`DELETE FROM comment_reactions WHERE comment_id=$1 AND user_id=$2`,[cid,u.id]);const rows=(await pool.query(`SELECT reaction,COUNT(*)::int count FROM comment_reactions WHERE comment_id=$1 GROUP BY reaction`,[cid])).rows,summary=reactionSummary(rows);res.json({ok:true,reaction,total:Object.values(summary).reduce((a,b)=>a+b,0),summary})}catch(e){res.status(500).json({ok:false,error:"COMMENT_REACTION_FAILED"})}});
app.get("/api/social/profile/:username",async(req,res)=>{try{const viewer=await requireAuth(req,res);if(!viewer)return;const uname=clean(req.params.username,24).toLowerCase(),p=(await pool.query(`SELECT u.id,u.username,u.display_name,u.gender,u.bio,u.avatar_url,u.cover_url,u.last_seen_at,u.created_at,u.birth_date,u.pinned_post_id,l.city,COALESCE(pp.show_last_seen,TRUE) show_last_seen,COALESCE(pp.show_city,TRUE) show_city,COALESCE(pp.show_online,TRUE) show_online,COALESCE(pp.birth_visibility,'age') birth_visibility,COALESCE(pp.who_can_message,'friends') who_can_message,COALESCE(pp.who_can_see_posts,'everyone') who_can_see_posts,COALESCE(pp.who_can_see_friends,'friends') who_can_see_friends FROM users u LEFT JOIN user_locations l ON l.user_id=u.id LEFT JOIN profile_privacy pp ON pp.user_id=u.id WHERE LOWER(u.username)=$1 AND u.account_status='active'`,[uname])).rows[0];if(!p)return res.status(404).json({ok:false,error:"USER_NOT_FOUND"});if(String(viewer.id)!==String(p.id)&&await blocked(viewer.id,p.id))return res.status(404).json({ok:false,error:"USER_NOT_FOUND"});const rel=await relation(viewer.id,p.id),canPosts=await allowed(p.who_can_see_posts,viewer.id,p.id),canFriends=await allowed(p.who_can_see_friends,viewer.id,p.id),canMessage=await allowed(p.who_can_message,viewer.id,p.id),friendCount=canFriends?Number((await pool.query(`SELECT COUNT(*)::int c FROM friendships WHERE status='accepted' AND(requester_id=$1 OR addressee_id=$1)`,[p.id])).rows[0].c):null,postCount=canPosts?Number((await pool.query(`SELECT COUNT(*)::int c FROM posts WHERE user_id=$1 AND deleted_at IS NULL`,[p.id])).rows[0].c):0,online=p.show_online?Boolean(await redis.zScore("presence:users",String(p.id)).then(s=>s&&Number(s)>Date.now()-120000).catch(()=>false)):false;let posts=[];if(canPosts){const rows=(await pool.query(`${postSql} AND p.user_id=$2 ORDER BY p.id DESC LIMIT 30`,[viewer.id,p.id])).rows;posts=await filterVisible(rows,viewer.id)}res.json({ok:true,profile:{...p,last_seen_at:p.show_last_seen?p.last_seen_at:null,city:p.show_city?p.city:null,birth_date:undefined,friends_count:friendCount,posts_count:postCount,relation:rel,can_message:canMessage,online},posts})}catch(e){console.error("FGH regression profile",e);res.status(500).json({ok:false,error:"PROFILE_LOAD_FAILED"})}});
}
