import crypto from "crypto";
import {pool,requireAuth,isAdmin,clean} from "../runtime.mjs";

const VISIBILITIES=new Set(["public","friends","private"]);
const JOIN_POLICIES=new Set(["open","request","invite"]);

export function registerCoreRooms(app){
  app.get("/api/rooms",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const q=clean(req.query.q||"",80),admin=isAdmin(u);const rows=(await pool.query(`SELECT r.id,r.name,r.slug,r.description,r.is_public,r.visibility,r.join_policy,r.owner_id,owner.gender owner_gender,r.created_at,EXISTS(SELECT 1 FROM room_members rm WHERE rm.room_id=r.id AND rm.user_id=$1) joined,(SELECT COUNT(*)::int FROM room_members x WHERE x.room_id=r.id) members_count FROM rooms r LEFT JOIN users owner ON owner.id=r.owner_id WHERE ($3::boolean OR r.visibility='public' OR EXISTS(SELECT 1 FROM room_members my WHERE my.room_id=r.id AND my.user_id=$1) OR (r.visibility='friends' AND EXISTS(SELECT 1 FROM friendships f WHERE f.status='accepted' AND ((f.requester_id=$1 AND f.addressee_id=r.owner_id) OR (f.addressee_id=$1 AND f.requester_id=r.owner_id)))) ) AND($2='' OR r.name ILIKE '%'||$2||'%' OR r.description ILIKE '%'||$2||'%') ORDER BY members_count DESC,r.id ASC LIMIT 100`,[u.id,q,admin])).rows;res.json({ok:true,rooms:rows})});
  app.post("/api/rooms",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const name=clean(req.body?.name,60),description=clean(req.body?.description,180),visibility=VISIBILITIES.has(req.body?.visibility)?req.body.visibility:"public",joinPolicy=JOIN_POLICIES.has(req.body?.joinPolicy)?req.body.joinPolicy:(visibility==="private"?"invite":"open");if(name.length<3)return res.status(400).json({ok:false,error:"INVALID_ROOM_NAME"});const slug=`${name.toLowerCase().replace(/[^a-z0-9\u0600-\u06ff]+/g,"-").replace(/^-|-$/g,"").slice(0,45)||"room"}-${crypto.randomBytes(3).toString("hex")}`;const client=await pool.connect();try{await client.query("BEGIN");const room=(await client.query(`INSERT INTO rooms(name,slug,description,is_public,visibility,join_policy,owner_id) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[name,slug,description,visibility==="public",visibility,joinPolicy,u.id])).rows[0];await client.query(`INSERT INTO room_members(room_id,user_id,role) VALUES($1,$2,'owner')`,[room.id,u.id]);await client.query("COMMIT");res.status(201).json({ok:true,room:{...room,joined:true,members_count:1}})}catch(e){await client.query("ROLLBACK");console.error("room create",e);res.status(500).json({ok:false,error:"ROOM_CREATE_FAILED"})}finally{client.release()}});
  app.post("/api/rooms/:id/join",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const id=Number(req.params.id),admin=isAdmin(u);const room=(await pool.query(`SELECT r.id,r.owner_id,r.visibility,r.join_policy,EXISTS(SELECT 1 FROM room_members rm WHERE rm.room_id=r.id AND rm.user_id=$2) joined,EXISTS(SELECT 1 FROM friendships f WHERE f.status='accepted' AND ((f.requester_id=$2 AND f.addressee_id=r.owner_id) OR (f.addressee_id=$2 AND f.requester_id=r.owner_id))) owner_friend FROM rooms r WHERE r.id=$1`,[id,u.id])).rows[0];if(!room)return res.status(404).json({ok:false,error:"ROOM_NOT_FOUND"});if(room.joined)return res.json({ok:true});if(!admin&&room.visibility==="private")return res.status(403).json({ok:false,error:"INVITE_REQUIRED"});if(!admin&&room.visibility==="friends"&&!room.owner_friend)return res.status(403).json({ok:false,error:"FRIENDS_ONLY_ROOM"});if(!admin&&room.join_policy!=="open")return res.status(403).json({ok:false,error:room.join_policy==="request"?"JOIN_REQUIRED":"INVITE_REQUIRED"});await pool.query(`INSERT INTO room_members(room_id,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING`,[id,u.id]);res.json({ok:true})});
  app.post("/api/rooms/:id/leave",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const id=Number(req.params.id),m=(await pool.query(`SELECT role FROM room_members WHERE room_id=$1 AND user_id=$2`,[id,u.id])).rows[0];if(m?.role==="owner"&&!isAdmin(u))return res.status(409).json({ok:false,error:"OWNER_CANNOT_LEAVE"});await pool.query(`DELETE FROM room_members WHERE room_id=$1 AND user_id=$2`,[id,u.id]);res.json({ok:true})});
}
