import crypto from "crypto";
import {pool,requireAuth,turnConfig,emitUser,emitChat,actionRateLimit,rejectRateLimit} from "../runtime.mjs";

const PEER_TIMEOUT_SECONDS=14,RING_TIMEOUT_SECONDS=60;
async function callFor(id,u){return(await pool.query(`SELECT c.*,cu.username caller_username,cu.display_name caller_name,cu.avatar_url caller_avatar,tu.username callee_username,tu.display_name callee_name,tu.avatar_url callee_avatar FROM rtc_calls c JOIN users cu ON cu.id=c.caller_id JOIN users tu ON tu.id=c.callee_id WHERE c.id=$1 AND ($2=c.caller_id OR $2=c.callee_id)`,[id,u.id])).rows[0]||null}
async function blocked(a,b){return Boolean((await pool.query(`SELECT 1 FROM user_blocks WHERE (blocker_id=$1 AND blocked_id=$2) OR (blocker_id=$2 AND blocked_id=$1) LIMIT 1`,[a,b])).rows[0])}
async function friends(a,b){return Boolean((await pool.query(`SELECT 1 FROM friendships WHERE status='accepted' AND ((requester_id=$1 AND addressee_id=$2) OR (requester_id=$2 AND addressee_id=$1)) LIMIT 1`,[a,b])).rows[0])}
async function mutual(a,b){return Boolean((await pool.query(`WITH af AS(SELECT CASE WHEN requester_id=$1 THEN addressee_id ELSE requester_id END id FROM friendships WHERE status='accepted' AND(requester_id=$1 OR addressee_id=$1)),bf AS(SELECT CASE WHEN requester_id=$2 THEN addressee_id ELSE requester_id END id FROM friendships WHERE status='accepted' AND(requester_id=$2 OR addressee_id=$2))SELECT 1 FROM af JOIN bf USING(id) LIMIT 1`,[a,b])).rows[0])}
async function callAllowed(callerId,calleeId){if(await blocked(callerId,calleeId))return false;const rule=(await pool.query(`SELECT COALESCE(who_can_call,'friends') rule FROM profile_privacy WHERE user_id=$1`,[calleeId])).rows[0]?.rule||"friends";if(rule==="everyone")return true;if(rule==="nobody")return false;if(await friends(callerId,calleeId))return true;return rule==="friends_of_friends"&&await mutual(callerId,calleeId)}
const durationSql=()=>`GREATEST(0,EXTRACT(EPOCH FROM (COALESCE(c.ended_at,NOW())-COALESCE(c.answered_at,c.created_at)))::int)`;
function notifyCall(c,event="call:updated"){const payload={id:c.id,conversationId:Number(c.conversation_id),callerId:Number(c.caller_id),calleeId:Number(c.callee_id),kind:c.kind,status:c.status,createdAt:c.created_at,answeredAt:c.answered_at||null,endedAt:c.ended_at||null};emitUser(c.caller_id,event,payload);emitUser(c.callee_id,event,payload);emitChat(c.conversation_id,event,payload)}
async function touchAndExpirePeer(c,u){if(!c||c.status!=="answered")return c;const caller=Number(c.caller_id)===Number(u.id);await pool.query(`UPDATE rtc_calls SET caller_heartbeat_at=CASE WHEN $2 THEN NOW() ELSE caller_heartbeat_at END,callee_heartbeat_at=CASE WHEN $2 THEN callee_heartbeat_at ELSE NOW() END WHERE id=$1 AND status='answered'`,[c.id,caller]);const row=(await pool.query(`SELECT * FROM rtc_calls WHERE id=$1`,[c.id])).rows[0];const peerBeat=caller?row.callee_heartbeat_at:row.caller_heartbeat_at,answered=row.answered_at?new Date(row.answered_at).getTime():0;if(answered&&Date.now()-answered>PEER_TIMEOUT_SECONDS*1000&&(!peerBeat||Date.now()-new Date(peerBeat).getTime()>PEER_TIMEOUT_SECONDS*1000)){const ended=(await pool.query(`UPDATE rtc_calls SET status='ended',ended_at=NOW() WHERE id=$1 AND status='answered' RETURNING *`,[c.id])).rows[0];if(ended){notifyCall(ended);return ended}}return row}
async function expireRingingCall(c){if(!c||c.status!=="ringing")return c;const created=new Date(c.created_at).getTime();if(!Number.isFinite(created)||Date.now()-created<RING_TIMEOUT_SECONDS*1000)return c;const row=(await pool.query(`UPDATE rtc_calls SET status='missed',ended_at=NOW() WHERE id=$1 AND status='ringing' AND created_at<NOW()-($2::text||' seconds')::interval RETURNING *`,[c.id,String(RING_TIMEOUT_SECONDS)])).rows[0];if(row){notifyCall(row);return row}return(await pool.query(`SELECT * FROM rtc_calls WHERE id=$1`,[c.id])).rows[0]||c}
function callIceConfig(userId){const cfg=turnConfig(userId),external=String(process.env.TURN_EXTERNAL_IP||"").trim(),primary=String(process.env.TURN_HOST||"").trim(),turn=cfg.iceServers.find(x=>x?.username&&Array.isArray(x.urls));if(turn&&external&&external!==primary){const extra=[`turn:${external}:3478?transport=udp`,`turn:${external}:3478?transport=tcp`];turn.urls=[...new Set([...turn.urls,...extra])]}return cfg}

export function registerCoreCalls(app){
app.post("/api/calls",async(req,res)=>{try{const u=await requireAuth(req,res);if(!u)return;const rate=await actionRateLimit("call-create",u.id,{limit:8,windowSeconds:60});if(!rate.allowed)return rejectRateLimit(res,rate,"CALL_RATE_LIMITED");const conv=Number(req.body?.conversationId),kind=req.body?.kind==="video"?"video":"audio";if(!Number.isInteger(conv)||conv<1)return res.status(400).json({ok:false,error:"BAD_CONVERSATION"});const c=(await pool.query(`SELECT id,user1_id,user2_id FROM direct_conversations WHERE id=$1 AND ($2=user1_id OR $2=user2_id)`,[conv,u.id])).rows[0];if(!c)return res.status(403).json({ok:false,error:"CHAT_FORBIDDEN"});const callee=Number(c.user1_id)===Number(u.id)?Number(c.user2_id):Number(c.user1_id);if(!await callAllowed(u.id,callee))return res.status(403).json({ok:false,error:"CALL_PRIVACY_RESTRICTED"});const target=(await pool.query(`SELECT id FROM users WHERE id=$1 AND account_status='active'`,[callee])).rows[0];if(!target)return res.status(404).json({ok:false,error:"USER_NOT_FOUND"});await pool.query(`UPDATE rtc_calls SET status=CASE WHEN status='ringing' THEN 'cancelled' ELSE 'ended' END,ended_at=NOW() WHERE status IN ('ringing','answered') AND ((caller_id=$1 AND callee_id=$2) OR (caller_id=$2 AND callee_id=$1))`,[u.id,callee]);const id=crypto.randomUUID(),row=(await pool.query(`INSERT INTO rtc_calls(id,conversation_id,caller_id,callee_id,kind,caller_heartbeat_at) VALUES($1,$2,$3,$4,$5,NOW()) RETURNING *`,[id,conv,u.id,callee,kind])).rows[0];notifyCall(row,"call:incoming");res.status(201).json({ok:true,call:row})}catch(e){console.error("create call",e);res.status(500).json({ok:false,error:"CALL_CREATE_FAILED"})}});
 app.get("/api/calls/incoming",async(req,res)=>{try{const u=await requireAuth(req,res);if(!u)return;const expired=(await pool.query(`UPDATE rtc_calls SET status='missed',ended_at=NOW() WHERE callee_id=$1 AND status='ringing' AND created_at<NOW()-($2::text||' seconds')::interval RETURNING *`,[u.id,String(RING_TIMEOUT_SECONDS)])).rows;expired.forEach(c=>notifyCall(c));const rows=(await pool.query(`SELECT c.*,x.username caller_username,x.display_name caller_name,x.avatar_url caller_avatar FROM rtc_calls c JOIN users x ON x.id=c.caller_id WHERE c.callee_id=$1 AND c.status='ringing' ORDER BY c.created_at DESC LIMIT 5`,[u.id])).rows;let row=null;for(const candidate of rows){if(await callAllowed(candidate.caller_id,u.id)){row=candidate;break}await pool.query(`UPDATE rtc_calls SET status='cancelled',ended_at=NOW() WHERE id=$1 AND status='ringing'`,[candidate.id]).catch(()=>{})}res.json({ok:true,call:row})}catch(e){console.error("incoming call",e);res.status(500).json({ok:false,error:"CALL_LOAD_FAILED"})}});
 app.get("/api/calls/history",async(req,res)=>{try{const u=await requireAuth(req,res);if(!u)return;const conv=Math.max(0,Number(req.query.conversationId)||0),rows=(await pool.query(`SELECT c.*,CASE WHEN c.caller_id=$1 THEN 'outgoing' ELSE 'incoming' END direction,CASE WHEN c.caller_id=$1 THEN tu.display_name ELSE cu.display_name END peer_name,CASE WHEN c.caller_id=$1 THEN tu.username ELSE cu.username END peer_username,CASE WHEN c.caller_id=$1 THEN tu.avatar_url ELSE cu.avatar_url END peer_avatar,CASE WHEN c.caller_id=$1 THEN tu.gender ELSE cu.gender END peer_gender,${durationSql()} duration_seconds FROM rtc_calls c JOIN users cu ON cu.id=c.caller_id JOIN users tu ON tu.id=c.callee_id WHERE (c.caller_id=$1 OR c.callee_id=$1) AND ($2::bigint=0 OR c.conversation_id=$2) ORDER BY c.created_at DESC LIMIT 150`,[u.id,conv])).rows;res.json({ok:true,calls:rows})}catch(e){console.error("call history",e);res.status(500).json({ok:false,error:"CALL_HISTORY_FAILED"})}});
 app.get("/api/calls/config",async(req,res)=>{try{const u=await requireAuth(req,res);if(!u)return;res.json({ok:true,...callIceConfig(u.id)})}catch(e){console.error("call config",e);res.status(500).json({ok:false,error:"CALL_CONFIG_FAILED"})}});
 app.get("/api/calls/:id",async(req,res)=>{try{const u=await requireAuth(req,res);if(!u)return;let c=await callFor(req.params.id,u);if(!c)return res.status(404).json({ok:false,error:"CALL_NOT_FOUND"});c=await expireRingingCall(c);c=await touchAndExpirePeer(c,u);res.json({ok:true,call:c})}catch(e){console.error("call load",e);res.status(500).json({ok:false,error:"CALL_LOAD_FAILED"})}});
 app.post("/api/calls/:id/answer",async(req,res)=>{try{const u=await requireAuth(req,res);if(!u)return;const c=await callFor(req.params.id,u);if(!c)return res.status(404).json({ok:false,error:"CALL_NOT_FOUND"});if(Number(c.callee_id)!==Number(u.id))return res.status(403).json({ok:false,error:"FORBIDDEN"});if(!await callAllowed(c.caller_id,c.callee_id))return res.status(403).json({ok:false,error:"CALL_PRIVACY_RESTRICTED"});const row=(await pool.query(`UPDATE rtc_calls SET status='answered',answered_at=COALESCE(answered_at,NOW()),caller_heartbeat_at=COALESCE(caller_heartbeat_at,NOW()),callee_heartbeat_at=NOW() WHERE id=$1 AND status='ringing' RETURNING *`,[c.id])).rows[0];if(!row)return res.status(409).json({ok:false,error:"CALL_NOT_RINGING"});notifyCall(row);res.json({ok:true,call:row})}catch{res.status(500).json({ok:false,error:"CALL_ANSWER_FAILED"})}});
 app.post("/api/calls/:id/decline",async(req,res)=>{try{const u=await requireAuth(req,res);if(!u)return;const c=await callFor(req.params.id,u);if(!c)return res.status(404).json({ok:false,error:"CALL_NOT_FOUND"});if(Number(c.callee_id)!==Number(u.id))return res.status(403).json({ok:false,error:"FORBIDDEN"});const row=(await pool.query(`UPDATE rtc_calls SET status='declined',ended_at=NOW() WHERE id=$1 AND status='ringing' RETURNING *`,[c.id])).rows[0];if(row)notifyCall(row);res.json({ok:true})}catch{res.status(500).json({ok:false,error:"CALL_DECLINE_FAILED"})}});
 app.post("/api/calls/:id/fail",async(req,res)=>{try{const u=await requireAuth(req,res);if(!u)return;const c=await callFor(req.params.id,u);if(!c)return res.status(404).json({ok:false,error:"CALL_NOT_FOUND"});const row=(await pool.query(`UPDATE rtc_calls SET status='failed',ended_at=NOW() WHERE id=$1 AND status IN ('ringing','answered') RETURNING *`,[c.id])).rows[0];if(row)notifyCall(row);res.json({ok:true})}catch{res.status(500).json({ok:false,error:"CALL_END_FAILED"})}});
 app.post("/api/calls/:id/end",async(req,res)=>{try{const u=await requireAuth(req,res);if(!u)return;const c=await callFor(req.params.id,u);if(!c)return res.status(404).json({ok:false,error:"CALL_NOT_FOUND"});const row=(await pool.query(`UPDATE rtc_calls SET status=CASE WHEN status='ringing' THEN 'cancelled' ELSE 'ended' END,ended_at=NOW() WHERE id=$1 AND status IN ('ringing','answered') RETURNING *`,[c.id])).rows[0];if(row)notifyCall(row);res.json({ok:true})}catch{res.status(500).json({ok:false,error:"CALL_END_FAILED"})}});
 app.post("/api/calls/:id/signals",async(req,res)=>{try{const u=await requireAuth(req,res);if(!u)return;const rate=await actionRateLimit("call-signal",u.id,{limit:120,windowSeconds:30});if(!rate.allowed)return rejectRateLimit(res,rate,"SIGNAL_RATE_LIMITED");const c=await callFor(req.params.id,u);if(!c)return res.status(404).json({ok:false,error:"CALL_NOT_FOUND"});if(!["ringing","answered"].includes(c.status))return res.status(409).json({ok:false,error:"CALL_NOT_ACTIVE"});if(!await callAllowed(c.caller_id,c.callee_id))return res.status(403).json({ok:false,error:"CALL_PRIVACY_RESTRICTED"});const kind=String(req.body?.kind||"");if(!["offer","answer","ice"].includes(kind))return res.status(400).json({ok:false,error:"BAD_SIGNAL"});if(kind==="offer"&&Number(c.caller_id)!==Number(u.id))return res.status(403).json({ok:false,error:"BAD_SIGNAL_ROLE"});if(kind==="answer"&&Number(c.callee_id)!==Number(u.id))return res.status(403).json({ok:false,error:"BAD_SIGNAL_ROLE"});const recipient=Number(c.caller_id)===Number(u.id)?Number(c.callee_id):Number(c.caller_id),payload=req.body?.payload;if(!payload||typeof payload!=="object")return res.status(400).json({ok:false,error:"BAD_SIGNAL"});const row=(await pool.query(`INSERT INTO rtc_call_signals(call_id,sender_id,recipient_id,kind,payload) VALUES($1,$2,$3,$4,$5) RETURNING id,created_at`,[c.id,u.id,recipient,kind,payload])).rows[0];emitUser(recipient,"call:signal",{id:row.id,callId:c.id,kind,payload,createdAt:row.created_at});res.status(201).json({ok:true,id:row.id})}catch(e){console.error("call signal",e);res.status(500).json({ok:false,error:"SIGNAL_FAILED"})}});
 app.get("/api/calls/:id/signals",async(req,res)=>{try{const u=await requireAuth(req,res);if(!u)return;const c=await callFor(req.params.id,u);if(!c)return res.status(404).json({ok:false,error:"CALL_NOT_FOUND"});if(!["ringing","answered"].includes(c.status))return res.status(409).json({ok:false,error:"CALL_NOT_ACTIVE"});if(!await callAllowed(c.caller_id,c.callee_id))return res.status(403).json({ok:false,error:"CALL_PRIVACY_RESTRICTED"});const since=Math.max(0,Number(req.query.since)||0),rows=(await pool.query(`SELECT id,kind,payload,created_at FROM rtc_call_signals WHERE call_id=$1 AND recipient_id=$2 AND id>$3 ORDER BY id ASC LIMIT 200`,[c.id,u.id,since])).rows;res.json({ok:true,signals:rows})}catch{res.status(500).json({ok:false,error:"SIGNAL_LOAD_FAILED"})}});
}
