import {pool,requireAuth,isAdmin,clean,emitChat,emitUser} from "../runtime.mjs";

const allowedKind=new Set(["text","image","video"]),allowedPrivacy=new Set(["everyone","friends"]),allowedFilter=new Set(["normal","warm","cool","mono"]);
const clamp=(value,min,max,fallback)=>{const n=Number(value);return Number.isFinite(n)?Math.min(max,Math.max(min,n)):fallback};
const ownMediaUrl=value=>{
 const raw=String(value||"").split("?")[0];
 const prefix=raw.startsWith("/api/uploads/")?"/api/uploads/":raw.startsWith("/uploads/")?"/uploads/":"";
 if(!prefix)return false;
 const parts=raw.slice(prefix.length).split("/");
 return parts.length>0&&parts.every(p=>p&&p!=="."&&p!==".."&&/^[A-Za-z0-9._-]+$/.test(p));
};
const mediaKindFromUrl=value=>{const raw=String(value||"").split("?")[0].toLowerCase();if(/\.(jpe?g|png|webp|gif)$/.test(raw))return"image";if(/\.(mp4|webm|mov)$/.test(raw))return"video";return""};
async function areFriends(a,b){return Boolean((await pool.query(`SELECT 1 FROM friendships WHERE status='accepted' AND ((requester_id=$1 AND addressee_id=$2) OR (requester_id=$2 AND addressee_id=$1)) LIMIT 1`,[a,b])).rows[0])}
async function mutualCount(a,b){return Number((await pool.query(`WITH af AS(SELECT CASE WHEN requester_id=$1 THEN addressee_id ELSE requester_id END id FROM friendships WHERE status='accepted' AND (requester_id=$1 OR addressee_id=$1)),bf AS(SELECT CASE WHEN requester_id=$2 THEN addressee_id ELSE requester_id END id FROM friendships WHERE status='accepted' AND (requester_id=$2 OR addressee_id=$2)) SELECT COUNT(*)::int n FROM af JOIN bf USING(id)`,[a,b])).rows[0]?.n||0)}
async function blocked(a,b){return Boolean((await pool.query(`SELECT 1 FROM user_blocks WHERE(blocker_id=$1 AND blocked_id=$2)OR(blocker_id=$2 AND blocked_id=$1) LIMIT 1`,[a,b])).rows[0])}
async function accountStoryAllowed(ownerId,viewerId){if(String(ownerId)===String(viewerId))return true;if(await blocked(ownerId,viewerId))return false;const rule=(await pool.query(`SELECT who_can_see_story FROM profile_privacy WHERE user_id=$1`,[ownerId])).rows[0]?.who_can_see_story||"everyone";if(rule==="everyone")return true;if(rule==="nobody")return false;if(await areFriends(ownerId,viewerId))return true;return rule==="friends_of_friends"&&(await mutualCount(ownerId,viewerId))>0}
async function canSee(story,viewerId){if(String(story.user_id)===String(viewerId))return true;if(!await accountStoryAllowed(story.user_id,viewerId))return false;if(story.privacy==="everyone")return true;return areFriends(viewerId,story.user_id)}
const STORY_EMOJI=new Set(["❤️","😂","😍","😢","🔥"]);
async function ruleAllows(rule,owner,viewer){if(String(owner)===String(viewer))return true;if(rule==="everyone")return true;if(rule==="nobody")return false;if(await areFriends(owner,viewer))return true;return rule==="friends_of_friends"&&(await mutualCount(owner,viewer))>0}
async function storyAllowed(story,viewer){return canSee(story,viewer.id)}
async function notify(userId,actor,type,title,body,refId){if(!userId||String(userId)===String(actor?.id))return null;const row=(await pool.query(`INSERT INTO notifications(user_id,actor_id,type,title,body,ref_id) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,user_id,actor_id,type,title,body,ref_id,read_at,created_at`,[userId,actor?.id||null,type,title,body||"",refId||null])).rows[0];emitUser(userId,"notification:new",{...row,actor_username:actor?.username||null,actor_name:actor?.display_name||null,actor_avatar:actor?.avatar_url||null});return row}

export function registerCoreStories(app){
  app.get("/api/stories",async(req,res)=>{try{const viewer=await requireAuth(req,res);if(!viewer)return;const rows=(await pool.query(`SELECT s.id,s.user_id,s.kind,s.text_body,s.media_url,s.media_type,s.privacy,s.filter_name,s.overlay_x,s.overlay_y,s.created_at,s.expires_at,u.username,u.display_name,u.gender,u.avatar_url,EXISTS(SELECT 1 FROM story_views v WHERE v.story_id=s.id AND v.viewer_id=$1) seen,CASE WHEN s.user_id=$1 THEN (SELECT COUNT(*)::int FROM story_views v WHERE v.story_id=s.id AND v.viewer_id<>$1) ELSE NULL END views_count FROM stories s JOIN users u ON u.id=s.user_id WHERE s.deleted_at IS NULL AND s.expires_at>NOW() AND u.account_status='active' AND NOT EXISTS(SELECT 1 FROM story_mutes sm WHERE sm.user_id=$1 AND sm.muted_user_id=s.user_id) ORDER BY CASE WHEN s.user_id=$1 THEN 0 ELSE 1 END,s.created_at ASC,s.id ASC`,[viewer.id])).rows,visible=[];for(const s of rows)if(await storyAllowed(s,viewer))visible.push(s);const ids=visible.map(x=>x.id);let reactions=[];if(ids.length)reactions=(await pool.query(`SELECT story_id,emoji,COUNT(*)::int count,BOOL_OR(user_id=$2) mine FROM story_reactions WHERE story_id=ANY($1::bigint[]) GROUP BY story_id,emoji ORDER BY story_id,count DESC`,[ids,viewer.id])).rows;for(const s of visible){const mine=reactions.filter(r=>String(r.story_id)===String(s.id));s.reactions=mine;s.my_reaction=mine.find(r=>r.mine)?.emoji||null;s.reactions_count=mine.reduce((n,r)=>n+Number(r.count||0),0)}res.json({ok:true,stories:visible,viewerId:viewer.id})}catch(e){console.error("IJKL stories list",e);res.status(500).json({ok:false,error:"STORIES_LOAD_FAILED"})}});
  app.post("/api/stories",async(req,res)=>{try{const viewer=await requireAuth(req,res);if(!viewer)return;const kind=clean(req.body?.kind,12),privacy=allowedPrivacy.has(req.body?.privacy)?req.body.privacy:"friends",text=clean(req.body?.text,600),rawMediaUrl=clean(req.body?.mediaUrl,900)||null,rawMediaType=clean(req.body?.mediaType,100)||null,filterName=allowedFilter.has(req.body?.filterName)?req.body.filterName:"normal",overlayX=clamp(req.body?.overlayX,5,95,50),overlayY=clamp(req.body?.overlayY,10,90,78);if(!allowedKind.has(kind))return res.status(400).json({ok:false,error:"INVALID_STORY_KIND"});if(kind==="text"&&!text)return res.status(400).json({ok:false,error:"EMPTY_STORY"});if((kind==="image"||kind==="video")&&!rawMediaUrl)return res.status(400).json({ok:false,error:"STORY_MEDIA_REQUIRED"});if(kind!=="text"&&!ownMediaUrl(rawMediaUrl))return res.status(400).json({ok:false,error:"INVALID_STORY_MEDIA"});if(kind==="image"&&(!String(rawMediaType||"").startsWith("image/")||mediaKindFromUrl(rawMediaUrl)!=="image"))return res.status(400).json({ok:false,error:"INVALID_STORY_MEDIA_TYPE"});if(kind==="video"&&(!String(rawMediaType||"").startsWith("video/")||mediaKindFromUrl(rawMediaUrl)!=="video"))return res.status(400).json({ok:false,error:"INVALID_STORY_MEDIA_TYPE"});const mediaUrl=kind==="text"?null:rawMediaUrl,mediaType=kind==="text"?null:rawMediaType;const row=(await pool.query(`INSERT INTO stories(user_id,kind,text_body,media_url,media_type,privacy,filter_name,overlay_x,overlay_y) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[viewer.id,kind,text,mediaUrl,mediaType,privacy,filterName,overlayX,overlayY])).rows[0];res.status(201).json({ok:true,story:{...row,username:viewer.username,display_name:viewer.display_name,gender:viewer.gender,avatar_url:viewer.avatar_url,seen:true,views_count:0}})}catch(e){console.error("story create",e);res.status(500).json({ok:false,error:"STORY_CREATE_FAILED"})}});
  app.post("/api/stories/:id/view",async(req,res)=>{try{const viewer=await requireAuth(req,res);if(!viewer)return;const id=Number(req.params.id),story=(await pool.query(`SELECT * FROM stories WHERE id=$1 AND deleted_at IS NULL AND expires_at>NOW()`,[id])).rows[0];if(!story)return res.status(404).json({ok:false,error:"STORY_NOT_FOUND"});if(!await canSee(story,viewer.id))return res.status(403).json({ok:false,error:"STORY_FORBIDDEN"});if(String(story.user_id)!==String(viewer.id))await pool.query(`INSERT INTO story_views(story_id,viewer_id,viewed_at) VALUES($1,$2,NOW()) ON CONFLICT(story_id,viewer_id) DO UPDATE SET viewed_at=NOW()`,[id,viewer.id]);res.json({ok:true})}catch(e){console.error("story view",e);res.status(500).json({ok:false,error:"STORY_VIEW_FAILED"})}});

  app.get("/api/stories/:id/viewers",async(req,res)=>{try{const viewer=await requireAuth(req,res);if(!viewer)return;const id=Number(req.params.id),story=(await pool.query(`SELECT user_id FROM stories WHERE id=$1`,[id])).rows[0];if(!story)return res.status(404).json({ok:false,error:"STORY_NOT_FOUND"});if(String(story.user_id)!==String(viewer.id)&&!isAdmin(viewer))return res.status(403).json({ok:false,error:"FORBIDDEN"});const rows=(await pool.query(`SELECT v.viewer_id,v.viewed_at,u.username,u.display_name,u.gender,u.avatar_url FROM story_views v JOIN users u ON u.id=v.viewer_id WHERE v.story_id=$1 ORDER BY v.viewed_at DESC LIMIT 500`,[id])).rows;res.json({ok:true,viewers:rows})}catch(e){console.error("story viewers",e);res.status(500).json({ok:false,error:"STORY_VIEWERS_FAILED"})}});

  app.delete("/api/stories/:id",async(req,res)=>{try{const viewer=await requireAuth(req,res);if(!viewer)return;const id=Number(req.params.id),story=(await pool.query(`SELECT user_id FROM stories WHERE id=$1 AND deleted_at IS NULL`,[id])).rows[0];if(!story)return res.status(404).json({ok:false,error:"STORY_NOT_FOUND"});if(String(story.user_id)!==String(viewer.id)&&!isAdmin(viewer))return res.status(403).json({ok:false,error:"FORBIDDEN"});const client=await pool.connect();try{await client.query("BEGIN");await client.query(`UPDATE stories SET deleted_at=NOW() WHERE id=$1`,[id]);await client.query(`DELETE FROM story_highlights WHERE story_id=$1`,[id]);await client.query(`DELETE FROM notifications WHERE ref_id=$1 AND type IN('story_reaction','story_reply')`,[id]);await client.query("COMMIT")}catch(e){await client.query("ROLLBACK").catch(()=>{});throw e}finally{client.release()}res.json({ok:true})}catch(e){console.error("story delete",e);res.status(500).json({ok:false,error:"STORY_DELETE_FAILED"})}});
  app.put("/api/stories/:id/reaction",async(req,res)=>{try{const u=await requireAuth(req,res);if(!u)return;const id=Number(req.params.id),emoji=String(req.body?.emoji||"");if(!STORY_EMOJI.has(emoji))return res.status(400).json({ok:false,error:"INVALID_STORY_REACTION"});const story=(await pool.query(`SELECT id,user_id,privacy FROM stories WHERE id=$1 AND deleted_at IS NULL AND expires_at>NOW()`,[id])).rows[0];if(!story)return res.status(404).json({ok:false,error:"STORY_NOT_FOUND"});if(!await storyAllowed(story,u))return res.status(403).json({ok:false,error:"STORY_FORBIDDEN"});await pool.query(`INSERT INTO story_reactions(story_id,user_id,emoji) VALUES($1,$2,$3) ON CONFLICT(story_id,user_id) DO UPDATE SET emoji=EXCLUDED.emoji,created_at=NOW()`,[id,u.id,emoji]);await pool.query(`DELETE FROM notifications WHERE user_id=$1 AND actor_id=$2 AND type='story_reaction' AND ref_id=$3`,[story.user_id,u.id,id]).catch(()=>{});await notify(story.user_id,u,"story_reaction",`${u.display_name||u.username} تفاعل مع ستوريك`,emoji,id);res.json({ok:true,emoji})}catch(e){console.error("story reaction",e);res.status(500).json({ok:false,error:"STORY_REACTION_FAILED"})}});
  app.delete("/api/stories/:id/reaction",async(req,res)=>{try{const u=await requireAuth(req,res);if(!u)return;const id=Number(req.params.id),story=(await pool.query(`SELECT user_id FROM stories WHERE id=$1 AND deleted_at IS NULL`,[id])).rows[0];await pool.query(`DELETE FROM story_reactions WHERE story_id=$1 AND user_id=$2`,[id,u.id]);if(story)await pool.query(`DELETE FROM notifications WHERE user_id=$1 AND actor_id=$2 AND type='story_reaction' AND ref_id=$3`,[story.user_id,u.id,id]).catch(()=>{});res.json({ok:true,emoji:null})}catch(e){res.status(500).json({ok:false,error:"STORY_REACTION_FAILED"})}});
  app.post("/api/stories/:id/reply",async(req,res)=>{try{const u=await requireAuth(req,res);if(!u)return;const id=Number(req.params.id),body=clean(req.body?.body,500);if(!body)return res.status(400).json({ok:false,error:"EMPTY_REPLY"});const story=(await pool.query(`SELECT id,user_id,kind,text_body,media_url,media_type,privacy FROM stories WHERE id=$1 AND deleted_at IS NULL AND expires_at>NOW()`,[id])).rows[0];if(!story)return res.status(404).json({ok:false,error:"STORY_NOT_FOUND"});if(String(story.user_id)===String(u.id))return res.status(400).json({ok:false,error:"OWN_STORY_REPLY"});if(!await storyAllowed(story,u))return res.status(403).json({ok:false,error:"STORY_FORBIDDEN"});const rule=(await pool.query(`SELECT who_can_reply_story FROM profile_privacy WHERE user_id=$1`,[story.user_id])).rows[0]?.who_can_reply_story||"friends";if(!await ruleAllows(rule,story.user_id,u.id))return res.status(403).json({ok:false,error:"STORY_REPLY_RESTRICTED"});let conv=(await pool.query(`SELECT * FROM direct_conversations WHERE LEAST(user1_id,user2_id)=LEAST($1,$2) AND GREATEST(user1_id,user2_id)=GREATEST($1,$2)`,[u.id,story.user_id])).rows[0];if(!conv)conv=(await pool.query(`INSERT INTO direct_conversations(user1_id,user2_id) VALUES($1,$2) RETURNING *`,[u.id,story.user_id])).rows[0];const context=story.text_body?`↩️ رد على الستوري: ${story.text_body.slice(0,90)}\n${body}`:`↩️ رد على الستوري\n${body}`,msg=(await pool.query(`INSERT INTO direct_messages(conversation_id,sender_id,body,attachment_url,attachment_type) VALUES($1,$2,$3,$4,$5) RETURNING *`,[conv.id,u.id,context,story.media_url||null,story.media_type||null])).rows[0];await pool.query(`UPDATE direct_conversations SET updated_at=NOW() WHERE id=$1`,[conv.id]);emitChat(conv.id,"direct:new",{...msg,username:u.username,display_name:u.display_name,gender:u.gender,story_id:id});await notify(story.user_id,u,"story_reply",`${u.display_name||u.username} رد على ستوريك`,body.slice(0,120),id);res.status(201).json({ok:true,conversationId:conv.id,message:msg})}catch(e){console.error("story reply",e);res.status(500).json({ok:false,error:"STORY_REPLY_FAILED"})}});
  app.get("/api/stories/mutes",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const rows=(await pool.query(`SELECT sm.muted_user_id user_id,x.username,x.display_name,x.avatar_url,x.gender FROM story_mutes sm JOIN users x ON x.id=sm.muted_user_id WHERE sm.user_id=$1 AND x.account_status='active' ORDER BY LOWER(COALESCE(x.display_name,x.username)),x.id`,[u.id])).rows;res.json({ok:true,mutes:rows})});
  app.put("/api/stories/mutes/:userId",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const target=Number(req.params.userId);if(!Number.isSafeInteger(target)||target<=0||String(target)===String(u.id))return res.status(400).json({ok:false,error:"INVALID_USER"});if(!(await pool.query(`SELECT 1 FROM users WHERE id=$1 AND account_status=\'active\'`,[target])).rows[0])return res.status(404).json({ok:false,error:"USER_NOT_FOUND"});await pool.query(`INSERT INTO story_mutes(user_id,muted_user_id) VALUES($1,$2) ON CONFLICT DO NOTHING`,[u.id,target]);res.json({ok:true,muted:true})});
  app.delete("/api/stories/mutes/:userId",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;await pool.query(`DELETE FROM story_mutes WHERE user_id=$1 AND muted_user_id=$2`,[u.id,Number(req.params.userId)]);res.json({ok:true,muted:false})});
  app.post("/api/stories/:id/highlight",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const id=Number(req.params.id),story=(await pool.query(`SELECT user_id FROM stories WHERE id=$1 AND deleted_at IS NULL`,[id])).rows[0];if(!story)return res.status(404).json({ok:false,error:"STORY_NOT_FOUND"});if(String(story.user_id)!==String(u.id))return res.status(403).json({ok:false,error:"FORBIDDEN"});const title=clean(req.body?.title,40)||"مميزة";await pool.query(`INSERT INTO story_highlights(user_id,story_id,title) VALUES($1,$2,$3) ON CONFLICT(user_id,story_id) DO UPDATE SET title=EXCLUDED.title`,[u.id,id,title]);res.json({ok:true})});
  app.delete("/api/stories/:id/highlight",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;await pool.query(`DELETE FROM story_highlights WHERE user_id=$1 AND story_id=$2`,[u.id,Number(req.params.id)]);res.json({ok:true})});
  app.get("/api/users/:userId/story-highlights",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const owner=Number(req.params.userId),rows=(await pool.query(`SELECT h.id highlight_id,h.title,h.created_at highlighted_at,s.id,s.user_id,s.kind,s.text_body,s.media_url,s.media_type,s.privacy,s.filter_name,s.overlay_x,s.overlay_y,s.created_at FROM story_highlights h JOIN stories s ON s.id=h.story_id WHERE h.user_id=$1 AND s.deleted_at IS NULL ORDER BY h.id DESC LIMIT 50`,[owner])).rows,visible=[];for(const s of rows)if(await storyAllowed(s,u))visible.push(s);res.json({ok:true,highlights:visible})});
}
