import crypto from "crypto";
import {pool,requireAuth,isAdmin,clean} from "../runtime.mjs";

export function registerCoreRooms(app){
  app.get("/api/rooms",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const q=clean(req.query.q||"",80);const rows=(await pool.query(`SELECT r.id,r.name,r.slug,r.description,r.is_public,r.owner_id,r.created_at,EXISTS(SELECT 1 FROM room_members rm WHERE rm.room_id=r.id AND rm.user_id=$1) joined,(SELECT COUNT(*)::int FROM room_members x WHERE x.room_id=r.id) members_count FROM rooms r WHERE r.is_public=TRUE AND($2='' OR r.name ILIKE '%'||$2||'%' OR r.description ILIKE '%'||$2||'%') ORDER BY members_count DESC,r.id ASC LIMIT 100`,[u.id,q])).rows;res.json({ok:true,rooms:rows})});
  app.post("/api/rooms",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const name=clean(req.body?.name,60),description=clean(req.body?.description,180);if(name.length<3)return res.status(400).json({ok:false,error:"INVALID_ROOM_NAME"});const slug=`${name.toLowerCase().replace(/[^a-z0-9\u0600-\u06ff]+/g,"-").replace(/^-|-$/g,"").slice(0,45)||"room"}-${crypto.randomBytes(3).toString("hex")}`;const client=await pool.connect();try{await client.query("BEGIN");const room=(await client.query(`INSERT INTO rooms(name,slug,description,is_public,owner_id) VALUES($1,$2,$3,TRUE,$4) RETURNING *`,[name,slug,description,u.id])).rows[0];await client.query(`INSERT INTO room_members(room_id,user_id,role) VALUES($1,$2,'owner')`,[room.id,u.id]);await client.query("COMMIT");res.status(201).json({ok:true,room:{...room,joined:true,members_count:1}})}catch{await client.query("ROLLBACK");res.status(500).json({ok:false,error:"ROOM_CREATE_FAILED"})}finally{client.release()}});
  app.post("/api/rooms/:id/join",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const id=Number(req.params.id);if(!(await pool.query(`SELECT id FROM rooms WHERE id=$1 AND is_public=TRUE`,[id])).rows[0])return res.status(404).json({ok:false,error:"ROOM_NOT_FOUND"});await pool.query(`INSERT INTO room_members(room_id,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING`,[id,u.id]);res.json({ok:true})});
  app.post("/api/rooms/:id/leave",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const id=Number(req.params.id),m=(await pool.query(`SELECT role FROM room_members WHERE room_id=$1 AND user_id=$2`,[id,u.id])).rows[0];if(m?.role==="owner"&&!isAdmin(u))return res.status(409).json({ok:false,error:"OWNER_CANNOT_LEAVE"});await pool.query(`DELETE FROM room_members WHERE room_id=$1 AND user_id=$2`,[id,u.id]);res.json({ok:true})});
}
