import {pool,requireAuth,emitUser} from "../runtime.mjs";
const audience=new Set(["everyone","friends","friends_of_friends","nobody"]),birthModes=new Set(["full","age","hidden"]),messageRules=new Set(["everyone","friends","nobody"]);
async function friends(a,b){return Boolean((await pool.query(`SELECT 1 FROM friendships WHERE status='accepted' AND ((requester_id=$1 AND addressee_id=$2) OR (requester_id=$2 AND addressee_id=$1))`,[a,b])).rows[0])}
async function mutual(a,b){return Number((await pool.query(`WITH a1 AS(SELECT CASE WHEN requester_id=$1 THEN addressee_id ELSE requester_id END id FROM friendships WHERE status='accepted' AND(requester_id=$1 OR addressee_id=$1)),b1 AS(SELECT CASE WHEN requester_id=$2 THEN addressee_id ELSE requester_id END id FROM friendships WHERE status='accepted' AND(requester_id=$2 OR addressee_id=$2)) SELECT COUNT(*)::int n FROM a1 JOIN b1 USING(id)`,[a,b])).rows[0]?.n||0)}
async function blocked(a,b){return Boolean((await pool.query(`SELECT 1 FROM user_blocks WHERE(blocker_id=$1 AND blocked_id=$2)OR(blocker_id=$2 AND blocked_id=$1)`,[a,b])).rows[0])}
async function privacy(id){await pool.query(`INSERT INTO profile_privacy(user_id)VALUES($1)ON CONFLICT DO NOTHING`,[id]);return(await pool.query(`SELECT * FROM profile_privacy WHERE user_id=$1`,[id])).rows[0]}
async function updatePrivacy(userId,b={}){const p=await privacy(userId),pick=(v,f)=>audience.has(v)?v:f;await pool.query(`UPDATE profile_privacy SET who_can_message=$2,who_can_add=$3,show_last_seen=$4,show_city=$5,birth_visibility=$6,who_can_see_posts=$7,who_can_see_story=$8,who_can_reply_story=$9,who_can_call=$10,who_can_see_friends=$11,who_can_invite_room=$12,show_online=$13,read_receipts=$14,message_requests_enabled=$15,who_can_mention=$16,who_can_tag=$17,updated_at=NOW()WHERE user_id=$1`,[userId,messageRules.has(b.whoCanMessage)?b.whoCanMessage:p.who_can_message,pick(b.whoCanAdd,p.who_can_add),b.showLastSeen??p.show_last_seen,b.showCity??p.show_city,birthModes.has(b.birthVisibility)?b.birthVisibility:p.birth_visibility,pick(b.whoCanSeePosts,p.who_can_see_posts),pick(b.whoCanSeeStory,p.who_can_see_story),pick(b.whoCanReplyStory,p.who_can_reply_story),pick(b.whoCanCall,p.who_can_call),pick(b.whoCanSeeFriends,p.who_can_see_friends),pick(b.whoCanInviteRoom,p.who_can_invite_room),b.showOnline??p.show_online,b.readReceipts??p.read_receipts,b.messageRequestsEnabled??p.message_requests_enabled,pick(b.whoCanMention,p.who_can_mention||"friends"),pick(b.whoCanTag,p.who_can_tag||"friends")]);return privacy(userId)}
async function allowed(rule,a,b){if(String(a)===String(b)||rule==="everyone")return true;if(rule==="nobody")return false;if(await friends(a,b))return true;return rule==="friends_of_friends"&&(await mutual(a,b))>0}
function age(v){if(!v)return null;const d=new Date(`${String(v).slice(0,10)}T00:00:00Z`),n=new Date();if(Number.isNaN(d.getTime()))return null;let x=n.getUTCFullYear()-d.getUTCFullYear();if(n.getUTCMonth()<d.getUTCMonth()||(n.getUTCMonth()===d.getUTCMonth()&&n.getUTCDate()<d.getUTCDate()))x--;return x>=0?x:null}
function validBirth(v){if(v===null||v==="")return null;if(!/^\d{4}-\d{2}-\d{2}$/.test(String(v)))return undefined;const d=new Date(`${v}T00:00:00Z`),x=age(v);return Number.isNaN(d.getTime())||d>new Date()||x===null||x>120?undefined:String(v)}
export function registerFghSocial(app){
 app.use(async(req,res,next)=>{try{const friendReq=req.method==="POST"&&req.path==="/api/friends/request",start=req.method==="POST"&&req.path.match(/^\/api\/chats\/with\/(\d+)$/),send=req.method==="POST"&&req.path.match(/^\/api\/chats\/(\d+)\/messages$/);if(!friendReq&&!start&&!send)return next();const u=await requireAuth(req,res);if(!u)return;if(friendReq){const target=Number(req.body?.userId);if(!Number.isInteger(target))return next();const targetUser=(await pool.query(`SELECT id FROM users WHERE id=$1 AND account_status='active'`,[target])).rows[0];if(!targetUser)return res.status(404).json({ok:false,error:"USER_NOT_FOUND"});if(await blocked(u.id,target))return res.status(403).json({ok:false,error:"USER_BLOCKED"});const p=await privacy(target);if(!await allowed(p.who_can_add||"everyone",u.id,target))return res.status(403).json({ok:false,error:"PRIVACY_RESTRICTED"})}if(start){const target=Number(start[1]);if(await blocked(u.id,target))return res.status(403).json({ok:false,error:"USER_BLOCKED"});if(!await friends(u.id,target)){const p=await privacy(target);if(!p.message_requests_enabled)return res.status(403).json({ok:false,error:"MESSAGE_REQUESTS_DISABLED"});if(!await allowed(p.who_can_message||"friends",u.id,target))return res.status(403).json({ok:false,error:"PRIVACY_RESTRICTED"});await pool.query(`INSERT INTO message_requests(requester_id,recipient_id,status)VALUES($1,$2,'pending')ON CONFLICT(requester_id,recipient_id)DO UPDATE SET status=CASE WHEN message_requests.status='accepted'THEN'accepted'ELSE'pending'END,updated_at=NOW()`,[u.id,target]);emitUser(target,"message-request:new",{requester_id:u.id,requester_name:u.display_name,requester_username:u.username})}}if(send){const c=(await pool.query(`SELECT user1_id,user2_id FROM direct_conversations WHERE id=$1 AND(user1_id=$2 OR user2_id=$2)`,[Number(send[1]),u.id])).rows[0];if(c){const peer=String(c.user1_id)===String(u.id)?c.user2_id:c.user1_id,r=(await pool.query(`SELECT requester_id,recipient_id FROM message_requests WHERE((requester_id=$1 AND recipient_id=$2)OR(requester_id=$2 AND recipient_id=$1))AND status='pending' ORDER BY id DESC LIMIT 1`,[u.id,peer])).rows[0];if(r&&String(r.recipient_id)===String(u.id))return res.status(409).json({ok:false,error:"MESSAGE_REQUEST_PENDING"})}}next()}catch(e){next(e)}});
 app.get("/api/profile/social",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const p=await privacy(u.id),x=(await pool.query(`SELECT id,username,display_name,gender,bio,avatar_url,cover_url,birth_date,pinned_post_id,verified,role,created_at FROM users WHERE id=$1`,[u.id])).rows[0],badges=(await pool.query(`SELECT badge FROM user_badges WHERE user_id=$1 ORDER BY granted_at`,[u.id])).rows.map(v=>v.badge);res.json({ok:true,user:{...x,age:age(x.birth_date)},privacy:p,badges})});
 app.patch("/api/profile/social",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const d=validBirth(req.body?.birthDate);if(d===undefined)return res.status(400).json({ok:false,error:"INVALID_BIRTH_DATE"});const g=req.body?.gender;if(g!==undefined&&!['male','female'].includes(g))return res.status(400).json({ok:false,error:"INVALID_GENDER"});await pool.query(`UPDATE users SET birth_date=$1,gender=COALESCE($2,gender),updated_at=NOW()WHERE id=$3`,[d,g||null,u.id]);const m=birthModes.has(req.body?.birthVisibility)?req.body.birthVisibility:"age";await pool.query(`INSERT INTO profile_privacy(user_id,birth_visibility)VALUES($1,$2)ON CONFLICT(user_id)DO UPDATE SET birth_visibility=EXCLUDED.birth_visibility,updated_at=NOW()`,[u.id,m]);res.json({ok:true})});
 app.get("/api/privacy/v2",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;res.json({ok:true,privacy:await privacy(u.id)})});
 app.patch("/api/privacy/v2",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;res.json({ok:true,privacy:await updatePrivacy(u.id,req.body||{})})});
 app.get("/api/privacy",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;res.json({ok:true,privacy:await privacy(u.id),compatibility:"v2"})});
 app.patch("/api/privacy",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;res.json({ok:true,privacy:await updatePrivacy(u.id,req.body||{}),compatibility:"v2"})});
 app.get("/api/users/:id/social",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const id=Number(req.params.id);if(!Number.isSafeInteger(id)||id<=0)return res.status(400).json({ok:false,error:"INVALID_USER"});const x=(await pool.query(`SELECT id,username,display_name,gender,bio,avatar_url,cover_url,birth_date,pinned_post_id,verified,role,created_at FROM users WHERE id=$1 AND account_status='active'`,[id])).rows[0];if(!x||String(id)!==String(u.id)&&await blocked(u.id,id))return res.status(404).json({ok:false,error:"USER_NOT_FOUND"});const p=await privacy(id),self=String(id)===String(u.id),badges=(await pool.query(`SELECT badge FROM user_badges WHERE user_id=$1 ORDER BY granted_at`,[id])).rows.map(v=>v.badge);res.json({ok:true,user:{...x,birth_date:self||p.birth_visibility==='full'?x.birth_date:null,age:self||p.birth_visibility!=='hidden'?age(x.birth_date):null},relation:{friends:await friends(u.id,id),mutual_count:await mutual(u.id,id)},badges})});
 app.get("/api/users/:id/mutual-friends",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const id=Number(req.params.id);if(!Number.isSafeInteger(id)||id<=0)return res.status(400).json({ok:false,error:"INVALID_USER"});const target=(await pool.query(`SELECT id FROM users WHERE id=$1 AND account_status='active'`,[id])).rows[0];if(!target||String(id)!==String(u.id)&&await blocked(u.id,id))return res.status(404).json({ok:false,error:"USER_NOT_FOUND"});const p=await privacy(id);if(!await allowed(p.who_can_see_friends||"friends",u.id,id))return res.status(403).json({ok:false,error:"PRIVACY_RESTRICTED"});const rows=(await pool.query(`WITH a AS(SELECT CASE WHEN requester_id=$1 THEN addressee_id ELSE requester_id END id FROM friendships WHERE status='accepted'AND(requester_id=$1 OR addressee_id=$1)),b AS(SELECT CASE WHEN requester_id=$2 THEN addressee_id ELSE requester_id END id FROM friendships WHERE status='accepted'AND(requester_id=$2 OR addressee_id=$2))SELECT x.id,x.username,x.display_name,x.gender,x.avatar_url FROM a JOIN b USING(id)JOIN users x ON x.id=a.id WHERE x.account_status='active' AND NOT EXISTS(SELECT 1 FROM user_blocks ub WHERE (ub.blocker_id=$1 AND ub.blocked_id=x.id) OR (ub.blocked_id=$1 AND ub.blocker_id=x.id)) ORDER BY x.display_name LIMIT 100`,[u.id,id])).rows;res.json({ok:true,friends:rows,count:rows.length})});
 app.get("/api/friends/suggestions-v2",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const rows=(await pool.query(`SELECT x.id,x.username,x.display_name,x.gender,x.avatar_url,x.bio FROM users x WHERE x.id<>$1 AND x.account_status='active' AND NOT EXISTS(SELECT 1 FROM friendships f WHERE LEAST(f.requester_id,f.addressee_id)=LEAST($1,x.id)AND GREATEST(f.requester_id,f.addressee_id)=GREATEST($1,x.id))AND NOT EXISTS(SELECT 1 FROM user_blocks b WHERE(b.blocker_id=$1 AND b.blocked_id=x.id)OR(b.blocker_id=x.id AND b.blocked_id=$1))ORDER BY x.created_at DESC LIMIT 30`,[u.id])).rows;for(const x of rows)x.mutual_count=await mutual(u.id,x.id);rows.sort((a,b)=>b.mutual_count-a.mutual_count);res.json({ok:true,suggestions:rows})});
 app.get("/api/profile/completeness",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const x=(await pool.query(`SELECT display_name,username,bio,avatar_url,cover_url,birth_date,gender FROM users WHERE id=$1`,[u.id])).rows[0],l=(await pool.query(`SELECT city FROM user_locations WHERE user_id=$1`,[u.id])).rows[0]||{},v=[x.display_name,x.username,x.bio,x.avatar_url,x.cover_url,x.birth_date,x.gender,l.city],n=v.filter(Boolean).length;res.json({ok:true,percent:Math.round(n/v.length*100),completed:n,total:v.length})});
 app.post("/api/profile/pin-post/:postId",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const id=Number(req.params.postId);if(!(await pool.query(`SELECT 1 FROM posts WHERE id=$1 AND user_id=$2 AND deleted_at IS NULL`,[id,u.id])).rows[0])return res.status(404).json({ok:false,error:"POST_NOT_FOUND"});await pool.query(`UPDATE users SET pinned_post_id=$1 WHERE id=$2`,[id,u.id]);res.json({ok:true,pinnedPostId:id})});
 app.delete("/api/profile/pin-post",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;await pool.query(`UPDATE users SET pinned_post_id=NULL WHERE id=$1`,[u.id]);res.json({ok:true})});
 app.get("/api/message-requests",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const rows=(await pool.query(`SELECT mr.id,mr.created_at,x.id user_id,x.username,x.display_name,x.gender,x.avatar_url,c.id conversation_id,(SELECT dm.body FROM direct_messages dm WHERE dm.conversation_id=c.id AND dm.deleted_at IS NULL ORDER BY dm.id DESC LIMIT 1)last_message,(SELECT dm.created_at FROM direct_messages dm WHERE dm.conversation_id=c.id ORDER BY dm.id DESC LIMIT 1)last_message_at FROM message_requests mr JOIN users x ON x.id=mr.requester_id LEFT JOIN direct_conversations c ON LEAST(c.user1_id,c.user2_id)=LEAST(mr.requester_id,mr.recipient_id)AND GREATEST(c.user1_id,c.user2_id)=GREATEST(mr.requester_id,mr.recipient_id)WHERE mr.recipient_id=$1 AND mr.status='pending' ORDER BY COALESCE((SELECT MAX(dm.created_at)FROM direct_messages dm WHERE dm.conversation_id=c.id),mr.created_at)DESC`,[u.id])).rows;res.json({ok:true,requests:rows,count:rows.length})});
 app.get("/api/message-requests/count",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const n=Number((await pool.query(`SELECT COUNT(*)::int n FROM message_requests WHERE recipient_id=$1 AND status='pending'`,[u.id])).rows[0]?.n||0);res.json({ok:true,count:n})});
 app.post("/api/message-requests/:id/respond",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const id=Number(req.params.id),a=req.body?.action;if(!['accept','delete','block'].includes(a))return res.status(400).json({ok:false,error:"INVALID_ACTION"});const r=(await pool.query(`SELECT * FROM message_requests WHERE id=$1 AND recipient_id=$2 AND status='pending'`,[id,u.id])).rows[0];if(!r)return res.status(404).json({ok:false,error:"REQUEST_NOT_FOUND"});if(a==='accept'){await pool.query(`UPDATE message_requests SET status='accepted',updated_at=NOW()WHERE id=$1`,[id]);emitUser(r.requester_id,"message-request:accepted",{recipient_id:u.id});return res.json({ok:true,status:'accepted'})}if(a==='block')await pool.query(`INSERT INTO user_blocks(blocker_id,blocked_id)VALUES($1,$2)ON CONFLICT DO NOTHING`,[u.id,r.requester_id]);const c=(await pool.query(`SELECT id FROM direct_conversations WHERE LEAST(user1_id,user2_id)=LEAST($1,$2)AND GREATEST(user1_id,user2_id)=GREATEST($1,$2)`,[r.requester_id,r.recipient_id])).rows[0];if(c)await pool.query(`DELETE FROM direct_conversations WHERE id=$1`,[c.id]);await pool.query(`UPDATE message_requests SET status='rejected',updated_at=NOW()WHERE id=$1`,[id]);res.json({ok:true,status:a==='block'?'blocked':'deleted'})});
}
