import {pool,requireAuth,emitUser,clean} from "../runtime.mjs";

const audienceValues=new Set(["everyone","friends","friends_of_friends","nobody"]);
const birthValues=new Set(["full","age","hidden"]);
const simpleValues=new Set(["everyone","friends","nobody"]);

async function areFriends(a,b){return Boolean((await pool.query(`SELECT 1 FROM friendships WHERE status='accepted' AND ((requester_id=$1 AND addressee_id=$2) OR (requester_id=$2 AND addressee_id=$1))`,[a,b])).rows[0])}
async function mutualCount(a,b){return Number((await pool.query(`WITH af AS (SELECT CASE WHEN requester_id=$1 THEN addressee_id ELSE requester_id END id FROM friendships WHERE status='accepted' AND (requester_id=$1 OR addressee_id=$1)),bf AS (SELECT CASE WHEN requester_id=$2 THEN addressee_id ELSE requester_id END id FROM friendships WHERE status='accepted' AND (requester_id=$2 OR addressee_id=$2)) SELECT COUNT(*)::int n FROM af JOIN bf USING(id)`,[a,b])).rows[0]?.n||0)}
async function blocked(a,b){return Boolean((await pool.query(`SELECT 1 FROM user_blocks WHERE (blocker_id=$1 AND blocked_id=$2) OR (blocker_id=$2 AND blocked_id=$1) LIMIT 1`,[a,b])).rows[0])}
async function privacyFor(id){await pool.query(`INSERT INTO profile_privacy(user_id) VALUES($1) ON CONFLICT DO NOTHING`,[id]);return (await pool.query(`SELECT * FROM profile_privacy WHERE user_id=$1`,[id])).rows[0]}
async function allows(rule,viewer,target){if(String(viewer)===String(target))return true;if(rule==="everyone")return true;if(rule==="nobody")return false;if(await areFriends(viewer,target))return true;if(rule==="friends_of_friends")return (await mutualCount(viewer,target))>0;return false}
function ageFrom(date){if(!date)return null;const d=new Date(`${date}T00:00:00Z`);if(Number.isNaN(d.getTime()))return null;const now=new Date();let age=now.getUTCFullYear()-d.getUTCFullYear();const m=now.getUTCMonth()-d.getUTCMonth();if(m<0||(m===0&&now.getUTCDate()<d.getUTCDate()))age--;return age>=0?age:null}
function validBirth(v){if(v===null||v==="")return null;if(!/^\d{4}-\d{2}-\d{2}$/.test(String(v)))return undefined;const d=new Date(`${v}T00:00:00Z`),now=new Date();if(Number.isNaN(d.getTime())||d>now)return undefined;const age=ageFrom(v);if(age===null||age>120)return undefined;return String(v)}

export function registerFghSocial(app){
  // These guards are registered before the legacy social/messaging routes.
  app.use(async(req,res,next)=>{try{
    const u=await requireAuth(req,res);if(!u)return;
    if(req.method==="POST"&&req.path==="/api/friends/request"){
      const target=Number(req.body?.userId);if(!Number.isInteger(target))return next();
      if(await blocked(u.id,target))return res.status(403).json({ok:false,error:"USER_BLOCKED"});
      const p=await privacyFor(target);if(!await allows(p.who_can_add||"everyone",u.id,target))return res.status(403).json({ok:false,error:"PRIVACY_RESTRICTED"});
    }
    const start=req.path.match(/^\/api\/chats\/with\/(\d+)$/);
    if(req.method==="POST"&&start){
      const target=Number(start[1]);if(await blocked(u.id,target))return res.status(403).json({ok:false,error:"USER_BLOCKED"});
      if(!await areFriends(u.id,target)){
        const p=await privacyFor(target),rule=p.who_can_message||"friends";
        if(!p.message_requests_enabled)return res.status(403).json({ok:false,error:"MESSAGE_REQUESTS_DISABLED"});
        if(!await allows(rule,u.id,target))return res.status(403).json({ok:false,error:"PRIVACY_RESTRICTED"});
        await pool.query(`INSERT INTO message_requests(requester_id,recipient_id,status) VALUES($1,$2,'pending') ON CONFLICT(requester_id,recipient_id) DO UPDATE SET status=CASE WHEN message_requests.status='accepted' THEN 'accepted' ELSE 'pending' END,updated_at=NOW()`,[u.id,target]);
        emitUser(target,"message-request:new",{requester_id:u.id,requester_name:u.display_name,requester_username:u.username});
      }
    }
    const send=req.path.match(/^\/api\/chats\/(\d+)\/messages$/);
    if(req.method==="POST"&&send){
      const conv=(await pool.query(`SELECT user1_id,user2_id FROM direct_conversations WHERE id=$1 AND (user1_id=$2 OR user2_id=$2)`,[Number(send[1]),u.id])).rows[0];
      if(conv){const peer=String(conv.user1_id)===String(u.id)?conv.user2_id:conv.user1_id;const pending=(await pool.query(`SELECT requester_id,recipient_id,status FROM message_requests WHERE ((requester_id=$1 AND recipient_id=$2) OR (requester_id=$2 AND recipient_id=$1)) AND status='pending' ORDER BY id DESC LIMIT 1`,[u.id,peer])).rows[0];if(pending&&String(pending.recipient_id)===String(u.id))return res.status(409).json({ok:false,error:"MESSAGE_REQUEST_PENDING"})}
    }
    next();
  }catch(e){next(e)}});

  app.get("/api/profile/social",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const p=await privacyFor(u.id),row=(await pool.query(`SELECT id,username,display_name,gender,bio,avatar_url,cover_url,birth_date,pinned_post_id,verified,role,created_at FROM users WHERE id=$1`,[u.id])).rows[0],badges=(await pool.query(`SELECT badge FROM user_badges WHERE user_id=$1 ORDER BY granted_at`,[u.id])).rows.map(x=>x.badge);res.json({ok:true,user:{...row,age:ageFrom(row.birth_date)},privacy:p,badges})});
  app.patch("/api/profile/social",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const birth=validBirth(req.body?.birthDate);if(birth===undefined)return res.status(400).json({ok:false,error:"INVALID_BIRTH_DATE"});const gender=req.body?.gender;if(gender!==undefined&&!['male','female'].includes(gender))return res.status(400).json({ok:false,error:"INVALID_GENDER"});await pool.query(`UPDATE users SET birth_date=$1,gender=COALESCE($2,gender),updated_at=NOW() WHERE id=$3`,[birth,gender||null,u.id]);const visibility=birthValues.has(req.body?.birthVisibility)?req.body.birthVisibility:"age";await pool.query(`INSERT INTO profile_privacy(user_id,birth_visibility) VALUES($1,$2) ON CONFLICT(user_id) DO UPDATE SET birth_visibility=EXCLUDED.birth_visibility,updated_at=NOW()`,[u.id,visibility]);res.json({ok:true})});

  app.get("/api/privacy/v2",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;res.json({ok:true,privacy:await privacyFor(u.id)})});
  app.patch("/api/privacy/v2",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const current=await privacyFor(u.id),b=req.body||{};const pick=(value,fallback)=>audienceValues.has(value)?value:fallback,whoMessage=simpleValues.has(b.whoCanMessage)?b.whoCanMessage:current.who_can_message,whoAdd=audienceValues.has(b.whoCanAdd)?b.whoCanAdd:current.who_can_add,birth=birthValues.has(b.birthVisibility)?b.birthVisibility:current.birth_visibility;await pool.query(`UPDATE profile_privacy SET who_can_message=$2,who_can_add=$3,show_last_seen=$4,show_city=$5,birth_visibility=$6,who_can_see_posts=$7,who_can_see_story=$8,who_can_reply_story=$9,who_can_call=$10,who_can_see_friends=$11,who_can_invite_room=$12,show_online=$13,read_receipts=$14,message_requests_enabled=$15,updated_at=NOW() WHERE user_id=$1`,[u.id,whoMessage,whoAdd,b.showLastSeen??current.show_last_seen,b.showCity??current.show_city,birth,pick(b.whoCanSeePosts,current.who_can_see_posts),pick(b.whoCanSeeStory,current.who_can_see_story),pick(b.whoCanReplyStory,current.who_can_reply_story),pick(b.whoCanCall,current.who_can_call),pick(b.whoCanSeeFriends,current.who_can_see_friends),pick(b.whoCanInviteRoom,current.who_can_invite_room),b.showOnline??current.show_online,b.readReceipts??current.read_receipts,b.messageRequestsEnabled??current.message_requests_enabled]);res.json({ok:true,privacy:await privacyFor(u.id)})});

  app.get("/api/users/:id/social",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const target=Number(req.params.id);if(!Number.isInteger(target))return res.status(400).json({ok:false,error:"INVALID_USER"});const p=await privacyFor(target),row=(await pool.query(`SELECT id,username,display_name,gender,bio,avatar_url,cover_url,birth_date,pinned_post_id,verified,role,created_at FROM users WHERE id=$1 AND account_status='active'`,[target])).rows[0];if(!row)return res.status(404).json({ok:false,error:"USER_NOT_FOUND"});const friends=await areFriends(u.id,target),mutual=await mutualCount(u.id,target),age=ageFrom(row.birth_date),birthVisible=String(u.id)===String(target)||p.birth_visibility==='full',ageVisible=String(u.id)===String(target)||p.birth_visibility!=='hidden',badges=(await pool.query(`SELECT badge FROM user_badges WHERE user_id=$1 ORDER BY granted_at`,[target])).rows.map(x=>x.badge);res.json({ok:true,user:{...row,birth_date:birthVisible?row.birth_date:null,age:ageVisible?age:null},relation:{friends,mutual_count:mutual},badges})});
  app.get("/api/users/:id/mutual-friends",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const target=Number(req.params.id),rows=(await pool.query(`WITH af AS (SELECT CASE WHEN requester_id=$1 THEN addressee_id ELSE requester_id END id FROM friendships WHERE status='accepted' AND (requester_id=$1 OR addressee_id=$1)),bf AS (SELECT CASE WHEN requester_id=$2 THEN addressee_id ELSE requester_id END id FROM friendships WHERE status='accepted' AND (requester_id=$2 OR addressee_id=$2)) SELECT x.id,x.username,x.display_name,x.gender,x.avatar_url FROM af JOIN bf USING(id) JOIN users x ON x.id=af.id WHERE x.account_status='active' ORDER BY x.display_name LIMIT 100`,[u.id,target])).rows;res.json({ok:true,friends:rows,count:rows.length})});
  app.get("/api/friends/suggestions-v2",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const rows=(await pool.query(`SELECT x.id,x.username,x.display_name,x.gender,x.avatar_url,x.bio,COUNT(m.id)::int mutual_count FROM users x LEFT JOIN LATERAL (SELECT f1.id FROM friendships f1 JOIN friendships f2 ON (CASE WHEN f1.requester_id=$1 THEN f1.addressee_id ELSE f1.requester_id END)=(CASE WHEN f2.requester_id=x.id THEN f2.addressee_id ELSE f2.requester_id END) WHERE f1.status='accepted' AND f2.status='accepted' AND (f1.requester_id=$1 OR f1.addressee_id=$1) AND (f2.requester_id=x.id OR f2.addressee_id=x.id)) m ON TRUE WHERE x.id<>$1 AND x.account_status='active' AND NOT EXISTS(SELECT 1 FROM friendships f WHERE LEAST(f.requester_id,f.addressee_id)=LEAST($1,x.id) AND GREATEST(f.requester_id,f.addressee_id)=GREATEST($1,x.id)) AND NOT EXISTS(SELECT 1 FROM user_blocks b WHERE (b.blocker_id=$1 AND b.blocked_id=x.id) OR (b.blocker_id=x.id AND b.blocked_id=$1)) GROUP BY x.id ORDER BY COUNT(m.id) DESC,x.created_at DESC LIMIT 30`,[u.id])).rows;res.json({ok:true,suggestions:rows})});

  app.get("/api/profile/completeness",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const row=(await pool.query(`SELECT display_name,username,bio,avatar_url,cover_url,birth_date,gender FROM users WHERE id=$1`,[u.id])).rows[0],loc=(await pool.query(`SELECT city FROM user_locations WHERE user_id=$1`,[u.id])).rows[0]||{},fields=[row.display_name,row.username,row.bio,row.avatar_url,row.cover_url,row.birth_date,row.gender,loc.city],done=fields.filter(Boolean).length;res.json({ok:true,percent:Math.round(done/fields.length*100),completed:done,total:fields.length})});
  app.post("/api/profile/pin-post/:postId",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const postId=Number(req.params.postId),post=(await pool.query(`SELECT id FROM posts WHERE id=$1 AND user_id=$2`,[postId,u.id])).rows[0];if(!post)return res.status(404).json({ok:false,error:"POST_NOT_FOUND"});await pool.query(`UPDATE users SET pinned_post_id=$1,updated_at=NOW() WHERE id=$2`,[postId,u.id]);res.json({ok:true,pinnedPostId:postId})});
  app.delete("/api/profile/pin-post",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;await pool.query(`UPDATE users SET pinned_post_id=NULL,updated_at=NOW() WHERE id=$1`,[u.id]);res.json({ok:true})});

  app.get("/api/message-requests",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const rows=(await pool.query(`SELECT mr.id,mr.status,mr.created_at,mr.updated_at,x.id user_id,x.username,x.display_name,x.gender,x.avatar_url,c.id conversation_id,(SELECT CASE WHEN dm.deleted_at IS NULL THEN dm.body ELSE 'تم حذف الرسالة' END FROM direct_messages dm WHERE dm.conversation_id=c.id ORDER BY dm.id DESC LIMIT 1) last_message,(SELECT dm.created_at FROM direct_messages dm WHERE dm.conversation_id=c.id ORDER BY dm.id DESC LIMIT 1) last_message_at FROM message_requests mr JOIN users x ON x.id=mr.requester_id LEFT JOIN direct_conversations c ON LEAST(c.user1_id,c.user2_id)=LEAST(mr.requester_id,mr.recipient_id) AND GREATEST(c.user1_id,c.user2_id)=GREATEST(mr.requester_id,mr.recipient_id) WHERE mr.recipient_id=$1 AND mr.status='pending' ORDER BY COALESCE((SELECT MAX(dm.created_at) FROM direct_messages dm WHERE dm.conversation_id=c.id),mr.created_at) DESC`,[u.id])).rows;res.json({ok:true,requests:rows,count:rows.length})});
  app.get("/api/message-requests/count",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const count=Number((await pool.query(`SELECT COUNT(*)::int n FROM message_requests WHERE recipient_id=$1 AND status='pending'`,[u.id])).rows[0]?.n||0);res.json({ok:true,count})});
  app.post("/api/message-requests/:id/respond",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const id=Number(req.params.id),action=req.body?.action;if(!['accept','delete','block'].includes(action))return res.status(400).json({ok:false,error:"INVALID_ACTION"});const mr=(await pool.query(`SELECT * FROM message_requests WHERE id=$1 AND recipient_id=$2 AND status='pending'`,[id,u.id])).rows[0];if(!mr)return res.status(404).json({ok:false,error:"REQUEST_NOT_FOUND"});if(action==='accept'){await pool.query(`UPDATE message_requests SET status='accepted',updated_at=NOW() WHERE id=$1`,[id]);emitUser(mr.requester_id,"message-request:accepted",{recipient_id:u.id});return res.json({ok:true,status:'accepted'})}const conv=(await pool.query(`SELECT id FROM direct_conversations WHERE LEAST(user1_id,user2_id)=LEAST($1,$2) AND GREATEST(user1_id,user2_id)=GREATEST($1,$2)`,[mr.requester_id,mr.recipient_id])).rows[0];if(action==='block')await pool.query(`INSERT INTO user_blocks(blocker_id,blocked_id) VALUES($1,$2) ON CONFLICT DO NOTHING`,[u.id,mr.requester_id]);if(conv)await pool.query(`DELETE FROM direct_conversations WHERE id=$1`,[conv.id]);await pool.query(`UPDATE message_requests SET status='rejected',updated_at=NOW() WHERE id=$1`,[id]);res.json({ok:true,status:action==='block'?'blocked':'deleted'})});

  // Replace the legacy chat list so pending incoming requests stay outside the main inbox.
  app.get("/api/chats",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const rows=(await pool.query(`SELECT c.id,c.updated_at,x.id user_id,x.username,x.display_name,x.gender,x.avatar_url,x.last_seen_at,(vp.last_seen>NOW()-INTERVAL '75 seconds') online,(SELECT CASE WHEN dm.deleted_at IS NULL THEN dm.body ELSE 'تم حذف الرسالة' END FROM direct_messages dm WHERE dm.conversation_id=c.id ORDER BY dm.id DESC LIMIT 1) last_message,(SELECT dm.created_at FROM direct_messages dm WHERE dm.conversation_id=c.id ORDER BY dm.id DESC LIMIT 1) last_message_at,GREATEST(0,(SELECT COUNT(*)::int FROM direct_messages dm WHERE dm.conversation_id=c.id AND dm.sender_id<>$1 AND dm.id>COALESCE((SELECT last_message_id FROM message_reads WHERE kind='direct' AND scope_id=c.id AND user_id=$1),0))) unread_count FROM direct_conversations c JOIN users x ON x.id=CASE WHEN c.user1_id=$1 THEN c.user2_id ELSE c.user1_id END LEFT JOIN visitor_presence vp ON vp.user_id=x.id LEFT JOIN message_requests mr ON mr.requester_id=x.id AND mr.recipient_id=$1 AND mr.status='pending' WHERE (c.user1_id=$1 OR c.user2_id=$1) AND mr.id IS NULL ORDER BY c.updated_at DESC`,[u.id])).rows;res.json({ok:true,chats:rows})});
}
