import {registerAuthRegistration} from "./auth-registration.mjs";
import {registerAuthSession} from "./auth-session.mjs";
import {registerCoreRooms} from "./core-rooms.mjs";
import {registerCoreMessaging} from "./core-messaging.mjs";
import {registerCoreSocial} from "./core-social.mjs";
import {registerCoreLocation} from "./core-location.mjs";
import {registerCoreAdminRooms} from "./core-admin-rooms.mjs";
import {registerCoreAdminControl} from "./core-admin-control.mjs";
import {registerCorePresence} from "./core-presence.mjs";
import {registerFghSocial} from "./fgh-social.mjs";
import {registerGroupMNEngagement} from "./group-mn-engagement.mjs";
import {registerGroupOAdmin} from "./group-o-admin.mjs";
import {registerFeedMode} from "./feed-mode.mjs";
import {registerStabilityOverrides} from "./stability-overrides.mjs";
import {registerTv} from "./tv.mjs";
import {registerTvAdmin} from "./tv-admin.mjs";
import {registerLive} from "./live.mjs";
import {registerLiveSocial} from "./live-social.mjs";
import {registerLiveHardening} from "./live-hardening.mjs";

export function registerExplicitRoutes(app){
  registerAuthRegistration(app);
  registerAuthSession(app);
  registerFghSocial(app);
  registerCoreRooms(app);
  registerCoreMessaging(app);
  registerCoreSocial(app);
  registerCoreLocation(app);
  registerCoreAdminRooms(app);
  registerCoreAdminControl(app);
  registerCorePresence(app);
  registerGroupMNEngagement(app);
  registerFeedMode(app);
  registerStabilityOverrides(app);
  registerTv(app);
  registerTvAdmin(app);
  registerLiveHardening(app);
  registerLive(app);
  registerLiveSocial(app);
  registerGroupOAdmin(app);
}
