import {pool,requireAuth,turnConfig,clean} from "../runtime.mjs";

const MAX_VIEWERS=8,VIEWER_TTL_SECONDS=24;
async function purge(sessionId){
  await pool.query(`DELETE FROM live_viewers WHERE session_id=$1 AND last_seen_at<NOW()-($2::text||' seconds')::interval`,[sessionId,String(VIEWER_TTL_SECONDS)]);
  await pool.query(`DELETE FROM live_signals WHERE session_id=$1 AND created_at<NOW()-INTERVAL '10 minutes'`,[sessionId]);
}
async function sessionFor(id){return(await pool.query(`SELECT s.*,u.username,u.display_name,u.avatar_url,u.gender FROM live_sessions s JOIN users u ON u.id=s.host_id WHERE s.id=$1`,[id])).rows[0]||null}
async function activeViewerCount(id){await purge(id);return Number((await pool.query(`SELECT COUNT(*)::int c FROM live_viewers WHERE session_id=$1`,[id])).rows[0]?.c||0)}
async function allowed(session,u){if(!session||session.status!=="active")return false;if(Number(session.host_id)===Number(u.id))return true;const row=(await pool.query(`SELECT 1 FROM live_viewers WHERE session_id=$1 AND user_id=$2 AND last_seen_at>=NOW()-($3::text||' seconds')::interval`,[session.id,u.id,String(VIEWER_TTL_SECONDS)])).rowCount;return row>0}
async function updatePeak(id){const count=await activeViewerCount(id);await pool.query(`UPDATE live_sessions SET peak_viewers=GREATEST(peak_viewers,$2) WHERE id=$1`,[id,count]);return count}
async function wipeTransient(id){await pool.query(`DELETE FROM live_signals WHERE session_id=$1`,[id]);await pool.query(`DELETE FROM live_messages WHERE session_id=$1`,[id]);await pool.query(`DELETE FROM live_reactions WHERE session_id=$1`,[id]);await pool.query(`DELETE FROM live_viewers WHERE session_id=$1`,[id])}
export function registerLive(app){
  app.get('/api/live',async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const rows=(await pool.query(`SELECT s.id,s.host_id,s.title,s.started_at,s.peak_viewers,u.username,u.display_name,u.avatar_url,u.gender,(SELECT COUNT(*)::int FROM live_viewers v WHERE v.session_id=s.id AND v.last_seen_at>=NOW()-($1::text||' seconds')::interval) viewers_count FROM live_sessions s JOIN users u ON u.id=s.host_id WHERE s.status='active' ORDER BY viewers_count DESC,s.started_at DESC LIMIT 30`,[String(VIEWER_TTL_SECONDS)])).rows;res.json({ok:true,lives:rows,maxViewers:MAX_VIEWERS,scaleMode:'p2p-beta'})});
  app.post('/api/live',async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const title=clean(req.body?.title||`${u.display_name} لايف`,90)||`${u.display_name} لايف`;const existing=(await pool.query(`SELECT id FROM live_sessions WHERE host_id=$1 AND status='active' ORDER BY id DESC LIMIT 1`,[u.id])).rows[0];if(existing){await pool.query(`UPDATE live_sessions SET status='ended',ended_at=NOW() WHERE id=$1`,[existing.id]);await wipeTransient(existing.id)}const row=(await pool.query(`INSERT INTO live_sessions(host_id,title) VALUES($1,$2) RETURNING *`,[u.id,title])).rows[0];res.status(201).json({ok:true,live:row,maxViewers:MAX_VIEWERS,scaleMode:'p2p-beta'})});
  app.get('/api/live/:id',async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const s=await sessionFor(Number(req.params.id));if(!s)return res.status(404).json({ok:false,error:'LIVE_NOT_FOUND'});const viewers=s.status==='active'?await activeViewerCount(s.id):0,messages=(await pool.query(`SELECT m.id,m.user_id,m.body,m.created_at,u.username,u.display_name,u.avatar_url FROM live_messages m JOIN users u ON u.id=m.user_id WHERE m.session_id=$1 ORDER BY m.id DESC LIMIT 80`,[s.id])).rows.reverse(),reactions=(await pool.query(`SELECT reaction,COUNT(*)::int count FROM live_reactions WHERE session_id=$1 AND created_at>NOW()-INTERVAL '15 minutes' GROUP BY reaction`,[s.id])).rows;res.json({ok:true,live:{...s,viewers_count:viewers},messages,reactions,maxViewers:MAX_VIEWERS,viewerId:u.id,iceServers:turnConfig(u.id).iceServers})});
  app.post('/api/live/:id/join',async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const s=await sessionFor(Number(req.params.id));if(!s||s.status!=="active")return res.status(404).json({ok:false,error:'LIVE_ENDED'});if(Number(s.host_id)===Number(u.id))return res.json({ok:true,host:true,viewerId:u.id});await purge(s.id);const count=await activeViewerCount(s.id),already=(await pool.query(`SELECT 1 FROM live_viewers WHERE session_id=$1 AND user_id=$2`,[s.id,u.id])).rowCount>0;if(!already&&count>=MAX_VIEWERS)return res.status(409).json({ok:false,error:'LIVE_FULL'});await pool.query(`INSERT INTO live_viewers(session_id,user_id) VALUES($1,$2) ON CONFLICT(session_id,user_id) DO UPDATE SET last_seen_at=NOW()`,[s.id,u.id]);const current=await updatePeak(s.id);res.json({ok:true,viewerId:u.id,hostId:Number(s.host_id),viewers:current,maxViewers:MAX_VIEWERS,iceServers:turnConfig(u.id).iceServers})});
  app.post('/api/live/:id/heartbeat',async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const s=await sessionFor(Number(req.params.id));if(!s||s.status!=="active")return res.status(410).json({ok:false,error:'LIVE_ENDED'});if(Number(s.host_id)!==Number(u.id))await pool.query(`UPDATE live_viewers SET last_seen_at=NOW() WHERE session_id=$1 AND user_id=$2`,[s.id,u.id]);const viewers=await updatePeak(s.id);res.json({ok:true,viewers})});
  app.get('/api/live/:id/viewers',async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const s=await sessionFor(Number(req.params.id));if(!s)return res.status(404).json({ok:false,error:'LIVE_NOT_FOUND'});if(Number(s.host_id)!==Number(u.id))return res.status(403).json({ok:false,error:'FORBIDDEN'});await purge(s.id);const rows=(await pool.query(`SELECT v.user_id,u.username,u.display_name,u.avatar_url FROM live_viewers v JOIN users u ON u.id=v.user_id WHERE v.session_id=$1 ORDER BY v.joined_at`,[s.id])).rows;res.json({ok:true,viewers:rows,maxViewers:MAX_VIEWERS})});
  app.post('/api/live/:id/signals',async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const s=await sessionFor(Number(req.params.id));if(!s||s.status!=="active")return res.status(410).json({ok:false,error:'LIVE_ENDED'});if(!(await allowed(s,u)))return res.status(403).json({ok:false,error:'FORBIDDEN'});const kind=String(req.body?.kind||''),payload=req.body?.payload,recipient=Number(req.body?.recipientId);if(!['offer','answer','ice'].includes(kind)||!payload||typeof payload!=='object'||!Number.isInteger(recipient))return res.status(400).json({ok:false,error:'BAD_SIGNAL'});const host=Number(s.host_id),sender=Number(u.id);if(sender===host){const active=(await pool.query(`SELECT 1 FROM live_viewers WHERE session_id=$1 AND user_id=$2 AND last_seen_at>=NOW()-($3::text||' seconds')::interval`,[s.id,recipient,String(VIEWER_TTL_SECONDS)])).rowCount;if(!active)return res.status(409).json({ok:false,error:'VIEWER_GONE'})}else if(recipient!==host)return res.status(403).json({ok:false,error:'BAD_RECIPIENT'});const row=(await pool.query(`INSERT INTO live_signals(session_id,sender_id,recipient_id,kind,payload) VALUES($1,$2,$3,$4,$5) RETURNING id`,[s.id,sender,recipient,kind,payload])).rows[0];res.status(201).json({ok:true,id:row.id})});
  app.get('/api/live/:id/signals',async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const s=await sessionFor(Number(req.params.id));if(!s||s.status!=="active")return res.status(410).json({ok:false,error:'LIVE_ENDED'});if(!(await allowed(s,u)))return res.status(403).json({ok:false,error:'FORBIDDEN'});const since=Math.max(0,Number(req.query.since)||0),rows=(await pool.query(`SELECT id,sender_id,kind,payload,created_at FROM live_signals WHERE session_id=$1 AND recipient_id=$2 AND id>$3 ORDER BY id LIMIT 200`,[s.id,u.id,since])).rows;res.json({ok:true,signals:rows})});
  app.post('/api/live/:id/messages',async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const s=await sessionFor(Number(req.params.id));if(!s||s.status!=="active")return res.status(410).json({ok:false,error:'LIVE_ENDED'});if(!(await allowed(s,u)))return res.status(403).json({ok:false,error:'FORBIDDEN'});const body=clean(req.body?.body||'',500);if(!body)return res.status(400).json({ok:false,error:'EMPTY_MESSAGE'});const row=(await pool.query(`INSERT INTO live_messages(session_id,user_id,body) VALUES($1,$2,$3) RETURNING id,user_id,body,created_at`,[s.id,u.id,body])).rows[0];res.status(201).json({ok:true,message:{...row,username:u.username,display_name:u.display_name,avatar_url:u.avatar_url||null}})});
  app.post('/api/live/:id/reactions',async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const s=await sessionFor(Number(req.params.id));if(!s||s.status!=="active")return res.status(410).json({ok:false,error:'LIVE_ENDED'});if(!(await allowed(s,u)))return res.status(403).json({ok:false,error:'FORBIDDEN'});const reaction=String(req.body?.reaction||'');if(!['❤️','🔥','👏','😂','👍'].includes(reaction))return res.status(400).json({ok:false,error:'BAD_REACTION'});await pool.query(`INSERT INTO live_reactions(session_id,user_id,reaction) VALUES($1,$2,$3)`,[s.id,u.id,reaction]);res.status(201).json({ok:true})});
  app.post('/api/live/:id/end',async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const s=await sessionFor(Number(req.params.id));if(!s)return res.status(404).json({ok:false,error:'LIVE_NOT_FOUND'});if(Number(s.host_id)!==Number(u.id))return res.status(403).json({ok:false,error:'FORBIDDEN'});await updatePeak(s.id);const row=(await pool.query(`UPDATE live_sessions SET status='ended',ended_at=COALESCE(ended_at,NOW()) WHERE id=$1 AND status='active' RETURNING *`,[s.id])).rows[0]||s;await wipeTransient(s.id);res.json({ok:true,live:row,mediaStored:false})});
}
