import {lookup} from "node:dns/promises";
import net from "node:net";
import {pool,requireAuth,clean} from "../runtime.mjs";
const isAdmin=u=>u?.role==='admin';
const safeHttp=value=>{try{const u=new URL(String(value||''));return ['http:','https:'].includes(u.protocol)?u:null}catch{return null}};
function privateIp(ip){if(net.isIPv4(ip)){const p=ip.split('.').map(Number);return p[0]===10||p[0]===127||p[0]===0||(p[0]===169&&p[1]===254)||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&p[1]===168)||(p[0]===100&&p[1]>=64&&p[1]<=127)||p[0]>=224}if(net.isIPv6(ip)){const v=ip.toLowerCase();return v==='::1'||v==='::'||v.startsWith('fc')||v.startsWith('fd')||v.startsWith('fe8')||v.startsWith('fe9')||v.startsWith('fea')||v.startsWith('feb')||v.startsWith('ff')}return true}
async function publicHttp(value){const u=safeHttp(value);if(!u||u.username||u.password)return null;try{const rows=await lookup(u.hostname,{all:true,verbatim:true});return rows.length&&!rows.some(x=>privateIp(x.address))?u:null}catch{return null}}
function parseM3uCount(text=''){return String(text).replace(/\r/g,'').split('\n').filter(x=>x.trim().startsWith('#EXTINF:')).length}
async function admin(req,res){const u=await requireAuth(req,res);if(!u)return null;if(!isAdmin(u)){res.status(403).json({ok:false,error:'FORBIDDEN'});return null}return u}
async function audit(adminId,action,details={}){await pool.query(`INSERT INTO audit_logs(user_id,level,category,action,details) VALUES($1,'INFO','TV',$2,$3::jsonb)`,[adminId,action,JSON.stringify(details)]).catch(()=>{})}
async function testSourceRow(s){const started=Date.now();if(!s)throw new Error('SOURCE_NOT_CONFIGURED');if(s.kind==='m3u'){const url=await publicHttp(s.m3u_url);if(!url)throw new Error('M3U_URL_REQUIRED');const r=await fetch(url,{redirect:'error',signal:AbortSignal.timeout(12000),headers:{'user-agent':'MARBO3A-TV/1.0'}});if(!r.ok)throw new Error('SOURCE_FETCH_FAILED');const text=await r.text();if(text.length>8*1024*1024)throw new Error('PLAYLIST_TOO_LARGE');return{ok:true,count:parseM3uCount(text),latencyMs:Date.now()-started,kind:'m3u'}}if(!s.base_url||!s.username||!s.password)throw new Error('XTREAM_CONFIG_REQUIRED');const source=await publicHttp(s.base_url);if(!source)throw new Error('INVALID_SOURCE_URL');const base=source.toString().replace(/\/$/,''),url=`${base}/player_api.php?username=${encodeURIComponent(s.username)}&password=${encodeURIComponent(s.password)}&action=get_live_streams`,r=await fetch(url,{redirect:'error',signal:AbortSignal.timeout(12000),headers:{'user-agent':'MARBO3A-TV/1.0'}});if(!r.ok)throw new Error('SOURCE_FETCH_FAILED');const data=await r.json();return{ok:true,count:Array.isArray(data)?Math.min(data.length,10000):0,latencyMs:Date.now()-started,kind:'xtream'}}
export function registerTvAdmin(app){
 app.get('/api/admin/tv/channels',async(req,res)=>{if(!await admin(req,res))return;const rows=(await pool.query(`SELECT id,name,logo_url,group_title,enabled,sort_order,updated_at FROM tv_channels ORDER BY sort_order,id LIMIT 10000`)).rows;res.json({ok:true,channels:rows})});
 app.patch('/api/admin/tv/channels/:id',async(req,res)=>{const a=await admin(req,res);if(!a)return;const id=Number(req.params.id);if(!Number.isInteger(id))return res.status(400).json({ok:false,error:'CHANNEL_NOT_FOUND'});const current=(await pool.query(`SELECT * FROM tv_channels WHERE id=$1`,[id])).rows[0];if(!current)return res.status(404).json({ok:false,error:'CHANNEL_NOT_FOUND'});const name=clean(req.body?.name??current.name,120)||current.name,group=clean(req.body?.groupTitle??current.group_title??'أخرى',100)||'أخرى',enabled=typeof req.body?.enabled==='boolean'?req.body.enabled:current.enabled,sortOrder=Number.isFinite(Number(req.body?.sortOrder))?Math.max(-100000,Math.min(100000,Number(req.body.sortOrder))):current.sort_order,row=(await pool.query(`UPDATE tv_channels SET name=$1,group_title=$2,enabled=$3,sort_order=$4,updated_at=NOW() WHERE id=$5 RETURNING id,name,logo_url,group_title,enabled,sort_order,updated_at`,[name,group,enabled,sortOrder,id])).rows[0];await audit(a.id,'tv_channel_update',{channelId:id,before:{name:current.name,groupTitle:current.group_title,enabled:current.enabled,sortOrder:current.sort_order},after:{name:row.name,groupTitle:row.group_title,enabled:row.enabled,sortOrder:row.sort_order}});res.json({ok:true,channel:row})});
 app.delete('/api/admin/tv/channels/:id',async(req,res)=>{const a=await admin(req,res);if(!a)return;const id=Number(req.params.id),reason=clean(req.body?.reason,500);if(reason.length<3)return res.status(400).json({ok:false,error:'AUDIT_REASON_REQUIRED'});const row=(await pool.query(`DELETE FROM tv_channels WHERE id=$1 RETURNING id,name,group_title,enabled,sort_order`,[id])).rows[0];if(!row)return res.status(404).json({ok:false,error:'CHANNEL_NOT_FOUND'});await audit(a.id,'tv_channel_delete',{channel:row,reason});res.json({ok:true})});
 app.post('/api/admin/tv/test-source',async(req,res)=>{if(!await admin(req,res))return;const s=(await pool.query(`SELECT * FROM tv_sources ORDER BY id DESC LIMIT 1`)).rows[0];try{return res.json(await testSourceRow(s))}catch(e){return res.status(400).json({ok:false,error:e.message||'SOURCE_TEST_FAILED'})}});
 app.post('/api/admin/tv/channels/:id/test',async(req,res)=>{if(!await admin(req,res))return;const id=Number(req.params.id),row=(await pool.query(`SELECT stream_url FROM tv_channels WHERE id=$1`,[id])).rows[0];if(!row)return res.status(404).json({ok:false,error:'CHANNEL_NOT_FOUND'});const url=await publicHttp(row.stream_url);if(!url)return res.status(400).json({ok:false,error:'INVALID_SOURCE_URL'});const started=Date.now();try{const r=await fetch(url,{redirect:'error',signal:AbortSignal.timeout(8000),headers:{'user-agent':'MARBO3A-TV/1.0','range':'bytes=0-1023'}});if(!r.ok)return res.status(502).json({ok:false,error:'CHANNEL_UNREACHABLE',status:r.status});try{await r.body?.cancel?.()}catch{}return res.json({ok:true,status:r.status,latencyMs:Date.now()-started,contentType:r.headers.get('content-type')||null})}catch{return res.status(502).json({ok:false,error:'CHANNEL_UNREACHABLE'})}});
}
