import {pool,requireAuth,clean} from "../runtime.mjs";
const isAdmin=u=>u?.role==='admin';
const safeHttp=value=>{try{const u=new URL(String(value||''));return ['http:','https:'].includes(u.protocol)?u:null}catch{return null}};
function parseM3uCount(text=''){return String(text).replace(/\r/g,'').split('\n').filter(x=>x.trim().startsWith('#EXTINF:')).length}
async function admin(req,res){const u=await requireAuth(req,res);if(!u)return null;if(!isAdmin(u)){res.status(403).json({ok:false,error:'FORBIDDEN'});return null}return u}
async function testSourceRow(s){const started=Date.now();if(!s)throw new Error('SOURCE_NOT_CONFIGURED');if(s.kind==='m3u'){
  const url=safeHttp(s.m3u_url);if(!url)throw new Error('M3U_URL_REQUIRED');const r=await fetch(url,{signal:AbortSignal.timeout(12000),headers:{'user-agent':'MARBO3A-TV/1.0'}});if(!r.ok)throw new Error('SOURCE_FETCH_FAILED');const text=await r.text();return{ok:true,count:parseM3uCount(text),latencyMs:Date.now()-started,kind:'m3u'};
 }
 if(!s.base_url||!s.username||!s.password)throw new Error('XTREAM_CONFIG_REQUIRED');const base=String(s.base_url).replace(/\/$/,'');if(!safeHttp(base))throw new Error('INVALID_SOURCE_URL');const url=`${base}/player_api.php?username=${encodeURIComponent(s.username)}&password=${encodeURIComponent(s.password)}&action=get_live_streams`;const r=await fetch(url,{signal:AbortSignal.timeout(12000),headers:{'user-agent':'MARBO3A-TV/1.0'}});if(!r.ok)throw new Error('SOURCE_FETCH_FAILED');const data=await r.json();return{ok:true,count:Array.isArray(data)?data.length:0,latencyMs:Date.now()-started,kind:'xtream'};
}
export function registerTvAdmin(app){
 app.get('/api/admin/tv/channels',async(req,res)=>{if(!await admin(req,res))return;const rows=(await pool.query(`SELECT id,name,logo_url,group_title,enabled,sort_order,updated_at FROM tv_channels ORDER BY sort_order,id LIMIT 10000`)).rows;res.json({ok:true,channels:rows})});
 app.patch('/api/admin/tv/channels/:id',async(req,res)=>{if(!await admin(req,res))return;const id=Number(req.params.id);if(!Number.isInteger(id))return res.status(400).json({ok:false,error:'CHANNEL_NOT_FOUND'});const current=(await pool.query(`SELECT * FROM tv_channels WHERE id=$1`,[id])).rows[0];if(!current)return res.status(404).json({ok:false,error:'CHANNEL_NOT_FOUND'});const name=clean(req.body?.name??current.name,120)||current.name,group=clean(req.body?.groupTitle??current.group_title??'أخرى',100)||'أخرى',enabled=typeof req.body?.enabled==='boolean'?req.body.enabled:current.enabled,sortOrder=Number.isFinite(Number(req.body?.sortOrder))?Math.max(-100000,Math.min(100000,Number(req.body.sortOrder))):current.sort_order;const row=(await pool.query(`UPDATE tv_channels SET name=$1,group_title=$2,enabled=$3,sort_order=$4,updated_at=NOW() WHERE id=$5 RETURNING id,name,logo_url,group_title,enabled,sort_order,updated_at`,[name,group,enabled,sortOrder,id])).rows[0];res.json({ok:true,channel:row})});
 app.delete('/api/admin/tv/channels/:id',async(req,res)=>{if(!await admin(req,res))return;const id=Number(req.params.id);const row=(await pool.query(`DELETE FROM tv_channels WHERE id=$1 RETURNING id`,[id])).rows[0];if(!row)return res.status(404).json({ok:false,error:'CHANNEL_NOT_FOUND'});res.json({ok:true})});
 app.post('/api/admin/tv/test-source',async(req,res)=>{if(!await admin(req,res))return;const s=(await pool.query(`SELECT * FROM tv_sources ORDER BY id DESC LIMIT 1`)).rows[0];try{return res.json(await testSourceRow(s))}catch(e){return res.status(400).json({ok:false,error:e.message||'SOURCE_TEST_FAILED'})}});
 app.post('/api/admin/tv/channels/:id/test',async(req,res)=>{if(!await admin(req,res))return;const id=Number(req.params.id),row=(await pool.query(`SELECT stream_url FROM tv_channels WHERE id=$1`,[id])).rows[0];if(!row)return res.status(404).json({ok:false,error:'CHANNEL_NOT_FOUND'});const url=safeHttp(row.stream_url);if(!url)return res.status(400).json({ok:false,error:'INVALID_SOURCE_URL'});const started=Date.now();try{const r=await fetch(url,{redirect:'follow',signal:AbortSignal.timeout(8000),headers:{'user-agent':'MARBO3A-TV/1.0','range':'bytes=0-1023'}});if(!r.ok)return res.status(502).json({ok:false,error:'CHANNEL_UNREACHABLE',status:r.status});try{await r.body?.cancel?.()}catch{}return res.json({ok:true,status:r.status,latencyMs:Date.now()-started,contentType:r.headers.get('content-type')||null})}catch{return res.status(502).json({ok:false,error:'CHANNEL_UNREACHABLE'})}});
}
