import {randomUUID} from "node:crypto";
import {Readable} from "node:stream";
import {lookup} from "node:dns/promises";
import net from "node:net";
import express from "express";
import {pool,requireAuth,clean} from "../runtime.mjs";

function isAdmin(u){return u?.role==='admin'}
const tickets=new Map(),TICKET_TTL=15*60*1000;
function pruneTickets(){const now=Date.now();for(const[k,v]of tickets){if(v.expires<=now)tickets.delete(k)}while(tickets.size>12000){tickets.delete(tickets.keys().next().value)}}
function ticketFor(target,ttl=TICKET_TTL){pruneTickets();const id=randomUUID().replaceAll('-','');tickets.set(id,{target,expires:Date.now()+ttl});return id}
function takeTicket(id){pruneTickets();const row=tickets.get(String(id||''));return row&&row.expires>Date.now()?row:null}
function safeHttp(value){try{const u=new URL(String(value||''));return ['http:','https:'].includes(u.protocol)?u:null}catch{return null}}
function privateIp(ip){if(net.isIPv4(ip)){const p=ip.split('.').map(Number);return p[0]===10||p[0]===127||p[0]===0||(p[0]===169&&p[1]===254)||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&p[1]===168)||(p[0]===100&&p[1]>=64&&p[1]<=127)||p[0]>=224}if(net.isIPv6(ip)){const v=ip.toLowerCase();return v==='::1'||v==='::'||v.startsWith('fc')||v.startsWith('fd')||v.startsWith('fe8')||v.startsWith('fe9')||v.startsWith('fea')||v.startsWith('feb')||v.startsWith('ff')||v.startsWith('::ffff:127.')||v.startsWith('::ffff:10.')||v.startsWith('::ffff:192.168.')}return true}
async function publicHttp(value){const u=safeHttp(value);if(!u)return null;if(u.username||u.password)return null;try{const addresses=await lookup(u.hostname,{all:true,verbatim:true});if(!addresses.length||addresses.some(x=>privateIp(x.address)))return null;return u}catch{return null}}
function parseM3u(text=''){
  const lines=String(text).replace(/\r/g,'').split('\n'),out=[];
  for(let i=0;i<lines.length;i++){const line=lines[i].trim();if(!line.startsWith('#EXTINF:'))continue;let next='';for(let j=i+1;j<Math.min(lines.length,i+5);j++){const c=lines[j].trim();if(c&&!c.startsWith('#')){next=c;break}}if(!safeHttp(next))continue;const name=clean(line.split(',').slice(1).join(',').trim()||'قناة',160)||'قناة',logo=(line.match(/tvg-logo="([^"]*)"/i)||[])[1]||'',group=clean((line.match(/group-title="([^"]*)"/i)||[])[1]||'أخرى',120)||'أخرى';out.push({name,logo_url:safeHttp(logo)?logo:'',group_title:group,stream_url:next});if(out.length>=10000)break}
  }return out;
}
async function replaceChannels(rows){const client=await pool.connect();try{await client.query('BEGIN');await client.query('DELETE FROM tv_channels');let order=0;for(const c of rows.slice(0,10000))await client.query(`INSERT INTO tv_channels(name,logo_url,group_title,stream_url,sort_order) VALUES($1,$2,$3,$4,$5)`,[c.name,c.logo_url||null,c.group_title||'أخرى',c.stream_url,order++]);await client.query('COMMIT')}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}
async function audit(adminId,action,details={}){await pool.query(`INSERT INTO audit_logs(user_id,level,category,action,details) VALUES($1,'INFO','TV',$2,$3::jsonb)`,[adminId,action,JSON.stringify(details)]).catch(()=>{})}
function proxied(target){return `/api/tv/proxy?t=${encodeURIComponent(ticketFor(target))}`}
function rewritePlaylist(text,sourceUrl){return String(text).replace(/\r/g,'').split('\n').map(line=>{if(line.includes('URI="'))return line.replace(/URI="([^"]+)"/g,(m,value)=>{try{const target=new URL(value,sourceUrl).toString();return safeHttp(target)?`URI="${proxied(target)}"`:m}catch{return m}});const value=line.trim();if(!value||value.startsWith('#'))return line;try{const target=new URL(value,sourceUrl).toString();return safeHttp(target)?proxied(target):line}catch{return line}}).join('\n')}
async function proxyTarget(target,req,res){const url=await publicHttp(target);if(!url)return res.status(400).json({ok:false,error:'UNSAFE_STREAM_URL'});const headers={'user-agent':'MARBO3A-TV/1.0'};if(req.headers.range)headers.range=req.headers.range;let upstream;try{upstream=await fetch(url,{redirect:'manual',signal:AbortSignal.timeout(20000),headers});for(let i=0;i<4&&[301,302,303,307,308].includes(upstream.status);i++){const location=upstream.headers.get('location');if(!location)return res.status(502).end();const next=await publicHttp(new URL(location,url).toString());if(!next)return res.status(400).json({ok:false,error:'UNSAFE_STREAM_URL'});upstream=await fetch(next,{redirect:'manual',signal:AbortSignal.timeout(20000),headers});url.href=next.href}}catch{return res.status(502).end()}if(!upstream.ok)return res.status(upstream.status).end();const type=String(upstream.headers.get('content-type')||'').toLowerCase(),finalUrl=upstream.url||url.toString();if(type.includes('mpegurl')||/\.m3u8?(\?|$)/i.test(finalUrl)){const text=await upstream.text();if(text.length>4*1024*1024)return res.status(502).json({ok:false,error:'PLAYLIST_TOO_LARGE'});res.setHeader('content-type','application/vnd.apple.mpegurl; charset=utf-8');res.setHeader('cache-control','private, no-store');return res.send(rewritePlaylist(text,finalUrl))}for(const name of ['content-type','content-length','content-range','accept-ranges']){const value=upstream.headers.get(name);if(value)res.setHeader(name,value)}res.setHeader('cache-control','private, no-store');res.status(upstream.status);if(!upstream.body)return res.end();Readable.fromWeb(upstream.body).on('error',()=>{try{res.end()}catch{}}).pipe(res)}
export function registerTv(app){
  app.get('/api/tv/channels',async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const rows=(await pool.query(`SELECT id,name,logo_url,group_title,stream_url FROM tv_channels WHERE enabled=TRUE ORDER BY sort_order,id`)).rows;res.json({ok:true,channels:rows.map(({stream_url,...c})=>({...c,play_url:`/api/tv/stream/${c.id}?t=${ticketFor(stream_url)}`}))})});
  app.get('/api/tv/stream/:id',async(req,res)=>{const row=takeTicket(req.query.t);if(!row)return res.status(401).json({ok:false,error:'STREAM_TICKET_EXPIRED'});return proxyTarget(row.target,req,res)});
  app.get('/api/tv/proxy',async(req,res)=>{const row=takeTicket(req.query.t);if(!row)return res.status(401).end();return proxyTarget(row.target,req,res)});
  app.get('/api/admin/tv/source',async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;if(!isAdmin(u))return res.status(403).json({ok:false,error:'FORBIDDEN'});const s=(await pool.query(`SELECT id,kind,base_url,username,m3u_url,enabled,updated_at FROM tv_sources ORDER BY id DESC LIMIT 1`)).rows[0]||null,count=(await pool.query(`SELECT COUNT(*)::int c FROM tv_channels`)).rows[0].c;res.json({ok:true,source:s,channels:count})});
  app.put('/api/admin/tv/source',async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;if(!isAdmin(u))return res.status(403).json({ok:false,error:'FORBIDDEN'});const kind=['m3u','xtream'].includes(req.body?.kind)?req.body.kind:'m3u',base=String(req.body?.baseUrl||'').trim(),username=clean(req.body?.username,180),password=String(req.body?.password||'').trim(),m3u=String(req.body?.m3uUrl||'').trim();if(base&&!await publicHttp(base))return res.status(400).json({ok:false,error:'INVALID_SOURCE_URL'});if(m3u&&!await publicHttp(m3u))return res.status(400).json({ok:false,error:'INVALID_SOURCE_URL'});const current=(await pool.query(`SELECT * FROM tv_sources ORDER BY id DESC LIMIT 1`)).rows[0];if(current)await pool.query(`UPDATE tv_sources SET kind=$1,base_url=$2,username=$3,password=CASE WHEN $4='' THEN password ELSE $4 END,m3u_url=$5,updated_at=NOW() WHERE id=$6`,[kind,base||null,username||null,password,m3u||null,current.id]);else await pool.query(`INSERT INTO tv_sources(kind,base_url,username,password,m3u_url) VALUES($1,$2,$3,$4,$5)`,[kind,base||null,username||null,password||null,m3u||null]);await audit(u.id,'tv_source_update',{kind,baseHost:base?safeHttp(base)?.host:null,m3uHost:m3u?safeHttp(m3u)?.host:null,usernameChanged:Boolean(username),passwordChanged:Boolean(password)});res.json({ok:true})});
  app.post('/api/admin/tv/import-m3u',express.text({type:'text/plain',limit:'8mb'}),async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;if(!isAdmin(u))return res.status(403).json({ok:false,error:'FORBIDDEN'});const rows=parseM3u(typeof req.body==='string'?req.body:'');if(!rows.length)return res.status(400).json({ok:false,error:'NO_CHANNELS'});await replaceChannels(rows);await audit(u.id,'tv_import_m3u',{count:rows.length});res.json({ok:true,count:rows.length})});
  app.post('/api/admin/tv/refresh',async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;if(!isAdmin(u))return res.status(403).json({ok:false,error:'FORBIDDEN'});const s=(await pool.query(`SELECT * FROM tv_sources ORDER BY id DESC LIMIT 1`)).rows[0];if(!s)return res.status(400).json({ok:false,error:'SOURCE_NOT_CONFIGURED'});let rows=[];if(s.kind==='m3u'){if(!s.m3u_url)return res.status(400).json({ok:false,error:'M3U_URL_REQUIRED'});const source=await publicHttp(s.m3u_url);if(!source)return res.status(400).json({ok:false,error:'INVALID_SOURCE_URL'});const r=await fetch(source,{redirect:'error',signal:AbortSignal.timeout(15000),headers:{'user-agent':'MARBO3A-TV/1.0'}});if(!r.ok)return res.status(502).json({ok:false,error:'SOURCE_FETCH_FAILED'});const text=await r.text();if(text.length>8*1024*1024)return res.status(413).json({ok:false,error:'PLAYLIST_TOO_LARGE'});rows=parseM3u(text)}else{if(!s.base_url||!s.username||!s.password)return res.status(400).json({ok:false,error:'XTREAM_CONFIG_REQUIRED'});const source=await publicHttp(s.base_url);if(!source)return res.status(400).json({ok:false,error:'INVALID_SOURCE_URL'});const base=source.toString().replace(/\/$/,'');const url=`${base}/player_api.php?username=${encodeURIComponent(s.username)}&password=${encodeURIComponent(s.password)}&action=get_live_streams`,r=await fetch(url,{redirect:'error',signal:AbortSignal.timeout(15000),headers:{'user-agent':'MARBO3A-TV/1.0'}});if(!r.ok)return res.status(502).json({ok:false,error:'SOURCE_FETCH_FAILED'});const data=await r.json();rows=(Array.isArray(data)?data:[]).slice(0,10000).map((x,i)=>({name:clean(x.name||`قناة ${i+1}`,160),logo_url:safeHttp(x.stream_icon)?x.stream_icon:'',group_title:clean(String(x.category_name||x.category_id||'أخرى'),120)||'أخرى',stream_url:`${base}/live/${encodeURIComponent(s.username)}/${encodeURIComponent(s.password)}/${x.stream_id}.m3u8`}))}if(!rows.length)return res.status(400).json({ok:false,error:'NO_CHANNELS'});await replaceChannels(rows);await audit(u.id,'tv_refresh',{kind:s.kind,count:rows.length});res.json({ok:true,count:rows.length})});
}
