import http from "http";
import crypto from "crypto";
import {pool,ensureRedis,requireAuth,turnConfig,emitUser,emitChat} from "./runtime.mjs";
const prior=http.createServer.bind(http);let ready;
async function infra(){if(!ready)ready=(async()=>{await ensureRedis();await pool.query(`CREATE TABLE IF NOT EXISTS rtc_calls(id TEXT PRIMARY KEY,conversation_id BIGINT NOT NULL,caller_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,callee_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,kind TEXT NOT NULL CHECK(kind IN ('audio','video')),status TEXT NOT NULL DEFAULT 'ringing',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),answered_at TIMESTAMPTZ,ended_at TIMESTAMPTZ)`);await pool.query(`ALTER TABLE rtc_calls DROP CONSTRAINT IF EXISTS rtc_calls_status_check`);await pool.query(`ALTER TABLE rtc_calls ADD CONSTRAINT rtc_calls_status_check CHECK(status IN ('ringing','answered','declined','ended','missed','cancelled','failed'))`).catch(()=>{});await pool.query(`CREATE INDEX IF NOT EXISTS rtc_calls_callee_status_idx ON rtc_calls(callee_id,status,created_at DESC)`);await pool.query(`CREATE INDEX IF NOT EXISTS rtc_calls_conversation_created_idx ON rtc_calls(conversation_id,created_at DESC)`);await pool.query(`CREATE TABLE IF NOT EXISTS rtc_call_signals(id BIGSERIAL PRIMARY KEY,call_id TEXT NOT NULL REFERENCES rtc_calls(id) ON DELETE CASCADE,sender_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,recipient_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,kind TEXT NOT NULL CHECK(kind IN ('offer','answer','ice')),payload JSONB NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);await pool.query(`CREATE INDEX IF NOT EXISTS rtc_call_signals_recipient_idx ON rtc_call_signals(call_id,recipient_id,id)`);})().catch(e=>{ready=null;throw e});return ready}
async function auth(req,res){await infra();return requireAuth(req,res)}
async function callFor(id,u){return(await pool.query(`SELECT c.*,cu.username caller_username,cu.display_name caller_name,cu.avatar_url caller_avatar,tu.username callee_username,tu.display_name callee_name,tu.avatar_url callee_avatar FROM rtc_calls c JOIN users cu ON cu.id=c.caller_id JOIN users tu ON tu.id=c.callee_id WHERE c.id=$1 AND ($2=c.caller_id OR $2=c.callee_id)`,[id,u.id])).rows[0]||null}
const durationSql=()=>`GREATEST(0,EXTRACT(EPOCH FROM (COALESCE(c.ended_at,NOW())-COALESCE(c.answered_at,c.created_at)))::int)`;
function notifyCall(c,event="call:updated"){const payload={id:c.id,conversationId:Number(c.conversation_id),callerId:Number(c.caller_id),calleeId:Number(c.callee_id),kind:c.kind,status:c.status,createdAt:c.created_at,answeredAt:c.answered_at||null,endedAt:c.ended_at||null};emitUser(c.caller_id,event,payload);emitUser(c.callee_id,event,payload);emitChat(c.conversation_id,event,payload)}
http.createServer=function(app,...args){if(typeof app==="function"&&app?.use){infra().catch(e=>console.error("calls infra",e));
 app.post("/api/calls",async(req,res)=>{try{const u=await auth(req,res);if(!u)return;const conv=Number(req.body?.conversationId),kind=req.body?.kind==="video"?"video":"audio";if(!Number.isInteger(conv)||conv<1)return res.status(400).json({ok:false,error:"BAD_CONVERSATION"});const c=(await pool.query(`SELECT id,user1_id,user2_id FROM direct_conversations WHERE id=$1 AND ($2=user1_id OR $2=user2_id)`,[conv,u.id])).rows[0];if(!c)return res.status(403).json({ok:false,error:"CHAT_FORBIDDEN"});const callee=Number(c.user1_id)===Number(u.id)?Number(c.user2_id):Number(c.user1_id);await pool.query(`UPDATE rtc_calls SET status=CASE WHEN status='ringing' THEN 'cancelled' ELSE 'ended' END,ended_at=NOW() WHERE status IN ('ringing','answered') AND ((caller_id=$1 AND callee_id=$2) OR (caller_id=$2 AND callee_id=$1))`,[u.id,callee]);const id=crypto.randomUUID(),row=(await pool.query(`INSERT INTO rtc_calls(id,conversation_id,caller_id,callee_id,kind) VALUES($1,$2,$3,$4,$5) RETURNING *`,[id,conv,u.id,callee,kind])).rows[0];notifyCall(row,"call:incoming");res.status(201).json({ok:true,call:row})}catch(e){console.error("create call",e);res.status(500).json({ok:false,error:"CALL_CREATE_FAILED"})}});
 app.get("/api/calls/incoming",async(req,res)=>{try{const u=await auth(req,res);if(!u)return;const expired=(await pool.query(`UPDATE rtc_calls SET status='missed',ended_at=NOW() WHERE callee_id=$1 AND status='ringing' AND created_at<NOW()-INTERVAL '75 seconds' RETURNING *`,[u.id])).rows;expired.forEach(c=>notifyCall(c));const row=(await pool.query(`SELECT c.*,x.username caller_username,x.display_name caller_name,x.avatar_url caller_avatar FROM rtc_calls c JOIN users x ON x.id=c.caller_id WHERE c.callee_id=$1 AND c.status='ringing' ORDER BY c.created_at DESC LIMIT 1`,[u.id])).rows[0]||null;res.json({ok:true,call:row})}catch(e){console.error("incoming call",e);res.status(500).json({ok:false,error:"CALL_LOAD_FAILED"})}});
 app.get("/api/calls/history",async(req,res)=>{try{const u=await auth(req,res);if(!u)return;const conv=Math.max(0,Number(req.query.conversationId)||0),rows=(await pool.query(`SELECT c.*,CASE WHEN c.caller_id=$1 THEN 'outgoing' ELSE 'incoming' END direction,CASE WHEN c.caller_id=$1 THEN tu.display_name ELSE cu.display_name END peer_name,CASE WHEN c.caller_id=$1 THEN tu.username ELSE cu.username END peer_username,CASE WHEN c.caller_id=$1 THEN tu.avatar_url ELSE cu.avatar_url END peer_avatar,${durationSql()} duration_seconds FROM rtc_calls c JOIN users cu ON cu.id=c.caller_id JOIN users tu ON tu.id=c.callee_id WHERE (c.caller_id=$1 OR c.callee_id=$1) AND ($2::bigint=0 OR c.conversation_id=$2) ORDER BY c.created_at DESC LIMIT 150`,[u.id,conv])).rows;res.json({ok:true,calls:rows})}catch(e){console.error("call history",e);res.status(500).json({ok:false,error:"CALL_HISTORY_FAILED"})}});
 app.get("/api/calls/config",async(req,res)=>{try{const u=await auth(req,res);if(!u)return;res.json({ok:true,...turnConfig(u.id)})}catch(e){console.error("call config",e);res.status(500).json({ok:false,error:"CALL_CONFIG_FAILED"})}});
 app.get("/api/calls/:id",async(req,res)=>{try{const u=await auth(req,res);if(!u)return;const c=await callFor(req.params.id,u);if(!c)return res.status(404).json({ok:false,error:"CALL_NOT_FOUND"});res.json({ok:true,call:c})}catch{res.status(500).json({ok:false,error:"CALL_LOAD_FAILED"})}});
 app.post("/api/calls/:id/answer",async(req,res)=>{try{const u=await auth(req,res);if(!u)return;const c=await callFor(req.params.id,u);if(!c)return res.status(404).json({ok:false,error:"CALL_NOT_FOUND"});if(Number(c.callee_id)!==Number(u.id))return res.status(403).json({ok:false,error:"FORBIDDEN"});const row=(await pool.query(`UPDATE rtc_calls SET status='answered',answered_at=COALESCE(answered_at,NOW()) WHERE id=$1 AND status='ringing' RETURNING *`,[c.id])).rows[0];if(!row)return res.status(409).json({ok:false,error:"CALL_NOT_RINGING"});notifyCall(row);res.json({ok:true,call:row})}catch{res.status(500).json({ok:false,error:"CALL_ANSWER_FAILED"})}});
 app.post("/api/calls/:id/decline",async(req,res)=>{try{const u=await auth(req,res);if(!u)return;const c=await callFor(req.params.id,u);if(!c)return res.status(404).json({ok:false,error:"CALL_NOT_FOUND"});if(Number(c.callee_id)!==Number(u.id))return res.status(403).json({ok:false,error:"FORBIDDEN"});const row=(await pool.query(`UPDATE rtc_calls SET status='declined',ended_at=NOW() WHERE id=$1 AND status='ringing' RETURNING *`,[c.id])).rows[0];if(row)notifyCall(row);res.json({ok:true})}catch{res.status(500).json({ok:false,error:"CALL_DECLINE_FAILED"})}});
 app.post("/api/calls/:id/fail",async(req,res)=>{try{const u=await auth(req,res);if(!u)return;const c=await callFor(req.params.id,u);if(!c)return res.status(404).json({ok:false,error:"CALL_NOT_FOUND"});const row=(await pool.query(`UPDATE rtc_calls SET status='failed',ended_at=NOW() WHERE id=$1 AND status IN ('ringing','answered') RETURNING *`,[c.id])).rows[0];if(row)notifyCall(row);res.json({ok:true})}catch{res.status(500).json({ok:false,error:"CALL_END_FAILED"})}});
 app.post("/api/calls/:id/end",async(req,res)=>{try{const u=await auth(req,res);if(!u)return;const c=await callFor(req.params.id,u);if(!c)return res.status(404).json({ok:false,error:"CALL_NOT_FOUND"});const row=(await pool.query(`UPDATE rtc_calls SET status=CASE WHEN status='ringing' THEN 'cancelled' ELSE 'ended' END,ended_at=NOW() WHERE id=$1 AND status IN ('ringing','answered') RETURNING *`,[c.id])).rows[0];if(row)notifyCall(row);res.json({ok:true})}catch{res.status(500).json({ok:false,error:"CALL_END_FAILED"})}});
 app.post("/api/calls/:id/signals",async(req,res)=>{try{const u=await auth(req,res);if(!u)return;const c=await callFor(req.params.id,u);if(!c)return res.status(404).json({ok:false,error:"CALL_NOT_FOUND"});const kind=String(req.body?.kind||"");if(!["offer","answer","ice"].includes(kind))return res.status(400).json({ok:false,error:"BAD_SIGNAL"});const recipient=Number(c.caller_id)===Number(u.id)?Number(c.callee_id):Number(c.caller_id),payload=req.body?.payload;if(!payload||typeof payload!=="object")return res.status(400).json({ok:false,error:"BAD_SIGNAL"});const row=(await pool.query(`INSERT INTO rtc_call_signals(call_id,sender_id,recipient_id,kind,payload) VALUES($1,$2,$3,$4,$5) RETURNING id,created_at`,[c.id,u.id,recipient,kind,payload])).rows[0];emitUser(recipient,"call:signal",{id:row.id,callId:c.id,kind,payload,createdAt:row.created_at});res.status(201).json({ok:true,id:row.id})}catch(e){console.error("call signal",e);res.status(500).json({ok:false,error:"SIGNAL_FAILED"})}});
 app.get("/api/calls/:id/signals",async(req,res)=>{try{const u=await auth(req,res);if(!u)return;const c=await callFor(req.params.id,u);if(!c)return res.status(404).json({ok:false,error:"CALL_NOT_FOUND"});const since=Math.max(0,Number(req.query.since)||0),rows=(await pool.query(`SELECT id,kind,payload,created_at FROM rtc_call_signals WHERE call_id=$1 AND recipient_id=$2 AND id>$3 ORDER BY id ASC LIMIT 200`,[c.id,u.id,since])).rows;res.json({ok:true,signals:rows})}catch{res.status(500).json({ok:false,error:"SIGNAL_LOAD_FAILED"})}});
 }return prior(app,...args)};
