import http from "http";
import multer from "multer";
import {pool,redis,ensureRedis,requireAuth,clean,emitRoom,emitChat} from "./runtime.mjs";
import {saveObject,storageInfo} from "./storage.mjs";
const prior=http.createServer.bind(http),upload=multer({storage:multer.memoryStorage(),limits:{fileSize:8*1024*1024,files:1}});
function detected(buf){if(!buf||buf.length<4)return null;if(buf[0]===0xff&&buf[1]===0xd8&&buf[2]===0xff)return{type:"image/jpeg",ext:"jpg"};if(buf.subarray(0,8).equals(Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a])))return{type:"image/png",ext:"png"};if(["GIF87a","GIF89a"].includes(buf.subarray(0,6).toString("ascii")))return{type:"image/gif",ext:"gif"};if(buf.subarray(0,4).toString("ascii")==="RIFF"&&buf.subarray(8,12).toString("ascii")==="WEBP")return{type:"image/webp",ext:"webp"};if(buf.subarray(0,4).toString("ascii")==="OggS")return{type:"audio/ogg",ext:"ogg"};if(buf.subarray(0,4).toString("ascii")==="RIFF"&&buf.subarray(8,12).toString("ascii")==="WAVE")return{type:"audio/wav",ext:"wav"};if(buf.subarray(0,3).toString("ascii")==="ID3"||(buf[0]===0xff&&(buf[1]&0xe0)===0xe0))return{type:"audio/mpeg",ext:"mp3"};if(buf.length>12&&buf.subarray(4,8).toString("ascii")==="ftyp")return{type:"audio/mp4",ext:"m4a"};if(buf.subarray(0,5).toString("ascii")==="%PDF-")return{type:"application/pdf",ext:"pdf"};return null}
async function presenceMap(ids){if(!ids.length)return new Map();const scores=await redis.zMScore("presence:users",ids.map(String));const cutoff=Date.now()-120000;return new Map(ids.map((id,i)=>[String(id),Number(scores?.[i]||0)>cutoff]))}
http.createServer=function experienceCreateServer(app,...args){if(typeof app==="function"&&app?.use){
 app.post("/api/uploads",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;upload.single("file")(req,res,async err=>{try{if(err)return res.status(err.code==="LIMIT_FILE_SIZE"?413:400).json({ok:false,error:err.code==="LIMIT_FILE_SIZE"?"FILE_TOO_LARGE":"UPLOAD_FAILED"});if(!req.file)return res.status(400).json({ok:false,error:"NO_FILE"});const kind=detected(req.file.buffer);if(!kind)return res.status(400).json({ok:false,error:"UNSUPPORTED_FILE"});const saved=await saveObject({buffer:req.file.buffer,extension:kind.ext,contentType:kind.type});res.status(201).json({ok:true,file:{url:saved.url,type:saved.type,size:saved.size,name:req.file.originalname,storage:saved.driver}})}catch(e){console.error("storage upload",e);res.status(500).json({ok:false,error:e.message==="STORAGE_DRIVER_NOT_CONFIGURED"?e.message:"UPLOAD_FAILED"})}})});
 app.get("/api/storage/status",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;res.json({ok:true,...storageInfo()})});
 app.post("/api/typing/:kind/:scopeId",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;await ensureRedis();const kind=req.params.kind==="room"?"room":req.params.kind==="direct"?"direct":"",scope=Number(req.params.scopeId);if(!kind||!Number.isInteger(scope)||scope<1)return res.status(400).json({ok:false,error:"INVALID_SCOPE"});const active=Boolean(req.body?.typing??req.body?.active),key=`typing:${kind}:${scope}:${u.id}`,event={kind,scopeId:scope,userId:Number(u.id),username:u.username,displayName:u.display_name,active};if(active)await redis.set(key,JSON.stringify({userId:Number(u.id),username:u.username,displayName:u.display_name}),{EX:8});else await redis.del(key);if(kind==="room")emitRoom(scope,"typing:update",event);else emitChat(scope,"typing:update",event);res.json({ok:true})});
 app.get("/api/typing/:kind/:scopeId",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;await ensureRedis();const kind=req.params.kind==="room"?"room":req.params.kind==="direct"?"direct":"",scope=Number(req.params.scopeId);if(!kind||!Number.isInteger(scope)||scope<1)return res.status(400).json({ok:false,error:"INVALID_SCOPE"});const users=[];for await(const raw of redis.scanIterator({MATCH:`typing:${kind}:${scope}:*`,COUNT:100})){const value=await redis.get(String(raw));if(!value)continue;try{const item=JSON.parse(value);if(String(item.userId)!==String(u.id))users.push(item)}catch{}}res.json({ok:true,users})});
 app.get("/api/onboarding",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const loc=(await pool.query(`SELECT city,share_precise FROM user_locations WHERE user_id=$1`,[u.id])).rows[0]||null;res.json({ok:true,completed:Boolean(u.onboarding_completed),profile:{displayName:u.display_name,bio:u.bio||"",avatarUrl:u.avatar_url||null,city:loc?.city||"",sharePrecise:Boolean(loc?.share_precise)}})});
 app.patch("/api/onboarding/complete",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const bio=clean(req.body?.bio??u.bio,160),city=clean(req.body?.city,80),showCity=req.body?.showCity!==false;await pool.query(`UPDATE users SET bio=$1,onboarding_completed=TRUE,updated_at=NOW() WHERE id=$2`,[bio,u.id]);if(city){await pool.query(`INSERT INTO user_locations(user_id,city,share_precise,updated_at) VALUES($1,$2,FALSE,NOW()) ON CONFLICT(user_id) DO UPDATE SET city=EXCLUDED.city,share_precise=FALSE,updated_at=NOW()`,[u.id,city]);await pool.query(`INSERT INTO profile_privacy(user_id,show_city) VALUES($1,$2) ON CONFLICT(user_id) DO UPDATE SET show_city=EXCLUDED.show_city,updated_at=NOW()`,[u.id,showCity]).catch(()=>{})}res.json({ok:true,completed:true})});
 app.get("/api/search/advanced",async(req,res)=>{try{const viewer=await requireAuth(req,res);if(!viewer)return;await ensureRedis();const q=clean(req.query.q,100),type=["all","users","rooms","posts"].includes(String(req.query.type))?String(req.query.type):"all",city=clean(req.query.city,80),onlyOnline=String(req.query.online)==="1",limit=Math.min(30,Math.max(5,Number(req.query.limit)||20));if(q.length<2)return res.json({ok:true,users:[],rooms:[],posts:[]});const out={ok:true,users:[],rooms:[],posts:[]};if(type==="all"||type==="users"){const params=[`%${q}%`,viewer.id,limit*2],extra=city?` AND LOWER(COALESCE(l.city,''))=LOWER($4)`:"";if(city)params.push(city);const rows=(await pool.query(`SELECT u.id,u.username,u.display_name,u.avatar_url,u.bio,CASE WHEN COALESCE(p.show_city,TRUE) THEN l.city ELSE NULL END city FROM users u LEFT JOIN user_locations l ON l.user_id=u.id LEFT JOIN profile_privacy p ON p.user_id=u.id WHERE u.account_status='active' AND u.id<>$2 AND (u.display_name ILIKE $1 OR u.username ILIKE $1 OR u.bio ILIKE $1 OR COALESCE(l.city,'') ILIKE $1)${extra} ORDER BY u.id DESC LIMIT $3`,params)).rows,presence=await presenceMap(rows.map(x=>x.id));out.users=rows.map(row=>({...row,online:Boolean(presence.get(String(row.id)))})).filter(row=>!onlyOnline||row.online).slice(0,limit)}
 if(type==="all"||type==="rooms")out.rooms=(await pool.query(`SELECT r.id,r.name,r.slug,r.description,r.image_url,(SELECT COUNT(*)::int FROM room_members rm WHERE rm.room_id=r.id) members_count FROM rooms r WHERE r.is_public=TRUE AND (r.name ILIKE $1 OR r.description ILIKE $1) ORDER BY members_count DESC,r.id DESC LIMIT $2`,[`%${q}%`,limit])).rows;
 if(type==="all"||type==="posts")out.posts=(await pool.query(`SELECT p.id,p.body,p.image_url,p.created_at,u.id user_id,u.username,u.display_name,u.avatar_url,(SELECT COUNT(*)::int FROM post_likes pl WHERE pl.post_id=p.id) likes_count,(SELECT COUNT(*)::int FROM post_comments pc WHERE pc.post_id=p.id AND pc.deleted_at IS NULL) comments_count FROM posts p JOIN users u ON u.id=p.user_id WHERE p.deleted_at IS NULL AND u.account_status='active' AND p.body ILIKE $1 ORDER BY p.id DESC LIMIT $2`,[`%${q}%`,limit])).rows;res.json(out)}catch(e){console.error("advanced search",e);res.status(500).json({ok:false,error:"SEARCH_FAILED"})}});
 }return prior(app,...args)};
