import http from "http";
import crypto from "crypto";
import express from "express";
import {promisify} from "util";
import {pool,redis,ensureRedis,requireAuth,requireAdmin,createSession,destroySession,tokenFrom,clean,ipOf,isAdmin} from "./runtime.mjs";
const prior=http.createServer.bind(http),scryptAsync=promisify(crypto.scrypt),SESSION_TTL=7*24*60*60;
const allowedOrigin=o=>!o||o==="https://marbo3a.ly"||o==="https://www.marbo3a.ly"||/^https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/i.test(o);
function cookieToken(req){const c=String(req.headers.cookie||"").split(";").map(x=>x.trim()).find(x=>x.startsWith("marbo3a_session="));const t=c?decodeURIComponent(c.slice(17)):"";return /^[a-f0-9]{64}$/i.test(t)?t:""}
function setSessionCookie(res,token){res.setHeader("Set-Cookie",`marbo3a_session=${encodeURIComponent(token)}; Path=/; Max-Age=${SESSION_TTL}; HttpOnly; Secure; SameSite=Lax`)}function clearSessionCookie(res){res.setHeader("Set-Cookie","marbo3a_session=; Path=/; Max-Age=0; HttpOnly; Secure; SameSite=Lax")}
async function verifyPassword(password,stored){try{const[algo,saltHex,hashHex]=String(stored||"").split(":");if(algo!=="scrypt")return false;const out=await scryptAsync(password,Buffer.from(saltHex,"hex"),64),a=Buffer.from(hashHex,"hex"),b=Buffer.from(out);return a.length===b.length&&crypto.timingSafeEqual(a,b)}catch{return false}}
const hashCode=(id,code)=>crypto.createHash("sha256").update(`${id}:${code}`).digest("hex");
async function sendMail(email,subject,html){if(!process.env.BREVO_API_KEY)throw new Error("EMAIL_NOT_CONFIGURED");const r=await fetch("https://api.brevo.com/v3/smtp/email",{method:"POST",headers:{accept:"application/json","content-type":"application/json","api-key":process.env.BREVO_API_KEY},body:JSON.stringify({sender:{name:"مربوعة",email:"no-reply@marbo3a.ly"},to:[{email}],subject,htmlContent:html})});if(!r.ok)throw new Error("EMAIL_SEND_FAILED")}
async function sendCode(user,code,purpose){await sendMail(user.email,purpose==="login"?"رمز الدخول الآمن إلى مربوعة":"تأكيد المصادقة الثنائية",`<div dir="rtl" style="font-family:Arial;padding:28px"><h2 style="color:#ff7a00">مربوعة</h2><p>رمز الأمان الخاص بك:</p><div style="font-size:34px;font-weight:900;letter-spacing:7px">${code}</div><p>صالح لمدة 10 دقائق. لا تشاركه مع أي شخص.</p></div>`)}
async function recordSecurity(userId,kind,req,details={}){await pool.query(`INSERT INTO account_security_events(user_id,kind,ip_address,user_agent,details) VALUES($1,$2,$3,$4,$5::jsonb)`,[userId,kind,ipOf(req),clean(req.headers["user-agent"],300),JSON.stringify(details)]).catch(()=>{})}
async function loginAlert(user,req){try{await sendMail(user.email,"تسجيل دخول جديد إلى مربوعة",`<div dir="rtl" style="font-family:Arial;padding:24px"><h2 style="color:#ff7a00">مربوعة</h2><p>تم تسجيل دخول جديد إلى حسابك.</p><p>الوقت: ${new Date().toISOString()}</p><p>إذا لم تكن أنت، غيّر كلمة المرور وأنهِ الجلسات الأخرى من إعدادات الأمان.</p></div>`)}catch{}}
http.createServer=function productCreateServer(app,...args){if(typeof app==="function"&&app?.use){app.use(express.json({limit:"64kb"}));app.use((req,res,next)=>{const origin=String(req.headers.origin||"");if(!allowedOrigin(origin))return res.status(403).json({ok:false,error:"ORIGIN_NOT_ALLOWED"});res.setHeader("Content-Security-Policy","default-src 'self'; base-uri 'self'; frame-ancestors 'none'; object-src 'none'; img-src 'self' data: blob: https:; media-src 'self' blob: https:; connect-src 'self' https: wss:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; font-src 'self' data:");res.setHeader("Referrer-Policy","strict-origin-when-cross-origin");res.setHeader("Permissions-Policy","camera=(self), microphone=(self), geolocation=(self)");const c=cookieToken(req);if(c&&!req.headers.authorization)req.headers.authorization=`Bearer ${c}`;next()});
 app.post("/api/auth/login",async(req,res)=>{await ensureRedis();const identifier=String(req.body?.identifier||"").trim().toLowerCase(),password=String(req.body?.password||"");if(!identifier||password.length<8||password.length>128)return res.status(400).json({ok:false,error:"INVALID_LOGIN"});const u=(await pool.query(`SELECT id,email,username,display_name,gender,bio,avatar_url,password_hash,account_status,ban_reason,role,two_factor_enabled,onboarding_completed,created_at FROM users WHERE LOWER(email)=LOWER($1) OR LOWER(username)=LOWER($1) LIMIT 1`,[identifier])).rows[0];if(!u||!await verifyPassword(password,u.password_hash)){await recordSecurity(u?.id||null,"failed_login",req,{identifier:identifier.slice(0,60)});return res.status(401).json({ok:false,error:"INVALID_LOGIN"})}if(!isAdmin(u)&&u.account_status!=="active")return res.status(403).json({ok:false,error:u.account_status==="banned"?"ACCOUNT_BANNED":"ACCOUNT_FROZEN",reason:u.ban_reason||""});if(u.two_factor_enabled){const challengeId=crypto.randomBytes(24).toString("hex"),code=String(crypto.randomInt(100000,1000000));await redis.set(`2fa:login:${challengeId}`,JSON.stringify({userId:u.id,hash:hashCode(u.id,code),attempts:0}),{EX:600});try{await sendCode(u,code,"login")}catch(e){await redis.del(`2fa:login:${challengeId}`);return res.status(502).json({ok:false,error:e.message})}await recordSecurity(u.id,"login_2fa_challenge",req);return res.status(202).json({ok:true,twoFactorRequired:true,challengeId,expiresIn:600})}const token=await createSession(u.id);setSessionCookie(res,token);delete u.password_hash;await recordSecurity(u.id,"login",req);loginAlert(u,req);res.json({ok:true,token,expiresIn:SESSION_TTL,user:u,isAdmin:isAdmin(u)})});
 app.post("/api/auth/verify-2fa",async(req,res)=>{await ensureRedis();const challengeId=String(req.body?.challengeId||""),code=String(req.body?.code||"");if(!/^[a-f0-9]{48}$/i.test(challengeId)||!/^\d{6}$/.test(code))return res.status(400).json({ok:false,error:"INVALID_2FA"});const key=`2fa:login:${challengeId}`,raw=await redis.get(key);if(!raw)return res.status(400).json({ok:false,error:"2FA_EXPIRED"});const p=JSON.parse(raw);if(p.attempts>=5){await redis.del(key);return res.status(429).json({ok:false,error:"2FA_TOO_MANY_ATTEMPTS"})}if(hashCode(p.userId,code)!==p.hash){p.attempts++;await redis.set(key,JSON.stringify(p),{EX:Math.max(1,await redis.ttl(key))});return res.status(400).json({ok:false,error:"2FA_INVALID"})}const u=(await pool.query(`SELECT id,email,username,display_name,gender,bio,avatar_url,account_status,ban_reason,role,two_factor_enabled,onboarding_completed,created_at FROM users WHERE id=$1`,[p.userId])).rows[0];if(!u)return res.status(404).json({ok:false,error:"USER_NOT_FOUND"});await redis.del(key);const token=await createSession(u.id);setSessionCookie(res,token);await recordSecurity(u.id,"login_2fa_verified",req);loginAlert(u,req);res.json({ok:true,token,expiresIn:SESSION_TTL,user:u,isAdmin:isAdmin(u)})});
 app.get("/api/auth/me",async(req,res)=>{const u=await requireAuth(req,res);if(u)res.json({ok:true,user:u,isAdmin:isAdmin(u)})});
 app.post("/api/auth/logout",async(req,res)=>{const t=tokenFrom(req)||cookieToken(req);await destroySession(t);clearSessionCookie(res);res.json({ok:true})});
 app.get("/api/account/security",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const events=(await pool.query(`SELECT kind,ip_address,user_agent,created_at FROM account_security_events WHERE user_id=$1 ORDER BY id DESC LIMIT 10`,[u.id])).rows;res.json({ok:true,twoFactorEnabled:Boolean(u.two_factor_enabled),events})});
 app.post("/api/account/2fa/request",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const password=String(req.body?.currentPassword||""),enable=Boolean(req.body?.enable),stored=(await pool.query(`SELECT password_hash,email FROM users WHERE id=$1`,[u.id])).rows[0];if(!await verifyPassword(password,stored.password_hash))return res.status(403).json({ok:false,error:"WRONG_PASSWORD"});const code=String(crypto.randomInt(100000,1000000));await redis.set(`2fa:setup:${u.id}`,JSON.stringify({hash:hashCode(u.id,code),enable}),{EX:600});try{await sendCode({...u,email:stored.email},code,"setup")}catch(e){await redis.del(`2fa:setup:${u.id}`);return res.status(502).json({ok:false,error:e.message})}res.json({ok:true,expiresIn:600,enable})});
 app.post("/api/account/2fa/confirm",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const code=String(req.body?.code||""),raw=await redis.get(`2fa:setup:${u.id}`);if(!raw||!/^\d{6}$/.test(code))return res.status(400).json({ok:false,error:"2FA_EXPIRED"});const p=JSON.parse(raw);if(hashCode(u.id,code)!==p.hash)return res.status(400).json({ok:false,error:"2FA_INVALID"});await pool.query(`UPDATE users SET two_factor_enabled=$1 WHERE id=$2`,[Boolean(p.enable),u.id]);await redis.del(`2fa:setup:${u.id}`);await recordSecurity(u.id,p.enable?"2fa_enabled":"2fa_disabled",req);res.json({ok:true,twoFactorEnabled:Boolean(p.enable)})});
 app.post("/api/users/:id/mute",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const target=Number(req.params.id);if(!Number.isInteger(target)||target===Number(u.id))return res.status(400).json({ok:false,error:"INVALID_USER"});await pool.query(`INSERT INTO user_mutes(muter_id,muted_id) VALUES($1,$2) ON CONFLICT DO NOTHING`,[u.id,target]);res.json({ok:true})});app.delete("/api/users/:id/mute",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;await pool.query(`DELETE FROM user_mutes WHERE muter_id=$1 AND muted_id=$2`,[u.id,Number(req.params.id)]);res.json({ok:true})});
 app.post("/api/reports",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const type=clean(req.body?.targetType,30),target=Number(req.body?.targetId),reason=clean(req.body?.reason,100),details=clean(req.body?.details,1000);if(!["user","message","room","direct_message","post","comment"].includes(type)||!Number.isInteger(target)||!reason)return res.status(400).json({ok:false,error:"INVALID_REPORT"});const row=(await pool.query(`INSERT INTO reports(reporter_id,target_type,target_id,reason,details) VALUES($1,$2,$3,$4,$5) RETURNING id,created_at`,[u.id,type,target,reason,details])).rows[0];res.status(201).json({ok:true,report:row})});
 app.use("/api/admin",async(req,res,next)=>{const a=await requireAdmin(req,res);if(!a)return;req.marbo3aAdmin=a;next()});
 }return prior(app,...args)};
