import http from "http";
import crypto from "crypto";
import {pool,redis,ensureRedis,requireAuth,clean} from "./runtime.mjs";
const prior=http.createServer.bind(http);
const cityCoords={"طرابلس":[32.8872,13.1913],"tripoli":[32.8872,13.1913],"بنغازي":[32.1167,20.0667],"benghazi":[32.1167,20.0667],"مصراتة":[32.3754,15.0925],"misrata":[32.3754,15.0925],"الزاوية":[32.7522,12.7278],"zawiya":[32.7522,12.7278],"سبها":[27.0377,14.4283],"sebha":[27.0377,14.4283],"الخمس":[32.6486,14.2619],"khoms":[32.6486,14.2619],"ترهونة":[32.435,13.6332],"tarhuna":[32.435,13.6332],"درنة":[32.767,22.6367],"derna":[32.767,22.6367],"طبرق":[32.0836,23.9764],"tobruk":[32.0836,23.9764],"تاجوراء":[32.8817,13.3506],"tajoura":[32.8817,13.3506],"جنزور":[32.8187,13.0033],"janzour":[32.8187,13.0033],"سوق الجمعة":[32.894,13.267],"souq al jumaa":[32.894,13.267],"قصر بن غشير":[32.6803,13.1748],"غريان":[32.1722,13.0203],"gharyan":[32.1722,13.0203],"زليتن":[32.4674,14.5687],"zliten":[32.4674,14.5687],"صبراتة":[32.7934,12.4885],"sabratha":[32.7934,12.4885],"زوارة":[32.9312,12.0819],"zuwara":[32.9312,12.0819],"بني وليد":[31.7566,13.9942],"bani walid":[31.7566,13.9942],"سرت":[31.2089,16.5887],"sirte":[31.2089,16.5887],"اجدابيا":[30.7554,20.2263],"أجدابيا":[30.7554,20.2263],"ajdabiya":[30.7554,20.2263],"البيضاء":[32.7627,21.7551],"bayda":[32.7627,21.7551],"المرج":[32.4926,20.8291],"marj":[32.4926,20.8291],"الكفرة":[24.1833,23.2833],"kufra":[24.1833,23.2833],"أوباري":[26.5903,12.7751],"اوباري":[26.5903,12.7751],"ubari":[26.5903,12.7751],"غات":[24.9633,10.1806],"ghat":[24.9633,10.1806]};
const norm=v=>String(v||"").trim().toLowerCase().replace(/[أإآ]/g,"ا").replace(/ة/g,"ه").replace(/ى/g,"ي").replace(/\s+/g," ");
const normalized=Object.entries(cityCoords).map(([name,coords])=>[norm(name),coords]);
const provided=v=>v!==undefined&&v!==null&&v!=="";
function base(city){const n=norm(city),hit=normalized.find(([name])=>name===n)||normalized.find(([name])=>n.includes(name)||name.includes(n));return hit?.[1]||null}
function approx(id,city){const b=base(city);if(!b)return null;const h=crypto.createHash("sha256").update(String(id)).digest();return{latitude:b[0]+(h[0]/255-.5)*.12,longitude:b[1]+(h[1]/255-.5)*.12,precision:"city"}}
async function visibleCities(viewerId){return(await pool.query(`SELECT l.city,COUNT(*)::int users FROM user_locations l JOIN users x ON x.id=l.user_id LEFT JOIN profile_privacy p ON p.user_id=l.user_id WHERE x.account_status='active' AND l.city<>'' AND l.ghost_mode=FALSE AND COALESCE(p.show_city,TRUE)=TRUE AND (l.visibility_mode='everyone' OR (l.visibility_mode='friends' AND EXISTS(SELECT 1 FROM friendships f WHERE f.status='accepted' AND ((f.requester_id=$1 AND f.addressee_id=l.user_id) OR (f.addressee_id=$1 AND f.requester_id=l.user_id)))) OR l.user_id=$1) AND (l.user_id=$1 OR NOT EXISTS(SELECT 1 FROM user_blocks b WHERE (b.blocker_id=$1 AND b.blocked_id=l.user_id) OR (b.blocker_id=l.user_id AND b.blocked_id=$1))) GROUP BY l.city ORDER BY users DESC`,[viewerId])).rows}
async function people(req,res){try{const viewer=await requireAuth(req,res);if(!viewer)return;await ensureRedis();const limit=Math.min(500,Math.max(25,Number(req.query.limit)||500)),cursor=Math.max(0,Number(req.query.cursor)||0);const rows=(await pool.query(`SELECT u.id,u.username,u.display_name,u.gender,u.avatar_url,u.last_seen_at,l.city,l.latitude,l.longitude,l.share_precise,l.visibility_mode,l.ghost_mode,COALESCE(p.show_city,TRUE) show_city,COALESCE(p.show_online,TRUE) show_online,COALESCE(p.show_last_seen,TRUE) show_last_seen,EXISTS(SELECT 1 FROM friendships f WHERE f.status='accepted' AND ((f.requester_id=$1 AND f.addressee_id=u.id) OR (f.addressee_id=$1 AND f.requester_id=u.id))) is_friend FROM users u JOIN user_locations l ON l.user_id=u.id LEFT JOIN profile_privacy p ON p.user_id=u.id WHERE u.account_status='active' AND COALESCE(p.show_city,TRUE)=TRUE AND l.city<>'' AND ($2::bigint=0 OR u.id<$2) AND (u.id=$1 OR NOT EXISTS(SELECT 1 FROM user_blocks b WHERE (b.blocker_id=$1 AND b.blocked_id=u.id) OR (b.blocker_id=u.id AND b.blocked_id=$1))) ORDER BY u.id DESC LIMIT $3`,[viewer.id,cursor,limit])).rows;await redis.zRemRangeByScore("presence:users",0,Date.now()-90000).catch(()=>{});const scores=await redis.zRangeWithScores("presence:users",0,-1).catch(()=>[]),online=new Set(scores.filter(x=>Number(x.score)>Date.now()-90000).map(x=>String(x.value))),users=[];for(const row of rows){const self=String(row.id)===String(viewer.id);if(!self&&row.ghost_mode)continue;if(!self&&row.visibility_mode==="friends"&&!row.is_friend)continue;const precise=row.share_precise&&Number.isFinite(Number(row.latitude))&&Number.isFinite(Number(row.longitude)),point=precise?{latitude:Number(row.latitude),longitude:Number(row.longitude),precision:"precise"}:approx(row.id,row.city);if(!point)continue;const actualOnline=online.has(String(row.id)),onlineVisible=Boolean(row.show_online),lastSeenVisible=Boolean(row.show_last_seen);users.push({id:row.id,username:row.username,display_name:row.display_name,gender:row.gender,avatar_url:row.avatar_url,city:row.city,online:onlineVisible&&actualOnline,last_seen_at:lastSeenVisible&&!actualOnline?row.last_seen_at:null,presence_visible:onlineVisible||lastSeenVisible,is_friend:Boolean(row.is_friend),relation:self?"self":row.is_friend?"friend":"other",...point})}res.json({ok:true,users,viewerId:viewer.id,nextCursor:rows.length===limit?rows.at(-1)?.id:null})}catch(e){console.error("real map people",e);res.status(500).json({ok:false,error:"MAP_LOAD_FAILED"})}}
async function cities(req,res){try{const viewer=await requireAuth(req,res);if(!viewer)return;res.json({ok:true,cities:await visibleCities(viewer.id)})}catch(e){console.error("real map cities",e);res.status(500).json({ok:false,error:"MAP_LOAD_FAILED"})}}
async function legacyLocation(req,res){try{const u=await requireAuth(req,res);if(!u)return;const city=clean(req.body?.city,80),sharePrecise=req.body?.sharePrecise===true,shareMap=Boolean(req.body?.shareMap),rawLat=req.body?.latitude,rawLng=req.body?.longitude,lat=Number(rawLat),lng=Number(rawLng),valid=provided(rawLat)&&provided(rawLng)&&Number.isFinite(lat)&&lat>=-90&&lat<=90&&Number.isFinite(lng)&&lng>=-180&&lng<=180;if(sharePrecise&&!valid)return res.status(400).json({ok:false,error:"INVALID_PRECISE_LOCATION"});await pool.query(`INSERT INTO user_locations(user_id,city,latitude,longitude,share_precise,share_map,updated_at) VALUES($1,$2,$3,$4,$5,$6,NOW()) ON CONFLICT(user_id) DO UPDATE SET city=EXCLUDED.city,latitude=EXCLUDED.latitude,longitude=EXCLUDED.longitude,share_precise=EXCLUDED.share_precise,share_map=EXCLUDED.share_map,updated_at=NOW()`,[u.id,city,sharePrecise?lat:null,sharePrecise?lng:null,sharePrecise,shareMap]);res.json({ok:true,compatibility:true})}catch(e){console.error("legacy map location",e);res.status(500).json({ok:false,error:"LOCATION_UPDATE_FAILED"})}}
async function places(req,res){try{const viewer=await requireAuth(req,res);if(!viewer)return;const rows=await visibleCities(viewer.id),places=[];for(const row of rows){if(Number(row.users)<3)continue;const point=base(row.city);if(!point)continue;places.push({city:row.city,latitude:Number(point[0].toFixed(2)),longitude:Number(point[1].toFixed(2)),users:Number(row.users)})}res.json({ok:true,places})}catch(e){console.error("real map places",e);res.status(500).json({ok:false,error:"MAP_LOAD_FAILED"})}}
http.createServer=function realMapCreateServer(app,...args){if(typeof app==="function"&&app?.use){
 app.get("/api/map/people-v2",people);
 // Compatibility owners keep historical callers functional without exposing old unguarded payloads.
 app.get("/api/map/people",people);
 app.get("/api/map/cities",cities);
 app.get("/api/map/places",places);
 app.post("/api/profile/location",legacyLocation);
 }return prior(app,...args)};
