import http from "http";
import {pool,ensureRedis,requireAuth,isAdmin,turnConfig} from "./runtime.mjs";

const prior=http.createServer.bind(http);let ready;
async function infra(){if(!ready)ready=(async()=>{await ensureRedis();await pool.query(`CREATE TABLE IF NOT EXISTS room_voice_presence(room_id BIGINT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,role TEXT NOT NULL DEFAULT 'listener' CHECK(role IN('listener','speaker')),requested BOOLEAN NOT NULL DEFAULT FALSE,muted BOOLEAN NOT NULL DEFAULT FALSE,joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),last_seen TIMESTAMPTZ NOT NULL DEFAULT NOW(),PRIMARY KEY(room_id,user_id))`);await pool.query(`CREATE INDEX IF NOT EXISTS room_voice_presence_active_idx ON room_voice_presence(room_id,last_seen DESC)`);await pool.query(`CREATE TABLE IF NOT EXISTS room_voice_signals(id BIGSERIAL PRIMARY KEY,room_id BIGINT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,sender_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,recipient_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,kind TEXT NOT NULL CHECK(kind IN('offer','answer','ice')),payload JSONB NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);await pool.query(`CREATE INDEX IF NOT EXISTS room_voice_signals_recv_idx ON room_voice_signals(room_id,recipient_id,id)`);})().catch(e=>{ready=null;throw e});return ready}
async function auth(req,res){await infra();return requireAuth(req,res)}
async function access(roomId,u){const room=(await pool.query(`SELECT id,is_public,owner_id,name,join_policy,max_members FROM rooms WHERE id=$1`,[roomId])).rows[0];if(!room)return {ok:false,error:"ROOM_NOT_FOUND"};if(!isAdmin(u)){const banned=(await pool.query(`SELECT 1 FROM room_bans WHERE room_id=$1 AND user_id=$2 LIMIT 1`,[roomId,u.id])).rows[0];if(banned)return {ok:false,error:"ROOM_BANNED"}}let mem=(await pool.query(`SELECT role FROM room_members WHERE room_id=$1 AND user_id=$2`,[roomId,u.id])).rows[0];if(!mem&&!isAdmin(u)){if(!room.is_public||room.join_policy!=="open")return {ok:false,error:room.join_policy==="invite"?"INVITE_REQUIRED":"JOIN_REQUIRED"};const members=Number((await pool.query(`SELECT COUNT(*)::int n FROM room_members WHERE room_id=$1`,[roomId])).rows[0]?.n||0);if(members>=Number(room.max_members||500))return {ok:false,error:"ROOM_FULL"};await pool.query(`INSERT INTO room_members(room_id,user_id,role) VALUES($1,$2,'member') ON CONFLICT DO NOTHING`,[roomId,u.id]);mem={role:"member"}}return {ok:true,room,memberRole:isAdmin(u)?"owner":(mem?.role||"member"),manager:isAdmin(u)||Number(room.owner_id)===Number(u.id)||["owner","moderator"].includes(mem?.role)}}
const deny=(res,a)=>res.status(a.error==="ROOM_NOT_FOUND"?404:a.error==="ROOM_FULL"?409:403).json({ok:false,error:a.error});

http.createServer=function(app,...args){if(typeof app==="function"&&app?.use){infra().catch(e=>console.error("room voice infra",e));
 app.get("/api/rooms/:id/voice/state",async(req,res)=>{try{const u=await auth(req,res);if(!u)return;const roomId=Number(req.params.id),a=await access(roomId,u);if(!a.ok)return deny(res,a);await pool.query(`DELETE FROM room_voice_presence WHERE room_id=$1 AND last_seen<NOW()-INTERVAL '20 seconds'`,[roomId]);const rows=(await pool.query(`SELECT p.user_id,p.role,p.requested,p.muted,p.joined_at,p.last_seen,u.username,u.display_name,u.avatar_url FROM room_voice_presence p JOIN users u ON u.id=p.user_id WHERE p.room_id=$1 ORDER BY CASE p.role WHEN 'speaker' THEN 0 ELSE 1 END,p.joined_at`,[roomId])).rows;const rtc=turnConfig(u.id);res.json({ok:true,viewerId:u.id,manager:a.manager,roomName:a.room.name,participants:rows,iceServers:rtc.iceServers,turnConfigured:rtc.turnConfigured,tlsConfigured:rtc.tlsConfigured,forceRelay:rtc.forceRelay,maxSpeakers:6})}catch(e){console.error("voice state",e);res.status(500).json({ok:false,error:"VOICE_STATE_FAILED"})}});
 app.post("/api/rooms/:id/voice/join",async(req,res)=>{try{const u=await auth(req,res);if(!u)return;const roomId=Number(req.params.id),a=await access(roomId,u);if(!a.ok)return deny(res,a);await pool.query(`INSERT INTO room_voice_presence(room_id,user_id,role,last_seen) VALUES($1,$2,'listener',NOW()) ON CONFLICT(room_id,user_id) DO UPDATE SET last_seen=NOW()`,[roomId,u.id]);res.json({ok:true})}catch(e){res.status(500).json({ok:false,error:"VOICE_JOIN_FAILED"})}});
 app.post("/api/rooms/:id/voice/heartbeat",async(req,res)=>{try{const u=await auth(req,res);if(!u)return;const a=await access(Number(req.params.id),u);if(!a.ok)return deny(res,a);await pool.query(`UPDATE room_voice_presence SET last_seen=NOW(),muted=$3 WHERE room_id=$1 AND user_id=$2`,[Number(req.params.id),u.id,Boolean(req.body?.muted)]);res.json({ok:true})}catch{res.status(500).json({ok:false,error:"VOICE_HEARTBEAT_FAILED"})}});
 app.post("/api/rooms/:id/voice/leave",async(req,res)=>{try{const u=await auth(req,res);if(!u)return;const roomId=Number(req.params.id);await pool.query(`DELETE FROM room_voice_presence WHERE room_id=$1 AND user_id=$2`,[roomId,u.id]);await pool.query(`DELETE FROM room_voice_signals WHERE room_id=$1 AND (sender_id=$2 OR recipient_id=$2)`,[roomId,u.id]);res.json({ok:true})}catch{res.status(500).json({ok:false,error:"VOICE_LEAVE_FAILED"})}});
 app.post("/api/rooms/:id/voice/request",async(req,res)=>{try{const u=await auth(req,res);if(!u)return;const roomId=Number(req.params.id),a=await access(roomId,u);if(!a.ok)return deny(res,a);await pool.query(`UPDATE room_voice_presence SET requested=TRUE,last_seen=NOW() WHERE room_id=$1 AND user_id=$2`,[roomId,u.id]);res.json({ok:true})}catch{res.status(500).json({ok:false,error:"VOICE_REQUEST_FAILED"})}});
 app.post("/api/rooms/:id/voice/role",async(req,res)=>{try{const u=await auth(req,res);if(!u)return;const roomId=Number(req.params.id),a=await access(roomId,u);if(!a.ok)return deny(res,a);const target=Number(req.body?.userId||u.id),role=req.body?.role==="speaker"?"speaker":"listener";if(target!==Number(u.id)&&!a.manager)return res.status(403).json({ok:false,error:"FORBIDDEN"});if(target===Number(u.id)&&role==="speaker"&&!a.manager){const speakers=Number((await pool.query(`SELECT COUNT(*)::int n FROM room_voice_presence WHERE room_id=$1 AND role='speaker' AND last_seen>NOW()-INTERVAL '20 seconds'`,[roomId])).rows[0].n);if(speakers>0)return res.status(403).json({ok:false,error:"MIC_APPROVAL_REQUIRED"})}if(role==="speaker"){const speakers=Number((await pool.query(`SELECT COUNT(*)::int n FROM room_voice_presence WHERE room_id=$1 AND role='speaker' AND user_id<>$2 AND last_seen>NOW()-INTERVAL '20 seconds'`,[roomId,target])).rows[0].n);if(speakers>=6)return res.status(409).json({ok:false,error:"SPEAKER_LIMIT"})}await pool.query(`UPDATE room_voice_presence SET role=$3,requested=FALSE,muted=FALSE,last_seen=NOW() WHERE room_id=$1 AND user_id=$2`,[roomId,target,role]);res.json({ok:true})}catch(e){console.error("voice role",e);res.status(500).json({ok:false,error:"VOICE_ROLE_FAILED"})}});
 app.post("/api/rooms/:id/voice/kick",async(req,res)=>{try{const u=await auth(req,res);if(!u)return;const roomId=Number(req.params.id),a=await access(roomId,u);if(!a.ok)return deny(res,a);if(!a.manager)return res.status(403).json({ok:false,error:"FORBIDDEN"});const target=Number(req.body?.userId);await pool.query(`DELETE FROM room_voice_presence WHERE room_id=$1 AND user_id=$2`,[roomId,target]);await pool.query(`DELETE FROM room_voice_signals WHERE room_id=$1 AND (sender_id=$2 OR recipient_id=$2)`,[roomId,target]);res.json({ok:true})}catch{res.status(500).json({ok:false,error:"VOICE_KICK_FAILED"})}});
 app.post("/api/rooms/:id/voice/signals",async(req,res)=>{try{const u=await auth(req,res);if(!u)return;const roomId=Number(req.params.id),a=await access(roomId,u);if(!a.ok)return deny(res,a);const recipient=Number(req.body?.recipientId),kind=String(req.body?.kind||""),payload=req.body?.payload;if(!["offer","answer","ice"].includes(kind)||!recipient||!payload||typeof payload!=="object")return res.status(400).json({ok:false,error:"BAD_SIGNAL"});const active=(await pool.query(`SELECT 1 FROM room_voice_presence WHERE room_id=$1 AND user_id=$2 AND last_seen>NOW()-INTERVAL '20 seconds'`,[roomId,u.id])).rows[0],other=(await pool.query(`SELECT 1 FROM room_voice_presence WHERE room_id=$1 AND user_id=$2 AND last_seen>NOW()-INTERVAL '20 seconds'`,[roomId,recipient])).rows[0];if(!active||!other)return res.status(403).json({ok:false,error:"VOICE_NOT_JOINED"});const row=(await pool.query(`INSERT INTO room_voice_signals(room_id,sender_id,recipient_id,kind,payload) VALUES($1,$2,$3,$4,$5) RETURNING id`,[roomId,u.id,recipient,kind,payload])).rows[0];res.status(201).json({ok:true,id:row.id})}catch(e){console.error("voice signal",e);res.status(500).json({ok:false,error:"VOICE_SIGNAL_FAILED"})}});
 app.get("/api/rooms/:id/voice/signals",async(req,res)=>{try{const u=await auth(req,res);if(!u)return;const roomId=Number(req.params.id),a=await access(roomId,u);if(!a.ok)return deny(res,a);const since=Math.max(0,Number(req.query.since)||0),rows=(await pool.query(`SELECT id,sender_id,kind,payload,created_at FROM room_voice_signals WHERE room_id=$1 AND recipient_id=$2 AND id>$3 ORDER BY id ASC LIMIT 300`,[roomId,u.id,since])).rows;res.json({ok:true,signals:rows})}catch(e){console.error("voice signal load",e);res.status(500).json({ok:false,error:"VOICE_SIGNAL_LOAD_FAILED"})}});
 }return prior(app,...args)};
