import http from "http";
import crypto from "crypto";
import fs from "fs/promises";
import path from "path";
import multer from "multer";
import {requireAuth,turnConfig} from "./runtime.mjs";

const prior=http.createServer.bind(http),uploadDir=path.resolve(process.env.UPLOAD_DIR||"/app/uploads");
const memoryUpload=multer({storage:multer.memoryStorage(),limits:{fileSize:8*1024*1024,files:1}});
function detectedType(buf){if(!buf||buf.length<4)return null;if(buf[0]===0xff&&buf[1]===0xd8&&buf[2]===0xff)return{mime:"image/jpeg",ext:"jpg"};if(buf.subarray(0,8).equals(Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a])))return{mime:"image/png",ext:"png"};if(["GIF87a","GIF89a"].includes(buf.subarray(0,6).toString("ascii")))return{mime:"image/gif",ext:"gif"};if(buf.subarray(0,4).toString("ascii")==="RIFF"&&buf.subarray(8,12).toString("ascii")==="WEBP")return{mime:"image/webp",ext:"webp"};if(buf.subarray(0,5).toString("ascii")==="%PDF-")return{mime:"application/pdf",ext:"pdf"};if(buf.subarray(0,4).toString("ascii")==="OggS")return{mime:"audio/ogg",ext:"ogg"};if(buf.subarray(0,4).toString("ascii")==="RIFF"&&buf.subarray(8,12).toString("ascii")==="WAVE")return{mime:"audio/wav",ext:"wav"};if(buf.subarray(0,3).toString("ascii")==="ID3"||(buf[0]===0xff&&(buf[1]&0xe0)===0xe0))return{mime:"audio/mpeg",ext:"mp3"};if(buf.length>12&&buf.subarray(4,8).toString("ascii")==="ftyp")return{mime:"audio/mp4",ext:"m4a"};return null}
http.createServer=function p0CreateServer(app,...args){if(typeof app==="function"&&app?.use){
 app.post("/api/uploads",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;memoryUpload.single("file")(req,res,async err=>{try{if(err)return res.status(err.code==="LIMIT_FILE_SIZE"?413:400).json({ok:false,error:err.code==="LIMIT_FILE_SIZE"?"FILE_TOO_LARGE":"UPLOAD_FAILED"});if(!req.file)return res.status(400).json({ok:false,error:"NO_FILE"});const kind=detectedType(req.file.buffer);if(!kind)return res.status(400).json({ok:false,error:"UNSUPPORTED_FILE"});await fs.mkdir(uploadDir,{recursive:true});const name=`${Date.now()}-${crypto.randomBytes(12).toString("hex")}.${kind.ext}`;await fs.writeFile(path.join(uploadDir,name),req.file.buffer,{flag:"wx"});return res.status(201).json({ok:true,file:{url:`/api/uploads/files/${name}`,name:req.file.originalname,size:req.file.size,type:kind.mime}})}catch(e){console.error("secure upload",e);return res.status(500).json({ok:false,error:"UPLOAD_FAILED"})}})});
 app.get("/api/rtc/preflight",async(req,res)=>{const u=await requireAuth(req,res);if(!u)return;const cfg=turnConfig(u.id),turn=cfg.iceServers.find(x=>x.username);res.json({ok:true,turnConfigured:cfg.turnConfigured,tlsConfigured:cfg.tlsConfigured,forceRelay:cfg.forceRelay,iceServerCount:cfg.iceServers.length,relayUrls:turn?.urls||[]})});
 }return prior(app,...args)};
