import http from "http";
import crypto from "crypto";
import {pool,redis,ensureRedis,requireAuth,requireAdmin,tokenFrom,emitUser,isAdmin,clean} from "./runtime.mjs";
const prior=http.createServer.bind(http),hash=t=>crypto.createHash("sha256").update(String(t)).digest("hex");
const currentToken=req=>tokenFrom(req);
async function scan(fn){await ensureRedis();for await(const raw of redis.scanIterator({MATCH:"session:*",COUNT:200})){const key=String(raw);if(await fn(key)===false)break}}
http.createServer=function sessionControlCreateServer(app,...args){if(typeof app==="function"&&app?.use){
 app.delete("/api/account/sessions/:id",async(req,res)=>{try{const u=await requireAuth(req,res);if(!u)return;const prefix=String(req.params.id||"").slice(0,32);if(!/^[a-f0-9]{8,32}$/i.test(prefix))return res.status(400).json({ok:false,error:"INVALID_SESSION"});const row=(await pool.query(`SELECT session_hash FROM user_sessions WHERE user_id=$1 AND session_hash LIKE $2||'%' ORDER BY last_seen DESC LIMIT 1`,[u.id,prefix])).rows[0];if(!row)return res.status(404).json({ok:false,error:"SESSION_NOT_FOUND"});await scan(async key=>{const raw=key.slice(8);if(hash(raw)===row.session_hash){await redis.del(key);return false}});await Promise.all([pool.query(`DELETE FROM user_sessions WHERE session_hash=$1`,[row.session_hash]),pool.query(`DELETE FROM durable_sessions WHERE token_hash=$1`,[row.session_hash])]);emitUser(u.id,"session:revoked",{sessionId:row.session_hash.slice(0,16),reason:"ended-by-user",at:new Date().toISOString()});res.json({ok:true})}catch(e){console.error("session revoke",e);res.status(500).json({ok:false,error:"SESSION_REVOKE_FAILED"})}});
 app.post("/api/account/logout-all",async(req,res)=>{try{const current=currentToken(req),u=await requireAuth(req,res);if(!u)return;if(!current)return res.status(401).json({ok:false,error:"UNAUTHORIZED"});const currentHash=hash(current);await scan(async key=>{if(key===`session:${current}`)return;const value=await redis.get(key);if(String(value)===String(u.id))await redis.del(key)});await Promise.all([pool.query(`DELETE FROM user_sessions WHERE user_id=$1 AND session_hash<>$2`,[u.id,currentHash]).catch(()=>{}),pool.query(`DELETE FROM durable_sessions WHERE user_id=$1 AND token_hash<>$2`,[u.id,currentHash]).catch(()=>{})]);emitUser(u.id,"session:revoked",{exceptSessionId:currentHash.slice(0,16),reason:"logout-other-devices",at:new Date().toISOString()});res.json({ok:true})}catch(e){console.error("logout others",e);res.status(500).json({ok:false,error:"LOGOUT_ALL_FAILED"})}});

 // Authoritative moderation path uses role-based admin authorization, Redis SCAN
 // and durable-session revocation. Runtime reads HttpOnly cookie or Bearer directly.
 app.patch("/api/admin/users/:id/status",async(req,res)=>{try{const admin=await requireAdmin(req,res);if(!admin)return;const target=Number(req.params.id),status=String(req.body?.status||""),reason=clean(req.body?.reason,240);if(!Number.isSafeInteger(target)||target<1)return res.status(400).json({ok:false,error:"INVALID_USER"});if(!["active","frozen","banned"].includes(status))return res.status(400).json({ok:false,error:"INVALID_STATUS"});const user=(await pool.query(`SELECT id,email,username,display_name,role FROM users WHERE id=$1`,[target])).rows[0];if(!user)return res.status(404).json({ok:false,error:"USER_NOT_FOUND"});if(isAdmin(user))return res.status(409).json({ok:false,error:"CANNOT_MODERATE_ADMIN"});const row=(await pool.query(`UPDATE users SET account_status=$1,ban_reason=$2,updated_at=NOW() WHERE id=$3 RETURNING id,email,username,display_name,account_status,ban_reason`,[status,status==="active"?"":reason,target])).rows[0];if(status!=="active"){await scan(async key=>{if(String(await redis.get(key))===String(target))await redis.del(key)});await Promise.all([pool.query(`DELETE FROM user_sessions WHERE user_id=$1`,[target]).catch(()=>{}),pool.query(`DELETE FROM durable_sessions WHERE user_id=$1`,[target]).catch(()=>{})]);emitUser(target,"session:revoked",{reason:status==="banned"?"account-banned":"account-frozen",at:new Date().toISOString()})}res.json({ok:true,user:row})}catch(e){console.error("admin status update",e);res.status(500).json({ok:false,error:"USER_STATUS_UPDATE_FAILED"})}});
 }return prior(app,...args)};
