import http from "http";
import crypto from "crypto";
import {pool,redis,ensureRedis,requireAuth,requireAdmin,tokenFrom,emitUser,isAdmin,clean} from "./runtime.mjs";
const prior=http.createServer.bind(http),hash=t=>crypto.createHash("sha256").update(String(t)).digest("hex");
const currentToken=req=>tokenFrom(req);
async function scan(fn){await ensureRedis();for await(const raw of redis.scanIterator({MATCH:"session:*",COUNT:200})){const key=String(raw);if(await fn(key)===false)break}}
http.createServer=function sessionControlCreateServer(app,...args){if(typeof app==="function"&&app?.use){
 app.get("/api/account/sessions",async(req,res)=>{try{const u=await requireAuth(req,res);if(!u)return;const currentHash=hash(currentToken(req));const rows=(await pool.query(`SELECT d.token_hash,d.created_at,d.last_seen,d.expires_at,COALESCE(s.user_agent,'') user_agent,COALESCE(s.ip_address,'') ip_address FROM durable_sessions d LEFT JOIN user_sessions s ON s.session_hash=d.token_hash AND s.user_id=d.user_id WHERE d.user_id=$1 AND d.expires_at>NOW() ORDER BY d.last_seen DESC,d.created_at DESC LIMIT 50`,[u.id])).rows;res.json({ok:true,sessions:rows.map(x=>({id:x.token_hash.slice(0,16),user_agent:x.user_agent,ip_address:x.ip_address,created_at:x.created_at,last_seen:x.last_seen,expires_at:x.expires_at,current:x.token_hash===currentHash}))})}catch(e){console.error("session list",e);res.status(500).json({ok:false,error:"SESSIONS_LOAD_FAILED"})}});
 app.delete("/api/account/sessions/:id",async(req,res)=>{try{const u=await requireAuth(req,res);if(!u)return;const prefix=String(req.params.id||"");if(!/^[a-f0-9]{16}$/i.test(prefix))return res.status(400).json({ok:false,error:"INVALID_SESSION"});const rows=(await pool.query(`SELECT token_hash FROM durable_sessions WHERE user_id=$1 AND token_hash LIKE $2||'%' AND expires_at>NOW() ORDER BY last_seen DESC LIMIT 2`,[u.id,prefix])).rows;if(rows.length!==1)return res.status(rows.length?409:404).json({ok:false,error:rows.length?"SESSION_ID_AMBIGUOUS":"SESSION_NOT_FOUND"});const sessionHash=rows[0].token_hash;await scan(async key=>{const raw=key.slice(8);if(hash(raw)===sessionHash){await redis.del(key);return false}});await Promise.all([pool.query(`DELETE FROM user_sessions WHERE session_hash=$1`,[sessionHash]).catch(()=>{}),pool.query(`DELETE FROM durable_sessions WHERE token_hash=$1`,[sessionHash])]);emitUser(u.id,"session:revoked",{sessionId:sessionHash.slice(0,16),reason:"ended-by-user",at:new Date().toISOString()});res.json({ok:true})}catch(e){console.error("session revoke",e);res.status(500).json({ok:false,error:"SESSION_REVOKE_FAILED"})}});
 app.post("/api/account/logout-all",async(req,res)=>{try{const current=currentToken(req),u=await requireAuth(req,res);if(!u)return;if(!current)return res.status(401).json({ok:false,error:"UNAUTHORIZED"});const currentHash=hash(current);await scan(async key=>{if(key===`session:${current}`)return;const value=await redis.get(key);if(String(value)===String(u.id))await redis.del(key)});await Promise.all([pool.query(`DELETE FROM user_sessions WHERE user_id=$1 AND session_hash<>$2`,[u.id,currentHash]).catch(()=>{}),pool.query(`DELETE FROM durable_sessions WHERE user_id=$1 AND token_hash<>$2`,[u.id,currentHash]).catch(()=>{})]);emitUser(u.id,"session:revoked",{exceptSessionId:currentHash.slice(0,16),reason:"logout-other-devices",at:new Date().toISOString()});res.json({ok:true})}catch(e){console.error("logout others",e);res.status(500).json({ok:false,error:"LOGOUT_ALL_FAILED"})}});

 // Authoritative moderation path uses role-based admin authorization, Redis SCAN
 // and durable-session revocation. Runtime reads HttpOnly cookie or Bearer directly.
 }return prior(app,...args)};
