import http from "http";
import crypto from "crypto";
import {pool,redis,ensureRedis,requireAuth,tokenFrom,emitUser} from "./runtime.mjs";
const prior=http.createServer.bind(http),hash=t=>crypto.createHash("sha256").update(String(t)).digest("hex");
function cookieToken(req){const c=String(req.headers.cookie||"").split(";").map(x=>x.trim()).find(x=>x.startsWith("marbo3a_session="));const t=c?decodeURIComponent(c.slice("marbo3a_session=".length)):"";return /^[a-f0-9]{64}$/i.test(t)?t:""}
function prepare(req){const t=tokenFrom(req)||cookieToken(req);if(t&&!req.headers.authorization)req.headers.authorization=`Bearer ${t}`;return t}
async function scan(fn){await ensureRedis();for await(const raw of redis.scanIterator({MATCH:"session:*",COUNT:200})){const key=String(raw);if(await fn(key)===false)break}}
http.createServer=function sessionControlCreateServer(app,...args){if(typeof app==="function"&&app?.use){
 app.delete("/api/account/sessions/:id",async(req,res)=>{try{prepare(req);const u=await requireAuth(req,res);if(!u)return;const prefix=String(req.params.id||"").slice(0,32);if(!/^[a-f0-9]{8,32}$/i.test(prefix))return res.status(400).json({ok:false,error:"INVALID_SESSION"});const row=(await pool.query(`SELECT session_hash FROM user_sessions WHERE user_id=$1 AND session_hash LIKE $2||'%' ORDER BY last_seen DESC LIMIT 1`,[u.id,prefix])).rows[0];if(!row)return res.status(404).json({ok:false,error:"SESSION_NOT_FOUND"});await scan(async key=>{const raw=key.slice(8);if(hash(raw)===row.session_hash){await redis.del(key);return false}});await pool.query(`DELETE FROM user_sessions WHERE session_hash=$1`,[row.session_hash]);emitUser(u.id,"session:revoked",{sessionId:row.session_hash.slice(0,16),reason:"ended-by-user",at:new Date().toISOString()});res.json({ok:true})}catch(e){console.error("session revoke",e);res.status(500).json({ok:false,error:"SESSION_REVOKE_FAILED"})}});
 app.post("/api/account/logout-all",async(req,res)=>{try{const current=prepare(req),u=await requireAuth(req,res);if(!u)return;const currentHash=hash(current);await scan(async key=>{if(key===`session:${current}`)return;const value=await redis.get(key);if(String(value)===String(u.id))await redis.del(key)});await pool.query(`DELETE FROM user_sessions WHERE user_id=$1 AND session_hash<>$2`,[u.id,currentHash]).catch(()=>{});emitUser(u.id,"session:revoked",{exceptSessionId:currentHash.slice(0,16),reason:"logout-other-devices",at:new Date().toISOString()});res.json({ok:true})}catch(e){console.error("logout others",e);res.status(500).json({ok:false,error:"LOGOUT_ALL_FAILED"})}});
 }return prior(app,...args)};
