import http from "http";
import {pool,requireAuth,isAdmin,clean} from "./runtime.mjs";

const prior=http.createServer.bind(http);
const allowedKind=new Set(["text","image","video"]),allowedPrivacy=new Set(["everyone","friends"]),allowedFilter=new Set(["normal","warm","cool","mono"]);
const clamp=(value,min,max,fallback)=>{const n=Number(value);return Number.isFinite(n)?Math.min(max,Math.max(min,n)):fallback};
const localMediaUrl=value=>/^\/(?:api\/uploads(?:\/files)?|uploads)\/[A-Za-z0-9._-]+(?:\?.*)?$/.test(String(value||""));
async function areFriends(a,b){return Boolean((await pool.query(`SELECT 1 FROM friendships WHERE status='accepted' AND ((requester_id=$1 AND addressee_id=$2) OR (requester_id=$2 AND addressee_id=$1)) LIMIT 1`,[a,b])).rows[0])}
async function mutualCount(a,b){return Number((await pool.query(`WITH af AS(SELECT CASE WHEN requester_id=$1 THEN addressee_id ELSE requester_id END id FROM friendships WHERE status='accepted' AND (requester_id=$1 OR addressee_id=$1)),bf AS(SELECT CASE WHEN requester_id=$2 THEN addressee_id ELSE requester_id END id FROM friendships WHERE status='accepted' AND (requester_id=$2 OR addressee_id=$2)) SELECT COUNT(*)::int n FROM af JOIN bf USING(id)`,[a,b])).rows[0]?.n||0)}
async function blocked(a,b){return Boolean((await pool.query(`SELECT 1 FROM user_blocks WHERE(blocker_id=$1 AND blocked_id=$2)OR(blocker_id=$2 AND blocked_id=$1) LIMIT 1`,[a,b])).rows[0])}
async function accountStoryAllowed(ownerId,viewerId){if(String(ownerId)===String(viewerId))return true;if(await blocked(ownerId,viewerId))return false;const rule=(await pool.query(`SELECT who_can_see_story FROM profile_privacy WHERE user_id=$1`,[ownerId])).rows[0]?.who_can_see_story||"everyone";if(rule==="everyone")return true;if(rule==="nobody")return false;if(await areFriends(ownerId,viewerId))return true;return rule==="friends_of_friends"&&(await mutualCount(ownerId,viewerId))>0}
async function canSee(story,viewerId){if(String(story.user_id)===String(viewerId))return true;if(!await accountStoryAllowed(story.user_id,viewerId))return false;if(story.privacy==="everyone")return true;return areFriends(viewerId,story.user_id)}

http.createServer=function storiesCreateServer(app,...args){
 if(typeof app==="function"&&app?.use){
  app.get("/api/stories",async(req,res)=>{try{const viewer=await requireAuth(req,res);if(!viewer)return;const rows=(await pool.query(`SELECT s.id,s.user_id,s.kind,s.text_body,s.media_url,s.media_type,s.privacy,s.filter_name,s.overlay_x,s.overlay_y,s.created_at,s.expires_at,u.username,u.display_name,u.gender,u.avatar_url,EXISTS(SELECT 1 FROM story_views v WHERE v.story_id=s.id AND v.viewer_id=$1) seen,CASE WHEN s.user_id=$1 THEN (SELECT COUNT(*)::int FROM story_views v WHERE v.story_id=s.id AND v.viewer_id<>$1) ELSE NULL END views_count FROM stories s JOIN users u ON u.id=s.user_id WHERE s.deleted_at IS NULL AND s.expires_at>NOW() AND u.account_status='active' AND (s.user_id=$1 OR s.privacy='everyone' OR EXISTS(SELECT 1 FROM friendships f WHERE f.status='accepted' AND ((f.requester_id=$1 AND f.addressee_id=s.user_id) OR (f.addressee_id=$1 AND f.requester_id=s.user_id)))) ORDER BY CASE WHEN s.user_id=$1 THEN 0 ELSE 1 END,s.created_at ASC,s.id ASC`,[viewer.id])).rows,visible=[];for(const s of rows)if(await accountStoryAllowed(s.user_id,viewer.id))visible.push(s);res.json({ok:true,stories:visible,viewerId:viewer.id})}catch(e){console.error("stories list",e);res.status(500).json({ok:false,error:"STORIES_LOAD_FAILED"})}});

  app.post("/api/stories",async(req,res)=>{try{const viewer=await requireAuth(req,res);if(!viewer)return;const kind=clean(req.body?.kind,12),privacy=allowedPrivacy.has(req.body?.privacy)?req.body.privacy:"friends",text=clean(req.body?.text,600),rawMediaUrl=clean(req.body?.mediaUrl,900)||null,rawMediaType=clean(req.body?.mediaType,100)||null,filterName=allowedFilter.has(req.body?.filterName)?req.body.filterName:"normal",overlayX=clamp(req.body?.overlayX,5,95,50),overlayY=clamp(req.body?.overlayY,10,90,78);if(!allowedKind.has(kind))return res.status(400).json({ok:false,error:"INVALID_STORY_KIND"});if(kind==="text"&&!text)return res.status(400).json({ok:false,error:"EMPTY_STORY"});if((kind==="image"||kind==="video")&&!rawMediaUrl)return res.status(400).json({ok:false,error:"STORY_MEDIA_REQUIRED"});if(kind!=="text"&&!localMediaUrl(rawMediaUrl))return res.status(400).json({ok:false,error:"INVALID_STORY_MEDIA"});if(kind==="image"&&!String(rawMediaType||"").startsWith("image/"))return res.status(400).json({ok:false,error:"INVALID_STORY_MEDIA_TYPE"});if(kind==="video"&&!String(rawMediaType||"").startsWith("video/"))return res.status(400).json({ok:false,error:"INVALID_STORY_MEDIA_TYPE"});const mediaUrl=kind==="text"?null:rawMediaUrl,mediaType=kind==="text"?null:rawMediaType;const row=(await pool.query(`INSERT INTO stories(user_id,kind,text_body,media_url,media_type,privacy,filter_name,overlay_x,overlay_y) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[viewer.id,kind,text,mediaUrl,mediaType,privacy,filterName,overlayX,overlayY])).rows[0];res.status(201).json({ok:true,story:{...row,username:viewer.username,display_name:viewer.display_name,gender:viewer.gender,avatar_url:viewer.avatar_url,seen:true,views_count:0}})}catch(e){console.error("story create",e);res.status(500).json({ok:false,error:"STORY_CREATE_FAILED"})}});

  app.post("/api/stories/:id/view",async(req,res)=>{try{const viewer=await requireAuth(req,res);if(!viewer)return;const id=Number(req.params.id),story=(await pool.query(`SELECT * FROM stories WHERE id=$1 AND deleted_at IS NULL AND expires_at>NOW()`,[id])).rows[0];if(!story)return res.status(404).json({ok:false,error:"STORY_NOT_FOUND"});if(!await canSee(story,viewer.id))return res.status(403).json({ok:false,error:"STORY_FORBIDDEN"});if(String(story.user_id)!==String(viewer.id))await pool.query(`INSERT INTO story_views(story_id,viewer_id,viewed_at) VALUES($1,$2,NOW()) ON CONFLICT(story_id,viewer_id) DO UPDATE SET viewed_at=NOW()`,[id,viewer.id]);res.json({ok:true})}catch(e){console.error("story view",e);res.status(500).json({ok:false,error:"STORY_VIEW_FAILED"})}});

  app.get("/api/stories/:id/viewers",async(req,res)=>{try{const viewer=await requireAuth(req,res);if(!viewer)return;const id=Number(req.params.id),story=(await pool.query(`SELECT user_id FROM stories WHERE id=$1`,[id])).rows[0];if(!story)return res.status(404).json({ok:false,error:"STORY_NOT_FOUND"});if(String(story.user_id)!==String(viewer.id)&&!isAdmin(viewer))return res.status(403).json({ok:false,error:"FORBIDDEN"});const rows=(await pool.query(`SELECT v.viewer_id,v.viewed_at,u.username,u.display_name,u.gender,u.avatar_url FROM story_views v JOIN users u ON u.id=v.viewer_id WHERE v.story_id=$1 ORDER BY v.viewed_at DESC LIMIT 500`,[id])).rows;res.json({ok:true,viewers:rows})}catch(e){console.error("story viewers",e);res.status(500).json({ok:false,error:"STORY_VIEWERS_FAILED"})}});

  app.delete("/api/stories/:id",async(req,res)=>{try{const viewer=await requireAuth(req,res);if(!viewer)return;const id=Number(req.params.id),story=(await pool.query(`SELECT user_id FROM stories WHERE id=$1 AND deleted_at IS NULL`,[id])).rows[0];if(!story)return res.status(404).json({ok:false,error:"STORY_NOT_FOUND"});if(String(story.user_id)!==String(viewer.id)&&!isAdmin(viewer))return res.status(403).json({ok:false,error:"FORBIDDEN"});const client=await pool.connect();try{await client.query("BEGIN");await client.query(`UPDATE stories SET deleted_at=NOW() WHERE id=$1`,[id]);await client.query(`DELETE FROM story_highlights WHERE story_id=$1`,[id]);await client.query(`DELETE FROM notifications WHERE ref_id=$1 AND type IN('story_reaction','story_reply')`,[id]);await client.query("COMMIT")}catch(e){await client.query("ROLLBACK").catch(()=>{});throw e}finally{client.release()}res.json({ok:true})}catch(e){console.error("story delete",e);res.status(500).json({ok:false,error:"STORY_DELETE_FAILED"})}});
 }
 return prior(app,...args);
};