import http from "http";
import {pool,requireAuth,isAdmin,clean} from "./runtime.mjs";

const prior=http.createServer.bind(http);
const allowedKind=new Set(["text","image","video"]),allowedPrivacy=new Set(["everyone","friends"]);
async function canSee(story,viewerId){if(String(story.user_id)===String(viewerId)||story.privacy==="everyone")return true;return Boolean((await pool.query(`SELECT 1 FROM friendships WHERE status='accepted' AND ((requester_id=$1 AND addressee_id=$2) OR (requester_id=$2 AND addressee_id=$1)) LIMIT 1`,[viewerId,story.user_id])).rows[0])}

http.createServer=function storiesCreateServer(app,...args){
 if(typeof app==="function"&&app?.use){
  app.get("/api/stories",async(req,res)=>{try{const viewer=await requireAuth(req,res);if(!viewer)return;const rows=(await pool.query(`SELECT s.id,s.user_id,s.kind,s.text_body,s.media_url,s.media_type,s.privacy,s.created_at,s.expires_at,u.username,u.display_name,u.avatar_url,EXISTS(SELECT 1 FROM story_views v WHERE v.story_id=s.id AND v.viewer_id=$1) seen,CASE WHEN s.user_id=$1 THEN (SELECT COUNT(*)::int FROM story_views v WHERE v.story_id=s.id AND v.viewer_id<>$1) ELSE NULL END views_count FROM stories s JOIN users u ON u.id=s.user_id WHERE s.deleted_at IS NULL AND s.expires_at>NOW() AND u.account_status='active' AND (s.user_id=$1 OR s.privacy='everyone' OR EXISTS(SELECT 1 FROM friendships f WHERE f.status='accepted' AND ((f.requester_id=$1 AND f.addressee_id=s.user_id) OR (f.addressee_id=$1 AND f.requester_id=s.user_id)))) ORDER BY CASE WHEN s.user_id=$1 THEN 0 ELSE 1 END,s.created_at ASC,s.id ASC`,[viewer.id])).rows;res.json({ok:true,stories:rows,viewerId:viewer.id})}catch(e){console.error("stories list",e);res.status(500).json({ok:false,error:"STORIES_LOAD_FAILED"})}});

  app.post("/api/stories",async(req,res)=>{try{const viewer=await requireAuth(req,res);if(!viewer)return;const kind=clean(req.body?.kind,12),privacy=allowedPrivacy.has(req.body?.privacy)?req.body.privacy:"friends",text=clean(req.body?.text,600),mediaUrl=clean(req.body?.mediaUrl,900)||null,mediaType=clean(req.body?.mediaType,100)||null;if(!allowedKind.has(kind))return res.status(400).json({ok:false,error:"INVALID_STORY_KIND"});if(kind==="text"&&!text)return res.status(400).json({ok:false,error:"EMPTY_STORY"});if((kind==="image"||kind==="video")&&!mediaUrl)return res.status(400).json({ok:false,error:"STORY_MEDIA_REQUIRED"});const row=(await pool.query(`INSERT INTO stories(user_id,kind,text_body,media_url,media_type,privacy) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[viewer.id,kind,text,mediaUrl,mediaType,privacy])).rows[0];res.status(201).json({ok:true,story:{...row,username:viewer.username,display_name:viewer.display_name,avatar_url:viewer.avatar_url,seen:true,views_count:0}})}catch(e){console.error("story create",e);res.status(500).json({ok:false,error:"STORY_CREATE_FAILED"})}});

  app.post("/api/stories/:id/view",async(req,res)=>{try{const viewer=await requireAuth(req,res);if(!viewer)return;const id=Number(req.params.id),story=(await pool.query(`SELECT * FROM stories WHERE id=$1 AND deleted_at IS NULL AND expires_at>NOW()`,[id])).rows[0];if(!story)return res.status(404).json({ok:false,error:"STORY_NOT_FOUND"});if(!await canSee(story,viewer.id))return res.status(403).json({ok:false,error:"STORY_FORBIDDEN"});if(String(story.user_id)!==String(viewer.id))await pool.query(`INSERT INTO story_views(story_id,viewer_id,viewed_at) VALUES($1,$2,NOW()) ON CONFLICT(story_id,viewer_id) DO UPDATE SET viewed_at=NOW()`,[id,viewer.id]);res.json({ok:true})}catch(e){console.error("story view",e);res.status(500).json({ok:false,error:"STORY_VIEW_FAILED"})}});

  app.get("/api/stories/:id/viewers",async(req,res)=>{try{const viewer=await requireAuth(req,res);if(!viewer)return;const id=Number(req.params.id),story=(await pool.query(`SELECT user_id FROM stories WHERE id=$1`,[id])).rows[0];if(!story)return res.status(404).json({ok:false,error:"STORY_NOT_FOUND"});if(String(story.user_id)!==String(viewer.id)&&!isAdmin(viewer))return res.status(403).json({ok:false,error:"FORBIDDEN"});const rows=(await pool.query(`SELECT v.viewer_id,v.viewed_at,u.username,u.display_name,u.avatar_url FROM story_views v JOIN users u ON u.id=v.viewer_id WHERE v.story_id=$1 ORDER BY v.viewed_at DESC LIMIT 500`,[id])).rows;res.json({ok:true,viewers:rows})}catch(e){console.error("story viewers",e);res.status(500).json({ok:false,error:"STORY_VIEWERS_FAILED"})}});

  app.delete("/api/stories/:id",async(req,res)=>{try{const viewer=await requireAuth(req,res);if(!viewer)return;const id=Number(req.params.id),story=(await pool.query(`SELECT user_id FROM stories WHERE id=$1 AND deleted_at IS NULL`,[id])).rows[0];if(!story)return res.status(404).json({ok:false,error:"STORY_NOT_FOUND"});if(String(story.user_id)!==String(viewer.id)&&!isAdmin(viewer))return res.status(403).json({ok:false,error:"FORBIDDEN"});await pool.query(`UPDATE stories SET deleted_at=NOW() WHERE id=$1`,[id]);res.json({ok:true})}catch(e){console.error("story delete",e);res.status(500).json({ok:false,error:"STORY_DELETE_FAILED"})}});
 }
 return prior(app,...args);
};
