"use client";
import {useEffect,useMemo,useState} from "react";
import Icon from "../Icon";
import RealPeopleMap from "../RealPeopleMap";
import "./real-map.css";

const token=()=>localStorage.getItem("marbo3a_token")||sessionStorage.getItem("marbo3a_token")||"";
async function api(path){const t=token(),headers=t&&t!=="cookie"?{authorization:`Bearer ${t}`}:{ };const r=await fetch(path,{headers,credentials:"same-origin",cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"REQUEST_FAILED");return d}
export default function MapPage(){const[users,setUsers]=useState([]),[viewerId,setViewerId]=useState(null),[error,setError]=useState(""),[onlineOnly,setOnlineOnly]=useState(false);async function load(){try{const d=await api("/api/map/people-v2");setUsers(d.users||[]);setViewerId(d.viewerId||null);setError("")}catch(e){setError(e.message==="UNAUTHORIZED"?"سجل دخولك لاستخدام خريطة مربوعة":"تعذر تحميل الخريطة الآن")}}useEffect(()=>{if(!token()){location.href=`/?next=${encodeURIComponent("/map")}`;return}load();const t=setInterval(()=>document.visibilityState==="visible"&&load(),30000),live=()=>load();window.addEventListener("marbo3a:presence",live);return()=>{clearInterval(t);window.removeEventListener("marbo3a:presence",live)}},[]);const visible=useMemo(()=>onlineOnly?users.filter(u=>u.online):users,[users,onlineOnly]),online=users.filter(u=>u.online).length,precise=users.filter(u=>u.precision==="precise").length;return <main className="real-map-page" dir="rtl"><div className="real-map-shell"><header className="real-map-head"><div><h1>خريطة مربوعة</h1><p>ناس قريبين منك على خريطة حقيقية — الموقع الدقيق يظهر فقط بموافقة صاحبه.</p></div><div className="real-map-head-actions"><button type="button" onClick={()=>setOnlineOnly(v=>!v)} className={onlineOnly?"active":""}><Icon name="users"/><span>{onlineOnly?"عرض الكل":"المتصلون"}</span></button><a href="/profile/edit"><Icon name="map"/><span>إعداد موقعي</span></a></div></header><section className="real-map-summary"><div><small>ظاهرين على الخريطة</small><b>{users.length}</b></div><div><small>متصلون الآن</small><b className="green">{online}</b></div><div><small>موقع دقيق بموافقة</small><b>{precise}</b></div></section>{error?<div className="real-map-error" onClick={load}>{error} — اضغط للمحاولة</div>:<RealPeopleMap users={visible} viewerId={viewerId}/>}<div className="real-map-note"><b>الخصوصية أولًا:</b> لو المستخدم فعّل «مشاركة الموقع الدقيق» من ملفه، يظهر موقع GPS الذي وافق عليه. لو ما فعّلهاش، مربوعة تعرض نقطة تقريبية داخل مدينته فقط، وما تكشفش عنوانه أو مكانه الحقيقي.</div></div></main>}
