"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import Icon from "../Icon";
import RealPeopleMap from "../RealPeopleMap";
import "./real-map.css";

const token=()=>localStorage.getItem("marbo3a_token")||sessionStorage.getItem("marbo3a_token")||"";
async function api(path,options={}){const t=token(),headers=t&&t!=="cookie"?{authorization:`Bearer ${t}`}:{ };if(options.body)headers["content-type"]="application/json";const r=await fetch(path,{...options,headers,credentials:"same-origin",cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d.error||"REQUEST_FAILED");e.status=r.status;throw e}return d}
const mapError=e=>({UNAUTHORIZED:"سجل دخولك لاستخدام خريطة مربوعة",FEATURE_DISABLED:"الخريطة موقوفة مؤقتًا",INVALID_PRECISE_LOCATION:"تعذر التحقق من الموقع الدقيق",INVALID_LOCATION_VISIBILITY:"إعداد ظهور الموقع غير صالح"}[e?.message]||"تعذر تحميل الخريطة الآن");
export default function MapPage(){
 const[users,setUsers]=useState([]),[viewerId,setViewerId]=useState(null),[error,setError]=useState(""),[filter,setFilter]=useState("all"),[cities,setCities]=useState([]),[prefs,setPrefs]=useState({city:"",sharePrecise:false,visibilityMode:"everyone",ghostMode:false,latitude:null,longitude:null}),[settings,setSettings]=useState(false),[saving,setSaving]=useState(false),[notice,setNotice]=useState("");
 const loadSeq=useRef(0),mounted=useRef(true);
 async function load(){const seq=++loadSeq.current;try{const[d,c,l]=await Promise.all([api("/api/map/people-v2"),api("/api/map/cities").catch(()=>({cities:[]})),api("/api/location").catch(()=>({location:null}))]);if(!mounted.current||seq!==loadSeq.current)return;setUsers(d.users||[]);setViewerId(d.viewerId||null);setCities(c.cities||[]);if(l.location)setPrefs({city:l.location.city||"",sharePrecise:Boolean(l.location.share_precise),visibilityMode:l.location.visibility_mode||"everyone",ghostMode:Boolean(l.location.ghost_mode),latitude:l.location.latitude,longitude:l.location.longitude});setError("")}catch(e){if(mounted.current&&seq===loadSeq.current)setError(mapError(e))}}
 useEffect(()=>{mounted.current=true;if(!token()){location.href=`/?next=${encodeURIComponent("/map")}`;return()=>{mounted.current=false}}load();const t=setInterval(()=>document.visibilityState==="visible"&&load(),30000),live=()=>load();window.addEventListener("marbo3a:presence",live);return()=>{mounted.current=false;loadSeq.current+=1;clearInterval(t);window.removeEventListener("marbo3a:presence",live)}},[]);
 const visible=useMemo(()=>users.filter(u=>filter==="online"?u.online:filter==="friends"?u.is_friend:filter==="male"?u.gender==="male":filter==="female"?u.gender==="female":true),[users,filter]),online=users.filter(u=>u.online).length,precise=users.filter(u=>u.precision==="precise").length;
 async function savePrefs(){setSaving(true);setNotice("");try{let latitude=null,longitude=null;if(prefs.sharePrecise){if(!navigator.geolocation)throw new Error("GEO_UNAVAILABLE");const pos=await new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:10000,maximumAge:30000}));latitude=pos.coords.latitude;longitude=pos.coords.longitude}await api("/api/location",{method:"PUT",body:JSON.stringify({city:prefs.city,latitude,longitude,sharePrecise:prefs.sharePrecise,visibilityMode:prefs.visibilityMode,ghostMode:prefs.ghostMode})});setPrefs(p=>({...p,latitude,longitude}));setNotice(prefs.sharePrecise?"تم حفظ خصوصية الخريطة والموقع الدقيق بإذنك":"تم حفظ الخصوصية ومسح الموقع الدقيق المحفوظ");setSettings(false);await load()}catch(e){setNotice(e?.name==="NotAllowedError"?"لازم تسمح للموقع فقط إذا تبي تشارك موقعك الدقيق":mapError(e))}finally{setSaving(false)}}
 return <main className="real-map-page" dir="rtl"><div className="real-map-shell"><header className="real-map-head"><div><h1>خريطة مربوعة</h1><p>اكتشف الناس والمناطق النشطة مع تحكم كامل في ظهور موقعك.</p></div><div className="real-map-head-actions"><button type="button" onClick={()=>setSettings(v=>!v)} className={settings?"active":""}><Icon name="settings"/><span>خصوصية موقعي</span></button></div></header><div className="map-filter-chips" role="tablist">{[["all","الكل"],["friends","الأصدقاء"],["online","متصلون"],["male","♂ ذكر"],["female","♀ أنثى"]].map(([v,l])=><button key={v} type="button" className={filter===v?"active":""} onClick={()=>setFilter(v)}>{l}</button>)}</div>{settings&&<section className="map-privacy-panel"><h2>ظهوري على الخريطة</h2><label>المدينة<input value={prefs.city} maxLength={80} onChange={e=>setPrefs({...prefs,city:e.target.value})} placeholder="مثال: طرابلس"/></label><label>من يشوفني<select value={prefs.visibilityMode} onChange={e=>setPrefs({...prefs,visibilityMode:e.target.value})}><option value="everyone">كل المستخدمين</option><option value="friends">الأصدقاء فقط</option></select></label><label className="map-toggle"><input type="checkbox" checked={prefs.sharePrecise} onChange={e=>setPrefs({...prefs,sharePrecise:e.target.checked})}/><span>مشاركة الموقع الدقيق بموافقتي</span></label><label className="map-toggle"><input type="checkbox" checked={prefs.ghostMode} onChange={e=>setPrefs({...prefs,ghostMode:e.target.checked})}/><span>وضع الشبح — لا أظهر للآخرين</span></label><button type="button" disabled={saving} onClick={savePrefs}>{saving?"جاري الحفظ...":"حفظ"}</button></section>}{notice&&<div className="real-map-error" onClick={()=>setNotice("")}>{notice}</div>}<section className="real-map-summary"><div><small>ظاهرين على الخريطة</small><b>{users.length}</b></div><div><small>متصلون الآن</small><b className="green">{online}</b></div><div><small>موقع دقيق بموافقة</small><b>{precise}</b></div></section>{cities.length>0&&<section className="map-hot-regions"><b>المناطق النشطة</b><div>{cities.slice(0,6).map(c=><span key={c.city}>{c.city} <strong>{c.users}</strong></span>)}</div></section>}{error?<div className="real-map-error" onClick={load}>{error} — اضغط للمحاولة</div>:<RealPeopleMap users={visible} viewerId={viewerId}/>}<div className="real-map-note"><b>الخصوصية أولًا:</b> الموقع الدقيق لا يظهر إلا بموافقتك، ويتحذف من التخزين لما تطفي المشاركة. تقدر تعرض المدينة فقط، تحصر الظهور في أصحابك، أو تفعل وضع الشبح بالكامل.</div></div></main>}
