"use client";
import {useEffect,useState} from "react";
import Icon from "../../Icon";

const token=()=>typeof window!=="undefined"?(localStorage.getItem("marbo3a_token")||sessionStorage.getItem("marbo3a_token")||""):"";
async function api(path,options={}){const t=token(),headers={...(options.headers||{}),...(t&&t!=="cookie"?{authorization:`Bearer ${t}`}:{})};if(options.body)headers["content-type"]="application/json";const r=await fetch(path,{...options,headers,cache:"no-store",credentials:"same-origin"}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"REQUEST_FAILED");return d}
export default function SponsoredAdminPage(){
 const[list,setList]=useState([]),[postId,setPostId]=useState(""),[label,setLabel]=useState("مموّل"),[cta,setCta]=useState("اعرف أكثر"),[url,setUrl]=useState(""),[weight,setWeight]=useState("100"),[active,setActive]=useState(true),[busy,setBusy]=useState(false),[status,setStatus]=useState(""),[allowed,setAllowed]=useState(false);
 async function load(){try{const me=await api("/api/auth/me");if(!(me.isAdmin||me.user?.role==="admin")){location.href="/home";return}setAllowed(true);const d=await api("/api/admin/sponsored-posts");setList(d.sponsoredPosts||[])}catch{setStatus("تعذر تحميل الإعلانات")}}
 useEffect(()=>{if(!token()){location.href="/";return}load()},[]);
 async function save(e){e.preventDefault();if(!postId||busy)return;setBusy(true);setStatus("");try{await api("/api/admin/sponsored-posts",{method:"POST",body:JSON.stringify({postId:Number(postId),label,ctaLabel:cta,destinationUrl:url||null,weight:Number(weight)||100,active})});setStatus("تم حفظ الإعلان المموّل");setPostId("");setUrl("");await load()}catch(e){setStatus(e.message==="INVALID_POST"?"رقم المنشور غير صحيح":e.message==="INVALID_DESTINATION"?"رابط الوجهة غير صحيح":"تعذر حفظ الإعلان")}finally{setBusy(false)}}
 if(!allowed)return <main className="feature-page" dir="rtl"><section className="feature-shell"><div className="sf-skeleton">جاري التحقق من صلاحيات الإدارة...</div>{status&&<div className="sf-alert">{status}</div>}</section></main>;
 return <main className="feature-page sponsored-admin-page" dir="rtl"><section className="feature-shell"><header className="marketplace-preview-head"><a href="/admin" aria-label="رجوع"><Icon name="arrowRight"/></a><div><small>MONETIZATION</small><h1>المنشورات المموّلة</h1><p>فعّل منشور موجود ليظهر وسط الخلاصة مع إحصائيات الظهور والنقر.</p></div><span><Icon name="megaphone"/></span></header><form className="sponsored-admin-form" onSubmit={save}><label>رقم المنشور<input inputMode="numeric" value={postId} onChange={e=>setPostId(e.target.value.replace(/\D/g,""))} placeholder="مثال: 125" required/></label><label>وسم الإعلان<input value={label} onChange={e=>setLabel(e.target.value)} maxLength={30}/></label><label>نص الزر<input value={cta} onChange={e=>setCta(e.target.value)} maxLength={40}/></label><label>رابط الوجهة<input value={url} onChange={e=>setUrl(e.target.value)} placeholder="/marketplace أو https://..."/></label><label>الأولوية<input type="number" min="1" max="1000" value={weight} onChange={e=>setWeight(e.target.value)}/></label><label className="sponsored-toggle"><span><b>نشط</b><small>يدخل الإعلان في الخلاصة الذكية</small></span><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/></label><button disabled={busy||!postId}>{busy?"جاري الحفظ...":"حفظ الإعلان"}</button></form>{status&&<div className="sf-alert" role="status">{status}</div>}<section className="sponsored-admin-list"><header><div><small>الحملات الحالية</small><h2>{list.length} إعلان</h2></div></header>{list.map(x=><article key={x.id}><div><span className={x.active?"active":"paused"}>{x.active?"نشط":"متوقف"}</span><b>#{x.post_id} · @{x.username}</b><p>{x.body||"منشور وسائط"}</p></div><dl><div><dt>ظهور</dt><dd>{Number(x.impressions||0).toLocaleString("en-US")}</dd></div><div><dt>نقر</dt><dd>{Number(x.clicks||0).toLocaleString("en-US")}</dd></div><div><dt>CTR</dt><dd>{Number(x.impressions)?`${((Number(x.clicks||0)/Number(x.impressions))*100).toFixed(1)}%`:"0%"}</dd></div></dl></article>)}{!list.length&&<div className="sf-empty"><Icon name="megaphone"/><h2>ما فيش إعلانات مفعلة</h2><p>اختار رقم منشور موجود وفعّله من النموذج فوق.</p></div>}</section></section></main>;
}
