"use client";
import {useEffect,useMemo,useState} from "react";
const tok=()=>localStorage.getItem("marbo3a_token")||sessionStorage.getItem("marbo3a_token")||"";
async function api(p){const r=await fetch(p,{headers:{authorization:`Bearer ${tok()}`},cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"FAILED");return d}
const filters=[
 ["all","الكل"],["errors","Errors"],["warnings","Warnings"],["api","API"],["ui","UI"],["navigation","Navigation"],["calls","Calls"],["media","Media"],["voice","Voice"]
];
function match(type,filter){if(filter==="all")return true;if(filter==="errors")return /error|failed|overlap|overflow/.test(type);if(filter==="warnings")return /slow|warn|blocked|stalled|disconnected/.test(type);if(filter==="api")return /^api_/.test(type);if(filter==="ui")return /^ui_|^click$|^page_view$/.test(type);if(filter==="navigation")return /^navigation_/.test(type);if(filter==="calls")return /^rtc_/.test(type);if(filter==="media")return /^media_/.test(type);if(filter==="voice")return /^voice_/.test(type)||/audio|recorder/.test(type);return true}
export default function Debug(){
 const[list,setList]=useState([]),[sel,setSel]=useState(null),[err,setErr]=useState(""),[filter,setFilter]=useState("all"),[query,setQuery]=useState("");
 async function load(){try{setList((await api("/api/debug/sessions")).sessions||[])}catch{setErr("تعذر تحميل جلسات الديباق")}}
 async function open(id){try{setSel(await api(`/api/debug/sessions/${id}`));setErr("")}catch{setErr("تعذر فتح الجلسة")}}
 useEffect(()=>{load();const t=setInterval(load,5000);return()=>clearInterval(t)},[]);
 const events=useMemo(()=>{const q=query.trim().toLowerCase();return(sel?.events||[]).filter(e=>match(e.event_type,filter)&&(!q||`${e.event_type} ${e.path} ${JSON.stringify(e.payload)}`.toLowerCase().includes(q)))},[sel,filter,query]);
 return <main className="debug-admin-page" dir="rtl"><header><div><small>ADMIN ONLY</small><h1>ديباق مربوعة</h1><p>حركات، API، تنقل، وسائط وWebRTC بدون كلمات سر أو Tokens.</p></div><a href="/admin">لوحة الإدارة</a></header>{err&&<div className="debug-error">{err}</div>}<div className="debug-toolbar">{filters.map(([k,v])=><button key={k} className={filter===k?"active":""} onClick={()=>setFilter(k)}>{v}</button>)}<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="بحث..."/></div><section className="debug-grid"><aside><h2>الجلسات</h2>{list.map(s=><button key={s.id} className={sel?.session?.id===s.id?"active":""} onClick={()=>open(s.id)}><b>{new Date(s.started_at).toLocaleString("ar-LY")}</b><span>{s.event_count} حركة · {s.error_count} مشكلة</span><code>{s.id.slice(0,8)}</code></button>)}</aside><article>{!sel?<div className="debug-empty">افتح جلسة لمراجعة ما حدث.</div>:<><div className="debug-summary"><div><b>{sel.summary?.errors||0}</b><span>أخطاء</span></div><div><b>{sel.summary?.api||0}</b><span>API</span></div><div><b>{sel.summary?.ui||0}</b><span>واجهة</span></div><div><b>{sel.summary?.clicks||0}</b><span>ضغطات</span></div></div><h2>Session {sel.session.id}</h2><div className="debug-events">{events.map(e=><div key={e.id} className={`debug-event ${/error|overlap|overflow|failed/.test(e.event_type)?"bad":""}`}><time>{new Date(e.created_at).toLocaleTimeString("ar-LY")}</time><b>{e.event_type}</b><span>{e.path}</span><pre>{JSON.stringify(e.payload,null,2)}</pre></div>)}{!events.length&&<div className="debug-empty">ما فيش أحداث في الفلتر هذا.</div>}</div></>}</article></section></main>
}
