"use client";
import {useEffect,useRef,useState} from "react";
import {useParams} from "next/navigation";
import Icon from "../../../Icon";
import VoiceRecorder from "../../../VoiceRecorder";
import VoiceMessage from "../../../VoiceMessage";
import {uploadMedia} from "../../../imageTools";
const token=()=>localStorage.getItem("marbo3a_token")||sessionStorage.getItem("marbo3a_token")||"";
async function api(path,options={}){const headers={authorization:`Bearer ${token()}`,...(options.headers||{})};if(options.body&&!(options.body instanceof FormData))headers["content-type"]="application/json";const r=await fetch(path,{...options,headers,cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"REQUEST_FAILED");return d}
const human=e=>({UNAUTHORIZED:"انتهت جلسة الدخول",ROOM_BANNED:"أنت محظور من الغرفة",ROOM_NOT_FOUND:"الغرفة غير موجودة",UPLOAD_FAILED:"تعذر رفع الملف",UNSUPPORTED_FILE:"صيغة الملف غير مدعومة",FILE_TOO_LARGE:"الملف أكبر من الحد المسموح",HEIC_DECODE_FAILED:"تعذر تجهيز صورة الآيفون. جرّب حفظها كـ JPG أو لقطة شاشة.",IMAGE_PROCESS_FAILED:"تعذر تجهيز الصورة قبل الرفع",REQUEST_FAILED:"تعذر تنفيذ الطلب"}[e?.message]||e?.message||"صار خطأ")
export default function RoomChat(){
 const{id}=useParams();const[room,setRoom]=useState(null),[messages,setMessages]=useState([]),[text,setText]=useState(""),[reply,setReply]=useState(null),[pins,setPins]=useState([]),[typing,setTyping]=useState([]),[search,setSearch]=useState(""),[searchResults,setSearchResults]=useState([]),[status,setStatus]=useState(""),[attachment,setAttachment]=useState(null),[canManage,setCanManage]=useState(false),[sending,setSending]=useState(false),[uploading,setUploading]=useState(false),[menuMessage,setMenuMessage]=useState(null);
 const box=useRef(null),typingTimer=useRef(null),firstPaint=useRef(true),stickToBottom=useRef(true),lastRead=useRef(0),mounted=useRef(true);
 const scrollBottom=(smooth=false)=>requestAnimationFrame(()=>{const el=box.current;if(el)el.scrollTo({top:el.scrollHeight,behavior:smooth?"smooth":"auto"})});
 async function loadMeta(){try{const[r,p]=await Promise.all([api(`/api/rooms/${id}/manage`).catch(()=>null),api(`/api/rooms/${id}/pins`).catch(()=>({pins:[]}))]);if(!mounted.current)return;if(r?.room){setRoom(r.room);setCanManage(true)}setPins(p.pins||[])}catch{}}
 async function loadMessages(){try{const d=await api(`/api/rooms/${id}/messages`);if(!mounted.current)return;const list=d.messages||[];setMessages(list);const last=list.at(-1);if(last&&Number(last.id)>lastRead.current&&document.visibilityState==="visible"){lastRead.current=Number(last.id);api(`/api/read/room/${id}`,{method:"PUT",body:JSON.stringify({lastMessageId:last.id})}).catch(()=>{})}}catch(e){if(mounted.current)setStatus(human(e))}}
 useEffect(()=>{mounted.current=true;if(!token()){location.href="/";return}if(!id)return;loadMeta();loadMessages();const tick=()=>document.visibilityState==="visible"&&loadMessages();const t=setInterval(tick,4500);const ty=setInterval(()=>{if(document.visibilityState==="visible")api(`/api/typing/room/${id}`).then(d=>mounted.current&&setTyping(d.users||[])).catch(()=>{})},3000);const vis=()=>document.visibilityState==="visible"&&(loadMessages(),loadMeta());document.addEventListener("visibilitychange",vis);return()=>{mounted.current=false;clearInterval(t);clearInterval(ty);clearTimeout(typingTimer.current);document.removeEventListener("visibilitychange",vis)}},[id]);
 useEffect(()=>{const el=box.current;if(!el)return;if(firstPaint.current){firstPaint.current=false;scrollBottom();return}if(stickToBottom.current)scrollBottom()},[messages]);
 useEffect(()=>{if(!menuMessage)return;const esc=e=>e.key==="Escape"&&setMenuMessage(null);window.addEventListener("keydown",esc);return()=>window.removeEventListener("keydown",esc)},[menuMessage]);
 function onScroll(){const el=box.current;if(!el)return;stickToBottom.current=el.scrollHeight-el.scrollTop-el.clientHeight<100;if(menuMessage)setMenuMessage(null)}
 async function send(e){e.preventDefault();if((!text.trim()&&!attachment)||sending||uploading)return;setSending(true);stickToBottom.current=true;try{await api(`/api/rooms/${id}/messages`,{method:"POST",body:JSON.stringify({body:text.trim(),replyToId:reply?.id||null,attachmentUrl:attachment?.url||null,attachmentType:attachment?.type||null})});setText("");setReply(null);setAttachment(null);setStatus("");api(`/api/typing/room/${id}`,{method:"POST",body:JSON.stringify({typing:false})}).catch(()=>{});await loadMessages();scrollBottom(true)}catch(e){setStatus(human(e))}finally{setSending(false)}}
 function onType(v){setText(v);api(`/api/typing/room/${id}`,{method:"POST",body:JSON.stringify({typing:true})}).catch(()=>{});clearTimeout(typingTimer.current);typingTimer.current=setTimeout(()=>api(`/api/typing/room/${id}`,{method:"POST",body:JSON.stringify({typing:false})}).catch(()=>{}),4000)}
 async function upload(file){if(!file||uploading)return;setUploading(true);setStatus(file.type?.startsWith("audio/")?"جاري رفع التسجيل...":"جاري تجهيز الصورة...");try{const d=await uploadMedia(file,token(),{compress:true,onState:s=>{if(s==="processing"&&file.type?.startsWith("image/"))setStatus("جاري ضغط الصورة بجودة عالية...");if(s==="uploading")setStatus("جاري رفع الملف...")}});setAttachment(d.file);setStatus(d.file.type?.startsWith("audio/")?"المقطع الصوتي جاهز للإرسال":"الملف جاهز للإرسال")}catch(e){setAttachment(null);setStatus(human(e))}finally{setUploading(false)}}
 async function react(m,emoji){try{await api(`/api/messages/room/${m.id}/reactions`,{method:"POST",body:JSON.stringify({emoji})});setStatus(`تم التفاعل ${emoji}`)}catch(e){setStatus(human(e))}}
 async function pin(m){try{await api(`/api/rooms/${id}/pins/${m.id}`,{method:"POST"});setPins((await api(`/api/rooms/${id}/pins`)).pins||[]);setStatus("تم تثبيت الرسالة")}catch(e){setStatus(human(e))}}
 async function copyMessage(m){const value=m?.body||m?.attachment_url||"";if(!value)return setStatus("ما فيش نص للنسخ");try{await navigator.clipboard.writeText(value);setStatus("تم النسخ")}catch{setStatus("تعذر النسخ")}}
 async function doSearch(e){e.preventDefault();if(!search.trim())return;try{setSearchResults((await api(`/api/rooms/${id}/search?q=${encodeURIComponent(search.trim())}`)).messages||[])}catch(e){setStatus(human(e))}}
 const choose=fn=>{const m=menuMessage;setMenuMessage(null);if(m)fn(m)};
 return <main className="room-chat-page" dir="rtl"><section className="room-chat-shell"><header className="room-chat-head"><a href="/rooms" className="room-chat-icon" aria-label="رجوع"><Icon name="close"/></a><div><small>غرفة مربوعة</small><h1>{room?.name||`الغرفة #${id}`}</h1></div>{canManage?<a href={`/room/manage/${id}`} className="room-chat-icon" aria-label="إدارة"><Icon name="settings"/></a>:<span/>}</header>
 <details className="room-chat-tools"><summary>البحث والرسائل المثبتة</summary><div className="room-chat-tools-grid"><form onSubmit={doSearch}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="بحث داخل الغرفة"/><button>بحث</button></form><div className="room-pins">{pins.slice(0,5).map(p=><button key={p.message_id} onClick={()=>document.getElementById(`room-msg-${p.message_id}`)?.scrollIntoView({behavior:"smooth",block:"center"})}><b>@{p.username}</b><span>{p.body||"مرفق"}</span></button>)}{!pins.length&&<small>ما فيش رسائل مثبتة.</small>}</div></div></details>
 {searchResults.length>0&&<div className="room-search-results">{searchResults.map(m=><button key={m.id} onClick={()=>document.getElementById(`room-msg-${m.id}`)?.scrollIntoView({behavior:"smooth",block:"center"})}>{m.body||"مرفق"}</button>)}</div>}{status&&<div className="room-chat-status" onClick={()=>setStatus("")}>{status}</div>}
 <section ref={box} onScroll={onScroll} className="room-chat-stream">{messages.map(m=>{const alive=!m.deleted_at,isAudio=alive&&m.attachment_url&&(m.attachment_type?.startsWith("audio/")||/\.(webm|ogg|mp3|m4a|aac|wav)(\?|$)/i.test(m.attachment_url)),isImage=alive&&m.attachment_url&&(m.attachment_type?.startsWith("image/")||/\.(png|jpe?g|webp|gif)(\?|$)/i.test(m.attachment_url));return <article id={`room-msg-${m.id}`} key={m.id} className="room-bubble"><div className="room-bubble-head"><b>{m.display_name||m.username||`#${m.user_id}`}</b><button type="button" className="room-message-more" aria-label="خيارات الرسالة" onClick={()=>setMenuMessage(m)}><Icon name="more"/></button></div>{alive&&m.reply_to_id&&<small className="room-reply-tag">رد على رسالة #{m.reply_to_id}</small>}{m.deleted_at?<p>تم حذف الرسالة</p>:m.body?<p>{m.body}</p>:null}{isAudio?<VoiceMessage src={m.attachment_url}/>:isImage?<a href={m.attachment_url} target="_blank" rel="noreferrer"><img className="room-image" src={m.attachment_url} alt="صورة مرفقة" loading="lazy"/></a>:alive&&m.attachment_url?<a className="room-attachment" href={m.attachment_url} target="_blank" rel="noreferrer">فتح المرفق</a>:null}<footer>{new Date(m.created_at).toLocaleTimeString("ar-LY",{hour:"2-digit",minute:"2-digit"})}</footer></article>})}</section>
 {typing.length>0&&<div className="room-typing">{typing.map(x=>x.displayName||x.username).join("، ")} يكتب...</div>}{reply&&<div className="room-replying"><span>رد على: {reply.body?.slice(0,80)||"مرفق"}</span><button onClick={()=>setReply(null)}>إلغاء</button></div>}{attachment&&<div className="room-replying"><span>{attachment.type?.startsWith("audio/")?"🎙️ مقطع صوتي جاهز":"مرفق جاهز"}: {attachment.name}</span><button onClick={()=>setAttachment(null)}>إلغاء</button></div>}
 <form className="room-compose" onSubmit={send}><VoiceRecorder disabled={uploading||sending} onRecorded={upload} onError={setStatus}/><label className={uploading?"busy":""} aria-label="إرفاق ملف"><Icon name="image"/><input type="file" accept="image/*,audio/*,application/pdf" hidden disabled={uploading||sending} onChange={e=>{const f=e.target.files?.[0];e.target.value="";upload(f)}}/></label><input value={text} onChange={e=>onType(e.target.value)} placeholder={uploading?"جاري رفع الملف...":"اكتب رسالة..."} disabled={sending}/><button disabled={sending||uploading||(!text.trim()&&!attachment)} aria-label="إرسال"><Icon name="send"/></button></form></section>{menuMessage&&<div className="message-sheet-backdrop" role="presentation" onClick={()=>setMenuMessage(null)}><section className="message-sheet" role="dialog" aria-modal="true" aria-label="خيارات الرسالة" onClick={e=>e.stopPropagation()}><div className="message-sheet-handle"/><div className="message-sheet-reactions"><button type="button" onClick={()=>choose(m=>react(m,"😂"))}>😂</button><button type="button" onClick={()=>choose(m=>react(m,"❤️"))}>❤️</button><button type="button" onClick={()=>choose(m=>react(m,"👍"))}>👍</button></div><div className="message-sheet-actions"><button type="button" onClick={()=>choose(m=>setReply(m))}>رد</button><button type="button" onClick={()=>choose(copyMessage)}>نسخ</button>{!menuMessage.deleted_at&&<button type="button" onClick={()=>choose(pin)}>تثبيت</button>}</div><button type="button" className="message-sheet-cancel" onClick={()=>setMenuMessage(null)}>إلغاء</button></section></div>}</main>
}
