ALTER TABLE IF EXISTS user_locations ADD COLUMN IF NOT EXISTS share_precise BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS user_locations ADD COLUMN IF NOT EXISTS share_map BOOLEAN NOT NULL DEFAULT FALSE;
UPDATE user_locations SET share_map=TRUE WHERE share_precise=TRUE AND share_map=FALSE;

ALTER TABLE IF EXISTS room_bans ADD COLUMN IF NOT EXISTS created_by BIGINT REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE IF EXISTS room_bans ADD COLUMN IF NOT EXISTS banned_by BIGINT REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE IF EXISTS user_settings ADD COLUMN IF NOT EXISTS language TEXT NOT NULL DEFAULT 'ar';

ALTER TABLE IF EXISTS rooms ADD COLUMN IF NOT EXISTS pinned_message_id BIGINT;
ALTER TABLE IF EXISTS rooms ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE IF EXISTS rooms ADD COLUMN IF NOT EXISTS join_policy TEXT NOT NULL DEFAULT 'open';
ALTER TABLE IF EXISTS rooms ADD COLUMN IF NOT EXISTS rules TEXT NOT NULL DEFAULT '';
ALTER TABLE IF EXISTS rooms ADD COLUMN IF NOT EXISTS max_members INT NOT NULL DEFAULT 500;

ALTER TABLE IF EXISTS direct_messages ADD COLUMN IF NOT EXISTS reply_to_id BIGINT;
ALTER TABLE IF EXISTS direct_messages ADD COLUMN IF NOT EXISTS attachment_url TEXT;
ALTER TABLE IF EXISTS direct_messages ADD COLUMN IF NOT EXISTS attachment_type TEXT;
ALTER TABLE IF EXISTS messages ADD COLUMN IF NOT EXISTS reply_to_id BIGINT;
ALTER TABLE IF EXISTS messages ADD COLUMN IF NOT EXISTS attachment_url TEXT;
ALTER TABLE IF EXISTS messages ADD COLUMN IF NOT EXISTS attachment_type TEXT;
ALTER TABLE IF EXISTS messages ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
