ALTER TABLE stories ADD COLUMN IF NOT EXISTS filter_name TEXT NOT NULL DEFAULT 'normal';
ALTER TABLE stories ADD COLUMN IF NOT EXISTS overlay_x NUMERIC(5,2) NOT NULL DEFAULT 50;
ALTER TABLE stories ADD COLUMN IF NOT EXISTS overlay_y NUMERIC(5,2) NOT NULL DEFAULT 78;
