"use client";
import {useEffect,useRef,useState} from "react";
import Icon from "./Icon";

const token=()=>localStorage.getItem("marbo3a_token")||sessionStorage.getItem("marbo3a_token")||"";
async function api(path,options={}){const headers={authorization:`Bearer ${token()}`,...(options.headers||{})};if(options.body)headers["content-type"]="application/json";const r=await fetch(path,{...options,headers,cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"REQUEST_FAILED");return d}

function tone(notes=[440],duration=0.18,repeat=0){
  try{
    const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return()=>{};const ctx=new AC();let timer=null,stopped=false;
    const play=()=>{if(stopped)return;const now=ctx.currentTime;notes.forEach((hz,i)=>{const o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=hz;o.type="sine";g.gain.setValueAtTime(0.0001,now);g.gain.exponentialRampToValueAtTime(.11,now+.015);g.gain.exponentialRampToValueAtTime(.0001,now+duration);o.connect(g).connect(ctx.destination);o.start(now+i*.05);o.stop(now+duration+i*.05)});};
    play();if(repeat>0)timer=setInterval(play,repeat);return()=>{stopped=true;clearInterval(timer);ctx.close().catch(()=>{})}
  }catch{return()=>{}}
}

export default function CallCenter(){
 const[call,setCall]=useState(null),[phase,setPhase]=useState("idle"),[status,setStatus]=useState(""),[muted,setMuted]=useState(false),[cameraOff,setCameraOff]=useState(false),[facing,setFacing]=useState("user"),[speakerOn,setSpeakerOn]=useState(true),[near,setNear]=useState(false);
 const pc=useRef(null),local=useRef(null),remote=useRef(null),localVideo=useRef(null),remoteVideo=useRef(null),remoteAudio=useRef(null),poll=useRef(null),signalPoll=useRef(null),lastSignal=useRef(0),pendingIce=useRef([]),direction=useRef(null),stopTone=useRef(()=>{}),proxSensor=useRef(null);
 const stopTimers=()=>{clearInterval(poll.current);clearInterval(signalPoll.current);poll.current=null;signalPoll.current=null};
 const stopSounds=()=>{try{stopTone.current?.()}catch{}stopTone.current=()=>{}};
 const playRing=(incoming=false)=>{stopSounds();stopTone.current=tone(incoming?[660,880]:[440,554],.22,incoming?1450:1200)};
 const playEnd=()=>{stopSounds();stopTone.current=tone([520,390],.16,0);setTimeout(stopSounds,500)};
 const stopMedia=()=>{local.current?.getTracks?.().forEach(t=>t.stop());local.current=null;remote.current=null;try{pc.current?.close()}catch{}pc.current=null;if(localVideo.current)localVideo.current.srcObject=null;if(remoteVideo.current)remoteVideo.current.srcObject=null;if(remoteAudio.current)remoteAudio.current.srcObject=null};
 const stopProximity=()=>{try{proxSensor.current?.stop?.()}catch{}proxSensor.current=null;setNear(false)};
 const reset=()=>{stopTimers();stopSounds();stopMedia();stopProximity();lastSignal.current=0;pendingIce.current=[];direction.current=null;setCall(null);setPhase("idle");setStatus("");setMuted(false);setCameraOff(false);setFacing("user");setSpeakerOn(true)};
 useEffect(()=>()=>{stopTimers();stopSounds();stopMedia();stopProximity()},[]);

 async function getMedia(kind,face="user"){if(!navigator.mediaDevices?.getUserMedia)throw new Error("MEDIA_UNSUPPORTED");return navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:kind==="video"?{facingMode:{ideal:face},width:{ideal:1280},height:{ideal:720}}:false})}
 async function makePeer(c,stream){const cfg=await api("/api/calls/config").catch(()=>({iceServers:[{urls:"stun:stun.l.google.com:19302"}]}));const p=new RTCPeerConnection({iceServers:cfg.iceServers||[]});pc.current=p;local.current=stream;stream.getTracks().forEach(t=>p.addTrack(t,stream));const rs=new MediaStream();remote.current=rs;p.ontrack=e=>{(e.streams?.[0]?.getTracks?.()||[e.track]).forEach(t=>{if(!rs.getTracks().find(x=>x.id===t.id))rs.addTrack(t)});if(remoteVideo.current){remoteVideo.current.srcObject=rs;remoteVideo.current.play?.().catch(()=>{})}if(remoteAudio.current){remoteAudio.current.srcObject=rs;remoteAudio.current.play?.().catch(()=>{})}};p.onicecandidate=e=>{if(e.candidate)api(`/api/calls/${c.id}/signals`,{method:"POST",body:JSON.stringify({kind:"ice",payload:e.candidate.toJSON()})}).catch(()=>{})};p.onconnectionstatechange=()=>{if(p.connectionState==="connected"){stopSounds();setStatus("");setPhase("connected")}else if(["failed","closed","disconnected"].includes(p.connectionState)&&phase==="connected")setStatus("انقطع الاتصال")};return p}
 async function flushIce(){if(!pc.current?.remoteDescription)return;const list=[...pendingIce.current];pendingIce.current=[];for(const c of list)try{await pc.current.addIceCandidate(c)}catch{}}
 async function handleSignals(c){try{const d=await api(`/api/calls/${c.id}/signals?since=${lastSignal.current}`);for(const s of d.signals||[]){lastSignal.current=Math.max(lastSignal.current,Number(s.id)||0);if(s.kind==="offer"&&direction.current==="incoming"){if(!pc.current?.remoteDescription){await pc.current.setRemoteDescription(s.payload);await flushIce();const ans=await pc.current.createAnswer();await pc.current.setLocalDescription(ans);await api(`/api/calls/${c.id}/signals`,{method:"POST",body:JSON.stringify({kind:"answer",payload:pc.current.localDescription.toJSON()})});setPhase("connected");stopSounds()}}else if(s.kind==="answer"&&direction.current==="outgoing"){if(!pc.current?.remoteDescription){await pc.current.setRemoteDescription(s.payload);await flushIce();setPhase("connected");stopSounds()}}else if(s.kind==="ice"){if(pc.current?.remoteDescription)try{await pc.current.addIceCandidate(s.payload)}catch{}else pendingIce.current.push(s.payload)}}}catch{}}
 function startPolling(c){stopTimers();signalPoll.current=setInterval(()=>handleSignals(c),700);poll.current=setInterval(async()=>{try{const d=await api(`/api/calls/${c.id}`);const s=d.call?.status;if(s==="answered"&&phase==="ringing")setPhase("connecting");if(["declined","ended","missed"].includes(s)){playEnd();setStatus(s==="declined"?"تم رفض المكالمة":s==="missed"?"لم يتم الرد":"انتهت المكالمة");setTimeout(reset,850)}}catch{}},1100)}

 async function startOutgoing(detail){if(call||phase!=="idle")return;try{setPhase("preparing");direction.current="outgoing";const kind=detail.kind==="video"?"video":"audio";const stream=await getMedia(kind,facing);const d=await api("/api/calls",{method:"POST",body:JSON.stringify({conversationId:detail.conversationId,kind})});const c={...d.call,peer_name:detail.name||"مستخدم مربوعة",peer_avatar:detail.avatar||null};setCall(c);const p=await makePeer(c,stream);const offer=await p.createOffer({offerToReceiveAudio:true,offerToReceiveVideo:kind==="video"});await p.setLocalDescription(offer);await api(`/api/calls/${c.id}/signals`,{method:"POST",body:JSON.stringify({kind:"offer",payload:p.localDescription.toJSON()})});setPhase("ringing");playRing(false);startPolling(c);setTimeout(()=>{if(localVideo.current){localVideo.current.srcObject=stream;localVideo.current.play?.().catch(()=>{})}},0)}catch(e){setStatus(e?.name==="NotAllowedError"?"اسمح للكاميرا والمايكروفون":"تعذر بدء المكالمة");setPhase("error");setTimeout(reset,1500)}}

 useEffect(()=>{const fn=e=>startOutgoing(e.detail||{});window.addEventListener("marbo3a:start-call",fn);return()=>window.removeEventListener("marbo3a:start-call",fn)},[call,phase,facing]);
 useEffect(()=>{const tick=async()=>{if(!token()||call||phase!=="idle"||document.visibilityState!=="visible")return;try{const d=await api("/api/calls/incoming");if(d.call){direction.current="incoming";setCall({...d.call,peer_name:d.call.caller_name||d.call.caller_username||"مستخدم مربوعة",peer_avatar:d.call.caller_avatar||null});setPhase("incoming");playRing(true)}}catch{}};tick();const t=setInterval(tick,2000);return()=>clearInterval(t)},[call,phase]);

 useEffect(()=>{if(!call||call.kind!=="audio"||phase!=="connected")return;try{if("ProximitySensor" in window){const sensor=new window.ProximitySensor();proxSensor.current=sensor;sensor.addEventListener("reading",()=>setNear(Boolean(sensor.near??(sensor.distance!=null&&sensor.distance<3))));sensor.start()}}catch{}return stopProximity},[call,phase]);

 async function accept(){if(!call)return;try{setPhase("preparing");stopSounds();const stream=await getMedia(call.kind,facing);await api(`/api/calls/${call.id}/answer`,{method:"POST"});await makePeer(call,stream);setPhase("connecting");startPolling(call);setTimeout(()=>{if(localVideo.current){localVideo.current.srcObject=stream;localVideo.current.play?.().catch(()=>{})}},0);await handleSignals(call)}catch(e){setStatus(e?.name==="NotAllowedError"?"اسمح للكاميرا والمايكروفون":"تعذر قبول المكالمة");setPhase("error")}}
 async function decline(){if(!call)return;await api(`/api/calls/${call.id}/decline`,{method:"POST"}).catch(()=>{});playEnd();setTimeout(reset,350)}
 async function hangup(){if(call)await api(`/api/calls/${call.id}/end`,{method:"POST"}).catch(()=>{});playEnd();setTimeout(reset,350)}
 function toggleMute(){const track=local.current?.getAudioTracks?.()[0];if(track){track.enabled=!track.enabled;setMuted(!track.enabled)}}
 function toggleCamera(){const track=local.current?.getVideoTracks?.()[0];if(track){track.enabled=!track.enabled;setCameraOff(!track.enabled)}}
 async function switchCamera(){if(!call||call.kind!=="video"||cameraOff)return;const next=facing==="user"?"environment":"user";try{const fresh=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:next},width:{ideal:1280},height:{ideal:720}},audio:false});const nt=fresh.getVideoTracks()[0];const sender=pc.current?.getSenders?.().find(s=>s.track?.kind==="video");if(sender)await sender.replaceTrack(nt);const old=local.current?.getVideoTracks?.()[0];if(old){local.current.removeTrack(old);old.stop()}local.current.addTrack(nt);setFacing(next);if(localVideo.current){localVideo.current.srcObject=local.current;localVideo.current.play?.().catch(()=>{})}}catch{setStatus("تعذر تبديل الكاميرا")}}
 async function toggleSpeaker(){const media=remoteVideo.current||remoteAudio.current;if(!media)return;try{if(typeof media.setSinkId==="function"){const devices=await navigator.mediaDevices.enumerateDevices();const outs=devices.filter(d=>d.kind==="audiooutput");if(outs.length>1){const current=media.sinkId||"default";const alt=outs.find(d=>d.deviceId!==current&&d.deviceId!=="default")||outs[0];await media.setSinkId(speakerOn?(alt?.deviceId||"default"):"default");setSpeakerOn(v=>!v);return}}setSpeakerOn(v=>!v);setStatus("اختيار مخرج الصوت يعتمد على دعم المتصفح والهاتف") }catch{setStatus("تعذر تغيير مخرج الصوت")}}

 if(!call&&phase==="idle")return null;
 const video=call?.kind==="video",inCall=phase!=="incoming";
 return <div className={`call-overlay ${video?"video":"audio"} ${near?"proximity-near":""}`} dir="rtl"><div className="call-screen">
   <div className="call-backdrop">{call?.peer_avatar?<img src={call.peer_avatar} alt=""/>:null}</div>
   {video&&inCall?<div className="call-video-stage"><video ref={remoteVideo} autoPlay playsInline/><div className="remote-placeholder">{call?.peer_avatar?<img src={call.peer_avatar} alt=""/>:<div>{String(call?.peer_name||"م").slice(0,1)}</div>}</div>{!cameraOff&&<video ref={localVideo} autoPlay playsInline muted className={`call-local-video ${facing==="user"?"mirror":""}`}/>}</div>:<div className="call-audio-hero">{call?.peer_avatar?<img src={call.peer_avatar} alt=""/>:<div className="call-avatar-fallback">{String(call?.peer_name||"م").slice(0,1)}</div>}</div>}
   {!video&&<audio ref={remoteAudio} autoPlay playsInline/>}
   <div className="call-top"><h2>{call?.peer_name||"مكالمة مربوعة"}</h2><p>{phase==="incoming"?(video?"مكالمة فيديو واردة":"مكالمة صوتية واردة"):phase==="ringing"?"جاري الاتصال...":phase==="connecting"?"جاري توصيل المكالمة...":phase==="connected"?"متصل الآن":status||"جاري التجهيز..."}</p></div>
   {status&&phase!=="incoming"?<div className="call-status">{status}</div>:null}
   {phase==="incoming"?<div className="call-actions incoming"><button className="call-decline" onClick={decline}><Icon name="phoneOff" size={26}/><span>رفض</span></button><button className="call-accept" onClick={accept}><Icon name={video?"video":"phone"} size={26}/><span>رد</span></button></div>:<div className="call-actions active-call"><button onClick={toggleMute} className={muted?"active":""}><Icon name="mic"/><span>{muted?"فتح المايك":"كتم"}</span></button><button onClick={toggleSpeaker} className={speakerOn?"active":""}><Icon name="speaker"/><span>سبيكر</span></button>{video&&<button onClick={toggleCamera} className={cameraOff?"active":""}><Icon name={cameraOff?"cameraOff":"video"}/><span>{cameraOff?"فتح الفيديو":"إغلاق الفيديو"}</span></button>}{video&&<button onClick={switchCamera} disabled={cameraOff}><Icon name="switchCamera"/><span>تبديل</span></button>}<button className="call-decline end" onClick={hangup}><Icon name="phoneOff"/><span>إنهاء</span></button></div>}
   {near?<div className="proximity-cover" aria-hidden="true"/>:null}
 </div></div>;
}
