"use client";
import {useEffect,useRef,useState} from "react";
import Icon from "./Icon";

const token=()=>localStorage.getItem("marbo3a_token")||sessionStorage.getItem("marbo3a_token")||"";
async function api(path,options={}){const headers={authorization:`Bearer ${token()}`,...(options.headers||{})};if(options.body)headers["content-type"]="application/json";const r=await fetch(path,{...options,headers,cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d.error||"REQUEST_FAILED");e.status=r.status;throw e}return d}
const rtcTrace=(type,data={})=>{try{window.dispatchEvent(new CustomEvent("marbo3a:rtc-debug",{detail:{type,...data}}))}catch{}};

function tone(notes=[440],duration=.18,repeat=0){
  try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return()=>{};const ctx=new AC();let timer=null,stopped=false;const play=()=>{if(stopped)return;const now=ctx.currentTime;notes.forEach((hz,i)=>{const o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=hz;o.type="sine";g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(.11,now+.015);g.gain.exponentialRampToValueAtTime(.0001,now+duration);o.connect(g).connect(ctx.destination);o.start(now+i*.05);o.stop(now+duration+i*.05)})};play();if(repeat>0)timer=setInterval(play,repeat);return()=>{stopped=true;clearInterval(timer);ctx.close().catch(()=>{})}}catch{return()=>{}}
}

export default function CallCenter(){
 const[call,setCall]=useState(null),[phase,setPhase]=useState("idle"),[status,setStatus]=useState(""),[muted,setMuted]=useState(false),[cameraOff,setCameraOff]=useState(false),[facing,setFacing]=useState("user"),[speakerOn,setSpeakerOn]=useState(true),[near,setNear]=useState(false),[audioBlocked,setAudioBlocked]=useState(false),[remoteReady,setRemoteReady]=useState(false);
 const pc=useRef(null),local=useRef(null),remote=useRef(null),localVideo=useRef(null),remoteVideo=useRef(null),remoteAudio=useRef(null),poll=useRef(null),signalPoll=useRef(null),statsPoll=useRef(null),lastSignal=useRef(0),pendingIce=useRef([]),direction=useRef(null),stopTone=useRef(()=>{}),proxSensor=useRef(null),proxLegacy=useRef(null),connectedAt=useRef(0),warnedNoAudio=useRef(false),lastStats=useRef("");
 const stopTimers=()=>{clearInterval(poll.current);clearInterval(signalPoll.current);clearInterval(statsPoll.current);poll.current=null;signalPoll.current=null;statsPoll.current=null};
 const stopSounds=()=>{try{stopTone.current?.()}catch{}stopTone.current=()=>{}};
 const playRing=(incoming=false)=>{stopSounds();stopTone.current=tone(incoming?[660,880]:[440,554],.22,incoming?1450:1200)};
 const playEnd=()=>{stopSounds();stopTone.current=tone([520,390],.16,0);setTimeout(stopSounds,500)};
 const stopMedia=()=>{local.current?.getTracks?.().forEach(t=>t.stop());local.current=null;remote.current=null;try{pc.current?.close()}catch{}pc.current=null;if(localVideo.current)localVideo.current.srcObject=null;if(remoteVideo.current)remoteVideo.current.srcObject=null;if(remoteAudio.current)remoteAudio.current.srcObject=null};
 const stopProximity=()=>{try{proxSensor.current?.stop?.()}catch{}proxSensor.current=null;if(proxLegacy.current){window.removeEventListener("userproximity",proxLegacy.current.user);window.removeEventListener("deviceproximity",proxLegacy.current.device);proxLegacy.current=null}setNear(false)};
 const reset=()=>{stopTimers();stopSounds();stopMedia();stopProximity();lastSignal.current=0;pendingIce.current=[];direction.current=null;connectedAt.current=0;warnedNoAudio.current=false;lastStats.current="";setCall(null);setPhase("idle");setStatus("");setMuted(false);setCameraOff(false);setFacing("user");setSpeakerOn(true);setAudioBlocked(false);setRemoteReady(false)};
 useEffect(()=>()=>{stopTimers();stopSounds();stopMedia();stopProximity()},[]);

 async function getMedia(kind,face="user"){
  if(!navigator.mediaDevices?.getUserMedia)throw new Error("MEDIA_UNSUPPORTED");
  try{const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:kind==="video"?{facingMode:{ideal:face},width:{ideal:1280},height:{ideal:720}}:false});rtcTrace("rtc_local_media",{audioTracks:stream.getAudioTracks().length,videoTracks:stream.getVideoTracks().length,kind});return stream}catch(e){rtcTrace("rtc_error",{stage:"getUserMedia",name:e?.name||"Error",message:e?.message||"MEDIA_ERROR"});throw e}
 }
 async function playRemote(){const el=remoteVideo.current||remoteAudio.current;if(!el)return;try{await el.play?.();setAudioBlocked(false);rtcTrace("rtc_playback",{ok:true})}catch(e){setAudioBlocked(true);rtcTrace("rtc_error",{stage:"autoplay",name:e?.name||"Error",message:e?.message||"PLAY_BLOCKED"})}}
 function startStats(c,p){clearInterval(statsPoll.current);statsPoll.current=setInterval(async()=>{try{if(!p||p.connectionState==="closed")return;const s=await p.getStats();let inAudio=0,inVideo=0,outAudio=0,outVideo=0,lost=0,pair=null,lc=null,rc=null;s.forEach(r=>{if(r.type==="inbound-rtp"&&!r.isRemote){if(r.kind==="audio"||r.mediaType==="audio")inAudio+=Number(r.bytesReceived||0);if(r.kind==="video"||r.mediaType==="video")inVideo+=Number(r.bytesReceived||0);lost+=Number(r.packetsLost||0)}if(r.type==="outbound-rtp"&&!r.isRemote){if(r.kind==="audio"||r.mediaType==="audio")outAudio+=Number(r.bytesSent||0);if(r.kind==="video"||r.mediaType==="video")outVideo+=Number(r.bytesSent||0)}if(r.type==="transport"&&r.selectedCandidatePairId)pair=s.get(r.selectedCandidatePairId)});if(pair){lc=s.get(pair.localCandidateId);rc=s.get(pair.remoteCandidateId)}const summary={connection:p.connectionState,ice:p.iceConnectionState,inAudio,inVideo,outAudio,outVideo,lost,localCandidate:lc?.candidateType||null,remoteCandidate:rc?.candidateType||null,protocol:lc?.protocol||null};const key=JSON.stringify(summary);if(key!==lastStats.current){lastStats.current=key;rtcTrace("rtc_stats",summary)}if(p.connectionState==="connected"&&connectedAt.current&&Date.now()-connectedAt.current>7000&&inAudio===0&&!warnedNoAudio.current){warnedNoAudio.current=true;setStatus("الاتصال قائم لكن الصوت ما وصلش");rtcTrace("rtc_error",{stage:"media",code:"NO_REMOTE_AUDIO",summary})}}catch(e){rtcTrace("rtc_error",{stage:"getStats",message:e?.message||"STATS_FAILED"})}},3000)}
 async function makePeer(c,stream){
  let cfg;try{cfg=await api("/api/calls/config");rtcTrace("rtc_config",{turnConfigured:Boolean(cfg.turnConfigured),iceServerCount:(cfg.iceServers||[]).length})}catch(e){rtcTrace("rtc_error",{stage:"config",status:e?.status||0,message:e?.message||"CALL_CONFIG_FAILED"});cfg={iceServers:[{urls:["stun:stun.l.google.com:19302","stun:stun1.l.google.com:19302"]}]}}
  const p=new RTCPeerConnection({iceServers:cfg.iceServers||[]});pc.current=p;local.current=stream;stream.getTracks().forEach(t=>p.addTrack(t,stream));const rs=new MediaStream();remote.current=rs;
  p.ontrack=e=>{const tracks=e.streams?.[0]?.getTracks?.()||[e.track];tracks.forEach(t=>{if(!rs.getTracks().find(x=>x.id===t.id))rs.addTrack(t);rtcTrace("rtc_track",{kind:t.kind,enabled:t.enabled,muted:t.muted,readyState:t.readyState});t.onunmute=()=>rtcTrace("rtc_track_unmuted",{kind:t.kind});t.onmute=()=>rtcTrace("rtc_track_muted",{kind:t.kind})});if(tracks.some(t=>t.kind==="audio"||t.kind==="video"))setRemoteReady(true);if(remoteVideo.current)remoteVideo.current.srcObject=rs;if(remoteAudio.current)remoteAudio.current.srcObject=rs;setTimeout(playRemote,0)};
  p.onicecandidate=e=>{if(e.candidate){rtcTrace("rtc_candidate",{type:e.candidate.type||null,protocol:e.candidate.protocol||null});api(`/api/calls/${c.id}/signals`,{method:"POST",body:JSON.stringify({kind:"ice",payload:e.candidate.toJSON()})}).catch(err=>rtcTrace("rtc_error",{stage:"send_ice",message:err?.message||"ICE_SEND_FAILED"}))}else rtcTrace("rtc_ice_gathering_complete",{})};
  p.onicecandidateerror=e=>rtcTrace("rtc_error",{stage:"ice_candidate",code:e.errorCode||0,text:e.errorText||"ICE_CANDIDATE_ERROR"});
  p.oniceconnectionstatechange=()=>{rtcTrace("rtc_ice_state",{state:p.iceConnectionState});if(p.iceConnectionState==="failed")setStatus("تعذر إنشاء مسار الصوت/الفيديو");else if(p.iceConnectionState==="disconnected")setStatus("جاري إعادة الاتصال...")};
  p.onsignalingstatechange=()=>rtcTrace("rtc_signaling_state",{state:p.signalingState});
  p.onconnectionstatechange=()=>{rtcTrace("rtc_connection_state",{state:p.connectionState});if(p.connectionState==="connected"){connectedAt.current=Date.now();warnedNoAudio.current=false;stopSounds();setStatus("");setPhase("connected");startStats(c,p);setTimeout(playRemote,0)}else if(p.connectionState==="connecting"){setPhase("connecting")}else if(p.connectionState==="disconnected"){setStatus("جاري إعادة الاتصال...")}else if(p.connectionState==="failed"){setStatus("تعذر الاتصال. تحقق من الشبكة وحاول مرة ثانية");setPhase("error")}else if(p.connectionState==="closed"){rtcTrace("rtc_closed",{})}};
  return p
 }
 async function flushIce(){if(!pc.current?.remoteDescription)return;const list=[...pendingIce.current];pendingIce.current=[];for(const c of list)try{await pc.current.addIceCandidate(c)}catch(e){rtcTrace("rtc_error",{stage:"addIceCandidate",message:e?.message||"ICE_ADD_FAILED"})}}
 async function handleSignals(c){try{const d=await api(`/api/calls/${c.id}/signals?since=${lastSignal.current}`);for(const s of d.signals||[]){lastSignal.current=Math.max(lastSignal.current,Number(s.id)||0);rtcTrace("rtc_signal",{kind:s.kind});if(s.kind==="offer"&&direction.current==="incoming"){if(!pc.current?.remoteDescription){await pc.current.setRemoteDescription(s.payload);await flushIce();const ans=await pc.current.createAnswer();await pc.current.setLocalDescription(ans);await api(`/api/calls/${c.id}/signals`,{method:"POST",body:JSON.stringify({kind:"answer",payload:pc.current.localDescription.toJSON()})});setPhase("connecting")}}else if(s.kind==="answer"&&direction.current==="outgoing"){if(!pc.current?.remoteDescription){await pc.current.setRemoteDescription(s.payload);await flushIce();stopSounds();setPhase("connecting")}}else if(s.kind==="ice"){if(pc.current?.remoteDescription)try{await pc.current.addIceCandidate(s.payload)}catch(e){rtcTrace("rtc_error",{stage:"addIceCandidate",message:e?.message||"ICE_ADD_FAILED"})}else pendingIce.current.push(s.payload)}}}catch(e){rtcTrace("rtc_error",{stage:"signals",status:e?.status||0,message:e?.message||"SIGNAL_LOAD_FAILED"})}}
 function startPolling(c){stopTimers();signalPoll.current=setInterval(()=>handleSignals(c),700);poll.current=setInterval(async()=>{try{const d=await api(`/api/calls/${c.id}`);const s=d.call?.status;if(s==="answered"&&phase==="ringing")setPhase("connecting");if(["declined","ended","missed"].includes(s)){playEnd();rtcTrace("rtc_call_end",{status:s});setStatus(s==="declined"?"تم رفض المكالمة":s==="missed"?"لم يتم الرد":"انتهت المكالمة");setTimeout(reset,850)}}catch(e){rtcTrace("rtc_error",{stage:"call_poll",status:e?.status||0,message:e?.message||"CALL_LOAD_FAILED"})}},1100)}

 async function startOutgoing(detail){if(call||phase!=="idle")return;try{setPhase("preparing");direction.current="outgoing";const kind=detail.kind==="video"?"video":"audio";rtcTrace("rtc_call_start",{direction:"outgoing",kind});const stream=await getMedia(kind,facing);const d=await api("/api/calls",{method:"POST",body:JSON.stringify({conversationId:detail.conversationId,kind})});const c={...d.call,peer_name:detail.name||"مستخدم مربوعة",peer_avatar:detail.avatar||null};setCall(c);const p=await makePeer(c,stream);const offer=await p.createOffer({offerToReceiveAudio:true,offerToReceiveVideo:kind==="video"});await p.setLocalDescription(offer);await api(`/api/calls/${c.id}/signals`,{method:"POST",body:JSON.stringify({kind:"offer",payload:p.localDescription.toJSON()})});setPhase("ringing");playRing(false);startPolling(c);setTimeout(()=>{if(localVideo.current){localVideo.current.srcObject=stream;localVideo.current.play?.().catch(()=>{})}},0)}catch(e){rtcTrace("rtc_error",{stage:"start_outgoing",name:e?.name||"Error",status:e?.status||0,message:e?.message||"CALL_START_FAILED"});setStatus(e?.name==="NotAllowedError"?"اسمح للكاميرا والمايكروفون":"تعذر بدء المكالمة");setPhase("error");setTimeout(reset,1800)}}

 useEffect(()=>{const fn=e=>startOutgoing(e.detail||{});window.addEventListener("marbo3a:start-call",fn);return()=>window.removeEventListener("marbo3a:start-call",fn)},[call,phase,facing]);
 useEffect(()=>{const tick=async()=>{if(!token()||call||phase!=="idle"||document.visibilityState!=="visible")return;try{const d=await api("/api/calls/incoming");if(d.call){direction.current="incoming";setCall({...d.call,peer_name:d.call.caller_name||d.call.caller_username||"مستخدم مربوعة",peer_avatar:d.call.caller_avatar||null});setPhase("incoming");rtcTrace("rtc_call_start",{direction:"incoming",kind:d.call.kind});playRing(true)}}catch(e){rtcTrace("rtc_error",{stage:"incoming_poll",status:e?.status||0,message:e?.message||"INCOMING_LOAD_FAILED"})}};tick();const t=setInterval(tick,2000);return()=>clearInterval(t)},[call,phase]);

 useEffect(()=>{if(!call||call.kind!=="audio"||phase!=="connected")return;try{if("ProximitySensor" in window){const sensor=new window.ProximitySensor();proxSensor.current=sensor;sensor.addEventListener("reading",()=>setNear(Boolean(sensor.near??(sensor.distance!=null&&sensor.distance<3))));sensor.start();rtcTrace("rtc_proximity",{mode:"sensor"})}else{const user=e=>setNear(Boolean(e.near));const device=e=>setNear(Number(e.value)<Math.min(Number(e.max)||Infinity,3));proxLegacy.current={user,device};window.addEventListener("userproximity",user);window.addEventListener("deviceproximity",device);rtcTrace("rtc_proximity",{mode:"legacy"})}}catch(e){rtcTrace("rtc_error",{stage:"proximity",message:e?.message||"PROXIMITY_UNAVAILABLE"})}return stopProximity},[call,phase]);

 async function accept(){if(!call)return;try{setPhase("preparing");stopSounds();rtcTrace("rtc_accept",{kind:call.kind});const stream=await getMedia(call.kind,facing);await api(`/api/calls/${call.id}/answer`,{method:"POST"});await makePeer(call,stream);setPhase("connecting");startPolling(call);setTimeout(()=>{if(localVideo.current){localVideo.current.srcObject=stream;localVideo.current.play?.().catch(()=>{})}},0);await handleSignals(call)}catch(e){rtcTrace("rtc_error",{stage:"accept",name:e?.name||"Error",status:e?.status||0,message:e?.message||"CALL_ACCEPT_FAILED"});setStatus(e?.name==="NotAllowedError"?"اسمح للكاميرا والمايكروفون":"تعذر قبول المكالمة");setPhase("error")}}
 async function decline(){if(!call)return;await api(`/api/calls/${call.id}/decline`,{method:"POST"}).catch(()=>{});rtcTrace("rtc_call_end",{status:"declined_local"});playEnd();setTimeout(reset,350)}
 async function hangup(){if(call)await api(`/api/calls/${call.id}/end`,{method:"POST"}).catch(()=>{});rtcTrace("rtc_call_end",{status:"ended_local"});playEnd();setTimeout(reset,350)}
 function toggleMute(){const track=local.current?.getAudioTracks?.()[0];if(track){track.enabled=!track.enabled;setMuted(!track.enabled);rtcTrace("rtc_local_audio",{enabled:track.enabled})}}
 function toggleCamera(){const track=local.current?.getVideoTracks?.()[0];if(track){track.enabled=!track.enabled;setCameraOff(!track.enabled);rtcTrace("rtc_local_video",{enabled:track.enabled});setTimeout(()=>{if(localVideo.current&&local.current)localVideo.current.srcObject=local.current},0)}}
 async function switchCamera(){if(!call||call.kind!=="video"||cameraOff)return;const next=facing==="user"?"environment":"user";try{const fresh=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:next},width:{ideal:1280},height:{ideal:720}},audio:false});const nt=fresh.getVideoTracks()[0];const sender=pc.current?.getSenders?.().find(s=>s.track?.kind==="video");if(sender)await sender.replaceTrack(nt);const old=local.current?.getVideoTracks?.()[0];if(old){local.current.removeTrack(old);old.stop()}local.current.addTrack(nt);setFacing(next);rtcTrace("rtc_camera_switch",{facing:next});if(localVideo.current){localVideo.current.srcObject=local.current;localVideo.current.play?.().catch(()=>{})}}catch(e){rtcTrace("rtc_error",{stage:"switch_camera",message:e?.message||"CAMERA_SWITCH_FAILED"});setStatus("تعذر تبديل الكاميرا")}}
 async function toggleSpeaker(){const media=remoteVideo.current||remoteAudio.current;if(!media)return;try{if(typeof media.setSinkId==="function"){const devices=await navigator.mediaDevices.enumerateDevices();const outs=devices.filter(d=>d.kind==="audiooutput");const speaker=outs.find(d=>/speaker|مكبر/i.test(d.label));const earpiece=outs.find(d=>/earpiece|receiver|communications|سماعة/i.test(d.label));const target=speakerOn?(earpiece||outs.find(d=>d.deviceId==="default")||outs[0]):(speaker||outs.find(d=>d.deviceId!=="default")||outs[0]);if(target?.deviceId){await media.setSinkId(target.deviceId);setSpeakerOn(v=>!v);rtcTrace("rtc_audio_output",{speaker:!speakerOn,sink:"selected"});return}}setSpeakerOn(v=>!v);rtcTrace("rtc_audio_output",{speaker:!speakerOn,sink:"browser-managed"});setStatus("مخرج الصوت يتحكم فيه المتصفح على هذا الجهاز") }catch(e){rtcTrace("rtc_error",{stage:"audio_output",message:e?.message||"AUDIO_OUTPUT_FAILED"});setStatus("تعذر تغيير مخرج الصوت")}}

 if(!call&&phase==="idle")return null;
 const video=call?.kind==="video",inCall=phase!=="incoming";
 return <div className={`call-overlay ${video?"video":"audio"} ${near?"proximity-near":""}`} dir="rtl"><div className="call-screen">
   <div className="call-backdrop">{call?.peer_avatar?<img src={call.peer_avatar} alt=""/>:null}</div>
   {video&&inCall?<div className={`call-video-stage ${remoteReady?"has-remote-video":""}`}><video ref={remoteVideo} autoPlay playsInline/><div className={`remote-placeholder ${remoteReady?"ready":""}`}>{call?.peer_avatar?<img src={call.peer_avatar} alt=""/>:<div>{String(call?.peer_name||"م").slice(0,1)}</div>}</div><video ref={localVideo} autoPlay playsInline muted className={`call-local-video ${facing==="user"?"mirror":""} ${cameraOff?"camera-off":""}`}/></div>:<div className="call-audio-hero">{call?.peer_avatar?<img src={call.peer_avatar} alt=""/>:<div className="call-avatar-fallback">{String(call?.peer_name||"م").slice(0,1)}</div>}</div>}
   {!video&&<audio ref={remoteAudio} autoPlay playsInline/>}
   <div className="call-top"><h2>{call?.peer_name||"مكالمة مربوعة"}</h2><p>{phase==="incoming"?(video?"مكالمة فيديو واردة":"مكالمة صوتية واردة"):phase==="ringing"?"جاري الاتصال...":phase==="connecting"?"جاري توصيل الصوت والفيديو...":phase==="connected"?"متصل الآن":status||"جاري التجهيز..."}</p></div>
   {status&&phase!=="incoming"?<div className="call-status">{status}</div>:null}
   {audioBlocked&&inCall?<button className="call-audio-unlock" onClick={playRemote}>اضغط لتشغيل الصوت</button>:null}
   {phase==="incoming"?<div className="call-actions incoming"><button className="call-decline" onClick={decline}><Icon name="phoneOff" size={26}/><span>رفض</span></button><button className="call-accept" onClick={accept}><Icon name={video?"video":"phone"} size={26}/><span>رد</span></button></div>:<div className="call-actions active-call"><button onClick={toggleMute} className={muted?"active":""}><Icon name="mic"/><span>{muted?"فتح المايك":"كتم"}</span></button><button onClick={toggleSpeaker} className={speakerOn?"active":""}><Icon name="speaker"/><span>سبيكر</span></button>{video&&<button onClick={toggleCamera} className={cameraOff?"active":""}><Icon name={cameraOff?"cameraOff":"video"}/><span>{cameraOff?"فتح الفيديو":"إغلاق الفيديو"}</span></button>}{video&&<button onClick={switchCamera} disabled={cameraOff}><Icon name="switchCamera"/><span>تبديل</span></button>}<button className="call-decline end" onClick={hangup}><Icon name="phoneOff"/><span>إنهاء</span></button></div>}
   {near?<div className="proximity-cover" aria-hidden="true"/>:null}
 </div></div>;
}
