"use client";
import {useEffect,useState} from "react";
import {usePathname} from "next/navigation";
import {createPortal} from "react-dom";
import SafetyMenu from "./SafetyMenu";
const token=()=>typeof window!=="undefined"?(localStorage.getItem("marbo3a_token")||sessionStorage.getItem("marbo3a_token")||""):"";
export default function ContextSafety(){const path=usePathname(),[target,setTarget]=useState(null),[host,setHost]=useState(null),[postHosts,setPostHosts]=useState([]),[messageTarget,setMessageTarget]=useState(null),[messageHost,setMessageHost]=useState(null),[status,setStatus]=useState("");
 useEffect(()=>{setTarget(null);setHost(null);setPostHosts([]);setMessageTarget(null);setMessageHost(null);setStatus("");if(!token())return;let dead=false,timer;const chat=path?.match(/^\/chat\/(\d+)/)?.[1],room=path?.match(/^\/room\/(\d+)\/chat/)?.[1];
  async function resolve(){if(chat){try{const r=await fetch("/api/chats",{headers:{"x-marbo3a-session-mode":"cookie"},credentials:"same-origin",cache:"no-store"}),d=await r.json();const peer=(d.chats||[]).find(x=>String(x.id)===String(chat));if(!dead&&peer)setTarget({type:"user",id:Number(peer.user_id),userId:Number(peer.user_id)})}catch{}}else if(room)setTarget({type:"room",id:Number(room),userId:null})}
  function findHost(){const el=chat?document.querySelector(".chat-head-actions"):room?document.querySelector(".room-chat-tools-grid"):null;if(el){setHost(el);return}timer=setTimeout(findHost,250)}
  function scanPosts(){if(dead)return;const next=[];document.querySelectorAll('.sf-post[id^="post-"]').forEach(article=>{const id=Number(String(article.id).replace("post-","")),head=article.querySelector(".sf-post-head");if(!Number.isInteger(id)||!head)return;const ownerMenu=head.querySelector('.inline-more:not([aria-label="خيارات الأمان"])');if(!ownerMenu)next.push({id,host:head})});setPostHosts(prev=>prev.length===next.length&&prev.every((x,i)=>x.id===next[i]?.id&&x.host===next[i]?.host)?prev:next)}
  function onClick(e){const button=e.target?.closest?.(".chat-message-more,.room-message-more");if(!button)return;const article=button.closest?.("article[id]");if(!article)return;const direct=article.id.match(/^dm-(\d+)$/),roomMsg=article.id.match(/^room-msg-(\d+)$/);if(!direct&&!roomMsg)return;const next={type:direct?"direct_message":"message",id:Number((direct||roomMsg)[1])};setMessageTarget(next);setMessageHost(null);setTimeout(()=>{if(dead)return;const sheets=[...document.querySelectorAll(".message-sheet")],sheet=sheets.at(-1),actions=sheet?.querySelector(".message-sheet-actions");if(actions)setMessageHost(actions)},0)}
  if(chat||room){resolve();findHost()}scanPosts();const observer=new MutationObserver(()=>scanPosts());observer.observe(document.body,{childList:true,subtree:true});document.addEventListener("click",onClick,true);return()=>{dead=true;clearTimeout(timer);observer.disconnect();document.removeEventListener("click",onClick,true)}},[path]);
 const activeToken=token();if(!activeToken)return null;return <>{target&&host&&createPortal(<div className="context-safety-action"><SafetyMenu compact targetType={target.type} targetId={target.id} userId={target.userId} onStatus={setStatus}/></div>,host)}{postHosts.map(p=>createPortal(<SafetyMenu key={`post-${p.id}`} compact targetType="post" targetId={p.id} onStatus={setStatus}/>,p.host))}{messageTarget&&messageHost&&createPortal(<SafetyMenu compact={false} buttonLabel="إبلاغ" targetType={messageTarget.type} targetId={messageTarget.id} onStatus={setStatus}/>,messageHost)}{status&&<div className="context-safety-status" role="status" onClick={()=>setStatus("")}>{status}</div>}</>}
