import "./globals.css";
import "./brand.css";
import "./platform.css";
import "./social-feed.css";
import "./social-pages.css";
import "./social-hubs.css";
import "./chat-social.css";
import "./social-shell-v2.css";
import "./voice.css";
import "./room-voice.css";
import "./calls.css";
import "./system.css";
import "./safety.css";
import "./room-chat.css";
import "./product-components.css";
import "./auth.css";
import "./search-advanced.css";
import "./onboarding.css";
import "./navigation-cleanup.css";
import "./design-system.css";
import "./accessibility.css";
import "./ui-coherence.css";
import "./ui-components.css";
import "./ui-v3.css";
import "./ui-v3-screens.css";
import "./ui-v3-settings.css";
import "./ui-v3-rooms.css";
import "./ui-v3-messages.css";
import "./ui-v3-profile.css";
import "./ui-v3-chat.css";
import "./ui-v3-admin.css";
import "./ui-v3-brand.css";
import "./ui-v3-mobile-parity.css";
import "./ui-v3-mobile-components.css";
import "./ui-v3-density.css";
import "./ui-v3-controls.css";
import "./ui-v3-reference.css";
import "./ui-v3-features.css";
import "./ui-v3-final-audit.css";
import "./ui-v3-production-qa.css";
import "./ui-v3-navigation.css";
import "./ui-v3-room-community.css";
import "./ui-v3-experience-stage1.css";
import "./ui-v3-stories.css";
import "./stories-interactions.css";
import "./guest-entry.css";
import "./guest-rooms-v2.css";
import "./guest-rooms-v2-extra.css";
import "./first-run-stability.css";
import "./ui-v3-social-experience.css";
import "./r1-core.css";
import "./r1-admin.css";
import "./r1-brand-override.css";
import "./ui-v3-unified-scale.css";
import "./ui-contract-lock.css";
import { Cairo,Readex_Pro } from "next/font/google";
import AppRuntime from "./AppRuntime";
import InterfaceFixes from "./InterfaceFixes";
import IdentityMarksRuntime from "./IdentityMarksRuntime";
import {UI_BODY_CLASS} from "./ui-mode";
const cairo=Cairo({subsets:["arabic","latin"],weight:["400","500","600","700","800","900"],display:"swap",variable:"--font-cairo"});
const readex=Readex_Pro({subsets:["arabic","latin"],weight:["400","500","600","700"],display:"swap",variable:"--font-readex"});
export const metadata={metadataBase:new URL("https://marbo3a.ly"),title:{default:"مربوعة | MARBO3A",template:"%s | مربوعة"},description:"مربوعة منصة تواصل اجتماعي عربية للتواصل، الغرف، الأصحاب والمجتمع.",applicationName:"مربوعة",keywords:["مربوعة","MARBO3A","تواصل اجتماعي","غرف دردشة","أصدقاء","ليبيا"],alternates:{canonical:"/"},robots:{index:true,follow:true},openGraph:{type:"website",locale:"ar_LY",url:"https://marbo3a.ly/",siteName:"مربوعة",title:"مربوعة | MARBO3A",description:"أقرب الناس .. دايمًا معك. مكانك للتواصل، الغرف، الأصحاب والمجتمع.",images:[{url:"/opengraph-image",width:1200,height:630,alt:"مربوعة – MARBO3A"}]},twitter:{card:"summary_large_image",title:"مربوعة | MARBO3A",description:"أقرب الناس .. دايمًا معك.",images:["/opengraph-image"]},manifest:"/manifest.webmanifest",icons:{icon:[{url:"/favicon-32.png",sizes:"32x32",type:"image/png"},{url:"/favicon-16.png",sizes:"16x16",type:"image/png"},{url:"/pwa-192.png",sizes:"192x192",type:"image/png"}],apple:{url:"/apple-touch-icon.png",sizes:"180x180",type:"image/png"}}};
export const viewport={themeColor:"#FF7A00",width:"device-width",initialScale:1,viewportFit:"cover"};
export default function RootLayout({children}){const structuredData={"@context":"https://schema.org","@type":"WebSite",name:"مربوعة",alternateName:"MARBO3A",url:"https://marbo3a.ly/",inLanguage:"ar"};return <html lang="ar" dir="rtl" className={`${cairo.variable} ${readex.variable}`} data-site-font="readex"><body className={UI_BODY_CLASS}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData)}}/><AppRuntime>{children}</AppRuntime><IdentityMarksRuntime/><InterfaceFixes/></body></html>}
