"use client";
import {useEffect,useMemo,useState} from "react";
import {createPortal} from "react-dom";
import Icon from "./Icon";

const token=()=>typeof window!=="undefined"?(localStorage.getItem("marbo3a_token")||sessionStorage.getItem("marbo3a_token")||""):"";
async function api(path,options={}){const headers={...(options.headers||{})},t=token();if(t&&t!=="cookie")headers.authorization=`Bearer ${t}`;if(options.body&&!headers["content-type"])headers["content-type"]="application/json";const r=await fetch(path,{...options,headers,cache:"no-store",credentials:"same-origin"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"REQUEST_FAILED");return d}
const uniqByHost=list=>{const seen=new Set();return(list||[]).filter(x=>{const key=String(x.host_id||x.user_id||"");if(!key||seen.has(key))return false;seen.add(key);return true})};

function LiveComposerButton(){return <button type="button" className="composer-tool-button live-composer-entry" onClick={()=>{location.href="/live/new"}}><span className="live-composer-icon"><Icon name="video"/><i/></span><span>مباشر</span></button>}
function LiveFeedCards({lives}){return <>{lives.map(l=><article className="live-feed-post" key={l.id}><header><a href={`/u/${l.username}`} className="live-feed-user">{l.avatar_url?<img src={l.avatar_url} alt=""/>:<span>{String(l.display_name||"م")[0]}</span>}<div><b>{l.display_name}</b><small><bdi dir="ltr">@{l.username}</bdi></small></div></a><span className="live-feed-badge"><i/> مباشر توا</span></header><a className="live-feed-stage" href={`/live/${l.id}`}><div className="live-feed-avatar">{l.avatar_url?<img src={l.avatar_url} alt=""/>:<span>{String(l.display_name||"م")[0]}</span>}</div><div><b>{l.title||`${l.display_name} مباشر توا`}</b><small><Icon name="users" size={14}/>{Number(l.viewers_count||0)} يتفرجوا توا</small></div><span className="live-feed-watch"><Icon name="video" size={17}/> ادخل اللايف</span></a></article>)}</>}
function LiveStoryButtons({lives}){return <>{lives.map(l=><a className="story-person live-story-person" href={`/live/${l.id}`} key={l.id}><span className="story-avatar-wrap"><span className="story-avatar">{l.avatar_url?<img src={l.avatar_url} alt=""/>:<b>{String(l.display_name||"م")[0]}</b>}<i className="live-story-dot"/></span><b className="live-story-label">LIVE</b></span><small>{l.display_name}</small><em>{Number(l.viewers_count||0)}</em></a>)}</>}
function AudienceSheet({open,onClose,people,loading}){if(!open)return null;return createPortal(<div className="live-audience-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="live-audience-sheet" role="dialog" aria-modal="true"><header><div><small>مشاهدين اللايف</small><h3>{loading?"بنجيبوا القائمة...":`${people.length} يتفرجوا توا`}</h3></div><button type="button" onClick={onClose} aria-label="سكر"><Icon name="close"/></button></header><div>{!loading&&people.map(p=><a href={`/u/${p.username}`} key={p.user_id}>{p.avatar_url?<img src={p.avatar_url} alt=""/>:<span>{String(p.display_name||"م")[0]}</span>}<div><b>{p.display_name}</b><small><bdi dir="ltr">@{p.username}</bdi></small></div><Icon name="arrowLeft" size={17}/></a>)}{!loading&&!people.length&&<p>ما فيش مشاهدين توا.</p>}</div></section></div>,document.body)}

export default function LiveEntryRuntime(){
 const[lives,setLives]=useState([]),[composerMount,setComposerMount]=useState(null),[feedMount,setFeedMount]=useState(null),[storyMount,setStoryMount]=useState(null),[audienceOpen,setAudienceOpen]=useState(false),[audience,setAudience]=useState([]),[audienceLoading,setAudienceLoading]=useState(false);
 const currentLives=useMemo(()=>uniqByHost(lives),[lives]);
 useEffect(()=>{if(!token())return;let alive=true;const load=()=>api("/api/live").then(d=>alive&&setLives(d.lives||[])).catch(()=>{});load();const t=setInterval(load,10000);const onLive=()=>load();window.addEventListener("marbo3a:live-changed",onLive);return()=>{alive=false;clearInterval(t);window.removeEventListener("marbo3a:live-changed",onLive)}},[]);
 useEffect(()=>{if(typeof document==="undefined")return;let frame=0;const sync=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{
   const composer=document.querySelector(".sf-composer .composer-actions");let cm=document.getElementById("marbo3a-live-composer-mount");if(composer&&!cm){cm=document.createElement("span");cm.id="marbo3a-live-composer-mount";cm.className="live-composer-mount";const locationButton=composer.querySelector("button");composer.insertBefore(cm,locationButton||composer.lastChild)}if(cm&&cm.parentElement===composer)setComposerMount(cm);
   const center=document.querySelector(".feed-center");let fm=document.getElementById("marbo3a-live-feed-mount");if(center&&!fm){fm=document.createElement("div");fm.id="marbo3a-live-feed-mount";fm.className="live-feed-mount";center.appendChild(fm)}if(center&&fm){const pinned=center.querySelector(".sf-post.sf-post-pinned"),firstPost=[...center.querySelectorAll(".sf-post")].find(x=>x!==pinned);if(pinned)pinned.after(fm);else if(firstPost)center.insertBefore(fm,firstPost);else{const composerForm=center.querySelector(".sf-composer");if(composerForm)composerForm.after(fm)}setFeedMount(fm)}
   const rail=document.querySelector(".story-rail");let sm=document.getElementById("marbo3a-live-story-mount");if(rail&&!sm){sm=document.createElement("span");sm.id="marbo3a-live-story-mount";sm.className="live-story-mount";const add=rail.querySelector(".story-add");if(add)add.after(sm);else rail.prepend(sm)}if(sm&&sm.parentElement===rail)setStoryMount(sm);
   document.querySelectorAll(".story-person[data-live-shadowed='1']").forEach(el=>{el.hidden=false;delete el.dataset.liveShadowed});if(rail&&currentLives.length){const ordinary=[...rail.querySelectorAll(".story-person:not(.live-story-person)")];for(const live of currentLives){const match=ordinary.find(el=>{const name=el.querySelector("small")?.textContent?.trim();const img=el.querySelector("img")?.getAttribute("src")||"";return name===String(live.display_name||"")&&(!live.avatar_url||!img||img===live.avatar_url)});if(match){match.hidden=true;match.dataset.liveShadowed="1"}}}
   const audienceTrigger=document.querySelector(".live-watch-video>header>div>span");if(audienceTrigger&&!audienceTrigger.dataset.liveAudienceBound){audienceTrigger.dataset.liveAudienceBound="1";audienceTrigger.classList.add("live-audience-trigger");audienceTrigger.setAttribute("role","button");audienceTrigger.setAttribute("tabindex","0");const open=()=>openAudience();audienceTrigger.addEventListener("click",open);audienceTrigger.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();open()}})}
  })};sync();const obs=new MutationObserver(sync);obs.observe(document.body,{childList:true,subtree:true});window.addEventListener("popstate",sync);return()=>{cancelAnimationFrame(frame);obs.disconnect();window.removeEventListener("popstate",sync)}},[currentLives]);
 async function openAudience(){const m=location.pathname.match(/^\/live\/(\d+)$/);if(!m)return;setAudienceOpen(true);setAudienceLoading(true);try{const d=await api(`/api/live/${m[1]}/audience`);setAudience(d.viewers||[])}catch{setAudience([])}finally{setAudienceLoading(false)}}
 return <>{composerMount&&createPortal(<LiveComposerButton/>,composerMount)}{feedMount&&currentLives.length>0&&createPortal(<LiveFeedCards lives={currentLives}/>,feedMount)}{storyMount&&currentLives.length>0&&createPortal(<LiveStoryButtons lives={currentLives}/>,storyMount)}<AudienceSheet open={audienceOpen} onClose={()=>setAudienceOpen(false)} people={audience} loading={audienceLoading}/></>;
}
