"use client";
import {useEffect,useState} from "react";
const token=()=>typeof window!=="undefined"?(localStorage.getItem("marbo3a_token")||sessionStorage.getItem("marbo3a_token")||""):"";
const cache=new Map(),watchers=new Map(),queue=new Set();let flushTimer=null,eventsBound=false;
function publish(id,value,at=Date.now()){cache.set(String(id),{value:Boolean(value),at});for(const cb of watchers.get(String(id))||[])cb(Boolean(value))}
function announceWatch(){if(typeof window==="undefined")return;window.dispatchEvent(new CustomEvent("marbo3a:presence-watch-change",{detail:{userIds:[...watchers.keys()].map(Number).filter(Number.isInteger)}}))}
async function flush(){flushTimer=null;const ids=[...queue];queue.clear();if(!ids.length||!token())return;try{const t=token(),headers=t&&t!=="cookie"?{authorization:`Bearer ${t}`}:{},r=await fetch(`/api/presence/users?ids=${ids.join(",")}`,{headers,credentials:"same-origin",cache:"no-store"}),d=await r.json();const found=new Set();for(const u of d.users||[]){found.add(String(u.id));publish(u.id,u.online)}for(const id of ids)if(!found.has(String(id)))publish(id,false)}catch{}}
function request(id){if(!id)return;queue.add(String(id));if(!flushTimer)flushTimer=setTimeout(flush,35)}
function bindEvents(){if(eventsBound||typeof window==="undefined")return;eventsBound=true;window.addEventListener("marbo3a:presence:update",e=>{const d=e?.detail||{};if(d.userId!=null)publish(d.userId,d.online)});window.addEventListener("marbo3a:presence:snapshot",e=>{for(const u of e?.detail?.users||[])if(u?.userId!=null)publish(u.userId,u.online)});window.addEventListener("marbo3a:realtime",e=>{if(e?.detail?.connected){announceWatch();for(const id of watchers.keys())if(!cache.has(id)||Date.now()-cache.get(id).at>120000)request(id)}})}
export function useOnline(id){const key=id==null?null:String(id),initial=key&&cache.get(key)?.value||false,[online,setOnline]=useState(initial);useEffect(()=>{bindEvents();if(!key)return;let set=watchers.get(key);if(!set){set=new Set();watchers.set(key,set)}set.add(setOnline);const hit=cache.get(key);if(!hit||Date.now()-hit.at>120000)request(key);else setOnline(hit.value);announceWatch();return()=>{set.delete(setOnline);if(!set.size)watchers.delete(key);announceWatch()}},[key]);return online}
export default function OnlineDot({userId,className=""}){const online=useOnline(userId);return online?<i className={`online-dot ${className}`.trim()} aria-label="متصل الآن" title="متصل الآن"/>:null}
