"use client";
import {useEffect,useRef,useState} from "react";
import {usePathname} from "next/navigation";
import Icon from "./Icon";
const token=()=>localStorage.getItem("marbo3a_token")||sessionStorage.getItem("marbo3a_token")||"";
async function api(path,options={}){const headers={authorization:`Bearer ${token()}`,...(options.headers||{})};if(options.body)headers["content-type"]="application/json";const r=await fetch(path,{...options,headers,cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"REQUEST_FAILED");return d}
export default function RoomVoiceStage(){
 const pathname=usePathname();
 const[roomId,setRoomId]=useState(null),[joined,setJoined]=useState(false),[joining,setJoining]=useState(false),[open,setOpen]=useState(true),[state,setState]=useState(null),[status,setStatus]=useState(""),[muted,setMuted]=useState(false),[speaking,setSpeaking]=useState({});
 const stream=useRef(null),peers=useRef(new Map()),lastSignal=useRef(0),audioCtx=useRef(null),meters=useRef(new Map()),pollRef=useRef(null),signalRef=useRef(null),retryRef=useRef(null),retryCount=useRef(0),manualLeave=useRef(false),roleRef=useRef("listener"),stateRef=useRef(null),joinedRef=useRef(false),roomRef=useRef(null),signalBusy=useRef(false),stateBusy=useRef(false),joiningRef=useRef(false);
 useEffect(()=>{joinedRef.current=joined},[joined]);useEffect(()=>{roomRef.current=roomId},[roomId]);
 const me=state?.participants?.find(x=>Number(x.user_id)===Number(state?.viewerId));const role=me?.role||"listener";roleRef.current=role;stateRef.current=state;
 function trace(event,detail={}){try{window.dispatchEvent(new CustomEvent("marbo3a:rtc-debug",{detail:{scope:"room_voice",event,roomId:roomRef.current,...detail}}))}catch{}}
 function clearRetry(){clearTimeout(retryRef.current);retryRef.current=null}
 function closePeer(id){id=Number(id);const p=peers.current.get(id);if(p){try{p.pc.ontrack=null;p.pc.onicecandidate=null;p.pc.onconnectionstatechange=null;p.pc.close()}catch{}try{p.audio?.pause();p.audio.srcObject=null;p.audio.remove?.()}catch{}peers.current.delete(id)}const meter=meters.current.get(id);if(meter){clearInterval(meter.timer);try{meter.source.disconnect()}catch{}meters.current.delete(id)}setSpeaking(x=>{const n={...x};delete n[id];return n})}
 function closeAll(){[...peers.current.keys()].forEach(closePeer)}function stopLocal(){stream.current?.getTracks?.().forEach(t=>t.stop());stream.current=null}
 function cleanup({keepManual=false}={}){clearInterval(pollRef.current);clearInterval(signalRef.current);clearRetry();pollRef.current=null;signalRef.current=null;signalBusy.current=false;stateBusy.current=false;joiningRef.current=false;setJoining(false);closeAll();stopLocal();lastSignal.current=0;joinedRef.current=false;setJoined(false);setState(null);setSpeaking({});setMuted(false);retryCount.current=0;if(!keepManual)manualLeave.current=false;try{audioCtx.current?.close()}catch{}audioCtx.current=null}
 useEffect(()=>()=>cleanup(),[]);
 useEffect(()=>{const m=String(pathname||"").match(/^\/room\/(\d+)\/chat$/),next=m?Number(m[1]):null,previous=roomRef.current;if(previous!==next){if(joinedRef.current||previous)cleanup();manualLeave.current=false;retryCount.current=0}roomRef.current=next;setRoomId(next)},[pathname]);
 async function unlockAudio(){try{if(window.AudioContext||window.webkitAudioContext){audioCtx.current ||= new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.current.state==="suspended")await audioCtx.current.resume()}for(const p of peers.current.values())await p.audio?.play?.().catch(()=>{})}catch{}}
 useEffect(()=>{if(!roomId)return;const resume=()=>unlockAudio();document.addEventListener("pointerdown",resume,{passive:true});document.addEventListener("touchstart",resume,{passive:true});return()=>{document.removeEventListener("pointerdown",resume);document.removeEventListener("touchstart",resume)}},[roomId]);
 async function loadState(){const rid=roomRef.current;if(!rid||!joinedRef.current||stateBusy.current)return stateRef.current;stateBusy.current=true;try{const d=await api(`/api/rooms/${rid}/voice/state`);stateRef.current=d;roleRef.current=(d.participants||[]).find(x=>Number(x.user_id)===Number(d.viewerId))?.role||"listener";setState(d);const active=new Set((d.participants||[]).map(x=>Number(x.user_id)));for(const id of peers.current.keys())if(!active.has(id))closePeer(id);setStatus(s=>s==="تعذر تحديث الغرفة الصوتية"?"":s);return d}catch(e){setStatus("تعذر تحديث الغرفة الصوتية");trace("state_error",{error:String(e?.message||e)});return null}finally{stateBusy.current=false}}
 async function ensureLocal(){if(stream.current)return stream.current;if(!navigator.mediaDevices?.getUserMedia)throw new Error("MIC_UNSUPPORTED");const s=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});stream.current=s;s.getAudioTracks().forEach(t=>t.enabled=!muted);watchVolume(Number(stateRef.current?.viewerId||0),s);trace("local_audio_ready",{tracks:s.getAudioTracks().length});return s}
 function watchVolume(userId,s){if(!userId||meters.current.has(userId)||!s?.getAudioTracks?.().length)return;try{audioCtx.current ||= new (window.AudioContext||window.webkitAudioContext)();audioCtx.current.resume?.().catch(()=>{});const source=audioCtx.current.createMediaStreamSource(s),an=audioCtx.current.createAnalyser();an.fftSize=256;source.connect(an);const data=new Uint8Array(an.frequencyBinCount);let last=false;const timer=setInterval(()=>{an.getByteFrequencyData(data);const avg=data.reduce((a,b)=>a+b,0)/data.length,now=avg>16;if(now!==last){last=now;setSpeaking(x=>({...x,[userId]:now}))}},180);meters.current.set(userId,{source,timer})}catch{}}
 async function sendSignal(to,kind,payload){return api(`/api/rooms/${roomRef.current}/voice/signals`,{method:"POST",body:JSON.stringify({recipientId:to,kind,payload})})}
 async function makePeer(peerId,initiate=false){peerId=Number(peerId);if(peers.current.has(peerId))return peers.current.get(peerId).pc;const cfg=stateRef.current?.iceServers||[{urls:"stun:stun.l.google.com:19302"}];const pc=new RTCPeerConnection({iceServers:cfg,bundlePolicy:"max-bundle",rtcpMuxPolicy:"require",iceCandidatePoolSize:2}),audio=document.createElement("audio");audio.autoplay=true;audio.playsInline=true;audio.muted=false;audio.volume=1;audio.className="room-voice-remote-audio";audio.setAttribute("aria-hidden","true");document.body.appendChild(audio);const remoteStream=new MediaStream();audio.srcObject=remoteStream;pc.addTransceiver("audio",{direction:roleRef.current==="speaker"?"sendrecv":"recvonly"});pc.ontrack=e=>{if(e.track.kind!=="audio")return;const tracks=e.streams?.[0]?.getAudioTracks?.()||[e.track];tracks.forEach(t=>{if(!remoteStream.getTracks().some(x=>x.id===t.id))remoteStream.addTrack(t)});audio.srcObject=remoteStream;audio.play().then(()=>{setStatus(s=>s==="اضغط مرة داخل الغرفة لتفعيل الصوت"?"أنت تستمع الآن":s);trace("remote_audio_playing",{peerId,tracks:remoteStream.getAudioTracks().length})}).catch(err=>{trace("remote_audio_blocked",{peerId,error:String(err?.name||err)});setStatus("اضغط مرة داخل الغرفة لتفعيل الصوت")});watchVolume(peerId,remoteStream)};pc.onicecandidate=e=>{if(e.candidate)sendSignal(peerId,"ice",e.candidate.toJSON()).catch(err=>trace("signal_error",{stage:"send_ice",peerId,error:String(err?.message||err)}))};pc.onicecandidateerror=e=>trace("ice_candidate_error",{peerId,code:e.errorCode||0,text:e.errorText||""});pc.onconnectionstatechange=()=>{const state=pc.connectionState;trace("peer_state",{peerId,state,ice:pc.iceConnectionState});if(["failed","closed"].includes(state)){closePeer(peerId);setTimeout(()=>refreshState(),500)}else if(state==="disconnected")setTimeout(()=>{if(pc.connectionState==="disconnected"){closePeer(peerId);refreshState()}},1800)};peers.current.set(peerId,{pc,audio,pending:[]});if(roleRef.current==="speaker"){const s=await ensureLocal(),sender=pc.getSenders().find(x=>x.track?.kind==="audio")||pc.getSenders().find(x=>!x.track),track=s.getAudioTracks()[0];if(sender&&track)await sender.replaceTrack(track);else if(track)pc.addTrack(track,s)}if(initiate){const offer=await pc.createOffer();await pc.setLocalDescription(offer);await sendSignal(peerId,"offer",pc.localDescription.toJSON());trace("offer_sent",{peerId})}return pc}
 async function processSignal(s){if(!s||!joinedRef.current)return;const sid=Number(s.id)||0;if(sid&&sid<=lastSignal.current)return;if(sid)lastSignal.current=Math.max(lastSignal.current,sid);const peerId=Number(s.sender_id??s.senderId);if(!peerId)return;let pc=peers.current.get(peerId)?.pc;if(s.kind==="offer"){pc ||= await makePeer(peerId,false);if(pc.signalingState!=="stable"&&pc.localDescription?.type==="offer"){try{await pc.setLocalDescription({type:"rollback"})}catch{}}await pc.setRemoteDescription(s.payload);const entry=peers.current.get(peerId);for(const ice of entry?.pending||[])try{await pc.addIceCandidate(ice)}catch{}if(entry)entry.pending=[];const ans=await pc.createAnswer();await pc.setLocalDescription(ans);await sendSignal(peerId,"answer",pc.localDescription.toJSON());trace("answer_sent",{peerId})}else if(s.kind==="answer"){if(pc&&pc.signalingState==="have-local-offer"){await pc.setRemoteDescription(s.payload);const entry=peers.current.get(peerId);for(const ice of entry?.pending||[])try{await pc.addIceCandidate(ice)}catch{}if(entry)entry.pending=[]}}else if(s.kind==="ice"){pc ||= await makePeer(peerId,false);if(pc.remoteDescription)try{await pc.addIceCandidate(s.payload)}catch{}else peers.current.get(peerId)?.pending.push(s.payload)}}
 async function handleSignals(){const rid=roomRef.current;if(!joinedRef.current||!rid||signalBusy.current)return;signalBusy.current=true;try{const d=await api(`/api/rooms/${rid}/voice/signals?since=${lastSignal.current}`);for(const s of d.signals||[])await processSignal(s)}catch(e){trace("signal_error",{error:String(e?.message||e)})}finally{signalBusy.current=false}}
 async function reconcile(d){if(!d||!joinedRef.current)return;stateRef.current=d;const selfId=Number(d.viewerId),self=(d.participants||[]).find(x=>Number(x.user_id)===selfId);roleRef.current=self?.role||"listener";if(self?.role==="speaker"){try{await ensureLocal()}catch(e){setStatus(e?.name==="NotAllowedError"?"اسمح لمربوعة باستخدام المايكروفون حتى تتكلم":"تعذر تشغيل المايكروفون");trace("local_audio_error",{error:String(e?.name||e)})}}else stopLocal();const participants=d.participants||[],active=new Set(participants.map(x=>Number(x.user_id)));for(const id of peers.current.keys())if(!active.has(id))closePeer(id);for(const p of participants){const pid=Number(p.user_id);if(pid===selfId)continue;const shouldConnect=self?.role==="speaker"||p.role==="speaker";if(!shouldConnect){closePeer(pid);continue}const initiate=self?.role==="speaker"&&(p.role==="listener"||(p.role==="speaker"&&selfId<pid));if(!peers.current.has(pid))try{await makePeer(pid,initiate)}catch(e){trace("peer_create_error",{peerId:pid,error:String(e?.message||e)})}}}
 async function refreshState(){const d=await loadState();if(d)await reconcile(d)}
 function scheduleJoinRetry(){if(manualLeave.current||!roomRef.current||retryCount.current>=4)return;clearRetry();const delay=Math.min(5000,700*Math.pow(2,retryCount.current++));retryRef.current=setTimeout(()=>join(),delay)}
 async function join(){const rid=roomRef.current||roomId;if(!rid||joinedRef.current||joiningRef.current||manualLeave.current)return;joiningRef.current=true;setJoining(true);setStatus("جاري الدخول كمستمع...");try{if(typeof RTCPeerConnection==="undefined")throw new Error("UNSUPPORTED");await unlockAudio();await api(`/api/rooms/${rid}/voice/join`,{method:"POST",body:"{}"});joinedRef.current=true;setJoined(true);setOpen(true);retryCount.current=0;clearRetry();const d=await api(`/api/rooms/${rid}/voice/state`);stateRef.current=d;roleRef.current=(d.participants||[]).find(x=>Number(x.user_id)===Number(d.viewerId))?.role||"listener";setState(d);await reconcile(d);await handleSignals();clearInterval(pollRef.current);clearInterval(signalRef.current);pollRef.current=setInterval(refreshState,5000);signalRef.current=setInterval(handleSignals,1500);setStatus("أنت تستمع الآن");trace("joined",{viewerId:d.viewerId,role:"listener"})}catch(e){joinedRef.current=false;setJoined(false);setStatus(e?.message==="VOICE_ROOM_FULL"?"الغرفة الصوتية وصلت للحد الأقصى":"نعيد محاولة تشغيل الاستماع...");trace("join_error",{error:String(e?.message||e)});scheduleJoinRetry()}finally{joiningRef.current=false;setJoining(false)}}
 useEffect(()=>{if(!roomId||joinedRef.current||joiningRef.current||manualLeave.current)return;const t=setTimeout(()=>join(),80);return()=>clearTimeout(t)},[roomId]);
 async function leave(){manualLeave.current=true;clearRetry();if(roomRef.current)await api(`/api/rooms/${roomRef.current}/voice/leave`,{method:"POST",body:"{}"}).catch(()=>{});cleanup({keepManual:true});manualLeave.current=true;setStatus("خرجت من الصوت")}
 function retryJoin(){manualLeave.current=false;retryCount.current=0;join()}
 useEffect(()=>{if(!joined||!roomId)return;const liveSignal=e=>{const d=e.detail||{};if(Number(d.roomId)!==Number(roomId))return;processSignal(d).catch(err=>trace("signal_error",{stage:"live",error:String(err?.message||err)}))},liveState=e=>{const d=e.detail||{};if(Number(d.roomId)!==Number(roomId))return;refreshState()},kicked=e=>{const d=e.detail||{};if(Number(d.roomId)!==Number(roomId))return;manualLeave.current=true;cleanup({keepManual:true});manualLeave.current=true;setStatus("تم إخراجك من الصوت بواسطة مشرف")};window.addEventListener("marbo3a:roomvoice:signal",liveSignal);window.addEventListener("marbo3a:roomvoice:state",liveState);window.addEventListener("marbo3a:roomvoice:kicked",kicked);return()=>{window.removeEventListener("marbo3a:roomvoice:signal",liveSignal);window.removeEventListener("marbo3a:roomvoice:state",liveState);window.removeEventListener("marbo3a:roomvoice:kicked",kicked)}},[joined,roomId]);
 useEffect(()=>{if(!joined||!roomId)return;const t=setInterval(()=>api(`/api/rooms/${roomId}/voice/heartbeat`,{method:"POST",body:JSON.stringify({muted})}).catch(()=>{}),5000);return()=>clearInterval(t)},[joined,roomId,muted]);
 async function requestMic(){try{const speakers=(stateRef.current?.participants||[]).filter(x=>x.role==="speaker").length;if(!speakers){await ensureLocal();await api(`/api/rooms/${roomRef.current}/voice/role`,{method:"POST",body:JSON.stringify({role:"speaker"})});setStatus("المايك معاك — تقدر تتكلم")}else{await api(`/api/rooms/${roomRef.current}/voice/request`,{method:"POST",body:"{}"});setStatus("تم طلب المايك — في انتظار الموافقة")}await refreshState()}catch(e){setStatus(e?.name==="NotAllowedError"||e?.message==="NotAllowedError"?"اسمح لمربوعة باستخدام المايكروفون":"طلب المايك يحتاج موافقة المشرف")}}
 async function dropMic(){await api(`/api/rooms/${roomRef.current}/voice/role`,{method:"POST",body:JSON.stringify({role:"listener"})}).catch(()=>{});closeAll();stopLocal();setMuted(false);setStatus("رجعت مستمع");await refreshState()}
 async function grant(userId){if(!stateRef.current?.manager)return;await api(`/api/rooms/${roomRef.current}/voice/role`,{method:"POST",body:JSON.stringify({userId,role:"speaker"})}).catch(()=>{});await refreshState()}
 function toggleMute(){const t=stream.current?.getAudioTracks?.()[0];if(t){t.enabled=!t.enabled;setMuted(!t.enabled);setStatus(t.enabled?"المايك مفتوح":"المايك مكتوم");trace("local_mute",{muted:!t.enabled})}}
 if(!roomId)return null;if(!joined)return <div className="room-voice-entry"><span className="room-voice-listener-state"><Icon name="headphones"/><b>{joining?"جاري الدخول كمستمع...":"الصوت المباشر"}</b></span><button type="button" onClick={retryJoin} disabled={joining}><Icon name="headphones"/><span>{joining?"جاري...":"تشغيل الاستماع"}</span></button>{status&&<small role="status">{status}</small>}</div>;
 const speakers=(state?.participants||[]).filter(x=>x.role==="speaker"),listeners=(state?.participants||[]).filter(x=>x.role==="listener");
 return <section className={`room-voice-stage ${open?"open":"collapsed"}`} dir="rtl"><header onClick={()=>setOpen(x=>!x)}><div><Icon name="mic"/><b>الصوت المباشر</b><span>{role==="speaker"?(muted?"أنت متحدث · المايك مكتوم":"أنت متحدث · المايك مفتوح"):"أنت تستمع"} · {speakers.length} متحدث · {listeners.length} مستمع</span></div><button type="button" aria-label={open?"تصغير الصوت المباشر":"توسيع الصوت المباشر"}>{open?"−":"+"}</button></header>{open&&<div className="room-voice-body"><div className="voice-people">{(state?.participants||[]).map(p=><button type="button" key={p.user_id} className={`${p.role} ${speaking[p.user_id]?"speaking":""} ${p.requested?"requested":""}`} onClick={()=>p.requested&&state?.manager&&grant(p.user_id)} title={p.requested&&state?.manager?"اضغط لإعطائه المايك":""}>{p.avatar_url?<img src={p.avatar_url} alt=""/>:<i>{String(p.display_name||p.username||"م")[0]}</i>}<b>{p.display_name||p.username}</b><small>{p.role==="speaker"?(p.muted?"🔇 متحدث مكتوم":"🎙️ متحدث"):(p.requested?"✋ طالب المايك":"🎧 مستمع")}</small></button>)}</div><div className="room-voice-actions">{role==="speaker"?<><button type="button" onClick={toggleMute} className={muted?"active":""}><Icon name="mic"/>{muted?"فتح المايك":"كتم المايك"}</button><button type="button" onClick={dropMic}>الرجوع كمستمع</button></>:<button type="button" onClick={requestMic}><Icon name="mic"/>{me?.requested?"تم طلب المايك":"طلب المايك"}</button>}<button type="button" className="leave" onClick={leave}>خروج من الصوت</button></div>{status&&<small className="room-voice-status" role="status">{status}</small>}</div>}</section>;
}
