"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {usePathname} from "next/navigation";
import Icon from "./Icon";

const token=()=>typeof window!=="undefined"?(localStorage.getItem("marbo3a_token")||sessionStorage.getItem("marbo3a_token")||""):"";
const sleep=ms=>new Promise(r=>setTimeout(r,ms));

export default function RoomVoiceStage(){
 const pathname=usePathname();
 const route=useMemo(()=>{const auth=String(pathname||"").match(/^\/room\/(\d+)\/chat$/),guest=String(pathname||"").match(/^\/guest\/room\/(\d+)$/);return auth?{roomId:Number(auth[1]),guest:false}:guest?{roomId:Number(guest[1]),guest:true}:{roomId:null,guest:false}},[pathname]);
 const roomId=route.roomId,guestMode=route.guest;
 const[joined,setJoined]=useState(false),[joining,setJoining]=useState(false),[state,setState]=useState(null),[status,setStatus]=useState(""),[muted,setMuted]=useState(false),[speaking,setSpeaking]=useState({}),[accountGate,setAccountGate]=useState(false);
 const stream=useRef(null),peers=useRef(new Map()),audioCtx=useRef(null),meters=useRef(new Map()),poll=useRef(null),signalPoll=useRef(null),heartbeat=useRef(null),retryRef=useRef(null),retryCount=useRef(0),lastUserSignal=useRef(0),lastGuestSignal=useRef(0),joinedRef=useRef(false),stateRef=useRef(null),roleRef=useRef("listener"),roomRef=useRef(null),guestRef=useRef(false),busySignals=useRef(false),busyState=useRef(false),manualLeave=useRef(false),joiningRef=useRef(false),mutedRef=useRef(false);
 useEffect(()=>{joinedRef.current=joined},[joined]);useEffect(()=>{stateRef.current=state},[state]);useEffect(()=>{roomRef.current=roomId;guestRef.current=guestMode},[roomId,guestMode]);useEffect(()=>{mutedRef.current=muted},[muted]);
 const viewerId=Number(state?.viewerId||0),me=(state?.participants||[]).find(x=>Number(x.user_id)===viewerId),role=me?.role||"listener",seatCount=Math.max(1,Math.min(16,Number(state?.seatCount||state?.maxSpeakers||8)));roleRef.current=role;
 function trace(event,detail={}){try{window.dispatchEvent(new CustomEvent("marbo3a:rtc-debug",{detail:{scope:"room_voice_v2",event,roomId:roomRef.current,guest:guestRef.current,...detail}}))}catch{}}
 function endpoint(suffix=""){const rid=roomRef.current||roomId;return guestRef.current?`/api/public/rooms-v2/${rid}/voice${suffix}`:`/api/rooms/${rid}/voice${suffix}`}
 async function api(path,options={}){const headers={...(options.headers||{})};if(!guestRef.current&&token())headers.authorization=`Bearer ${token()}`;if(options.body)headers["content-type"]="application/json";const r=await fetch(path,{...options,headers,credentials:"same-origin",cache:"no-store"}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"REQUEST_FAILED");return d}
 function clearRetry(){clearTimeout(retryRef.current);retryRef.current=null}
 function closePeer(id){id=Number(id);const p=peers.current.get(id);if(p){try{p.pc.ontrack=null;p.pc.onicecandidate=null;p.pc.onconnectionstatechange=null;p.pc.close()}catch{}try{p.audio?.pause();p.audio.srcObject=null;p.audio.remove?.()}catch{}peers.current.delete(id)}const m=meters.current.get(id);if(m){clearInterval(m.timer);try{m.source.disconnect()}catch{}meters.current.delete(id)}setSpeaking(x=>{const n={...x};delete n[id];return n})}
 function stopLocal(){stream.current?.getTracks?.().forEach(t=>t.stop());stream.current=null}
 function clearRuntime({keepManual=false}={}){clearInterval(poll.current);clearInterval(signalPoll.current);clearInterval(heartbeat.current);clearRetry();poll.current=null;signalPoll.current=null;heartbeat.current=null;[...peers.current.keys()].forEach(closePeer);stopLocal();lastUserSignal.current=0;lastGuestSignal.current=0;joinedRef.current=false;joiningRef.current=false;setJoined(false);setState(null);setSpeaking({});setMuted(false);mutedRef.current=false;retryCount.current=0;if(!keepManual)manualLeave.current=false;try{audioCtx.current?.close()}catch{}audioCtx.current=null}
 useEffect(()=>()=>clearRuntime(),[]);
 useEffect(()=>{clearRuntime();manualLeave.current=false;if(roomId){const t=setTimeout(()=>join(),100);return()=>clearTimeout(t)}},[roomId,guestMode]);
 async function unlockAudio(){try{if(window.AudioContext||window.webkitAudioContext){audioCtx.current ||= new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.current.state==="suspended")await audioCtx.current.resume()}for(const p of peers.current.values())await p.audio?.play?.().catch(()=>{})}catch{}}
 useEffect(()=>{if(!roomId)return;const resume=()=>unlockAudio();document.addEventListener("pointerdown",resume,{passive:true});document.addEventListener("touchstart",resume,{passive:true});return()=>{document.removeEventListener("pointerdown",resume);document.removeEventListener("touchstart",resume)}},[roomId]);
 function watchVolume(userId,s){if(!userId||meters.current.has(userId)||!s?.getAudioTracks?.().length)return;try{audioCtx.current ||= new (window.AudioContext||window.webkitAudioContext)();audioCtx.current.resume?.().catch(()=>{});const source=audioCtx.current.createMediaStreamSource(s),an=audioCtx.current.createAnalyser();an.fftSize=256;source.connect(an);const data=new Uint8Array(an.frequencyBinCount);let last=false;const timer=setInterval(()=>{an.getByteFrequencyData(data);const avg=data.reduce((a,b)=>a+b,0)/Math.max(1,data.length),now=avg>16;if(now!==last){last=now;setSpeaking(x=>({...x,[userId]:now}))}},180);meters.current.set(userId,{source,timer})}catch{}}
 async function ensureLocal(){if(guestRef.current)throw new Error("GUEST_LISTEN_ONLY");if(stream.current)return stream.current;if(!navigator.mediaDevices?.getUserMedia)throw new Error("MIC_UNSUPPORTED");try{const s=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});stream.current=s;s.getAudioTracks().forEach(t=>t.enabled=!mutedRef.current);watchVolume(Number(stateRef.current?.viewerId||0),s);trace("local_audio_ready",{tracks:s.getAudioTracks().length});return s}catch(e){window.dispatchEvent(new CustomEvent("marbo3a:permissions-open",{detail:{focus:"microphone"}}));throw e}}
 async function sendSignal(to,kind,payload){return api(endpoint("/signals"),{method:"POST",body:JSON.stringify({recipientId:Number(to),kind,payload})})}
 async function makePeer(peerId,initiate=false){peerId=Number(peerId);if(peers.current.has(peerId))return peers.current.get(peerId).pc;const cfg=stateRef.current?.iceServers||[{urls:"stun:stun.l.google.com:19302"}],pc=new RTCPeerConnection({iceServers:cfg,bundlePolicy:"max-bundle",rtcpMuxPolicy:"require",iceCandidatePoolSize:2}),audio=document.createElement("audio");audio.autoplay=true;audio.playsInline=true;audio.muted=false;audio.volume=1;audio.className="room-voice-remote-audio";audio.setAttribute("aria-hidden","true");document.body.appendChild(audio);const remoteStream=new MediaStream();audio.srcObject=remoteStream;pc.addTransceiver("audio",{direction:roleRef.current==="speaker"?"sendrecv":"recvonly"});pc.ontrack=e=>{if(e.track.kind!=="audio")return;const tracks=e.streams?.[0]?.getAudioTracks?.()||[e.track];for(const t of tracks)if(!remoteStream.getTracks().some(x=>x.id===t.id))remoteStream.addTrack(t);audio.srcObject=remoteStream;audio.play().then(()=>{setStatus(s=>s.includes("تفعيل الصوت")?"أنت تستمع الآن":s);trace("remote_audio_playing",{peerId,tracks:remoteStream.getAudioTracks().length})}).catch(err=>{trace("remote_audio_blocked",{peerId,error:String(err?.name||err)});setStatus("اضغط داخل الغرفة مرة لتفعيل الصوت")});watchVolume(peerId,remoteStream)};pc.onicecandidate=e=>{if(e.candidate)sendSignal(peerId,"ice",e.candidate.toJSON()).catch(err=>trace("signal_error",{stage:"send_ice",peerId,error:String(err?.message||err)}))};pc.onconnectionstatechange=()=>{trace("peer_state",{peerId,state:pc.connectionState,ice:pc.iceConnectionState});if(["failed","closed"].includes(pc.connectionState)){closePeer(peerId);setTimeout(()=>refreshState(),500)}else if(pc.connectionState==="disconnected")setTimeout(()=>{if(pc.connectionState==="disconnected"){closePeer(peerId);refreshState()}},1800)};peers.current.set(peerId,{pc,audio,pending:[]});if(roleRef.current==="speaker"){const s=await ensureLocal(),track=s.getAudioTracks()[0],sender=pc.getSenders().find(x=>x.track?.kind==="audio")||pc.getSenders().find(x=>!x.track);if(sender&&track)await sender.replaceTrack(track);else if(track)pc.addTrack(track,s)}if(initiate){const offer=await pc.createOffer();await pc.setLocalDescription(offer);await sendSignal(peerId,"offer",pc.localDescription.toJSON());trace("offer_sent",{peerId})}return pc}
 async function processSignal(s){const peerId=Number(s?.sender_id??s?.senderId);if(!peerId||!joinedRef.current)return;let pc=peers.current.get(peerId)?.pc;if(s.kind==="offer"){pc ||= await makePeer(peerId,false);if(pc.signalingState!=="stable"&&pc.localDescription?.type==="offer")try{await pc.setLocalDescription({type:"rollback"})}catch{}await pc.setRemoteDescription(s.payload);const entry=peers.current.get(peerId);for(const ice of entry?.pending||[])try{await pc.addIceCandidate(ice)}catch{}if(entry)entry.pending=[];const ans=await pc.createAnswer();await pc.setLocalDescription(ans);await sendSignal(peerId,"answer",pc.localDescription.toJSON());trace("answer_sent",{peerId})}else if(s.kind==="answer"){if(pc&&pc.signalingState==="have-local-offer"){await pc.setRemoteDescription(s.payload);const entry=peers.current.get(peerId);for(const ice of entry?.pending||[])try{await pc.addIceCandidate(ice)}catch{}if(entry)entry.pending=[]}}else if(s.kind==="ice"){pc ||= await makePeer(peerId,false);if(pc.remoteDescription)try{await pc.addIceCandidate(s.payload)}catch{}else peers.current.get(peerId)?.pending.push(s.payload)}}
 async function pullSignals(){if(!joinedRef.current||busySignals.current)return;busySignals.current=true;try{if(guestRef.current){const d=await api(`${endpoint("/signals")}?since=${lastGuestSignal.current}`);for(const s of d.signals||[]){lastGuestSignal.current=Math.max(lastGuestSignal.current,Number(s.id)||0);await processSignal(s)}}else{const d=await api(`${endpoint("/signals")}?since=${lastUserSignal.current}&guestSince=${lastGuestSignal.current}`);for(const s of d.signals||[]){lastUserSignal.current=Math.max(lastUserSignal.current,Number(s.id)||0);await processSignal(s)}for(const s of d.guestSignals||[]){lastGuestSignal.current=Math.max(lastGuestSignal.current,Number(s.id)||0);await processSignal(s)}}}catch(e){trace("signal_pull_failed",{error:e.message})}finally{busySignals.current=false}}
 async function loadState(){if(!joinedRef.current||busyState.current)return null;busyState.current=true;try{const d=await api(endpoint("/state"));stateRef.current=d;setState(d);return d}catch(e){setStatus("تعذر تحديث الصوت المباشر");trace("state_error",{error:String(e?.message||e)});return null}finally{busyState.current=false}}
 async function reconcile(d){if(!d||!joinedRef.current)return;const selfId=Number(d.viewerId),self=(d.participants||[]).find(x=>Number(x.user_id)===selfId);roleRef.current=self?.role||"listener";if(self?.role==="speaker"&&!guestRef.current){try{await ensureLocal()}catch(e){setStatus(e?.name==="NotAllowedError"?"المايكروفون مرفوض — افتح مركز الأذونات":"تعذر تشغيل المايكروفون")}}else stopLocal();const active=new Set((d.participants||[]).map(x=>Number(x.user_id)));for(const id of peers.current.keys())if(!active.has(id))closePeer(id);for(const p of d.participants||[]){const pid=Number(p.user_id);if(pid===selfId)continue;if(guestRef.current&&p.guest)continue;const should=self?.role==="speaker"||p.role==="speaker";if(!should){closePeer(pid);continue}const initiate=self?.role==="speaker"&&(p.role==="listener"||(p.role==="speaker"&&selfId<pid));if(!peers.current.has(pid))try{await makePeer(pid,initiate)}catch(e){trace("peer_failed",{peerId:pid,error:e.message})}}}
 async function refreshState(){const d=await loadState();if(d)await reconcile(d)}
 function scheduleJoinRetry(){if(manualLeave.current||!roomRef.current||retryCount.current>=4)return;clearRetry();const delay=Math.min(5000,700*Math.pow(2,retryCount.current++));retryRef.current=setTimeout(()=>join(),delay)}
 async function join(){if(!roomRef.current||joiningRef.current||joinedRef.current||manualLeave.current)return;joiningRef.current=true;setJoining(true);setStatus("جاري الدخول كمستمع...");try{if(typeof RTCPeerConnection==="undefined")throw new Error("UNSUPPORTED");await unlockAudio();await api(endpoint("/join"),{method:"POST",body:"{}"});joinedRef.current=true;setJoined(true);retryCount.current=0;clearRetry();const d=await api(endpoint("/state"));stateRef.current=d;setState(d);await reconcile(d);await pullSignals();clearInterval(poll.current);clearInterval(signalPoll.current);clearInterval(heartbeat.current);poll.current=setInterval(refreshState,4000);signalPoll.current=setInterval(pullSignals,1200);heartbeat.current=setInterval(()=>api(endpoint("/heartbeat"),{method:"POST",body:JSON.stringify({muted:mutedRef.current})}).catch(()=>{}),5000);setStatus(guestRef.current?"أنت داخل كزائر ومستمع":"أنت تستمع الآن");trace("joined",{viewerId:d.viewerId,role:"listener",guest:guestRef.current})}catch(e){joinedRef.current=false;setJoined(false);setStatus(e.message==="VOICE_ROOM_FULL"?"الغرفة الصوتية ممتلئة":"نعيد محاولة تشغيل الاستماع...");trace("join_failed",{error:e.message});scheduleJoinRetry()}finally{joiningRef.current=false;setJoining(false)}}
 useEffect(()=>{if(!joined||!roomId||guestMode)return;const liveSignal=e=>{const d=e.detail||{};if(Number(d.roomId)!==Number(roomId))return;processSignal(d).catch(err=>trace("signal_error",{stage:"live",error:String(err?.message||err)}))},liveState=e=>{const d=e.detail||{};if(Number(d.roomId)!==Number(roomId))return;refreshState()},kicked=e=>{const d=e.detail||{};if(Number(d.roomId)!==Number(roomId))return;manualLeave.current=true;clearRuntime({keepManual:true});manualLeave.current=true;setStatus("تم إخراجك من الصوت بواسطة مشرف")};window.addEventListener("marbo3a:roomvoice:signal",liveSignal);window.addEventListener("marbo3a:roomvoice:state",liveState);window.addEventListener("marbo3a:roomvoice:kicked",kicked);return()=>{window.removeEventListener("marbo3a:roomvoice:signal",liveSignal);window.removeEventListener("marbo3a:roomvoice:state",liveState);window.removeEventListener("marbo3a:roomvoice:kicked",kicked)}},[joined,roomId,guestMode]);
 async function leave(){manualLeave.current=true;clearRetry();await api(endpoint("/leave"),{method:"POST",body:"{}"}).catch(()=>{});clearRuntime({keepManual:true});manualLeave.current=true;setStatus("خرجت من الصوت")}
 async function takeSeat(index){if(guestRef.current){setAccountGate(true);return}if(!joinedRef.current)return;setStatus("جاري فتح المايكروفون...");try{await ensureLocal();await api(endpoint("/role"),{method:"POST",body:JSON.stringify({role:"speaker",seatIndex:index})});await sleep(80);await refreshState();setStatus(`أنت على الكرسي ${index}`)}catch(e){if(e.message==="SEAT_TAKEN")setStatus("الكرسي سبقك له شخص ثاني");else if(e.name==="NotAllowedError")setStatus("اسمح لمربوعة باستخدام المايكروفون");else setStatus("تعذر أخذ الكرسي الآن")}}
 async function leaveSeat(){if(guestRef.current)return;try{await api(endpoint("/role"),{method:"POST",body:JSON.stringify({role:"listener"})});stopLocal();await refreshState();setStatus("رجعت مستمع")}catch{setStatus("تعذر النزول من الكرسي")}}
 function toggleMute(){const next=!muted;setMuted(next);mutedRef.current=next;stream.current?.getAudioTracks?.().forEach(t=>t.enabled=!next);api(endpoint("/heartbeat"),{method:"POST",body:JSON.stringify({muted:next})}).catch(()=>{})}
 const speakers=(state?.participants||[]).filter(x=>x.role==="speaker"),listeners=(state?.participants||[]).filter(x=>x.role!=="speaker"),guestCount=(state?.participants||[]).filter(x=>x.guest).length,memberCount=(state?.participants||[]).length-guestCount,seatMap=new Map();const free=Array.from({length:seatCount},(_,i)=>i+1);for(const p of speakers){let i=Number(p.seat_index);if(!i||i<1||i>seatCount||seatMap.has(i))i=free.find(x=>!seatMap.has(x));if(i)seatMap.set(i,p)}
 return <section className="room-seat-stage" aria-label="الصوت المباشر"><header className="room-seat-head"><div><span className="room-live-dot"/><b>الكراسي الصوتية</b><small>{speakers.length}/{seatCount} متحدث · {listeners.length} مستمع</small></div><div className="room-seat-counts"><span>{memberCount} أعضاء</span><span>{guestCount} زوار</span></div></header><div className="room-seat-grid">{Array.from({length:seatCount},(_,x)=>x+1).map(i=>{const p=seatMap.get(i),mine=p&&Number(p.user_id)===viewerId,talking=p&&speaking[Number(p.user_id)];return <button type="button" key={i} className={`room-seat ${p?"occupied":"empty"} ${talking?"speaking":""} ${mine?"mine":""}`} onClick={()=>p?mine&&leaveSeat():takeSeat(i)} aria-label={p?`${p.display_name||p.username} على الكرسي ${i}`:`الكرسي ${i} فارغ`}><span className="room-seat-avatar">{p?(p.avatar_url?<img src={p.avatar_url} alt=""/>:<b>{String(p.display_name||p.username||"م")[0]}</b>):<Icon name="plus"/>}</span><small>{p?(mine?"أنت":p.display_name||p.username):"كرسي فارغ"}</small>{p?.muted&&<i><Icon name="micOff"/></i>}</button>})}</div><div className="room-listener-strip"><b>المستمعون</b><div>{listeners.slice(0,24).map(p=><span key={p.user_id} className={p.guest?"guest":""}>{p.avatar_url?<img src={p.avatar_url} alt=""/>:<i>{p.guest?"ز":String(p.display_name||p.username||"م")[0]}</i>}<small>{p.guest?`زائر ${Math.abs(Number(p.user_id))}`:p.display_name||p.username}</small></span>)}{!listeners.length&&<small>ما فيش مستمعين توا.</small>}</div></div><div className="room-seat-controls">{joined?<>{role==="speaker"&&!guestMode&&<button type="button" onClick={toggleMute}><Icon name={muted?"micOff":"mic"}/>{muted?"فتح المايك":"كتم"}</button>}<button type="button" className="ghost" onClick={leave}>خروج من الصوت</button></>:<button type="button" disabled={joining} onClick={()=>{manualLeave.current=false;retryCount.current=0;join()}}>{joining?"جاري الدخول...":"دخول كمستمع"}</button>}</div>{status&&<div className="room-seat-status" role="status">{status}</div>}{accountGate&&<div className="guest-gate-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setAccountGate(false)}><section className="guest-gate" role="dialog" aria-modal="true"><div className="guest-gate-icon"><Icon name="mic"/></div><h2>تبي تطلع على كرسي؟</h2><p>الاستماع متاح للزوار. سجل حسابك باش تقدر تتكلم وتشارك في الغرفة.</p><a className="primary" href={`/?next=${encodeURIComponent(`/room/${roomId}/chat`)}#register`}>سجل الآن</a><a href={`/?next=${encodeURIComponent(`/room/${roomId}/chat`)}`}>عندي حساب</a><button onClick={()=>setAccountGate(false)}>كمل استماع</button></section></div>}</section>
}
