"use client";
import {useEffect,useRef} from "react";
import {usePathname} from "next/navigation";
const getToken=()=>localStorage.getItem("marbo3a_token")||sessionStorage.getItem("marbo3a_token")||"";
const clearToken=()=>{localStorage.removeItem("marbo3a_token");sessionStorage.removeItem("marbo3a_token")};
const markCookieAuth=()=>{localStorage.setItem("marbo3a_token","cookie");sessionStorage.removeItem("marbo3a_token")};
async function hashPrefix(token){if(!token||token==="cookie"||!globalThis.crypto?.subtle)return"";try{const raw=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(token));return Array.from(new Uint8Array(raw)).map(x=>x.toString(16).padStart(2,"0")).join("").slice(0,16)}catch{return""}}
export default function SessionGuard(){const path=usePathname(),ending=useRef(false);useEffect(()=>{let dead=false,checking=false;const channel=typeof BroadcastChannel!=="undefined"?new BroadcastChannel("marbo3a-auth"):null;async function end(reason="session-ended"){if(dead||ending.current)return;ending.current=true;clearToken();try{channel?.postMessage({type:"session-ended",reason})}catch{}try{window.dispatchEvent(new CustomEvent("marbo3a:auth-ended",{detail:{reason}}))}catch{}if(location.pathname!=="/")location.replace(`/?reason=${encodeURIComponent(reason)}`);else history.replaceState(null,"","/")}
async function validate(){const t=getToken();if(!t||checking||dead)return;checking=true;try{const headers=t!=="cookie"?{"x-marbo3a-session-mode":"cookie"}:{},r=await fetch("/api/auth/me",{headers,credentials:"same-origin",cache:"no-store"});if(r.status===401)await end("session-ended");else if(r.status===403){const d=await r.json().catch(()=>({}));if(["ACCOUNT_BANNED","ACCOUNT_FROZEN","ACCOUNT_RESTRICTED"].includes(d.error))await end(String(d.error).toLowerCase())}else if(r.ok&&t!=="cookie")markCookieAuth()}catch{}finally{checking=false}}
async function onRevoked(e){const d=e?.detail||{},t=getToken();if(!t)return;if(t==="cookie"){await validate();return}const mine=await hashPrefix(t);if(d.sessionId){if(mine&&String(d.sessionId).startsWith(mine.slice(0,8)))await end(d.reason||"session-ended");return}if(d.exceptSessionId){if(!mine||!String(d.exceptSessionId).startsWith(mine.slice(0,8)))await end(d.reason||"session-ended");return}await end(d.reason||"session-ended")}
const onStorage=e=>{if(e.key==="marbo3a_token"&&!e.newValue&&location.pathname!=="/")end("signed-out")},onVisible=()=>document.visibilityState==="visible"&&validate(),onFocus=()=>validate(),onChannel=e=>e.data?.type==="session-ended"&&end(e.data.reason||"session-ended"),onRealtime=e=>e?.detail?.connected&&validate();window.addEventListener("marbo3a:session-revoked",onRevoked);window.addEventListener("marbo3a:realtime",onRealtime);window.addEventListener("storage",onStorage);window.addEventListener("focus",onFocus);document.addEventListener("visibilitychange",onVisible);channel?.addEventListener("message",onChannel);validate();const timer=setInterval(()=>document.visibilityState==="visible"&&validate(),60000);return()=>{dead=true;clearInterval(timer);window.removeEventListener("marbo3a:session-revoked",onRevoked);window.removeEventListener("marbo3a:realtime",onRealtime);window.removeEventListener("storage",onStorage);window.removeEventListener("focus",onFocus);document.removeEventListener("visibilitychange",onVisible);channel?.removeEventListener("message",onChannel);channel?.close()}},[path]);return null}
