"use client";

import {useEffect,useState} from "react";
import Icon from "./Icon";
const token=()=>localStorage.getItem("marbo3a_token")||sessionStorage.getItem("marbo3a_token")||"";
const b64ToUint8=s=>{const pad="=".repeat((4-s.length%4)%4),raw=atob((s+pad).replace(/-/g,"+").replace(/_/g,"/"));return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)));};
export default function SettingsPanel(){
 const[visible,setVisible]=useState(false),[open,setOpen]=useState(false),[tab,setTab]=useState("app"),[settings,setSettings]=useState({theme:"dark",notifications_enabled:true,notification_sounds:true}),[permission,setPermission]=useState("default"),[privacy,setPrivacy]=useState({who_can_message:"friends",who_can_add:"everyone",show_last_seen:true,show_city:true}),[sessions,setSessions]=useState([]),[pushEnabled,setPushEnabled]=useState(false),[status,setStatus]=useState("");
 const[currentPassword,setCurrentPassword]=useState(""),[newPassword,setNewPassword]=useState(""),[newEmail,setNewEmail]=useState(""),[emailCode,setEmailCode]=useState("");
 async function api(path,options={}){const t=token();if(!t)throw new Error("NO_TOKEN");const headers={authorization:`Bearer ${t}`,...(options.headers||{})};if(options.body&&!(options.body instanceof FormData))headers["content-type"]="application/json";const r=await fetch(path,{...options,headers,cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"REQUEST_FAILED");return d}
 function applyTheme(theme){const actual=theme==="system"?(matchMedia("(prefers-color-scheme: light)").matches?"light":"dark"):theme;document.documentElement.dataset.theme=actual}
 async function refresh(){if(!token()){setVisible(false);return}const[d,p,s,pc]=await Promise.allSettled([api("/api/settings"),api("/api/privacy"),api("/api/account/sessions"),fetch("/api/push/config",{cache:"no-store"}).then(r=>r.ok?r.json():({enabled:false}))]);if(d.status==="fulfilled"){setSettings(d.value.settings);applyTheme(d.value.settings.theme)}if(p.status==="fulfilled")setPrivacy(p.value.privacy);if(s.status==="fulfilled")setSessions(s.value.sessions||[]);if(pc.status==="fulfilled")setPushEnabled(Boolean(pc.value.enabled));if(d.status==="fulfilled"||p.status==="fulfilled"){setVisible(true);return}if(d.reason?.message==="NO_TOKEN"||p.reason?.message==="NO_TOKEN")setVisible(false)}
 useEffect(()=>{setPermission(typeof Notification!=="undefined"?Notification.permission:"unsupported");refresh().catch(()=>{});const timer=setInterval(()=>{if(token()&&document.visibilityState==="visible")refresh().catch(()=>{})},45000);return()=>clearInterval(timer)},[]);
 async function save(next){setSettings(next);applyTheme(next.theme);try{await api("/api/settings",{method:"PATCH",body:JSON.stringify({theme:next.theme,notificationsEnabled:next.notifications_enabled,notificationSounds:next.notification_sounds})});setStatus("تم حفظ الإعدادات")}catch{setStatus("تعذر حفظ الإعدادات")}}
 async function subscribePush(){try{if(typeof Notification==="undefined"||!("serviceWorker" in navigator))throw new Error("UNSUPPORTED");const p=await Notification.requestPermission();setPermission(p);if(p!=="granted")return;const cfg=await fetch("/api/push/config").then(r=>r.json());if(!cfg.enabled||!cfg.publicKey){setStatus("Push يحتاج مفاتيح VAPID على السيرفر");return}const reg=await navigator.serviceWorker.ready;let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64ToUint8(cfg.publicKey)});await api("/api/push/subscribe",{method:"POST",body:JSON.stringify({subscription:sub.toJSON()})});await save({...settings,notifications_enabled:true});setStatus("تم تفعيل الإشعارات الفورية")}catch(e){setStatus(`تعذر التفعيل: ${e.message}`)}}
 async function savePrivacy(next){setPrivacy(next);try{await api("/api/privacy",{method:"PATCH",body:JSON.stringify({whoCanMessage:next.who_can_message,whoCanAdd:next.who_can_add,showLastSeen:next.show_last_seen,showCity:next.show_city})});setStatus("تم حفظ الخصوصية")}catch(e){setStatus(e.message)}}
 async function changePassword(e){e.preventDefault();try{await api("/api/account/change-password",{method:"POST",body:JSON.stringify({currentPassword,newPassword})});setCurrentPassword("");setNewPassword("");setStatus("تم تغيير كلمة المرور")}catch(e){setStatus(e.message==="WRONG_PASSWORD"?"كلمة المرور الحالية غير صحيحة":e.message)}}
 async function requestEmail(){try{await api("/api/account/request-email-change",{method:"POST",body:JSON.stringify({email:newEmail})});setStatus("بعثنا رمز للبريد الجديد")}catch(e){setStatus(e.message)}}
 async function confirmEmail(){try{await api("/api/account/confirm-email-change",{method:"POST",body:JSON.stringify({code:emailCode})});setEmailCode("");setStatus("تم تغيير البريد")}catch(e){setStatus(e.message)}}
 async function revokeSession(id){try{await api(`/api/account/sessions/${id}`,{method:"DELETE"});await refresh()}catch(e){setStatus(e.message)}}
 async function logoutOthers(){try{await api("/api/account/logout-all",{method:"POST"});await refresh();setStatus("تم تسجيل الخروج من باقي الأجهزة")}catch(e){setStatus(e.message)}}
 async function scheduleDelete(){if(!confirm("سيتم حذف الحساب نهائيًا بعد 7 أيام. متأكد؟"))return;try{const d=await api("/api/account/delete",{method:"POST"});setStatus(`تم جدولة الحذف إلى ${new Date(d.deleteAt).toLocaleString("ar-LY")}`)}catch(e){setStatus(e.message)}}
 if(!visible)return null;
 return <><button className="settings-fab" onClick={()=>setOpen(v=>!v)} aria-label="الإعدادات"><Icon name="settings"/></button>{open&&<div className="settings-overlay" onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><section className="settings-card settings-large"><header><div><small>إعدادات مربوعة</small><h3>الحساب والتطبيق</h3></div><button onClick={()=>setOpen(false)}><Icon name="close"/></button></header><nav className="settings-tabs"><button className={tab==="app"?"active":""} onClick={()=>setTab("app")}>التطبيق</button><button className={tab==="privacy"?"active":""} onClick={()=>setTab("privacy")}>الخصوصية</button><button className={tab==="security"?"active":""} onClick={()=>setTab("security")}>الأمان</button><button className={tab==="sessions"?"active":""} onClick={()=>setTab("sessions")}>الأجهزة</button></nav>
 {tab==="app"&&<><div className="setting-row"><div><b>المظهر</b><span>شكل مربوعة على جهازك</span></div><select value={settings.theme} onChange={e=>save({...settings,theme:e.target.value})}><option value="dark">داكن</option><option value="light">فاتح</option><option value="system">حسب الجهاز</option></select></div><div className="setting-row"><div><b>الإشعارات الفورية</b><span>{permission==="granted"?(pushEnabled?"الجهاز يسمح بها":"الإذن موجود لكن السيرفر يحتاج VAPID"):permission==="denied"?"محظورة من المتصفح":"فعّلها وقت ما تبي"}</span></div><button className="setting-action" onClick={subscribePush}>تفعيل Push</button></div><div className="setting-row"><div><b>صوت الإشعارات</b><span>صوت خفيف للتنبيهات</span></div><input type="checkbox" checked={settings.notification_sounds} onChange={e=>save({...settings,notification_sounds:e.target.checked})}/></div><div className="settings-links"><a href="/map">الخريطة</a><a href="/privacy">سياسة الخصوصية</a><a href="/terms">شروط الاستخدام</a></div></>}
 {tab==="privacy"&&<><div className="setting-row"><div><b>من يقدر يراسلك</b></div><select value={privacy.who_can_message} onChange={e=>savePrivacy({...privacy,who_can_message:e.target.value})}><option value="everyone">الجميع</option><option value="friends">الأصدقاء فقط</option><option value="nobody">لا أحد</option></select></div><div className="setting-row"><div><b>من يقدر يضيفك</b></div><select value={privacy.who_can_add} onChange={e=>savePrivacy({...privacy,who_can_add:e.target.value})}><option value="everyone">الجميع</option><option value="friends">أصدقاء الأصدقاء</option><option value="nobody">لا أحد</option></select></div><div className="setting-row"><div><b>إظهار آخر ظهور</b></div><input type="checkbox" checked={privacy.show_last_seen} onChange={e=>savePrivacy({...privacy,show_last_seen:e.target.checked})}/></div><div className="setting-row"><div><b>إظهار المدينة</b></div><input type="checkbox" checked={privacy.show_city} onChange={e=>savePrivacy({...privacy,show_city:e.target.checked})}/></div><div className="settings-links"><a href="/blocked">الحسابات المحظورة</a></div></>}
 {tab==="security"&&<><form className="settings-form" onSubmit={changePassword}><h4>تغيير كلمة المرور</h4><input type="password" placeholder="كلمة المرور الحالية" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)} required/><input type="password" placeholder="كلمة المرور الجديدة - 8 أحرف على الأقل" value={newPassword} onChange={e=>setNewPassword(e.target.value)} minLength={8} required/><button>تغيير كلمة المرور</button></form><div className="settings-form"><h4>تغيير البريد</h4><input type="email" placeholder="البريد الجديد" value={newEmail} onChange={e=>setNewEmail(e.target.value)}/><button onClick={requestEmail}>إرسال رمز</button><input inputMode="numeric" placeholder="رمز 6 أرقام" value={emailCode} onChange={e=>setEmailCode(e.target.value.replace(/\D/g,"").slice(0,6))}/><button onClick={confirmEmail} disabled={emailCode.length!==6}>تأكيد البريد</button></div><button className="danger-setting" onClick={scheduleDelete}>حذف الحساب بعد 7 أيام</button></>}
 {tab==="sessions"&&<><div className="session-head"><p>الأجهزة والجلسات النشطة التي استعملت حسابك.</p><button onClick={logoutOthers}>خروج من باقي الأجهزة</button></div><div className="session-list">{sessions.map(s=><article key={s.id}><div><b>{s.current?"هذا الجهاز":"جلسة أخرى"}</b><span>{s.user_agent||"جهاز غير معروف"}</span><small>{s.ip_address} • آخر نشاط {new Date(s.last_seen).toLocaleString("ar-LY")}</small></div>{!s.current&&<button onClick={()=>revokeSession(s.id)}>إنهاء</button>}</article>)}</div></>}
 {status&&<div className="settings-status" onClick={()=>setStatus("")}>{status}</div>}</section></div>}</>
}
