"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import Icon from "./Icon";
import MediaGallery from "./MediaGallery";
import AppDialog from "./AppDialog";
import {uploadMedia} from "./imageTools";

const token=()=>typeof window!=="undefined"?(localStorage.getItem("marbo3a_token")||sessionStorage.getItem("marbo3a_token")||""):"";
async function api(path,options={}){const headers={...(options.headers||{})},t=token();if(t&&t!=="cookie")headers.authorization=`Bearer ${t}`;if(options.body&&!(options.body instanceof FormData)&&!headers["content-type"])headers["content-type"]="application/json";const r=await fetch(path,{...options,headers,cache:"no-store",credentials:"same-origin"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"REQUEST_FAILED");return d}
const errText=e=>({UNAUTHORIZED:"انتهت جلسة الدخول",EMPTY_POST:"اكتب شيئًا أو أضف صورة أو فيديو",POST_NOT_FOUND:"المنشور غير موجود",EMPTY_COMMENT:"اكتب تعليقًا أولًا",FILE_TOO_LARGE:"الملف أكبر من الحد المسموح",UNSUPPORTED_FILE:"نوع الملف غير مدعوم",HEIC_DECODE_FAILED:"تعذر تجهيز صورة الآيفون",IMAGE_PROCESS_FAILED:"تعذر تجهيز الصورة",UPLOAD_FAILED:"تعذر رفع الملف",REQUEST_FAILED:"تعذر تنفيذ الطلب الآن"}[e?.message]||"صار خطأ. حاول مرة ثانية.");
const when=v=>{if(!v)return"";const mins=Math.max(1,Math.round((Date.now()-new Date(v).getTime())/60000));if(mins<60)return`منذ ${mins} د`;const h=Math.round(mins/60);if(h<24)return`منذ ${h} س`;return new Date(v).toLocaleDateString("ar-LY")};
const mediaKind=m=>m?.type==="video"||String(m?.type||"").startsWith("video/")||/\.(mp4|webm|mov)(\?|$)/i.test(m?.url||"")?"video":"image";

function Avatar({user,size=42}){return user?.avatar_url?<img className="sf-avatar" style={{width:size,height:size}} src={user.avatar_url} alt=""/>:<span className="sf-avatar sf-avatar-fallback" style={{width:size,height:size}}>{user?.display_name?.[0]||user?.username?.[0]||"م"}</span>}
function Meta({username,date}){return <small className="sf-meta-line"><bdi dir="ltr">@{username}</bdi><span> · {when(date)}</span></small>}

function Comment({comment,postId,me,onChanged,onDeleted,onError}){
 const[dialog,setDialog]=useState(null),[draft,setDraft]=useState(comment.body||"");
 const mine=String(comment.user_id)===String(me?.id)||me?.role==="admin";
 async function edit(){if(!draft.trim())return;try{const d=await api(`/api/feed/${postId}/comments/${comment.id}`,{method:"PATCH",body:JSON.stringify({body:draft.trim()})});onChanged({...comment,...d.comment});setDialog(null)}catch(e){onError(errText(e))}}
 async function remove(){try{await api(`/api/feed/${postId}/comments/${comment.id}`,{method:"DELETE"});onDeleted(comment.id);setDialog(null)}catch(e){onError(errText(e))}}
 return <div className="sf-comment"><Avatar user={comment} size={32}/><div className="sf-comment-body"><div className="sf-comment-head"><span><b>{comment.display_name}</b><Meta username={comment.username} date={comment.created_at}/></span>{mine&&<button className="inline-more" type="button" aria-label="خيارات التعليق" onClick={()=>setDialog("menu")}><Icon name="more"/></button>}</div><p>{comment.body}</p></div>{dialog==="menu"&&<AppDialog open title="خيارات التعليق" onClose={()=>setDialog(null)} confirmLabel="تعديل" onConfirm={()=>{setDraft(comment.body||"");setDialog("edit")}}><button type="button" className="dialog-danger-link" onClick={()=>setDialog("delete")}>حذف التعليق</button></AppDialog>}{dialog==="edit"&&<AppDialog open input value={draft} onValueChange={setDraft} title="تعديل التعليق" confirmLabel="حفظ" onConfirm={edit} onClose={()=>setDialog(null)}/>} {dialog==="delete"&&<AppDialog open title="حذف التعليق؟" description="لن يظهر التعليق بعد الحذف." danger confirmLabel="حذف" onConfirm={remove} onClose={()=>setDialog(null)}/>}</div>
}

function PostCard({post,me,onChanged,onRemoved,onError,autoOpen=false}){
 const[comments,setComments]=useState([]),[open,setOpen]=useState(autoOpen),[comment,setComment]=useState(""),[busy,setBusy]=useState(false),[likeBusy,setLikeBusy]=useState(false),[dialog,setDialog]=useState(null),[draft,setDraft]=useState(post.body||"");
 useEffect(()=>{if(autoOpen)loadComments()},[autoOpen,post.id]);
 async function loadComments(){if(comments.length)return;try{setComments((await api(`/api/feed/${post.id}/comments`)).comments||[])}catch(e){onError(errText(e))}}
 async function toggleComments(){const next=!open;setOpen(next);if(next)await loadComments()}
 async function like(){if(likeBusy)return;setLikeBusy(true);const optimistic={...post,liked:!post.liked,likes_count:Math.max(0,Number(post.likes_count||0)+(post.liked?-1:1))};onChanged(optimistic);try{const d=await api(`/api/feed/${post.id}/like`,{method:"POST"});onChanged({...optimistic,liked:d.liked,likes_count:d.likesCount})}catch(e){onChanged(post);onError(errText(e))}finally{setLikeBusy(false)}}
 async function sendComment(e){e.preventDefault();if(!comment.trim()||busy)return;setBusy(true);try{const d=await api(`/api/feed/${post.id}/comments`,{method:"POST",body:JSON.stringify({body:comment.trim()})});setComments(p=>[...p,d.comment]);setComment("");setOpen(true);onChanged({...post,comments_count:Number(post.comments_count||0)+1})}catch(e){onError(errText(e))}finally{setBusy(false)}}
 async function edit(){try{const d=await api(`/api/feed/${post.id}`,{method:"PATCH",body:JSON.stringify({body:draft.trim()})});onChanged({...post,...d.post});setDialog(null)}catch(e){onError(errText(e))}}
 async function remove(){try{await api(`/api/feed/${post.id}`,{method:"DELETE"});onRemoved(post.id);setDialog(null)}catch(e){onError(errText(e))}}
 async function share(){const url=`${location.origin}/home?post=${post.id}`;try{if(navigator.share)await navigator.share({title:"منشور على مربوعة",text:post.body||"",url});else{await navigator.clipboard.writeText(url);onError("تم نسخ رابط المنشور")}}catch(e){if(e?.name!=="AbortError")onError("تعذر مشاركة المنشور")}}
 const mine=String(me?.id)===String(post.user_id)||me?.role==="admin",media=Array.isArray(post.media)&&post.media.length?post.media:(post.image_url?[{url:post.image_url,type:"image"}]:[]);
 return <article id={`post-${post.id}`} className={`sf-post ${autoOpen?"sf-post-focus":""}`}><header className="sf-post-head"><Link prefetch href={`/u/${post.username}`} className="sf-user"><Avatar user={post}/><span><b>{post.display_name}</b><Meta username={post.username} date={post.created_at}/>{post.location_label&&<small className="sf-post-location"><Icon name="map" size={13}/><span>{post.location_label}</span></small>}</span></Link>{mine&&<button type="button" className="inline-more" aria-label="خيارات المنشور" onClick={()=>setDialog("menu")}><Icon name="more"/></button>}</header>{post.body&&<p className="sf-body">{post.body}</p>}<MediaGallery items={media} alt="وسائط المنشور"/><div className="sf-post-stats"><span>{post.likes_count||0} إعجاب</span><button type="button" className="sf-stat-button" onClick={toggleComments}>{post.comments_count||0} تعليق</button></div><div className="sf-actions"><button type="button" className={`sf-like ${post.liked?"active":""}`} disabled={likeBusy} onClick={like}><Icon name="heart"/><span>{post.liked?"معجب":"إعجاب"}</span></button><button type="button" className={open?"active":""} onClick={toggleComments}><Icon name="message"/><span>تعليق</span></button><button type="button" onClick={share}><Icon name="share"/><span>مشاركة</span></button></div>{open&&<section className="sf-comments">{comments.map(c=><Comment key={c.id} comment={c} postId={post.id} me={me} onError={onError} onChanged={next=>setComments(x=>x.map(v=>v.id===next.id?next:v))} onDeleted={cid=>{setComments(x=>x.filter(v=>v.id!==cid));onChanged({...post,comments_count:Math.max(0,Number(post.comments_count||0)-1)})}}/>)}{!comments.length&&<p className="sf-muted">ما فيش تعليقات حتى الآن.</p>}<form onSubmit={sendComment} className="sf-comment-form"><input value={comment} onChange={e=>setComment(e.target.value)} placeholder="اكتب تعليقًا..." maxLength={1000}/><button disabled={busy||!comment.trim()} aria-label="إرسال التعليق"><Icon name="send"/></button></form></section>}{dialog==="menu"&&<AppDialog open title="خيارات المنشور" onClose={()=>setDialog(null)} confirmLabel="تعديل" onConfirm={()=>{setDraft(post.body||"");setDialog("edit")}}><button type="button" className="dialog-danger-link" onClick={()=>setDialog("delete")}>حذف المنشور</button></AppDialog>}{dialog==="edit"&&<AppDialog open input value={draft} onValueChange={setDraft} title="تعديل المنشور" confirmLabel="حفظ" onConfirm={edit} onClose={()=>setDialog(null)}/>} {dialog==="delete"&&<AppDialog open title="حذف المنشور؟" description="سيختفي المنشور وتعليقاته من الخلاصة." danger confirmLabel="حذف" onConfirm={remove} onClose={()=>setDialog(null)}/>}</article>
}

export default function SocialFeed({home=false}){
 const[me,setMe]=useState(null),[posts,setPosts]=useState([]),[cursor,setCursor]=useState(null),[loadingMe,setLoadingMe]=useState(true),[loadingFeed,setLoadingFeed]=useState(true),[body,setBody]=useState(""),[media,setMedia]=useState([]),[uploading,setUploading]=useState(false),[submitting,setSubmitting]=useState(false),[error,setError]=useState(""),[mode,setMode]=useState("all"),[more,setMore]=useState(false),[extrasOpen,setExtrasOpen]=useState(false),[locationOpen,setLocationOpen]=useState(false),[locationLabel,setLocationLabel]=useState(""),[locationDraft,setLocationDraft]=useState("");
 const canPost=useMemo(()=>Boolean(body.trim()||media.length),[body,media]),focusId=typeof window!=="undefined"?Number(new URLSearchParams(location.search).get("post"))||null:null,endpoint=m=>m==="friends"?"/api/feed/friends":"/api/feed";
 async function loadFeed(m=mode){setLoadingFeed(true);try{const f=await api(endpoint(m));let list=f.posts||[];if(focusId&&!list.some(p=>Number(p.id)===focusId)){try{const extra=await api(`/api/feed/${focusId}`);if(extra?.post)list=[extra.post,...list]}catch{}}setPosts(list);setCursor(f.nextCursor||null);setTimeout(()=>focusId&&document.getElementById(`post-${focusId}`)?.scrollIntoView({behavior:"smooth",block:"center"}),120)}catch(e){setError(errText(e))}finally{setLoadingFeed(false)}}
 useEffect(()=>{if(!token()){location.href="/";return}let alive=true;api("/api/auth/me").then(d=>{if(alive)setMe(d.user||null)}).catch(e=>alive&&setError(errText(e))).finally(()=>alive&&setLoadingMe(false));loadFeed("all");return()=>{alive=false}},[]);
 async function switchMode(next){if(next===mode)return;setMode(next);await loadFeed(next)}
 async function uploadImages(files){const slots=Math.max(0,10-media.length),list=[...(files||[])].slice(0,slots);if(!list.length||uploading)return;setUploading(true);setError("");try{const uploaded=[];for(const file of list){const d=await uploadMedia(file,token(),{compress:true,onState:s=>{try{window.dispatchEvent(new CustomEvent("marbo3a:media-debug",{detail:{type:"media_upload_state",state:s,kind:"post_image"}}))}catch{}}});if(!d.file?.url)throw new Error("UPLOAD_FAILED");uploaded.push({url:d.file.url,type:"image",mime:d.file.type})}setMedia(x=>[...x,...uploaded].slice(0,10))}catch(e){setError(errText(e))}finally{setUploading(false)}}
 async function uploadVideo(file){if(!file||uploading||media.some(x=>mediaKind(x)==="video")||media.length>=10)return;setUploading(true);setError("");try{if(file.size>12*1024*1024)throw new Error("FILE_TOO_LARGE");const fd=new FormData();fd.append("file",file,file.name||"video");const headers={},t=token();if(t&&t!=="cookie")headers.authorization=`Bearer ${t}`;const r=await fetch("/api/uploads/video",{method:"POST",headers,body:fd,cache:"no-store",credentials:"same-origin"}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"UPLOAD_FAILED");if(!d.file?.url)throw new Error("UPLOAD_FAILED");setMedia(x=>[...x,{url:d.file.url,type:"video",mime:d.file.type}].slice(0,10));try{window.dispatchEvent(new CustomEvent("marbo3a:media-debug",{detail:{type:"media_upload_state",state:"done",kind:"post_video"}}))}catch{}}catch(e){setError(errText(e))}finally{setUploading(false)}}
 function chooseLocation(){setLocationDraft(locationLabel);setLocationOpen(true)}
 function applyLocation(){setLocationLabel(locationDraft.trim().slice(0,120));setLocationOpen(false)}
 async function create(e){e.preventDefault();if(!canPost||submitting||uploading)return;setSubmitting(true);setError("");try{const items=media.map(x=>({url:x.url,type:mediaKind(x)})),images=items.filter(x=>x.type==="image").map(x=>x.url);const d=await api("/api/feed",{method:"POST",body:JSON.stringify({body:body.trim(),mediaItems:items,imageUrl:images[0]||null,imageUrls:images,locationLabel:locationLabel.trim()||null})});if(!d.post)throw new Error("REQUEST_FAILED");setPosts(p=>[d.post,...p]);setBody("");setMedia([]);setLocationLabel("");setExtrasOpen(false);history.replaceState(null,"","/home");window.scrollTo({top:0,behavior:"smooth"})}catch(e){setError(errText(e))}finally{setSubmitting(false)}}
 async function loadMore(){if(!cursor||more)return;setMore(true);try{const d=await api(`${endpoint(mode)}?cursor=${cursor}`);setPosts(p=>[...p,...(d.posts||[])]);setCursor(d.nextCursor||null)}catch(e){setError(errText(e))}finally{setMore(false)}}
 const loading=loadingMe||loadingFeed;
 return <main className="social-page feed-page" dir="rtl"><div className="social-shell feed-shell"><header className="sf-top"><Link prefetch href="/home" className="sf-brand"><img src="/logo.svg" alt="مربوعة"/><span><b>مربوعة</b><small>MARBO3A</small></span></Link><div className="sf-top-actions"><Link prefetch href="/search" aria-label="البحث"><Icon name="search"/></Link><Link prefetch href="/notifications" aria-label="التنبيهات"><Icon name="bell"/></Link>{loadingMe?<span className="sf-avatar sf-avatar-loading"/>:me?<Link prefetch href={`/u/${me.username}`} aria-label="الملف الشخصي"><Avatar user={me} size={38}/></Link>:null}</div></header><section className="feed-center">
 {loadingMe?<div className="feed-composer-skeleton"><span/><div/></div>:<form id="compose" className="sf-composer compact" onSubmit={create}><div className="sf-composer-row"><Avatar user={me}/><textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="شن في بالك؟" maxLength={3000}/></div>{media.length>0&&<div className="sf-multi-preview">{media.map((m,i)=><div key={`${m.url}-${i}`} className={mediaKind(m)==="video"?"video-preview":""}>{mediaKind(m)==="video"?<video src={m.url} muted playsInline preload="metadata"/>:<img src={m.url} alt={`معاينة ${i+1}`}/>}<button type="button" aria-label="حذف المرفق" onClick={()=>setMedia(x=>x.filter((_,n)=>n!==i))}>×</button></div>)}</div>}{locationLabel&&<div className="composer-location-chip"><Icon name="map" size={14}/><span>{locationLabel}</span><button type="button" onClick={()=>setLocationLabel("")} aria-label="إزالة الموقع"><Icon name="close" size={13}/></button></div>}<div className="sf-composer-tools composer-tools-v3"><div className="composer-actions"><label title="إضافة صور"><Icon name="image"/><span>صورة</span><input type="file" accept="image/*" multiple hidden disabled={uploading||submitting||media.length>=10} onChange={e=>{uploadImages(e.target.files);e.target.value=""}}/></label><label title="إضافة فيديو" className={media.some(x=>mediaKind(x)==="video")?"disabled":""}><Icon name="video"/><span>فيديو</span><input type="file" accept="video/mp4,video/webm,video/quicktime" hidden disabled={uploading||submitting||media.length>=10||media.some(x=>mediaKind(x)==="video")} onChange={e=>{uploadVideo(e.target.files?.[0]);e.target.value=""}}/></label><button type="button" className="composer-tool-button" onClick={chooseLocation}><Icon name="map"/><span>موقع</span></button><button type="button" className={`composer-tool-button ${extrasOpen?"active":""}`} onClick={()=>setExtrasOpen(v=>!v)}><Icon name="more"/><span>المزيد</span></button></div><button type="submit" className="primary" disabled={!canPost||uploading||submitting}>{submitting?"ينشر...":uploading?"يرفع...":"نشر"}</button></div>{extrasOpen&&<div className="composer-extra-row"><span>{media.length?`${media.length}/10 مرفقات`:"بدون مرفقات"}{media.some(x=>mediaKind(x)==="video")?" · فيديو واحد":""}</span><div>{media.length>0&&<button type="button" onClick={()=>setMedia([])}>مسح المرفقات</button>}{locationLabel&&<button type="button" onClick={()=>setLocationLabel("")}>إزالة الموقع</button>}</div></div>}</form>}
 <div className="feed-tabs" role="tablist"><button type="button" role="tab" aria-selected={mode==="all"} className={mode==="all"?"active":""} onClick={()=>switchMode("all")}>الأحدث</button><button type="button" role="tab" aria-selected={mode==="friends"} className={mode==="friends"?"active":""} onClick={()=>switchMode("friends")}>أصحابي</button></div>
 {error&&<div className="sf-alert" role="status" onClick={()=>setError("")}>{error}</div>}
 {loading&&<div className="sf-skeleton">جاري تحميل المنشورات...</div>}
 {!loading&&posts.map(p=><PostCard key={p.id} post={p} me={me} autoOpen={Number(p.id)===focusId} onError={setError} onChanged={next=>setPosts(list=>list.map(x=>String(x.id)===String(next.id)?next:x))} onRemoved={id=>setPosts(list=>list.filter(x=>String(x.id)!==String(id)))}/>) }
 {!loading&&!posts.length&&!error&&<div className="sf-empty"><Icon name="sparkles"/><h2>{mode==="friends"?"ما فيش منشورات من أصحابك توا":"ما فيش منشورات حتى الآن"}</h2><p>{mode==="friends"?"لما أصحابك ينشروا، بتظهر منشوراتهم هنا.":"كن أول واحد يشارك حاجة على مربوعة."}</p></div>}
 {cursor&&<button type="button" className="feed-more-button" disabled={more} onClick={loadMore}>{more?"جاري التحميل...":"عرض المزيد"}</button>}
 </section></div>{locationOpen&&<AppDialog open input value={locationDraft} onValueChange={setLocationDraft} title="أضف موقع للمنشور" description="اكتب اسم المدينة أو المكان فقط. مربوعة لا تحفظ إحداثيات GPS من هذا الحقل." confirmLabel="إضافة" onConfirm={applyLocation} onClose={()=>setLocationOpen(false)}/>}</main>;
}
