"use client";
import {useEffect,useMemo,useState} from "react";
import Icon from "./Icon";
import {uploadMedia} from "./imageTools";

const token=()=>typeof window!=="undefined"?(localStorage.getItem("marbo3a_token")||sessionStorage.getItem("marbo3a_token")||""):"";
async function api(path,options={}){const headers={...(options.headers||{})};const t=token();if(t)headers.authorization=`Bearer ${t}`;if(options.body&&!(options.body instanceof FormData)&&!headers["content-type"])headers["content-type"]="application/json";const start=performance.now();const r=await fetch(path,{...options,headers,cache:"no-store"});let d={};try{d=await r.json()}catch{};try{window.dispatchEvent(new CustomEvent("marbo3a:api-timing",{detail:{url:path,status:r.status,duration:Math.round(performance.now()-start)}}))}catch{};if(!r.ok)throw new Error(d.error||"REQUEST_FAILED");return d}
const errText=e=>({UNAUTHORIZED:"انتهت جلسة الدخول",EMPTY_POST:"اكتب شيئًا أو أضف صورة",POST_NOT_FOUND:"المنشور غير موجود",EMPTY_COMMENT:"اكتب تعليقًا أولًا",FILE_TOO_LARGE:"الملف أكبر من الحد المسموح",UNSUPPORTED_FILE:"نوع الملف غير مدعوم",HEIC_DECODE_FAILED:"تعذر تجهيز صورة الآيفون. جرّب لقطة شاشة أو JPG.",IMAGE_PROCESS_FAILED:"تعذر تجهيز الصورة",UPLOAD_FAILED:"تعذر رفع الصورة",REQUEST_FAILED:"تعذر تنفيذ الطلب الآن"}[e?.message]||"صار خطأ. حاول مرة ثانية.");
const when=v=>{if(!v)return"";const mins=Math.max(1,Math.round((Date.now()-new Date(v).getTime())/60000));if(mins<60)return`منذ ${mins} د`;const h=Math.round(mins/60);if(h<24)return`منذ ${h} س`;return new Date(v).toLocaleDateString("ar-LY")};
function Avatar({user,size=42}){return user?.avatar_url?<img className="sf-avatar" style={{width:size,height:size}} src={user.avatar_url} alt=""/>:<span className="sf-avatar sf-avatar-fallback" style={{width:size,height:size}}>{user?.display_name?.[0]||"م"}</span>}

function Comment({comment,postId,me,onChanged,onDeleted,onError}){
 const mine=String(comment.user_id)===String(me?.id)||me?.username==="ahmed";
 async function edit(){const body=prompt("عدّل التعليق:",comment.body||"");if(body===null||!body.trim())return;try{const d=await api(`/api/feed/${postId}/comments/${comment.id}`,{method:"PATCH",body:JSON.stringify({body})});onChanged({...comment,...d.comment})}catch(e){onError(errText(e))}}
 async function remove(){if(!confirm("حذف التعليق؟"))return;try{await api(`/api/feed/${postId}/comments/${comment.id}`,{method:"DELETE"});onDeleted(comment.id)}catch(e){onError(errText(e))}}
 return <div className="sf-comment"><Avatar user={comment} size={32}/><div className="sf-comment-body"><div className="sf-comment-head"><span><b>{comment.display_name}</b><small>@{comment.username} · {when(comment.created_at)}</small></span>{mine&&<details className="sf-menu"><summary aria-label="خيارات التعليق"><Icon name="more"/></summary><div><button type="button" onClick={edit}>تعديل</button><button type="button" className="danger" onClick={remove}>حذف</button></div></details>}</div><p>{comment.body}</p></div></div>
}

function PostCard({post,me,onChanged,onRemoved,onError,autoOpen=false}){
 const[comments,setComments]=useState([]),[open,setOpen]=useState(autoOpen),[comment,setComment]=useState(""),[busy,setBusy]=useState(false),[likeBusy,setLikeBusy]=useState(false);
 useEffect(()=>{if(autoOpen)loadComments()},[autoOpen,post.id]);
 async function loadComments(){if(comments.length)return;try{setComments((await api(`/api/feed/${post.id}/comments`)).comments||[])}catch(e){onError(errText(e))}}
 async function toggleComments(){const next=!open;setOpen(next);if(next)await loadComments()}
 async function like(){if(likeBusy)return;setLikeBusy(true);const optimistic={...post,liked:!post.liked,likes_count:Math.max(0,Number(post.likes_count||0)+(post.liked?-1:1))};onChanged(optimistic);try{const d=await api(`/api/feed/${post.id}/like`,{method:"POST"});onChanged({...optimistic,liked:d.liked,likes_count:d.likesCount})}catch(e){onChanged(post);onError(errText(e))}finally{setLikeBusy(false)}}
 async function sendComment(e){e.preventDefault();if(!comment.trim()||busy)return;setBusy(true);try{const d=await api(`/api/feed/${post.id}/comments`,{method:"POST",body:JSON.stringify({body:comment.trim()})});setComments(p=>[...p,d.comment]);setComment("");setOpen(true);onChanged({...post,comments_count:Number(post.comments_count||0)+1})}catch(e){onError(errText(e))}finally{setBusy(false)}}
 async function edit(){const body=prompt("عدّل المنشور:",post.body||"");if(body===null)return;try{const d=await api(`/api/feed/${post.id}`,{method:"PATCH",body:JSON.stringify({body})});onChanged({...post,...d.post})}catch(e){onError(errText(e))}}
 async function remove(){if(!confirm("حذف المنشور؟"))return;try{await api(`/api/feed/${post.id}`,{method:"DELETE"});onRemoved(post.id)}catch(e){onError(errText(e))}}
 async function share(){const url=`${location.origin}/feed?post=${post.id}`;try{if(navigator.share)await navigator.share({title:"منشور على مربوعة",text:post.body||"",url});else{await navigator.clipboard.writeText(url);onError("تم نسخ رابط المنشور")}}catch(e){if(e?.name!=="AbortError")onError("تعذر مشاركة المنشور")}}
 const mine=String(me?.id)===String(post.user_id)||me?.username==="ahmed";
 return <article id={`post-${post.id}`} className={`sf-post ${autoOpen?"sf-post-focus":""}`}><header className="sf-post-head"><a href={`/u/${post.username}`} className="sf-user"><Avatar user={post}/><span><b>{post.display_name}</b><small>@{post.username} · {when(post.created_at)}</small></span></a>{mine&&<details className="sf-menu"><summary aria-label="خيارات المنشور"><Icon name="more"/></summary><div><button type="button" onClick={edit}>تعديل</button><button type="button" className="danger" onClick={remove}>حذف</button></div></details>}</header>{post.body&&<p className="sf-body">{post.body}</p>}{post.image_url&&<a href={post.image_url} target="_blank" rel="noreferrer"><img className="sf-post-image" src={post.image_url} alt="صورة المنشور" loading="lazy"/></a>}<div className="sf-post-stats"><span>{post.likes_count||0} إعجاب</span><button type="button" className="sf-stat-button" onClick={toggleComments}>{post.comments_count||0} تعليق</button></div><div className="sf-actions"><button type="button" className={post.liked?"active":""} disabled={likeBusy} onClick={like}><Icon name="heart"/><span>إعجاب</span></button><button type="button" onClick={toggleComments}><Icon name="message"/><span>تعليق</span></button><button type="button" onClick={share}><Icon name="share"/><span>مشاركة</span></button></div>{open&&<section className="sf-comments">{comments.map(c=><Comment key={c.id} comment={c} postId={post.id} me={me} onError={onError} onChanged={next=>setComments(x=>x.map(v=>v.id===next.id?next:v))} onDeleted={cid=>{setComments(x=>x.filter(v=>v.id!==cid));onChanged({...post,comments_count:Math.max(0,Number(post.comments_count||0)-1)})}}/>)}{!comments.length&&<p className="sf-muted">ما فيش تعليقات حتى الآن.</p>}<form onSubmit={sendComment} className="sf-comment-form"><input value={comment} onChange={e=>setComment(e.target.value)} placeholder="اكتب تعليقًا..." maxLength={1000}/><button disabled={busy||!comment.trim()} aria-label="إرسال التعليق"><Icon name="send"/></button></form></section>}</article>
}

export default function SocialFeed({home=false}){
 const[me,setMe]=useState(null),[posts,setPosts]=useState([]),[cursor,setCursor]=useState(null),[loadingMe,setLoadingMe]=useState(true),[loadingFeed,setLoadingFeed]=useState(true),[body,setBody]=useState(""),[image,setImage]=useState(""),[uploading,setUploading]=useState(false),[submitting,setSubmitting]=useState(false),[error,setError]=useState(""),[mode,setMode]=useState("all"),[more,setMore]=useState(false);
 const canPost=useMemo(()=>Boolean(body.trim()||image),[body,image]);
 const focusId=typeof window!=="undefined"?Number(new URLSearchParams(location.search).get("post"))||null:null;
 const endpoint=m=>m==="friends"?"/api/feed/friends":"/api/feed";
 async function loadFeed(m=mode){setLoadingFeed(true);try{const f=await api(endpoint(m));let list=f.posts||[];if(focusId&&!list.some(p=>Number(p.id)===focusId)){try{const extra=await api(`/api/feed/${focusId}`);if(extra?.post)list=[extra.post,...list]}catch{}}setPosts(list);setCursor(f.nextCursor||null);setTimeout(()=>focusId&&document.getElementById(`post-${focusId}`)?.scrollIntoView({behavior:"smooth",block:"center"}),120)}catch(e){setError(errText(e))}finally{setLoadingFeed(false)}}
 useEffect(()=>{if(!token()){location.href="/";return}let alive=true;api("/api/auth/me").then(d=>{if(alive)setMe(d.user||null)}).catch(e=>alive&&setError(errText(e))).finally(()=>alive&&setLoadingMe(false));loadFeed("all");return()=>{alive=false}},[]);
 async function switchMode(next){if(next===mode)return;setMode(next);await loadFeed(next)}
 async function upload(file){if(!file||uploading)return;setUploading(true);setError("");try{const d=await uploadMedia(file,token(),{compress:true,onState:s=>{try{window.dispatchEvent(new CustomEvent("marbo3a:media-debug",{detail:{type:"media_upload_state",state:s,kind:"post_image"}}))}catch{}}});if(!d.file?.url)throw new Error("UPLOAD_FAILED");setImage(d.file.url)}catch(e){setImage("");setError(errText(e))}finally{setUploading(false)}}
 async function create(e){e.preventDefault();if(!canPost||submitting||uploading)return;setSubmitting(true);setError("");try{const d=await api("/api/feed",{method:"POST",body:JSON.stringify({body:body.trim(),imageUrl:image})});if(!d.post)throw new Error("REQUEST_FAILED");setPosts(p=>[d.post,...p]);setBody("");setImage("");history.replaceState(null,"",home?"/home":"/feed");window.scrollTo({top:0,behavior:"smooth"})}catch(e){setError(errText(e))}finally{setSubmitting(false)}}
 async function loadMore(){if(!cursor||more)return;setMore(true);try{const d=await api(`${endpoint(mode)}?cursor=${cursor}`);setPosts(p=>[...p,...(d.posts||[])]);setCursor(d.nextCursor||null)}catch(e){setError(errText(e))}finally{setMore(false)}}
 const loading=loadingMe||loadingFeed;
 return <main className="social-page feed-page" dir="rtl"><div className="social-shell feed-shell"><header className="sf-top"><a href="/home" className="sf-brand"><img src="/logo.svg" alt="مربوعة"/><span><b>{home?"مربوعة":"المنشورات"}</b><small>MARBO3A</small></span></a><div className="sf-top-actions"><a href="/search" aria-label="البحث"><Icon name="search"/></a><a href="/notifications" aria-label="التنبيهات"><Icon name="bell"/></a>{loadingMe?<span className="sf-avatar sf-avatar-loading"/>:<a href={me?`/u/${me.username}`:"/"} aria-label="الملف الشخصي"><Avatar user={me} size={38}/></a>}</div></header><section className="feed-center">{loadingMe?<div className="feed-composer-skeleton" aria-label="جاري تحميل الحساب"><span/><div/></div>:<form id="compose" className="sf-composer compact" onSubmit={create}><div className="sf-composer-row"><Avatar user={me}/><textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="شن في بالك؟" maxLength={3000}/></div>{image&&<div className="sf-image-preview"><img src={image} alt="معاينة"/><button type="button" onClick={()=>setImage("")}>×</button></div>}<div className="sf-composer-tools"><label><Icon name="image"/><span>{uploading?"جاري الرفع...":"صورة"}</span><input className="sf-file-input" type="file" accept="image/*" hidden disabled={uploading||submitting} onChange={e=>{const f=e.target.files?.[0];e.target.value="";upload(f)}}/></label><button type="submit" className="primary" disabled={!canPost||uploading||submitting}>{submitting?"ينشر...":"نشر"}</button></div></form>}{!home&&<div className="feed-tabs"><button type="button" className={mode==="all"?"active":""} onClick={()=>switchMode("all")}>الأحدث</button><button type="button" className={mode==="friends"?"active":""} onClick={()=>switchMode("friends")}>أصحابي</button></div>}{error&&<div className="sf-alert" onClick={()=>setError("")}>{error}</div>}{loading?<div className="feed-skeleton-list"><div/><div/><div/></div>:posts.length?posts.map(p=><PostCard key={p.id} post={p} me={me} autoOpen={Number(p.id)===focusId} onError={setError} onRemoved={pid=>setPosts(a=>a.filter(x=>x.id!==pid))} onChanged={next=>setPosts(a=>a.map(x=>x.id===next.id?next:x))}/>):<div className="sf-empty"><Icon name="sparkles"/><h2>ما فيش منشورات توا</h2><p>كن أول واحد ينشر في مربوعة.</p></div>}{cursor&&<button className="sf-more" onClick={loadMore} disabled={more}>{more?"جاري التحميل...":"عرض المزيد"}</button>}</section></div></main>
}
