"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import Link from "next/link";
import Icon from "./Icon";
import {uploadMedia} from "./imageTools";

const token=()=>localStorage.getItem("marbo3a_token")||sessionStorage.getItem("marbo3a_token")||"";
async function api(path,options={}){const t=token(),headers={...(options.headers||{})};if(t&&t!=="cookie")headers.authorization=`Bearer ${t}`;if(options.body&&!(options.body instanceof FormData))headers["content-type"]="application/json";const r=await fetch(path,{...options,headers,credentials:"same-origin",cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"REQUEST_FAILED");return d}
const human=e=>({STORIES_LOAD_FAILED:"تعذر تحميل الستوريات",STORY_CREATE_FAILED:"تعذر نشر الستوري",FILE_TOO_LARGE:"الفيديو أكبر من الحد المسموح",UNSUPPORTED_FILE:"نوع الملف غير مدعوم",UPLOAD_FAILED:"تعذر رفع الملف",STORY_NOT_FOUND:"الستوري انتهت أو لم تعد موجودة"}[e?.message]||"صار خطأ. حاول مرة ثانية.");
const STILL_MS=6500;
const filters={normal:"عادي",warm:"دافئ",cool:"بارد",mono:"أبيض وأسود"};

export default function StoryRail({me,onStatus}){
 const[stories,setStories]=useState([]),[viewerId,setViewerId]=useState(null),[activeGroup,setActiveGroup]=useState(-1),[activeIndex,setActiveIndex]=useState(0),[createOpen,setCreateOpen]=useState(false),[kind,setKind]=useState("text"),[text,setText]=useState(""),[privacy,setPrivacy]=useState("friends"),[media,setMedia]=useState(null),[uploading,setUploading]=useState(false),[publishing,setPublishing]=useState(false),[viewers,setViewers]=useState(null),[progress,setProgress]=useState(0),[filterName,setFilterName]=useState("normal"),[overlay,setOverlay]=useState({x:50,y:78});
 const swipe=useRef(null),previewRef=useRef(null),dragging=useRef(false);
 async function load(){try{const d=await api("/api/stories");setStories(d.stories||[]);setViewerId(d.viewerId||null)}catch(e){onStatus?.(human(e))}}
 useEffect(()=>{if(token())load()},[]);
 const groups=useMemo(()=>{const m=new Map();for(const s of stories){const key=String(s.user_id);if(!m.has(key))m.set(key,{user_id:s.user_id,username:s.username,display_name:s.display_name,avatar_url:s.avatar_url,items:[]});m.get(key).items.push(s)}return[...m.values()].map(g=>({...g,unseen:g.items.some(x=>!x.seen&&String(x.user_id)!==String(viewerId))}))},[stories,viewerId]);
 const active=activeGroup>=0?groups[activeGroup]?.items?.[activeIndex]:null;
 useEffect(()=>{if(!active&&!createOpen)return;const body=document.body,html=document.documentElement,scrollY=window.scrollY;const prev={bodyOverflow:body.style.overflow,bodyPosition:body.style.position,bodyTop:body.style.top,bodyWidth:body.style.width,htmlOverscroll:html.style.overscrollBehavior};body.classList.add("story-overlay-open");body.style.overflow="hidden";body.style.position="fixed";body.style.top=`-${scrollY}px`;body.style.width="100%";html.style.overscrollBehavior="none";return()=>{body.classList.remove("story-overlay-open");body.style.overflow=prev.bodyOverflow;body.style.position=prev.bodyPosition;body.style.top=prev.bodyTop;body.style.width=prev.bodyWidth;html.style.overscrollBehavior=prev.htmlOverscroll;window.scrollTo(0,scrollY)}},[Boolean(active),createOpen]);
 async function markSeen(story){if(!story||String(story.user_id)===String(viewerId)||story.seen)return;setStories(list=>list.map(x=>String(x.id)===String(story.id)?{...x,seen:true}:x));api(`/api/stories/${story.id}/view`,{method:"POST"}).catch(()=>{})}
 function openGroup(index,start=0){setActiveGroup(index);setActiveIndex(start);setViewers(null);setProgress(0);markSeen(groups[index]?.items?.[start])}
 function closeViewer(){setActiveGroup(-1);setActiveIndex(0);setViewers(null);setProgress(0)}
 function step(delta){if(viewers!==null)return;const g=groups[activeGroup];if(!g)return closeViewer();const next=activeIndex+delta;if(next>=0&&next<g.items.length){setActiveIndex(next);setViewers(null);setProgress(0);markSeen(g.items[next]);return}const ng=activeGroup+delta;if(ng>=0&&ng<groups.length){const ni=delta>0?0:groups[ng].items.length-1;setActiveGroup(ng);setActiveIndex(ni);setViewers(null);setProgress(0);markSeen(groups[ng].items[ni]);return}closeViewer()}
 useEffect(()=>{if(!active||active.kind==="video"||viewers!==null)return;setProgress(0);const started=performance.now();let raf=0;const tick=now=>{const p=Math.min(1,(now-started)/STILL_MS);setProgress(p);if(p>=1){step(1);return}raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf)},[active?.id,viewers]);
 async function upload(file){if(!file)return;setUploading(true);try{if(file.type.startsWith("video/")){if(file.size>12*1024*1024)throw new Error("FILE_TOO_LARGE");const fd=new FormData();fd.append("file",file,file.name||"story-video");const headers={},t=token();if(t&&t!=="cookie")headers.authorization=`Bearer ${t}`;const r=await fetch("/api/uploads/video",{method:"POST",headers,body:fd,credentials:"same-origin"}),d=await r.json().catch(()=>({}));if(!r.ok||!d.file?.url)throw new Error(d.error||"UPLOAD_FAILED");setMedia(d.file);setKind("video")}else{const d=await uploadMedia(file,token(),{compress:true});if(!d.file?.url)throw new Error("UPLOAD_FAILED");setMedia(d.file);setKind("image")}}catch(e){onStatus?.(human(e));setMedia(null)}finally{setUploading(false)}}
 async function publish(){if(publishing||uploading)return;if(kind==="text"&&!text.trim())return onStatus?.("اكتب حاجة في الستوري أولًا");if(kind!=="text"&&!media?.url)return onStatus?.("اختار صورة أو فيديو أولًا");setPublishing(true);try{await api("/api/stories",{method:"POST",body:JSON.stringify({kind,text:text.trim(),mediaUrl:media?.url||null,mediaType:media?.type||null,privacy,filterName,overlayX:overlay.x,overlayY:overlay.y})});setText("");setMedia(null);setKind("text");setFilterName("normal");setOverlay({x:50,y:78});setCreateOpen(false);await load();onStatus?.("تم نشر الستوري · تختفي بعد 24 ساعة")}catch(e){onStatus?.(human(e))}finally{setPublishing(false)}}
 async function remove(){if(!active)return;try{await api(`/api/stories/${active.id}`,{method:"DELETE"});closeViewer();await load();onStatus?.("تم حذف الستوري")}catch(e){onStatus?.(human(e))}}
 async function loadViewers(){if(!active||String(active.user_id)!==String(viewerId))return;try{const d=await api(`/api/stories/${active.id}/viewers`);setViewers(Array.isArray(d.viewers)?d.viewers:[])}catch(e){onStatus?.(human(e))}}
 function beginSwipe(e){if(viewers!==null)return;swipe.current={x:e.clientX,y:e.clientY,t:Date.now()}}
 function endSwipe(e){const s=swipe.current;swipe.current=null;if(!s||viewers!==null)return;const dx=e.clientX-s.x,dy=e.clientY-s.y;if(Date.now()-s.t>700||Math.abs(dx)<48||Math.abs(dx)<Math.abs(dy)*1.25)return;step(dx<0?1:-1)}
 function moveOverlay(e){if(!dragging.current||!previewRef.current)return;const r=previewRef.current.getBoundingClientRect(),x=Math.min(95,Math.max(5,((e.clientX-r.left)/r.width)*100)),y=Math.min(90,Math.max(10,((e.clientY-r.top)/r.height)*100));setOverlay({x,y})}
 return <>
  <section className="story-rail" aria-label="الستوريات">
   <button type="button" className="story-add" onClick={()=>setCreateOpen(true)}><span className="story-avatar-wrap"><span className="story-avatar story-add-avatar">{me?.avatar_url?<img src={me.avatar_url} alt=""/>:<b>{me?.display_name?.[0]||"م"}</b>}<i><Icon name="plus"/></i></span></span><small>ستوري جديدة</small></button>
   {groups.map((g,i)=><button type="button" className={`story-person ${g.unseen?"unseen":"seen"}`} key={g.user_id} onClick={()=>openGroup(i,0)}><span className="story-avatar-wrap"><span className="story-avatar">{g.avatar_url?<img src={g.avatar_url} alt=""/>:<b>{g.display_name?.[0]||"م"}</b>}</span></span><small>{String(g.user_id)===String(viewerId)?"ستوريك":g.display_name}</small></button>)}
   {!groups.length&&<div className="story-empty"><Icon name="sparkles"/><span>الستوريات الجديدة بتظهر هنا</span></div>}
  </section>
  {createOpen&&<div className="story-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setCreateOpen(false)}><section className="story-create-card" role="dialog" aria-modal="true"><header><div><small>مربوعة Stories</small><h3>ستوري جديدة</h3></div><button type="button" onClick={()=>setCreateOpen(false)} aria-label="إغلاق"><Icon name="close"/></button></header><div className="story-kind-tabs"><button type="button" className={kind==="text"?"active":""} onClick={()=>{setKind("text");setMedia(null)}}>نص</button><label className={kind==="image"?"active":""}>صورة<input type="file" accept="image/*" hidden onChange={e=>{upload(e.target.files?.[0]);e.target.value=""}}/></label><label className={kind==="video"?"active":""}>فيديو<input type="file" accept="video/mp4,video/webm,video/quicktime" hidden onChange={e=>{upload(e.target.files?.[0]);e.target.value=""}}/></label></div><div ref={previewRef} className={`story-create-preview kind-${kind} filter-${filterName}`} onPointerMove={moveOverlay} onPointerUp={()=>{dragging.current=false}} onPointerCancel={()=>{dragging.current=false}}>{kind==="text"?<textarea value={text} onChange={e=>setText(e.target.value)} maxLength={600} placeholder="شن تبي تحكي اليوم؟"/>:uploading?<div className="story-uploading">جاري تجهيز الملف...</div>:media?(kind==="video"?<video src={media.url} controls playsInline/>:<img src={media.url} alt="معاينة الستوري"/>):<div className="story-uploading">اختار {kind==="video"?"فيديو":"صورة"}</div>}{kind!=="text"&&text&&<button type="button" className="story-overlay-edit" style={{left:`${overlay.x}%`,top:`${overlay.y}%`}} onPointerDown={e=>{e.preventDefault();dragging.current=true;e.currentTarget.setPointerCapture?.(e.pointerId)}}>{text}</button>}{kind!=="text"&&<input className="story-caption-input" value={text} onChange={e=>setText(e.target.value)} maxLength={160} placeholder="اكتب نصًا فوق الستوري..."/>}</div>{kind!=="text"&&<div className="story-filter-row" aria-label="فلاتر الستوري">{Object.entries(filters).map(([value,label])=><button type="button" key={value} className={filterName===value?"active":""} onClick={()=>setFilterName(value)}>{label}</button>)}</div>}<div className="story-create-foot"><label>من يشوفها؟<select value={privacy} onChange={e=>setPrivacy(e.target.value)}><option value="friends">الأصدقاء</option><option value="everyone">الجميع</option></select></label><button type="button" className="story-publish" disabled={publishing||uploading} onClick={publish}>{publishing?"ينشر...":"نشر لمدة 24 ساعة"}</button></div></section></div>}
  {active&&<div className={`story-viewer ${viewers!==null?"viewers-open":""}`} role="dialog" aria-modal="true" aria-label="عارض الستوري" onPointerDown={beginSwipe} onPointerUp={endSwipe}><div className="story-progress">{groups[activeGroup].items.map((x,i)=><i key={x.id}><span style={{transform:`scaleX(${i<activeIndex?1:i===activeIndex?progress:0})`}}/></i>)}</div><header><div className="story-viewer-user">{active.avatar_url?<img src={active.avatar_url} alt=""/>:<span>{active.display_name?.[0]||"م"}</span>}<div><b>{active.display_name}</b><small>@{active.username} · {Math.max(0,Math.ceil((new Date(active.expires_at)-Date.now())/3600000))} س متبقية</small></div></div><button type="button" onClick={closeViewer} aria-label="إغلاق"><Icon name="close"/></button></header><div className={`story-stage kind-${active.kind} filter-${active.filter_name||"normal"}`}>{active.kind==="image"?<img src={active.media_url} alt="ستوري"/>:active.kind==="video"?<video key={active.id} src={active.media_url} autoPlay playsInline onLoadedData={()=>setProgress(0)} onTimeUpdate={e=>{const v=e.currentTarget;if(v.duration>0)setProgress(Math.min(1,v.currentTime/v.duration))}} onEnded={()=>step(1)}/>:<p>{active.text_body}</p>}{active.kind!=="text"&&active.text_body&&<div className="story-stage-caption" style={{left:`${Number(active.overlay_x)||50}%`,top:`${Number(active.overlay_y)||78}%`}}>{active.text_body}</div>}</div><button className="story-nav prev" type="button" onClick={()=>step(-1)} aria-label="السابق"/><button className="story-nav next" type="button" onClick={()=>step(1)} aria-label="التالي"/>{String(active.user_id)===String(viewerId)&&<footer className="story-owner-tools"><button type="button" className="story-viewers-trigger" onClick={loadViewers}><Icon name="eye"/> {active.views_count||0} مشاهدة</button><button type="button" className="danger" onClick={remove}><Icon name="trash"/> حذف</button></footer>}{viewers!==null&&<aside className="story-viewers-panel" aria-label="قائمة المشاهدين" onPointerDown={e=>e.stopPropagation()} onPointerUp={e=>e.stopPropagation()}><header><b>المشاهدون</b><button type="button" onClick={()=>setViewers(null)} aria-label="إغلاق قائمة المشاهدين"><Icon name="close"/></button></header><div className="story-viewers-list">{viewers.map(v=><Link key={v.viewer_id} href={`/u/${v.username}`}>{v.avatar_url?<img src={v.avatar_url} alt=""/>:<span>{v.display_name?.[0]||"م"}</span>}<div><b>{v.display_name}</b><small>@{v.username}</small></div></Link>)}{!viewers.length&&<p>ما حد شاف الستوري حتى الآن.</p>}</div></aside>}</div>}
 </>;
}
