"use client";

export default function UiRoundFixes(){
  return <style jsx global>{`
    /* Home room rail */
    .ui-v3 .public-room-track{gap:10px!important;padding:2px 2px 6px!important;scroll-snap-type:x proximity!important}
    .ui-v3 .public-room-card{flex:0 0 min(252px,74vw)!important;width:min(252px,74vw)!important;min-width:0!important;border-radius:16px!important;overflow:hidden!important;scroll-snap-align:start!important;background:var(--ui-surface,#111821)!important;border:1px solid var(--ui-border,rgba(255,255,255,.1))!important}
    .ui-v3 .public-room-cover{min-height:112px!important;height:112px!important;padding:10px!important;display:flex!important;align-items:flex-end!important;border-radius:15px 15px 0 0!important;background-color:var(--ui-surface-2,#171e28)!important;background-size:cover!important;background-position:center!important;position:relative!important;overflow:hidden!important}
    .ui-v3 .public-room-cover>img{position:absolute!important;inset:18px auto auto 50%!important;transform:translateX(-50%)!important;width:48px!important;height:48px!important;object-fit:contain!important;opacity:.78!important}
    .ui-v3 .public-room-cover>div{position:relative!important;z-index:2!important;min-width:0!important}.ui-v3 .public-room-cover h3{margin:0!important;font-size:14px!important;line-height:1.25!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}.ui-v3 .public-room-cover p{margin:3px 0 0!important;font-size:10px!important;line-height:1.35!important;color:var(--ui-text-2,#b8c0cb)!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}
    .ui-v3 .public-room-card-meta{padding:8px 9px 5px!important;display:grid!important;grid-template-columns:1fr 1fr!important;gap:5px!important}.ui-v3 .public-room-card-meta span{font-size:9px!important;display:flex!important;align-items:center!important;gap:4px!important;color:var(--ui-muted,#8f99a7)!important}.ui-v3 .public-room-card-meta span:last-child{grid-column:1/-1!important}.ui-v3 .public-room-card-meta svg{width:14px!important;height:14px!important}
    .ui-v3 .public-room-enter{height:38px!important;min-height:38px!important;margin:5px 8px 8px!important;width:calc(100% - 16px)!important;border-radius:11px!important;font-size:11px!important;font-weight:850!important}
    .ui-v3 .public-room-rail>header{margin-bottom:6px!important}.ui-v3 .public-room-rail>header h2{font-size:22px!important;line-height:1.2!important}.ui-v3 .public-room-rail>header small{font-size:10px!important}

    /* Feed ordering */
    .ui-v3 .smart-feed-strip{display:none!important}
    .ui-v3 .feed-mode-tabs{display:flex!important;gap:7px!important;overflow-x:auto!important;overscroll-behavior-inline:contain!important;scrollbar-width:none!important;padding:6px 0 9px!important;margin:0!important}
    .ui-v3 .feed-mode-tabs::-webkit-scrollbar{display:none!important}
    .ui-v3 .feed-mode-tabs button{order:initial!important;flex:0 0 auto!important;min-height:38px!important;height:38px!important;padding:0 13px!important;border-radius:999px!important;font-size:11px!important;font-weight:800!important;background:var(--ui-surface,#111821)!important;border:1px solid var(--ui-border,rgba(255,255,255,.1))!important;color:var(--ui-text-2,#c0c7d1)!important}
    .ui-v3 .feed-mode-tabs button.active{background:var(--ui-accent-soft,rgba(255,122,0,.12))!important;border-color:rgba(255,122,0,.55)!important;color:var(--ui-accent-2,#ff9b43)!important}
    .ui-v3 .feed-more-button{width:100%!important;min-height:44px!important;margin:10px 0 calc(var(--app-safe-bottom,78px) + 8px)!important;border-radius:14px!important;border:1px solid rgba(255,122,0,.42)!important;background:linear-gradient(105deg,rgba(255,122,0,.18),rgba(255,122,0,.08))!important;color:var(--ui-accent-2,#ff9b43)!important;font-size:12px!important;font-weight:850!important;box-shadow:none!important}
    .ui-v3 .feed-more-button:disabled{opacity:.55!important;color:var(--ui-muted,#8f99a7)!important;background:var(--ui-surface-2,#171e28)!important;border-color:var(--ui-border,rgba(255,255,255,.1))!important}

    /* Comments: replies are compact inline rows, not large chat bubbles. */
    .ui-v3 .sf-comment-replies{margin:5px 34px 2px 0!important;padding:0 9px 0 0!important;border-inline-start:2px solid color-mix(in srgb,var(--ui-accent,#ff7a00) 20%,transparent)!important;display:grid!important;gap:3px!important}
    .ui-v3 .sf-comment-thread.depth-1{margin:0!important;padding:0!important}.ui-v3 .sf-comment-thread.depth-1>.sf-comment{background:transparent!important;border:0!important;border-radius:0!important;box-shadow:none!important;padding:5px 0!important;gap:7px!important;min-height:0!important}
    .ui-v3 .sf-comment-thread.depth-1 .sf-comment-body{background:transparent!important;border:0!important;padding:0!important;min-width:0!important}.ui-v3 .sf-comment-thread.depth-1 .sf-comment-head b{font-size:11px!important}.ui-v3 .sf-comment-thread.depth-1 .sf-meta-line{font-size:8.5px!important}.ui-v3 .sf-comment-thread.depth-1 .sf-comment-body>p{font-size:11px!important;line-height:1.55!important;margin:2px 0!important}.ui-v3 .sf-comment-thread.depth-1 .comment-engagement{gap:10px!important;margin-top:1px!important}.ui-v3 .sf-comment-thread.depth-1 .comment-engagement button,.ui-v3 .sf-comment-thread.depth-1 .comment-engagement span{font-size:9px!important;min-height:24px!important;padding:0 2px!important;background:transparent!important;border:0!important}
    .ui-v3 .sf-comment-preview .comment-engagement{display:flex!important}.ui-v3 .comment-reply-form{margin-top:6px!important;min-height:38px!important}

    /* Suggestions after a few posts */
    .ui-v3 .feed-friend-suggestions{margin:12px 0!important;padding:12px!important;border:1px solid var(--ui-border,rgba(255,255,255,.1))!important;border-radius:18px!important;background:linear-gradient(130deg,var(--ui-surface,#111821),color-mix(in srgb,var(--ui-accent,#ff7a00) 7%,var(--ui-surface,#111821)))!important;overflow:hidden!important}
    .ui-v3 .feed-friend-suggestions>header{margin-bottom:10px!important}.ui-v3 .feed-friend-suggestions>header>div{display:flex!important;gap:8px!important;align-items:center!important}.ui-v3 .feed-friend-suggestions>header svg{color:var(--ui-accent,#ff7a00)!important}.ui-v3 .feed-friend-suggestions>header span{display:grid!important}.ui-v3 .feed-friend-suggestions>header b{font-size:14px!important}.ui-v3 .feed-friend-suggestions>header small{font-size:9px!important;color:var(--ui-muted,#8f99a7)!important}
    .ui-v3 .feed-friend-suggestions-track{display:flex!important;gap:9px!important;overflow-x:auto!important;scroll-snap-type:x proximity!important;scrollbar-width:none!important;padding-bottom:3px!important}.ui-v3 .feed-friend-suggestions-track::-webkit-scrollbar{display:none!important}.ui-v3 .feed-friend-suggestions-track article{flex:0 0 132px!important;scroll-snap-align:start!important;background:var(--ui-surface-2,#171e28)!important;border:1px solid var(--ui-border,rgba(255,255,255,.08))!important;border-radius:15px!important;padding:10px 8px!important;text-align:center!important}.ui-v3 .feed-friend-suggestions-track article>a{display:grid!important;justify-items:center!important;gap:4px!important;color:inherit!important;text-decoration:none!important}.ui-v3 .feed-friend-suggestions-track article>a>b{font-size:11px!important;max-width:112px!important;overflow:hidden!important;text-overflow:ellipsis!important;white-space:nowrap!important}.ui-v3 .feed-friend-suggestions-track article>a>small{font-size:8px!important;color:var(--ui-muted,#8f99a7)!important}.ui-v3 .friend-suggestion-meta{display:grid!important;min-height:28px!important;margin:5px 0!important;font-size:8px!important;color:var(--ui-muted,#8f99a7)!important}.ui-v3 .feed-friend-suggestions-track article>button{width:100%!important;height:32px!important;border-radius:10px!important;background:var(--ui-accent,#ff7a00)!important;color:#fff!important;border:0!important;font-size:10px!important;font-weight:800!important}
    .ui-v3 .feed-pinned-ribbon{display:flex!important;align-items:center!important;gap:5px!important;padding:7px 12px!important;color:var(--ui-accent-2,#ff9b43)!important;font-size:10px!important;border-bottom:1px solid rgba(255,122,0,.18)!important}.ui-v3 .sf-post-pinned{border-color:rgba(255,122,0,.38)!important}

    /* Profiles */
    .ui-v3 .profile-v3-route .sf-profile-card{max-width:100%!important}.ui-v3 .profile-v3-route .sf-cover{min-height:150px!important;height:150px!important}.ui-v3 .profile-v3-route .sf-profile-body{padding:0 18px 16px!important}.ui-v3 .profile-v3-route .sf-profile-avatar{margin-top:-46px!important}.ui-v3 .profile-v3-route .sf-profile-main h1{font-size:26px!important;line-height:1.2!important}.ui-v3 .profile-v3-route .profile-meta-v3{gap:7px!important;flex-wrap:wrap!important}.ui-v3 .profile-v3-route .profile-meta-v3 span{font-size:10px!important}.ui-v3 .profile-v3-route .sf-profile-counts{margin-top:12px!important;padding:12px 0!important}.ui-v3 .profile-v3-route .sf-profile-actions{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:8px!important}.ui-v3 .profile-v3-route .sf-profile-actions>.sf-primary{grid-column:1/-1!important}.ui-v3 .profile-v3-route .profile-pin-action{display:none!important}.ui-v3 .profile-v3-route .profile-tabs-v3{overflow-x:auto!important;scrollbar-width:none!important}.ui-v3 .profile-v3-route .profile-tabs-v3::-webkit-scrollbar{display:none!important}

    /* Single close dialog action */
    .ui-v3 .app-dialog footer.single-action{grid-template-columns:1fr!important;display:grid!important}.ui-v3 .app-dialog footer.single-action>button{width:100%!important;min-width:0!important}

    /* Story controls */
    .ui-v3 .story-viewer-head-actions{display:flex!important;gap:6px!important;align-items:center!important}.ui-v3 .story-viewer-head-actions button{width:38px!important;height:38px!important;border-radius:12px!important}.ui-v3 .story-owner-tools,.ui-v3 .story-social-tools{padding-bottom:max(14px,env(safe-area-inset-bottom))!important}.ui-v3 .story-muted-manage{flex:0 0 auto!important;background:transparent!important;border:0!important;color:var(--ui-muted,#8f99a7)!important;display:grid!important;justify-items:center!important;gap:4px!important}.ui-v3 .story-muted-manage>span{width:54px!important;height:54px!important;border-radius:50%!important;border:1px dashed var(--ui-border,rgba(255,255,255,.14))!important;display:grid!important;place-items:center!important;background:var(--ui-surface,#111821)!important}.ui-v3 .story-muted-manage small{font-size:9px!important}.ui-v3 .story-muted-card{width:min(92vw,460px)!important;max-height:78dvh!important;overflow:auto!important;background:var(--ui-surface,#111821)!important;border:1px solid var(--ui-border,rgba(255,255,255,.12))!important;border-radius:20px!important;padding:16px!important}.ui-v3 .story-muted-card>header{display:flex!important;justify-content:space-between!important;align-items:center!important;margin-bottom:12px!important}.ui-v3 .story-muted-list{display:grid!important;gap:8px!important}.ui-v3 .story-muted-list article{display:grid!important;grid-template-columns:42px 1fr auto!important;align-items:center!important;gap:9px!important;padding:9px!important;background:var(--ui-surface-2,#171e28)!important;border-radius:13px!important}.ui-v3 .story-muted-list article>img,.ui-v3 .story-muted-list article>span{width:42px!important;height:42px!important;border-radius:50%!important;object-fit:cover!important;display:grid!important;place-items:center!important}.ui-v3 .story-muted-list article>div{display:grid!important}.ui-v3 .story-muted-list article small{font-size:9px!important;color:var(--ui-muted,#8f99a7)!important}.ui-v3 .story-muted-list article>button{height:34px!important;border-radius:10px!important;padding:0 9px!important;background:rgba(255,122,0,.12)!important;border:1px solid rgba(255,122,0,.35)!important;color:var(--ui-accent-2,#ff9b43)!important;font-size:9px!important}

    /* Room: fixed upper experience + independently scrolling chat */
    .ui-v3 .room-community-page{height:calc(100dvh - var(--app-header-height,72px) - 76px)!important;overflow:hidden!important;padding-bottom:0!important}.ui-v3 .room-community-shell{height:100%!important;max-height:100%!important;display:flex!important;flex-direction:column!important;overflow:hidden!important}.ui-v3 .room-community-head,.ui-v3 .room-live-card,.ui-v3 .room-community-tools,.ui-v3 .room-featured-pin,.ui-v3 .room-community-status,.ui-v3 .room-community-typing,.ui-v3 .room-community-replying,.ui-v3 .room-community-compose{flex:0 0 auto!important}.ui-v3 .room-community-stream{flex:1 1 auto!important;min-height:150px!important;overflow-y:auto!important;overscroll-behavior:contain!important;scrollbar-gutter:stable!important}.ui-v3 .room-leave-action{display:inline-flex!important;align-items:center!important;gap:5px!important;height:38px!important;padding:0 10px!important;border-radius:11px!important;border:1px solid rgba(239,68,68,.35)!important;background:rgba(239,68,68,.08)!important;color:#ef7070!important;font-size:10px!important;font-weight:800!important}.ui-v3 .room-leave-status{position:absolute!important;top:100%!important;inset-inline-end:0!important;width:min(260px,75vw)!important;background:var(--ui-surface-2,#171e28)!important;padding:7px!important;border-radius:9px!important;font-size:9px!important;z-index:10!important}.ui-v3 .room-system-events{display:grid!important;gap:5px!important;margin:8px 0!important}.ui-v3 .room-system-event{align-self:center!important;justify-self:center!important;display:flex!important;gap:6px!important;align-items:center!important;padding:5px 9px!important;border-radius:999px!important;background:rgba(255,122,0,.08)!important;color:var(--ui-muted,#8f99a7)!important;font-size:9px!important}.ui-v3 .room-system-event small{font-size:8px!important;opacity:.75!important}

    /* Install prompt and live notification cards */
    .install-nudge,.live-notification-toast{position:fixed!important;top:max(14px,env(safe-area-inset-top))!important;left:50%!important;transform:translateX(-50%)!important;width:min(92vw,520px)!important;z-index:2147482500!important;border:1px solid rgba(255,255,255,.12)!important;border-radius:18px!important;background:rgba(21,27,36,.97)!important;color:#fff!important;box-shadow:0 18px 50px rgba(0,0,0,.38)!important;backdrop-filter:blur(18px)!important;-webkit-backdrop-filter:blur(18px)!important}
    .install-nudge{display:grid!important;grid-template-columns:48px 1fr auto 28px!important;gap:9px!important;align-items:center!important;padding:10px!important;touch-action:pan-y!important}.install-nudge>img{width:46px!important;height:46px!important;object-fit:contain!important}.install-nudge>div{display:grid!important;min-width:0!important}.install-nudge>div>b{font-size:13px!important}.install-nudge>div>span{font-size:9px!important;color:#aeb7c4!important}.install-nudge>button:not(.install-nudge-close){height:36px!important;padding:0 14px!important;border:0!important;border-radius:11px!important;background:#ff7a00!important;color:white!important;font-weight:850!important}.install-nudge-close{background:transparent!important;border:0!important;color:#aeb7c4!important;padding:4px!important}
    .live-notification-toast{display:grid!important;grid-template-columns:38px 1fr auto!important;gap:9px!important;align-items:center!important;padding:10px 12px!important;text-align:start!important;cursor:pointer!important;animation:marbo3a-toast-in .24s ease-out!important}.live-notification-icon{width:38px!important;height:38px!important;border-radius:12px!important;display:grid!important;place-items:center!important;background:rgba(255,122,0,.13)!important;color:#ff8a25!important}.live-notification-toast>div{display:grid!important;min-width:0!important}.live-notification-toast>div>b{font-size:12px!important}.live-notification-toast>div>span{font-size:9.5px!important;color:#aeb7c4!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}.live-notification-toast>img{width:36px!important;height:36px!important;border-radius:50%!important;object-fit:cover!important}@keyframes marbo3a-toast-in{from{opacity:0;transform:translate(-50%,-14px)}to{opacity:1;transform:translate(-50%,0)}}

    /* Map */
    .ui-v3 .real-map-canvas{direction:ltr!important;isolation:isolate!important;background:#dfe5e8!important}.ui-v3 .real-map-tiles img{direction:ltr!important;image-rendering:auto!important}.ui-v3 .real-map-controls{inset-inline-start:12px!important;inset-inline-end:auto!important;top:12px!important;gap:7px!important}.ui-v3 .real-map-controls button{width:42px!important;height:42px!important;min-width:42px!important;min-height:42px!important;border-radius:12px!important}.ui-v3 .real-map-attribution{font-size:8px!important;direction:ltr!important;background:rgba(255,255,255,.82)!important;color:#26313a!important;padding:2px 5px!important;border-radius:6px 0 0 0!important}

    @media(max-width:430px){.ui-v3 .public-room-card{flex-basis:min(238px,72vw)!important;width:min(238px,72vw)!important}.ui-v3 .public-room-cover{height:106px!important;min-height:106px!important}.ui-v3 .public-room-rail>header h2{font-size:20px!important}.ui-v3 .feed-mode-tabs button{height:36px!important;min-height:36px!important;padding-inline:12px!important;font-size:10.5px!important}.ui-v3 .profile-v3-route .sf-cover{height:132px!important;min-height:132px!important}.ui-v3 .profile-v3-route .sf-profile-main h1{font-size:23px!important}.ui-v3 .room-live-card{max-height:180px!important;overflow:auto!important}.install-nudge{grid-template-columns:42px 1fr auto 24px!important}.install-nudge>img{width:40px!important;height:40px!important}}
  `}</style>;
}
