"use client";
import {useEffect,useRef,useState} from "react";
import Icon from "./Icon";
const MAX_SECONDS=120,fmt=s=>`${Math.floor(s/60)}:${String(s%60).padStart(2,"0")}`;
const trace=(type,data={})=>{try{window.dispatchEvent(new CustomEvent("marbo3a:media-debug",{detail:{type,...data}}))}catch{}};
function supportedType(){if(typeof MediaRecorder==="undefined")return"";const safari=/Safari/i.test(navigator.userAgent)&&!/Chrome|CriOS|Android/i.test(navigator.userAgent),types=safari?["audio/mp4","audio/webm;codecs=opus","audio/webm","audio/ogg;codecs=opus"]:["audio/webm;codecs=opus","audio/ogg;codecs=opus","audio/webm","audio/mp4"];return types.find(t=>MediaRecorder.isTypeSupported?.(t))||""}
export default function VoiceRecorder({disabled=false,onRecorded,onError}){
 const[state,setState]=useState("idle"),[seconds,setSeconds]=useState(0);const recorder=useRef(null),stream=useRef(null),chunks=useRef([]),timer=useRef(null),cancelled=useRef(false),startedAt=useRef(0),elapsed=useRef(0),pointer=useRef(null),locked=useRef(false);
 const cleanup=()=>{clearInterval(timer.current);timer.current=null;stream.current?.getTracks?.().forEach(t=>t.stop());stream.current=null;recorder.current=null;pointer.current=null;locked.current=false};useEffect(()=>()=>cleanup(),[]);
 async function start(){if(disabled||state!=="idle")return;try{if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==="undefined")throw new Error("VOICE_UNSUPPORTED");const s=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});stream.current=s;chunks.current=[];cancelled.current=false;locked.current=false;startedAt.current=Date.now();elapsed.current=0;setSeconds(0);const type=supportedType(),r=new MediaRecorder(s,type?{mimeType:type}:undefined);recorder.current=r;r.ondataavailable=e=>{if(e.data?.size)chunks.current.push(e.data)};r.onerror=e=>{trace("voice_recorder_error",{name:e?.error?.name||"MediaRecorderError"});cleanup();setState("idle");onError?.("تعذر تسجيل المقطع الصوتي")};r.onstop=()=>{const wasCancelled=cancelled.current,ms=Math.max(elapsed.current,Date.now()-startedAt.current),duration=Math.max(1,Math.round(ms/1000)),mime=r.mimeType||type||"audio/webm",blob=new Blob(chunks.current,{type:mime}),ext=mime.includes("ogg")?"ogg":mime.includes("mp4")?"m4a":"webm";trace("voice_recorded",{mime,size:blob.size,duration,chunks:chunks.current.length,cancelled:wasCancelled});cleanup();setState("idle");if(wasCancelled||blob.size<700)return;onRecorded?.(new File([blob],`voice-${Date.now()}.${ext}`,{type:mime,lastModified:Date.now()}),duration)};r.start(300);setState("recording");trace("voice_recorder_start",{mime:type||r.mimeType||"default"});timer.current=setInterval(()=>{elapsed.current=Date.now()-startedAt.current;const sec=Math.min(MAX_SECONDS,Math.floor(elapsed.current/1000));setSeconds(sec);if(sec>=MAX_SECONDS)finish()},250)}catch(e){cleanup();setState("idle");trace("voice_recorder_error",{name:e?.name||"Error",message:e?.message||"VOICE_UNSUPPORTED"});onError?.(e?.name==="NotAllowedError"?"اسمح لمربوعة باستخدام المايكروفون":"التسجيل الصوتي غير مدعوم على هذا الجهاز")}}
 function finish(){const r=recorder.current;if(!r||r.state==="inactive")return;elapsed.current=Math.max(elapsed.current,Date.now()-startedAt.current);try{r.requestData?.()}catch{};setState("sending");setTimeout(()=>{try{if(r.state!=="inactive")r.stop()}catch{}},30)}
 function cancel(){cancelled.current=true;finish()}
 function lockRecording(el){if(state!=="recording")return;locked.current=true;pointer.current=null;try{el?.releasePointerCapture?.()}catch{}setState("locked");trace("voice_recorder_locked")}
 function down(e){if(disabled||state!=="idle")return;e.preventDefault();pointer.current={id:e.pointerId,x:e.clientX,y:e.clientY};e.currentTarget.setPointerCapture?.(e.pointerId);start()}
 function move(e){if(state!=="recording"||!pointer.current)return;const dx=e.clientX-pointer.current.x,dy=e.clientY-pointer.current.y;if(dy<-82){lockRecording(e.currentTarget);return}if(Math.abs(dx)>115&&Math.abs(dx)>Math.abs(dy)){cancelled.current=true;finish()}}
 function up(e){if(pointer.current&&e.pointerId!==pointer.current.id)return;e.preventDefault();if(state==="recording"&&!locked.current)finish()}
 if(state==="locked")return <div className="voice-record-panel locked" role="group" aria-label="جارٍ تسجيل رسالة صوتية"><button type="button" className="voice-cancel" onClick={cancel} aria-label="إلغاء التسجيل"><Icon name="close"/><span>إلغاء</span></button><div className="voice-record-time"><span className="voice-dot"/><b>{fmt(seconds)}</b><small>التسجيل مستمر</small></div><button type="button" className="voice-send" onClick={finish} aria-label="إرسال التسجيل"><Icon name="send"/><span>إرسال</span></button></div>;
 if(state==="recording")return <button type="button" className="voice-record-btn recording hold" onPointerUp={up} onPointerCancel={cancel} onPointerMove={move} aria-label="اترك الزر للإرسال، اسحب للأعلى لتثبيت التسجيل"><span className="voice-dot"/><b>{fmt(seconds)}</b><span className="voice-record-hint">اترك للإرسال · ↑ تثبيت · اسحب جانبًا للإلغاء</span></button>;
 if(state==="sending")return <button type="button" className="voice-record-btn recording" disabled aria-label="جاري تجهيز التسجيل"><span className="voice-dot"/><b>{fmt(seconds)}</b><span>جاري الإرسال...</span></button>;
 return <button type="button" className="voice-record-btn hold" onPointerDown={down} onKeyDown={e=>{if((e.key===" "||e.key==="Enter")&&!e.repeat)start()}} onKeyUp={e=>{if((e.key===" "||e.key==="Enter")&&state==="recording")finish()}} disabled={disabled} aria-label="اضغط مطولاً لتسجيل رسالة صوتية" title="اضغط مطولاً للتسجيل"><Icon name="mic"/></button>
}
