"use client";
import {useEffect,useRef,useState} from "react";
const fmt=s=>{const n=Math.max(0,Math.floor(Number(s)||0));return `${Math.floor(n/60)}:${String(n%60).padStart(2,"0")}`};
const trace=(type,data={})=>{try{window.dispatchEvent(new CustomEvent("marbo3a:media-debug",{detail:{type,...data}}))}catch{}};
export default function VoiceMessage({src}){
 const audio=useRef(null),probing=useRef(false),[playing,setPlaying]=useState(false),[time,setTime]=useState(0),[duration,setDuration]=useState(0),[rate,setRate]=useState(1),[error,setError]=useState(false);
 useEffect(()=>{setPlaying(false);setTime(0);setDuration(0);setError(false);probing.current=false},[src]);
 function validDuration(a){const d=Number(a?.duration);if(Number.isFinite(d)&&d>0){setDuration(d);trace("voice_metadata",{duration:Math.round(d*100)/100});return true}return false}
 function recoverDuration(a){if(!a||probing.current||validDuration(a))return;probing.current=true;const old=a.currentTime||0;const onTime=()=>{a.removeEventListener("timeupdate",onTime);const d=Number(a.duration);if(Number.isFinite(d)&&d>0)setDuration(d);try{a.currentTime=Math.min(old,Number.isFinite(d)?d:0)}catch{};probing.current=false;trace("voice_duration_recovered",{duration:Number.isFinite(d)?d:0})};a.addEventListener("timeupdate",onTime,{once:true});try{a.currentTime=1e101}catch{probing.current=false}}
 async function toggle(){const a=audio.current;if(!a)return;try{if(a.paused){await a.play();setError(false)}else a.pause()}catch(e){setError(true);trace("voice_playback_error",{name:e?.name||"Error",message:e?.message||"PLAY_FAILED"})}}
 function cycle(){const next=rate===1?1.5:rate===1.5?2:1;setRate(next);if(audio.current)audio.current.playbackRate=next}
 function seek(v){const a=audio.current;if(!a||!Number.isFinite(duration)||duration<=0)return;const n=Math.max(0,Math.min(duration,Number(v)||0));try{a.currentTime=n;setTime(n)}catch{}}
 return <div className={`voice-message ${error?"has-error":""}`}><audio ref={audio} src={src} preload="metadata" playsInline onLoadedMetadata={e=>{if(!validDuration(e.currentTarget))recoverDuration(e.currentTarget)}} onDurationChange={e=>validDuration(e.currentTarget)} onCanPlay={e=>{validDuration(e.currentTarget);trace("voice_canplay",{})}} onTimeUpdate={e=>{const t=e.currentTarget.currentTime||0;if(Number.isFinite(t))setTime(t);if(!duration)validDuration(e.currentTarget)}} onPlay={()=>{setPlaying(true);trace("voice_play",{})}} onPause={()=>setPlaying(false)} onEnded={()=>{setPlaying(false);setTime(duration||0);trace("voice_ended",{})}} onStalled={()=>trace("voice_stalled",{})} onError={e=>{setError(true);trace("voice_playback_error",{code:e.currentTarget.error?.code||0,message:e.currentTarget.error?.message||"MEDIA_ERROR"})}}/><button type="button" className="voice-play" onClick={toggle} aria-label={playing?"إيقاف":"تشغيل"}>{playing?"❚❚":"▶"}</button><div className="voice-progress"><input type="range" min="0" max={Math.max(duration,1)} step="0.1" value={Math.min(time,Math.max(duration,1))} disabled={!duration} onChange={e=>seek(e.target.value)}/><span>{fmt(time)} / {duration?fmt(duration):"--:--"}</span></div><button type="button" className="voice-rate" onClick={cycle}>{rate}×</button>{error&&<button type="button" className="voice-retry" onClick={toggle}>إعادة</button>}</div>
}
