"use client";
import {useEffect,useRef,useState} from "react";
import Icon from "./Icon";
const MAX_SECONDS=120,CANCEL_PX=70,fmt=s=>`${Math.floor(s/60)}:${String(s%60).padStart(2,"0")}`;
const trace=(type,data={})=>{try{window.dispatchEvent(new CustomEvent("marbo3a:media-debug",{detail:{type,...data}}))}catch{}};
const vibrate=ms=>{try{navigator.vibrate?.(ms)}catch{}};
function supportedType(){if(typeof MediaRecorder==="undefined")return"";const safari=/Safari/i.test(navigator.userAgent)&&!/Chrome|CriOS|Android/i.test(navigator.userAgent),types=safari?["audio/mp4","audio/webm;codecs=opus","audio/webm","audio/ogg;codecs=opus"]:["audio/webm;codecs=opus","audio/webm","audio/ogg;codecs=opus","audio/mp4"];return types.find(t=>MediaRecorder.isTypeSupported?.(t))||""}
export default function VoiceRecorder({disabled=false,onRecorded,onError}){
 const[state,setState]=useState("idle"),[seconds,setSeconds]=useState(0),[cancelHint,setCancelHint]=useState(false);const recorder=useRef(null),stream=useRef(null),chunks=useRef([]),timer=useRef(null),cancelled=useRef(false),startedAt=useRef(0),elapsed=useRef(0),pointer=useRef(null),pressEnded=useRef(false),starting=useRef(false);
 const cleanup=()=>{clearInterval(timer.current);timer.current=null;stream.current?.getTracks?.().forEach(t=>t.stop());stream.current=null;recorder.current=null;pointer.current=null;pressEnded.current=false;starting.current=false;setCancelHint(false)};useEffect(()=>()=>cleanup(),[]);
 function finish(send=true){if(!send)cancelled.current=true;const r=recorder.current;if(!r||r.state==="inactive")return;elapsed.current=Math.max(elapsed.current,Date.now()-startedAt.current);try{r.requestData?.()}catch{};setState(send?"sending":"cancelling");vibrate(send?18:[20,25,20]);setTimeout(()=>{try{if(r.state!=="inactive")r.stop()}catch{}},30)}
 function moveGlobal(e){const p=pointer.current;if(!p||e.pointerId!==p.id||pressEnded.current)return;const dy=e.clientY-p.y,armed=dy<-42;setCancelHint(armed);if(dy<-CANCEL_PX){cancelled.current=true;pressEnded.current=true;trace("voice_recorder_cancel_gesture",{distance:Math.round(Math.abs(dy))});if(recorder.current?.state==="recording")finish(false)}}
 function upGlobal(e){const p=pointer.current;if(!p||e.pointerId!==p.id||pressEnded.current)return;pressEnded.current=true;if(cancelled.current){if(recorder.current?.state==="recording")finish(false);return}if(recorder.current?.state==="recording")finish(true)}
 function cancelGlobal(e){const p=pointer.current;if(!p||e.pointerId!==p.id)return;cancelled.current=true;pressEnded.current=true;if(recorder.current?.state==="recording")finish(false)}
 useEffect(()=>{document.addEventListener("pointermove",moveGlobal,{passive:true});document.addEventListener("pointerup",upGlobal,{passive:true});document.addEventListener("pointercancel",cancelGlobal,{passive:true});return()=>{document.removeEventListener("pointermove",moveGlobal);document.removeEventListener("pointerup",upGlobal);document.removeEventListener("pointercancel",cancelGlobal)}},[]);
 async function start(){if(disabled||state!=="idle"||starting.current)return;starting.current=true;try{if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==="undefined")throw new Error("VOICE_UNSUPPORTED");const s=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});stream.current=s;chunks.current=[];startedAt.current=Date.now();elapsed.current=0;setSeconds(0);const type=supportedType(),r=new MediaRecorder(s,type?{mimeType:type}:undefined);recorder.current=r;r.ondataavailable=e=>{if(e.data?.size)chunks.current.push(e.data)};r.onerror=e=>{trace("voice_recorder_error",{name:e?.error?.name||"MediaRecorderError"});cleanup();setState("idle");onError?.("تعذر تسجيل المقطع الصوتي")};r.onstop=()=>{const wasCancelled=cancelled.current,ms=Math.max(elapsed.current,Date.now()-startedAt.current),duration=Math.max(1,Math.round(ms/1000)),mime=r.mimeType||type||"audio/webm",blob=new Blob(chunks.current,{type:mime}),ext=mime.includes("ogg")?"ogg":mime.includes("mp4")?"m4a":"webm";trace("voice_recorded",{mime,size:blob.size,duration,chunks:chunks.current.length,cancelled:wasCancelled});cleanup();setState("idle");cancelled.current=false;if(wasCancelled||blob.size<700)return;onRecorded?.(new File([blob],`voice-${Date.now()}.${ext}`,{type:mime,lastModified:Date.now()}),duration)};r.start(250);setState("recording");starting.current=false;vibrate(18);trace("voice_recorder_start",{mime:type||r.mimeType||"default"});timer.current=setInterval(()=>{elapsed.current=Date.now()-startedAt.current;const sec=Math.min(MAX_SECONDS,Math.floor(elapsed.current/1000));setSeconds(sec);if(sec>=MAX_SECONDS){pressEnded.current=true;finish(true)}},250);if(pressEnded.current){setTimeout(()=>finish(!cancelled.current),0)}}catch(e){cleanup();setState("idle");cancelled.current=false;trace("voice_recorder_error",{name:e?.name||"Error",message:e?.message||"VOICE_UNSUPPORTED"});onError?.(e?.name==="NotAllowedError"?"اسمح لمربوعة باستخدام المايكروفون":"التسجيل الصوتي غير مدعوم على هذا الجهاز")}}
 function down(e){if(disabled||state!=="idle")return;e.preventDefault();cancelled.current=false;pressEnded.current=false;setCancelHint(false);pointer.current={id:e.pointerId,x:e.clientX,y:e.clientY};start()}
 function keyboardStart(e){if((e.key===" "||e.key==="Enter")&&!e.repeat&&state==="idle"){e.preventDefault();cancelled.current=false;pressEnded.current=false;pointer.current={id:-1,x:0,y:0};start()}}
 function keyboardEnd(e){if((e.key===" "||e.key==="Enter")){e.preventDefault();pressEnded.current=true;if(recorder.current?.state==="recording")finish(true)}}
 if(state==="recording")return <div className={`voice-record-panel active ${cancelHint?"cancel-armed":""}`} style={{position:"absolute",inset:4,zIndex:5}} role="status" aria-live="polite"><div className="voice-record-time"><span className="voice-dot"/><b>{fmt(seconds)}</b><small>{cancelHint?"كمّل لفوق للإلغاء":"ارفع إصبعك للإرسال · اسحب لفوق للإلغاء"}</small></div></div>;
 if(state==="sending")return <button type="button" className="voice-record-btn recording" disabled aria-label="جاري تجهيز التسجيل"><span className="voice-dot"/><b>{fmt(seconds)}</b><span>جاري الإرسال...</span></button>;
 if(state==="cancelling")return <button type="button" className="voice-record-btn recording" disabled aria-label="تم إلغاء التسجيل"><span>تم الإلغاء</span></button>;
 return <button type="button" className="voice-record-btn hold" onPointerDown={down} onKeyDown={keyboardStart} onKeyUp={keyboardEnd} disabled={disabled} aria-label="اضغط باستمرار للتسجيل، ارفع للإرسال، اسحب لفوق للإلغاء" title="اضغط للتسجيل"><Icon name="mic"/></button>
}
