"use client";
import {useEffect,useState} from "react";
import Icon from "../../Icon";
const token=()=>typeof window!=="undefined"?(localStorage.getItem("marbo3a_token")||sessionStorage.getItem("marbo3a_token")||""):"";
async function api(path,options={}){const headers={authorization:`Bearer ${token()}`,...(options.headers||{})};if(options.body&&!headers["content-type"])headers["content-type"]="application/json";const r=await fetch(path,{...options,headers,cache:"no-store",credentials:"same-origin"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"REQUEST_FAILED");return d}
export default function AdminTv(){
 const[kind,setKind]=useState("m3u"),[baseUrl,setBaseUrl]=useState(""),[username,setUsername]=useState(""),[password,setPassword]=useState(""),[m3uUrl,setM3uUrl]=useState(""),[count,setCount]=useState(0),[status,setStatus]=useState(""),[busy,setBusy]=useState(false);
 async function load(){try{const d=await api("/api/admin/tv/source");if(d.source){setKind(d.source.kind||"m3u");setBaseUrl(d.source.base_url||"");setUsername(d.source.username||"");setM3uUrl(d.source.m3u_url||"")}setCount(Number(d.channels)||0)}catch(e){setStatus(e.message==="FORBIDDEN"?"الحساب هذا مش أدمن":"ما قدرناش نحمّلوا إعدادات التلفزيون")}}
 useEffect(()=>{load()},[]);
 async function save(e){e.preventDefault();if(busy)return;setBusy(true);setStatus("بنحفظوا الإعدادات...");try{await api("/api/admin/tv/source",{method:"PUT",body:JSON.stringify({kind,baseUrl,username,password,m3uUrl})});setPassword("");setStatus("تم الحفظ ✓");await load()}catch{setStatus("صار خطأ في الحفظ")}finally{setBusy(false)}}
 async function refresh(){if(busy)return;setBusy(true);setStatus("بنجيبوا القنوات من المصدر...");try{const d=await api("/api/admin/tv/refresh",{method:"POST"});setCount(Number(d.count)||0);setStatus(`تمام، لقينا ${d.count||0} قناة`)}catch(e){setStatus(e.message==="SOURCE_NOT_CONFIGURED"?"حط المصدر الأول":e.message==="NO_CHANNELS"?"المصدر ما رجّعش قنوات":"ما قدرناش نحدّثوا القنوات") }finally{setBusy(false)}}
 async function uploadFile(file){if(!file||busy)return;setBusy(true);setStatus("بنقرو الملف...");try{const content=await file.text();const d=await api("/api/admin/tv/import-m3u",{method:"POST",body:JSON.stringify({content})});setCount(Number(d.count)||0);setStatus(`تمام، ضفنا ${d.count||0} قناة من الملف`)}catch{setStatus("الملف ما فيهش قنوات صالحة أو صار خطأ") }finally{setBusy(false)}}
 return <main className="admin-tv-page" dir="rtl"><section className="admin-tv-shell"><header><div><span>مربوعة TV</span><h1>إدارة التلفزيون</h1><p>غيّر المصدر من هني، ويتحدّث عند الناس كلهم.</p></div><div className="admin-tv-count"><b>{count}</b><small>قناة</small></div></header>
 <form onSubmit={save} className="admin-tv-card"><h2>مصدر القنوات</h2><div className="admin-tv-kind"><button type="button" className={kind==="m3u"?"active":""} onClick={()=>setKind("m3u")}>M3U / M3U8</button><button type="button" className={kind==="xtream"?"active":""} onClick={()=>setKind("xtream")}>IPTV / Xtream</button></div>{kind==="m3u"?<label><span>رابط M3U</span><input dir="ltr" value={m3uUrl} onChange={e=>setM3uUrl(e.target.value)} placeholder="https://.../playlist.m3u"/></label>:<><label><span>السيرفر / IP</span><input dir="ltr" value={baseUrl} onChange={e=>setBaseUrl(e.target.value)} placeholder="http://server:port"/></label><label><span>اليوزر</span><input dir="ltr" value={username} onChange={e=>setUsername(e.target.value)}/></label><label><span>الباسورد</span><input dir="ltr" type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="اتركه فاضي لو ما تبيش تغيّره"/></label></>}<div className="admin-tv-actions"><button disabled={busy} className="primary"><Icon name="check"/> حفظ</button><button disabled={busy} type="button" onClick={refresh}><Icon name="refresh"/> تحديث القنوات</button></div></form>
 <section className="admin-tv-card"><h2>أو ارفع ملف M3U</h2><p>اختار الملف من جهازك، ومربوعة تستخرج القنوات واللوقوهات والتصنيفات.</p><label className="admin-tv-upload"><Icon name="install"/><span>اختار ملف M3U</span><input type="file" accept=".m3u,.m3u8,text/plain" onChange={e=>uploadFile(e.target.files?.[0])}/></label></section>{status&&<div className="admin-tv-status" role="status">{status}</div>}</section></main>
}
