"use client";
import {useEffect,useMemo,useState} from "react";
import Icon from "../../Icon";
const token=()=>typeof window!=="undefined"?(localStorage.getItem("marbo3a_token")||sessionStorage.getItem("marbo3a_token")||""):"";
async function api(path,options={}){const headers={authorization:`Bearer ${token()}`,...(options.headers||{})};if(options.body&&!headers["content-type"]&&typeof options.body!=="string")headers["content-type"]="application/json";const r=await fetch(path,{...options,headers,cache:"no-store",credentials:"same-origin"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"REQUEST_FAILED");return d}
export default function AdminTv(){
 const[kind,setKind]=useState("m3u"),[baseUrl,setBaseUrl]=useState(""),[username,setUsername]=useState(""),[password,setPassword]=useState(""),[m3uUrl,setM3uUrl]=useState(""),[count,setCount]=useState(0),[status,setStatus]=useState(""),[busy,setBusy]=useState(false),[channels,setChannels]=useState([]),[q,setQ]=useState("");
 async function load(){try{const[d,c]=await Promise.all([api("/api/admin/tv/source"),api("/api/admin/tv/channels").catch(()=>({channels:[]}))]);if(d.source){setKind(d.source.kind||"m3u");setBaseUrl(d.source.base_url||"");setUsername(d.source.username||"");setM3uUrl(d.source.m3u_url||"")}setCount(Number(d.channels)||0);setChannels(c.channels||[])}catch(e){setStatus(e.message==="FORBIDDEN"?"الحساب هذا مش أدمن":"ما قدرناش نحمّلوا إعدادات التلفزيون")}}
 useEffect(()=>{load()},[]);const visible=useMemo(()=>channels.filter(c=>!q.trim()||`${c.name} ${c.group_title||""}`.toLowerCase().includes(q.trim().toLowerCase())),[channels,q]);
 async function save(e){e.preventDefault();if(busy)return;setBusy(true);setStatus("بنحفظوا الإعدادات...");try{await api("/api/admin/tv/source",{method:"PUT",body:JSON.stringify({kind,baseUrl,username,password,m3uUrl}),headers:{"content-type":"application/json"}});setPassword("");setStatus("تم الحفظ ✓");await load()}catch(e){setStatus(e.message==="INVALID_SOURCE_URL"?"الرابط غير صالح أو يشير لشبكة داخلية":"صار خطأ في الحفظ")}finally{setBusy(false)}}
 async function refresh(){if(busy)return;setBusy(true);setStatus("بنجيبوا القنوات من المصدر...");try{const d=await api("/api/admin/tv/refresh",{method:"POST"});setCount(Number(d.count)||0);setStatus(`تمام، لقينا ${d.count||0} قناة`);await load()}catch(e){setStatus(e.message==="SOURCE_NOT_CONFIGURED"?"حط المصدر الأول":e.message==="NO_CHANNELS"?"المصدر ما رجّعش قنوات":e.message==="PLAYLIST_TOO_LARGE"?"قائمة القنوات أكبر من الحد المسموح":"ما قدرناش نحدّثوا القنوات")}finally{setBusy(false)}}
 async function testSource(){if(busy)return;setBusy(true);setStatus("بنجربوا المصدر بدون ما نبدلوا القنوات...");try{const d=await api("/api/admin/tv/test-source",{method:"POST"});setStatus(`المصدر شغال ✓ · ${d.count||0} قناة · ${d.latencyMs||0}ms`)}catch(e){setStatus(`المصدر ما اشتغلش: ${e.message}`)}finally{setBusy(false)}}
 async function uploadFile(file){if(!file||busy)return;if(file.size>8*1024*1024){setStatus("ملف M3U أكبر من 8MB");return}setBusy(true);setStatus("بنقرو الملف...");try{const content=await file.text(),d=await api("/api/admin/tv/import-m3u",{method:"POST",body:content,headers:{"content-type":"text/plain; charset=utf-8"}});setCount(Number(d.count)||0);setStatus(`تمام، ضفنا ${d.count||0} قناة من الملف`);await load()}catch(e){setStatus(e.message==="NO_CHANNELS"?"الملف ما فيهش قنوات صالحة":"ما قدرناش نستوردوا الملف")}finally{setBusy(false)}}
 async function patchChannel(id,patch){try{const d=await api(`/api/admin/tv/channels/${id}`,{method:"PATCH",body:JSON.stringify(patch),headers:{"content-type":"application/json"}});setChannels(list=>list.map(c=>String(c.id)===String(id)?d.channel:c));setStatus("تم تحديث القناة ✓")}catch{setStatus("ما قدرناش نحدّثوا القناة")}}
 async function testChannel(id){setStatus("بنجربوا القناة...");try{const d=await api(`/api/admin/tv/channels/${id}/test`,{method:"POST"});setStatus(`القناة ترد ✓ · ${d.latencyMs||0}ms${d.contentType?` · ${d.contentType}`:""}`)}catch{setStatus("القناة ما ردّتش أو المصدر موقف")}}
 async function removeChannel(id){const reason=window.prompt("اكتب سبب حذف القناة من مربوعة TV");if(reason===null)return;if(reason.trim().length<3){setStatus("سبب الحذف مطلوب");return}try{await api(`/api/admin/tv/channels/${id}`,{method:"DELETE",body:JSON.stringify({reason:reason.trim()}),headers:{"content-type":"application/json"}});setChannels(list=>list.filter(c=>String(c.id)!==String(id)));setCount(v=>Math.max(0,v-1));setStatus("تم حذف القناة وتسجيل السبب") }catch{setStatus("ما قدرناش نحذفوا القناة")}}
 return <main className="admin-tv-page" dir="rtl"><section className="admin-tv-shell"><header><div><span>مربوعة TV</span><h1>إدارة التلفزيون</h1><p>غيّر المصدر من هني، ويتحدّث عند الناس كلهم.</p></div><div className="admin-tv-count"><b>{count}</b><small>قناة</small></div></header>
 <form onSubmit={save} className="admin-tv-card"><h2>مصدر القنوات</h2><div className="admin-tv-kind"><button type="button" className={kind==="m3u"?"active":""} onClick={()=>setKind("m3u")}>M3U / M3U8</button><button type="button" className={kind==="xtream"?"active":""} onClick={()=>setKind("xtream")}>IPTV / Xtream</button></div>{kind==="m3u"?<label><span>رابط M3U</span><input dir="ltr" value={m3uUrl} onChange={e=>setM3uUrl(e.target.value)} placeholder="https://.../playlist.m3u"/></label>:<><label><span>السيرفر / IP</span><input dir="ltr" value={baseUrl} onChange={e=>setBaseUrl(e.target.value)} placeholder="https://server:port"/></label><label><span>اليوزر</span><input dir="ltr" value={username} onChange={e=>setUsername(e.target.value)}/></label><label><span>الباسورد</span><input dir="ltr" type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="اتركه فاضي لو ما تبيش تغيّره"/></label></>}<div className="admin-tv-actions admin-tv-actions-3"><button disabled={busy} className="primary"><Icon name="check"/> حفظ</button><button disabled={busy} type="button" onClick={testSource}><Icon name="check"/> جرّب المصدر</button><button disabled={busy} type="button" onClick={refresh}><Icon name="refresh"/> تحديث القنوات</button></div></form>
 <section className="admin-tv-card"><h2>أو ارفع ملف M3U</h2><p>ملف نصي حتى 8MB. مربوعة تستخرج حتى 10,000 قناة مع اللوقوهات والتصنيفات.</p><label className="admin-tv-upload"><Icon name="install"/><span>اختار ملف M3U</span><input type="file" accept=".m3u,.m3u8,text/plain" onChange={e=>uploadFile(e.target.files?.[0])}/></label></section>
 <section className="admin-tv-card admin-tv-channels-card"><div className="admin-tv-channels-head"><div><h2>القنوات</h2><p>خبّي، عدّل، رتّب أو جرّب أي قناة بروحها.</p></div><label><Icon name="search"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="دوّر على قناة..."/></label></div><div className="admin-tv-channel-list">{visible.map(c=><article key={c.id} className={!c.enabled?"disabled":""}><div className="admin-tv-channel-main">{c.logo_url?<img src={c.logo_url} alt=""/>:<span><Icon name="video"/></span>}<div><input value={c.name} onChange={e=>setChannels(list=>list.map(x=>x.id===c.id?{...x,name:e.target.value}:x))} onBlur={()=>patchChannel(c.id,{name:c.name})}/><input value={c.group_title||""} onChange={e=>setChannels(list=>list.map(x=>x.id===c.id?{...x,group_title:e.target.value}:x))} onBlur={()=>patchChannel(c.id,{groupTitle:c.group_title})}/></div></div><div className="admin-tv-channel-actions"><button type="button" onClick={()=>patchChannel(c.id,{enabled:!c.enabled})}>{c.enabled?"إخفاء":"إظهار"}</button><button type="button" onClick={()=>patchChannel(c.id,{sortOrder:Number(c.sort_order||0)-1})}>↑</button><button type="button" onClick={()=>patchChannel(c.id,{sortOrder:Number(c.sort_order||0)+1})}>↓</button><button type="button" onClick={()=>testChannel(c.id)}>اختبار</button><button type="button" className="danger" onClick={()=>removeChannel(c.id)}>حذف</button></div></article>)}{!visible.length&&<p className="admin-tv-no-channels">ما لقيناش قنوات مطابقة.</p>}</div></section>{status&&<div className="admin-tv-status" role="status">{status}</div>}</section></main>
}
