"use client";
import {useEffect,useState} from "react";
import {cookieHeaders,markCookieSession} from "../../../webSession";

async function api(path,options={}){const headers=cookieHeaders(options.headers||{});if(options.body&&!headers["content-type"])headers["content-type"]="application/json";const r=await fetch(path,{...options,headers,cache:"no-store",credentials:"same-origin"});let d={};try{d=await r.json()}catch{}if(!r.ok){const e=new Error(d.error||"REQUEST_FAILED");e.status=r.status;throw e}return d}
const human=e=>({OAUTH_FLOW_INVALID:"رابط إكمال الحساب غير صالح",OAUTH_FLOW_EXPIRED:"انتهت جلسة التسجيل. ارجع وجرب الدخول الاجتماعي من جديد",INVALID_EMAIL:"البريد غير صحيح",EMAIL_NOT_VERIFIED:"أكد البريد أولًا",OTP_TOO_SOON:"استنى شوية قبل طلب رمز جديد",OTP_INVALID:"الرمز غير صحيح",OTP_EXPIRED:"انتهت صلاحية الرمز",USERNAME_TAKEN:"اسم المستخدم مستخدم بالفعل",EMAIL_ALREADY_REGISTERED:"البريد مربوط بحساب مربوعة موجود. ارجع واربط الحساب بدل إنشاء حساب جديد",INVALID_USERNAME:"اسم المستخدم لازم يكون 3-24 حرف إنجليزي أو رقم",INVALID_DISPLAY_NAME:"الاسم غير صحيح",INVALID_GENDER:"اختار الجنس",WEAK_PASSWORD:"كلمة المرور لازم تكون 8 أحرف على الأقل",SOCIAL_ACCOUNT_CONFLICT:"الحساب الاجتماعي مربوط بحساب آخر",OAUTH_COMPLETE_FAILED:"تعذر إنشاء الحساب الآن",REQUEST_FAILED:"تعذر الاتصال بالسيرفر"}[e?.message]||e?.message||"صار خطأ غير متوقع");
export default function SocialComplete(){const[flow,setFlow]=useState(""),[info,setInfo]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");const[email,setEmail]=useState(""),[emailStep,setEmailStep]=useState("email"),[code,setCode]=useState(""),[displayName,setDisplayName]=useState(""),[username,setUsername]=useState(""),[usernameState,setUsernameState]=useState(null),[gender,setGender]=useState(""),[password,setPassword]=useState(""),[confirm,setConfirm]=useState("");
useEffect(()=>{const f=new URLSearchParams(location.search).get("flow")||"";setFlow(f);if(!/^[a-f0-9]{48}$/i.test(f)){setError("رابط إكمال الحساب غير صالح");setLoading(false);return}api(`/api/auth/oauth/pending/${f}`).then(d=>{setInfo(d);setEmail(d.email||"");setDisplayName(d.displayName||"");setEmailStep(d.needsEmailVerification?"email":"done")}).catch(e=>setError(human(e))).finally(()=>setLoading(false))},[]);
useEffect(()=>{if(username.length<3){setUsernameState(null);return}const t=setTimeout(()=>api(`/api/users/username-available?username=${encodeURIComponent(username)}`).then(d=>setUsernameState(d.valid&&d.available?"ok":"bad")).catch(()=>setUsernameState(null)),350);return()=>clearTimeout(t)},[username]);
async function requestOtp(){setBusy(true);setError("");setMessage("");try{await api("/api/auth/request-email-otp",{method:"POST",body:JSON.stringify({email})});setEmailStep("otp");setMessage("بعثنالك رمز تحقق من 6 أرقام إلى البريد.")}catch(e){setError(human(e))}finally{setBusy(false)}}
async function verifyOtp(){setBusy(true);setError("");try{await api("/api/auth/verify-email-otp",{method:"POST",body:JSON.stringify({email,code})});setEmailStep("done");setMessage("تم تأكيد البريد.")}catch(e){setError(human(e))}finally{setBusy(false)}}
async function complete(e){e.preventDefault();setError("");setMessage("");if(password!==confirm)return setError("كلمتا المرور مش نفس الشي");if(usernameState==="bad")return setError("اسم المستخدم مستخدم أو غير صالح");if(info?.needsEmailVerification&&emailStep!=="done")return setError("أكد البريد أولًا");setBusy(true);try{const d=await api("/api/auth/oauth/complete",{method:"POST",body:JSON.stringify({flow,email,displayName,username,gender,password})});markCookieSession();if(d.next&&d.next!=="/home"&&d.next!=="/onboarding")sessionStorage.setItem("marbo3a_after_onboarding",d.next);location.replace("/onboarding")}catch(e){setError(human(e))}finally{setBusy(false)}}
if(loading)return <main className="auth-v1-page" dir="rtl"><section className="auth-v1-card"><h1>كمّل حسابك</h1><p>جاري تجهيز بيانات التسجيل...</p></section></main>;
return <main className="auth-v1-page" dir="rtl"><section className="auth-v1-card"><header><img src="/brand/official/marbo3a-mark.png" alt="مربوعة"/><div><small>MARBO3A</small><h1>كمّل حسابك</h1><p>خطوة أخيرة ونجهز حساب مربوعة الخاص بك.</p></div></header>{error&&<div className="auth-v1-error" role="alert">{error}</div>}{message&&<div className="auth-v1-ok" role="status">{message}</div>}{info&&<div className="social-complete-preview">{info.picture?<img src={info.picture} alt=""/>:<img src="/brand/official/marbo3a-mark.png" alt=""/>}<div><b>{info.displayName||"حساب جديد"}</b><small>{info.provider==="google"?"Google":"Facebook"}{info.email?` · ${info.email}`:""}</small></div></div>}{info?.needsEmailVerification&&emailStep!=="done"?<div className="auth-v1-form"><label>البريد الإلكتروني<input type="email" value={email} onChange={e=>setEmail(e.target.value.trim())} placeholder="name@example.com" disabled={emailStep==="otp"}/></label>{emailStep==="otp"&&<label>رمز التحقق<input inputMode="numeric" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,6))} maxLength={6}/></label>}<button type="button" disabled={busy||!email} onClick={emailStep==="otp"?verifyOtp:requestOtp}>{busy?"جاري...":emailStep==="otp"?"تأكيد البريد":"إرسال رمز التحقق"}</button></div>:<form className="auth-v1-form" onSubmit={complete}>{!info?.emailVerified&&<label>البريد الإلكتروني<input type="email" value={email} readOnly/></label>}<label>الاسم الظاهر<input value={displayName} onChange={e=>setDisplayName(e.target.value)} minLength={2} maxLength={50} required/></label><label>اسم المستخدم<input value={username} onChange={e=>setUsername(e.target.value.toLowerCase().replace(/[^a-z0-9._]/g,"").slice(0,24))} minLength={3} maxLength={24} required/>{usernameState&&<span className={`username-state ${usernameState}`}>{usernameState==="ok"?"اسم المستخدم متاح":"اسم المستخدم غير متاح"}</span>}</label><label>الجنس<select value={gender} onChange={e=>setGender(e.target.value)} required><option value="">اختار</option><option value="male">راجل</option><option value="female">مرا</option></select></label><label>كلمة مرور مربوعة<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} autoComplete="new-password" required/></label><label>تأكيد كلمة المرور<input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} minLength={8} autoComplete="new-password" required/></label><button disabled={busy||usernameState==="bad"}>{busy?"جاري إنشاء الحساب...":"إنشاء حساب مربوعة"}</button></form>}<footer><a href="/privacy">الخصوصية</a><a href="/terms">الشروط</a></footer></section></main>}
