"use client";
import {useEffect,useRef,useState} from "react";
import {useParams} from "next/navigation";
import Icon from "../../Icon";
const token=()=>localStorage.getItem("marbo3a_token")||sessionStorage.getItem("marbo3a_token")||"";
async function api(path,options={}){const headers={authorization:`Bearer ${token()}`,...(options.headers||{})};if(options.body&&!(options.body instanceof FormData))headers["content-type"]="application/json";const r=await fetch(path,{...options,headers});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"REQUEST_FAILED");return d;}
const human=e=>({REQUEST_FAILED:"تعذر تنفيذ الطلب",CHAT_FORBIDDEN:"لا يمكنك فتح هذه المحادثة",UNAUTHORIZED:"انتهت جلسة الدخول",MESSAGE_NOT_FOUND:"الرسالة غير موجودة",FORBIDDEN:"ليس لديك صلاحية لهذه العملية"}[e?.message]||"صار خطأ. حاول مرة ثانية.");
export default function DirectChat(){const{id}=useParams(),[messages,setMessages]=useState([]),[text,setText]=useState(""),[reply,setReply]=useState(null),[typing,setTyping]=useState([]),[search,setSearch]=useState(""),[results,setResults]=useState([]),[status,setStatus]=useState(""),[attachment,setAttachment]=useState(null),[chats,setChats]=useState([]),[me,setMe]=useState(null);const box=useRef(null),typingTimer=useRef(null);
async function load(){try{const [d,c,m]=await Promise.all([api(`/api/chats/${id}/messages`),api("/api/chats").catch(()=>({chats:[]})),api("/api/auth/me").catch(()=>null)]);setMessages(d.messages||[]);setChats(c.chats||[]);if(m?.user)setMe(m.user);const last=(d.messages||[]).at(-1);if(last)api(`/api/read/direct/${id}`,{method:"PUT",body:JSON.stringify({lastMessageId:last.id})}).catch(()=>{});}catch(e){setStatus(human(e))}}
useEffect(()=>{if(!id)return;load();const t=setInterval(load,2500),ty=setInterval(()=>api(`/api/typing/direct/${id}`).then(d=>setTyping(d.users||[])).catch(()=>{}),2200);return()=>{clearInterval(t);clearInterval(ty)}},[id]);useEffect(()=>{if(box.current)box.current.scrollTop=box.current.scrollHeight},[messages]);
async function send(e){e.preventDefault();if(!text.trim()&&!attachment)return;try{await api(`/api/chats/${id}/messages`,{method:"POST",body:JSON.stringify({body:text.trim(),replyToId:reply?.id||null,attachmentUrl:attachment?.url||null,attachmentType:attachment?.type||null})});setText("");setReply(null);setAttachment(null);await load()}catch(e){setStatus(human(e))}}
function onType(v){setText(v);api(`/api/typing/direct/${id}`,{method:"POST",body:JSON.stringify({typing:true})}).catch(()=>{});clearTimeout(typingTimer.current);typingTimer.current=setTimeout(()=>api(`/api/typing/direct/${id}`,{method:"POST",body:JSON.stringify({typing:false})}).catch(()=>{}),4500)}
async function upload(file){if(!file)return;const fd=new FormData();fd.append("file",file);try{setAttachment((await api("/api/uploads",{method:"POST",body:fd})).file)}catch(e){setStatus(human(e))}}
async function react(m,emoji){try{await api(`/api/messages/direct/${m.id}/reactions`,{method:"POST",body:JSON.stringify({emoji})});setStatus(`تم التفاعل ${emoji}`)}catch(e){setStatus(human(e))}}
async function edit(m){const body=prompt("تعديل الرسالة:",m.body||"");if(body===null||!body.trim())return;try{await api(`/api/direct-messages/${m.id}`,{method:"PATCH",body:JSON.stringify({body})});await load()}catch(e){setStatus(human(e))}}
async function remove(m){if(!confirm("حذف الرسالة من الطرفين؟"))return;try{await api(`/api/direct-messages/${m.id}`,{method:"DELETE"});await load()}catch(e){setStatus(human(e))}}
async function forward(m){const options=chats.filter(c=>String(c.id)!==String(id)).map(c=>`${c.id}: ${c.display_name} (@${c.username})`).join("\n");if(!options)return setStatus("ما عندكش محادثة ثانية لإعادة التوجيه");const target=Number(prompt(`اختر رقم المحادثة:\n${options}`));if(!Number.isInteger(target))return;try{await api(`/api/direct-messages/${m.id}/forward`,{method:"POST",body:JSON.stringify({conversationId:target})});setStatus("تمت إعادة توجيه الرسالة") }catch(e){setStatus(human(e))}}
async function doSearch(e){e.preventDefault();if(!search.trim())return;try{setResults((await api(`/api/chats/${id}/search?q=${encodeURIComponent(search)}`)).messages||[])}catch(e){setStatus(human(e))}}
return <main className="social-page chat-social" dir="rtl"><div className="chat-social-shell"><header className="chat-social-head"><a href="/messages" className="chat-icon-btn"><Icon name="close"/></a><div><small>محادثة خاصة</small><h1>الرسائل</h1></div><button className="chat-icon-btn" onClick={()=>document.getElementById("chat-search")?.classList.toggle("show")}><Icon name="search"/></button></header><form id="chat-search" className="chat-search" onSubmit={doSearch}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="بحث في المحادثة"/><button>بحث</button></form>{results.length>0&&<div className="chat-search-results">{results.map(m=><button key={m.id} onClick={()=>document.getElementById(`dm-${m.id}`)?.scrollIntoView({behavior:"smooth",block:"center"})}>{m.body}</button>)}</div>}{status&&<div className="chat-toast" onClick={()=>setStatus("")}>{status}</div>}<section ref={box} className="chat-stream">{messages.map(m=>{const mine=String(m.sender_id)===String(me?.id);return <article id={`dm-${m.id}`} key={m.id} className={`chat-bubble ${mine?"mine":"theirs"}`}><div className="chat-bubble-head"><b>{mine?"أنت":(m.display_name||m.username||`#${m.sender_id}`)}</b><details><summary><Icon name="more"/></summary><div><button onClick={()=>setReply(m)}>رد</button>{mine&&!m.deleted_at&&<button onClick={()=>edit(m)}>تعديل</button>}{!m.deleted_at&&<button onClick={()=>forward(m)}>إعادة توجيه</button>}{mine&&!m.deleted_at&&<button className="danger" onClick={()=>remove(m)}>حذف للطرفين</button>}</div></details></div>{m.reply_to_id&&<small className="chat-reply-tag">رد على رسالة #{m.reply_to_id}</small>}<p>{m.deleted_at?"تم حذف الرسالة":m.body}</p>{m.attachment_url&&<a className="chat-attachment" href={m.attachment_url} target="_blank" rel="noreferrer">فتح المرفق</a>}<footer><small>{new Date(m.created_at).toLocaleTimeString("ar-LY",{hour:"2-digit",minute:"2-digit"})}{m.edited_at?" · معدّلة":""}</small>{!m.deleted_at&&<div className="chat-reactions"><button onClick={()=>react(m,"👍")}>👍</button><button onClick={()=>react(m,"❤️")}>❤️</button><button onClick={()=>react(m,"😂")}>😂</button></div>}</footer></article>})}</section>{typing.length>0&&<div className="chat-typing">{typing.map(x=>x.displayName||x.username).join("، ")} يكتب...</div>}{reply&&<div className="chat-replying"><span>رد على: {reply.body?.slice(0,90)}</span><button onClick={()=>setReply(null)}>إلغاء</button></div>}{attachment&&<div className="chat-replying"><span>مرفق جاهز: {attachment.name}</span><button onClick={()=>setAttachment(null)}>إلغاء</button></div>}<form onSubmit={send} className="chat-compose"><label className="chat-icon-btn"><Icon name="image"/><input type="file" accept="image/*,audio/*,application/pdf" hidden onChange={e=>upload(e.target.files?.[0])}/></label><input value={text} onChange={e=>onType(e.target.value)} placeholder="اكتب رسالتك..."/><button className="chat-send"><Icon name="send"/></button></form></div></main>}
