"use client";
import {useEffect,useRef,useState} from "react";
import {useParams,useRouter} from "next/navigation";
import Icon from "../../Icon";
import {liveApi,liveErrorText} from "../live-api";

const trace=(type,data={})=>{try{window.dispatchEvent(new CustomEvent("marbo3a:rtc-debug",{detail:{type:`live_viewer_${type}`,...data}}))}catch{}};
export default function LiveViewer(){
 const{id}=useParams(),router=useRouter(),videoRef=useRef(null),pcRef=useRef(null),iceServersRef=useRef([]),pendingIce=useRef([]),signalSince=useRef(0),hostId=useRef(null),joined=useRef(false),signalTimer=useRef(null),metaTimer=useRef(null),heartbeatTimer=useRef(null),reconnectTimer=useRef(null),reconnectAttempts=useRef(0),[live,setLive]=useState(null),[messages,setMessages]=useState([]),[message,setMessage]=useState(""),[status,setStatus]=useState("بنجهزوا اللايف..."),[reactions,setReactions]=useState([]),[connected,setConnected]=useState(false),[reportOpen,setReportOpen]=useState(false),[reportReason,setReportReason]=useState("other"),[reportDetails,setReportDetails]=useState(""),[reporting,setReporting]=useState(false);
 async function signal(kind,payload){if(!hostId.current)return;await liveApi(`/api/live/${id}/signals`,{method:"POST",body:JSON.stringify({recipientId:hostId.current,kind,payload})});trace("signal_out",{kind,recipientId:hostId.current})}
 function destroyPeer(){if(pcRef.current)try{pcRef.current.close()}catch{}pcRef.current=null;pendingIce.current=[];setConnected(false)}
 async function flushIce(pc){const list=[...pendingIce.current];pendingIce.current=[];for(const candidate of list)try{await pc.addIceCandidate(candidate)}catch(e){trace("ice_add_error",{error:e?.message||"ICE_ADD_FAILED"})}}
 function scheduleReconnect(){if(reconnectAttempts.current>=3||!joined.current)return;clearTimeout(reconnectTimer.current);const delay=1000*(reconnectAttempts.current+1);reconnectAttempts.current++;setStatus(`الاتصال ضعف، بنعاودوا الربط... (${reconnectAttempts.current}/3)`);reconnectTimer.current=setTimeout(async()=>{try{destroyPeer();await join(true)}catch{}},delay)}
 async function setupPeer(iceServers=iceServersRef.current){if(pcRef.current)return pcRef.current;iceServersRef.current=Array.isArray(iceServers)?iceServers:[];const pc=new RTCPeerConnection({iceServers:iceServersRef.current});pcRef.current=pc;pc.ontrack=e=>{const stream=e.streams?.[0]||new MediaStream([e.track]);if(videoRef.current){videoRef.current.srcObject=stream;videoRef.current.play?.().catch(()=>{})}setConnected(true);setStatus("");reconnectAttempts.current=0;trace("track",{kind:e.track?.kind||"unknown",tracks:stream.getTracks?.().map(t=>t.kind)||[]})};pc.onicecandidate=e=>e.candidate&&signal("ice",e.candidate.toJSON()).catch(err=>trace("signal_error",{kind:"ice",error:err?.message||"SIGNAL_FAILED"}));pc.onicecandidateerror=e=>trace("ice_candidate_error",{code:e.errorCode||0,text:e.errorText||""});pc.oniceconnectionstatechange=()=>trace("ice_state",{state:pc.iceConnectionState});pc.onconnectionstatechange=()=>{trace("peer_state",{state:pc.connectionState});if(pc.connectionState==="connected"){setConnected(true);setStatus("");reconnectAttempts.current=0}else if(pc.connectionState==="connecting")setStatus("جاري ربط الصورة والصوت...");else if(pc.connectionState==="failed"||pc.connectionState==="disconnected"){setConnected(false);scheduleReconnect()}else if(pc.connectionState==="closed")setConnected(false)};return pc}
 async function pollSignals(){if(!joined.current)return;try{const d=await liveApi(`/api/live/${id}/signals?since=${signalSince.current}`);for(const s of d.signals||[]){signalSince.current=Math.max(signalSince.current,Number(s.id)||0);const pc=await setupPeer();trace("signal_in",{kind:s.kind,senderId:s.sender_id});if(s.kind==="offer"){if(pc.signalingState==="closed")continue;if(pc.signalingState!=="stable"&&pc.localDescription)try{await pc.setLocalDescription({type:"rollback"})}catch{}await pc.setRemoteDescription(s.payload);await flushIce(pc);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await signal("answer",pc.localDescription.toJSON())}else if(s.kind==="ice"){if(pc.remoteDescription)try{await pc.addIceCandidate(s.payload)}catch(e){trace("ice_add_error",{error:e?.message||"ICE_ADD_FAILED"})}else pendingIce.current.push(s.payload)}}}catch(e){trace("signals_error",{error:e.message,status:e.status||0});if(e.status===410){setStatus("اللايف سكّر.");cleanup(false)}else if(e.message==="LIVE_BLOCKED"){setStatus(liveErrorText(e));cleanup(true)}}}
 async function loadMeta(){try{const d=await liveApi(`/api/live/${id}`);setLive(d.live);setMessages(d.messages||[]);setReactions(d.reactions||[]);if(d.live?.status!=="active"){setStatus("اللايف سكّر.");cleanup(false)}}catch(e){if(e.status===404||e.status===410){setStatus("اللايف مش شغال توا.");cleanup(false)}else setStatus(liveErrorText(e))}}
 function startLoops(){clearInterval(signalTimer.current);clearInterval(metaTimer.current);clearInterval(heartbeatTimer.current);signalTimer.current=setInterval(pollSignals,450);metaTimer.current=setInterval(loadMeta,1400);heartbeatTimer.current=setInterval(()=>liveApi(`/api/live/${id}/heartbeat`,{method:"POST"}).catch(()=>{}),6000)}
 async function join(reconnect=false){try{const meta=await liveApi(`/api/live/${id}`);if(meta.live?.status!=="active")throw Object.assign(new Error("LIVE_ENDED"),{status:410});setLive(meta.live);setMessages(meta.messages||[]);setReactions(meta.reactions||[]);hostId.current=Number(meta.live.host_id);const d=await liveApi(`/api/live/${id}/join`,{method:"POST"});hostId.current=Number(d.hostId||meta.live.host_id);iceServersRef.current=d.iceServers||meta.iceServers||[];joined.current=true;await setupPeer(iceServersRef.current);setStatus(reconnect?"بنرجعوا الصورة...":"جاري ربط الصورة والصوت...");if(!reconnect)startLoops();trace(reconnect?"rejoin":"join",{sessionId:id,hostId:hostId.current,iceServers:iceServersRef.current.length});await pollSignals()}catch(e){trace("join_error",{error:e.message,status:e.status||0});setStatus(liveErrorText(e));if(e.message==="LIVE_BLOCKED")cleanup(true)}}
 function cleanup(closePc=true){clearInterval(signalTimer.current);clearInterval(metaTimer.current);clearInterval(heartbeatTimer.current);clearTimeout(reconnectTimer.current);signalTimer.current=null;metaTimer.current=null;heartbeatTimer.current=null;reconnectTimer.current=null;if(closePc)destroyPeer();joined.current=false}
 useEffect(()=>{if(!id)return;join();const onModeration=e=>{const d=e?.detail;if(String(d?.sessionId)!==String(id))return;if(d.action==="block"||d.action==="kick"){setStatus(d.action==="block"?"صاحب اللايف حظرك من اللايف.":"صاحب اللايف خرجك من اللايف.");cleanup(true)}};window.addEventListener("marbo3a:live-moderation",onModeration);window.addEventListener("marbo3a:live-kicked",onModeration);return()=>{window.removeEventListener("marbo3a:live-moderation",onModeration);window.removeEventListener("marbo3a:live-kicked",onModeration);cleanup(true)}},[id]);
 async function sendMessage(e){e.preventDefault();if(!message.trim()||live?.chat_enabled===false)return;try{await liveApi(`/api/live/${id}/messages`,{method:"POST",body:JSON.stringify({body:message.trim()})});setMessage("");await loadMeta()}catch(e){setStatus(liveErrorText(e))}}
 async function react(emoji){try{await liveApi(`/api/live/${id}/reactions`,{method:"POST",body:JSON.stringify({reaction:emoji})});setReactions(list=>{const found=list.find(x=>x.reaction===emoji);return found?list.map(x=>x.reaction===emoji?{...x,count:Number(x.count)+1}:x):[...list,{reaction:emoji,count:1}]})}catch(e){setStatus(liveErrorText(e))}}
 async function share(){const url=`${location.origin}/live/${id}`;try{if(navigator.share)await navigator.share({title:live?.title||"لايف على مربوعة",url});else{await navigator.clipboard.writeText(url);setStatus("نسخنا رابط اللايف ✓")}}catch(e){if(e?.name!=="AbortError")setStatus("ما قدرناش نشاركوا الرابط")}}
 async function report(){if(reporting)return;setReporting(true);try{await liveApi(`/api/live/${id}/report`,{method:"POST",body:JSON.stringify({reason:reportReason,details:reportDetails.trim()})});setReportOpen(false);setReportDetails("");setStatus("وصلنا بلاغك، شكراً.")}catch(e){setStatus(liveErrorText(e))}finally{setReporting(false)}}
 const chatOpen=live?.chat_enabled!==false;
 return <main className="live-watch-page live-immersive" dir="rtl"><section className="live-watch"><div className="live-watch-video"><video ref={videoRef} autoPlay playsInline controls={false}/><header><button className="live-exit-x" type="button" onClick={()=>router.push("/live")} aria-label="سكر اللايف"><Icon name="close"/></button><div><b><i/> LIVE</b><span><Icon name="users"/>{Number(live?.viewers_count||0)}</span></div><div className="live-watch-head-actions"><button type="button" onClick={share} aria-label="شارك"><Icon name="share"/></button><button type="button" onClick={()=>setReportOpen(true)} aria-label="بلغ"><Icon name="warning"/></button></div></header>{!connected&&<div className="live-video-wait"><span>{live?.avatar_url?<img src={live.avatar_url} alt=""/>:String(live?.display_name||"م")[0]}</span><p>{status}</p>{joined.current&&reconnectAttempts.current>=3&&<button type="button" onClick={()=>{reconnectAttempts.current=0;destroyPeer();join(true)}}>حاول من جديد</button>}</div>}<div className="live-watch-reactions">{["❤️","🔥","👏","😂","👍"].map(x=><button type="button" key={x} onClick={()=>react(x)}>{x}{Number(reactions.find(r=>r.reaction===x)?.count||0)>0&&<small>{reactions.find(r=>r.reaction===x)?.count}</small>}</button>)}</div></div><aside className="live-watch-chat"><header><div><b>{live?.title||"لايف مربوعة"}</b><small>{live?.display_name||""} {live?.username&&<><span>·</span> <bdi dir="ltr">@{live.username}</bdi></>} {Number(live?.slow_mode_seconds)>0&&<><span>·</span> بطيء {live.slow_mode_seconds}ث</>}</small></div></header><div className="live-chat-stream">{messages.map(m=><p key={m.id}><a href={`/u/${m.username}`}><b>{m.display_name||m.username}</b></a><span>{m.body}</span></p>)}{!chatOpen&&<p className="live-chat-closed">صاحب اللايف مقفل الشات توا.</p>}</div><form onSubmit={sendMessage}><input disabled={!chatOpen} value={message} onChange={e=>setMessage(e.target.value)} maxLength={500} placeholder={chatOpen?"اكتب تعليق...":"الشات مقفول"}/><button disabled={!chatOpen||!message.trim()} aria-label="ابعث"><Icon name="send"/></button></form></aside>{reportOpen&&<div className="live-report-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setReportOpen(false)}><section className="live-report-card"><header><h3>بلغ على اللايف</h3><button type="button" onClick={()=>setReportOpen(false)}><Icon name="close"/></button></header><label>السبب<select value={reportReason} onChange={e=>setReportReason(e.target.value)}><option value="spam">إزعاج / سبام</option><option value="abuse">إساءة</option><option value="harassment">تحرش</option><option value="nudity">محتوى غير مناسب</option><option value="violence">عنف</option><option value="other">سبب ثاني</option></select></label><textarea value={reportDetails} onChange={e=>setReportDetails(e.target.value)} maxLength={500} placeholder="وضح أكثر لو تبي..."/><button type="button" disabled={reporting} onClick={report}>{reporting?"لحظة...":"إرسال البلاغ"}</button></section></div>}</section></main>
}
