"use client";
import {useEffect,useRef,useState} from "react";
import {useParams,useRouter} from "next/navigation";
import Icon from "../../Icon";
import {liveApi,liveErrorText} from "../live-api";

export default function LiveViewer(){
 const{id}=useParams(),router=useRouter(),videoRef=useRef(null),pcRef=useRef(null),signalSince=useRef(0),hostId=useRef(null),joined=useRef(false),signalTimer=useRef(null),metaTimer=useRef(null),heartbeatTimer=useRef(null),[live,setLive]=useState(null),[messages,setMessages]=useState([]),[message,setMessage]=useState(""),[status,setStatus]=useState("بنجهزوا اللايف..."),[reactions,setReactions]=useState([]),[connected,setConnected]=useState(false);
 async function signal(kind,payload){if(!hostId.current)return;await liveApi(`/api/live/${id}/signals`,{method:"POST",body:JSON.stringify({recipientId:hostId.current,kind,payload})})}
 async function setupPeer(iceServers=[]){if(pcRef.current)return pcRef.current;const pc=new RTCPeerConnection({iceServers});pcRef.current=pc;pc.ontrack=e=>{if(videoRef.current)videoRef.current.srcObject=e.streams?.[0]||new MediaStream([e.track]);setConnected(true)};pc.onicecandidate=e=>e.candidate&&signal("ice",e.candidate.toJSON()).catch(()=>{});pc.onconnectionstatechange=()=>{const s=pc.connectionState;setConnected(s==="connected");if(s==="failed")setStatus("البث فصل. جرّب ادخل من جديد.")};return pc}
 async function pollSignals(){try{const d=await liveApi(`/api/live/${id}/signals?since=${signalSince.current}`);for(const s of d.signals||[]){signalSince.current=Math.max(signalSince.current,Number(s.id)||0);const pc=await setupPeer();if(s.kind==="offer"){await pc.setRemoteDescription(s.payload);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await signal("answer",pc.localDescription)}else if(s.kind==="ice"){try{await pc.addIceCandidate(s.payload)}catch{}}}}catch(e){if(e.status===410){setStatus("اللايف سكّر.");cleanup(false)}}}
 async function loadMeta(){try{const d=await liveApi(`/api/live/${id}`);setLive(d.live);setMessages(d.messages||[]);setReactions(d.reactions||[]);if(d.live?.status!=="active"){setStatus("اللايف سكّر.");cleanup(false)}}catch(e){if(e.status===404||e.status===410){setStatus("اللايف مش شغال توا.");cleanup(false)}else setStatus(liveErrorText(e))}}
 async function join(){try{const meta=await liveApi(`/api/live/${id}`);if(meta.live?.status!=="active")throw Object.assign(new Error("LIVE_ENDED"),{status:410});setLive(meta.live);setMessages(meta.messages||[]);setReactions(meta.reactions||[]);hostId.current=Number(meta.live.host_id);const d=await liveApi(`/api/live/${id}/join`,{method:"POST"});hostId.current=Number(d.hostId||meta.live.host_id);joined.current=true;await setupPeer(d.iceServers||meta.iceServers||[]);setStatus("مستنين الصورة توصل...");signalTimer.current=setInterval(pollSignals,650);metaTimer.current=setInterval(loadMeta,1800);heartbeatTimer.current=setInterval(()=>liveApi(`/api/live/${id}/heartbeat`,{method:"POST"}).catch(()=>{}),7000);pollSignals()}catch(e){setStatus(liveErrorText(e))}}
 function cleanup(closePc=true){clearInterval(signalTimer.current);clearInterval(metaTimer.current);clearInterval(heartbeatTimer.current);if(closePc&&pcRef.current)try{pcRef.current.close()}catch{}pcRef.current=null;joined.current=false}
 useEffect(()=>{if(!id)return;join();return()=>cleanup(true)},[id]);
 async function sendMessage(e){e.preventDefault();if(!message.trim())return;try{await liveApi(`/api/live/${id}/messages`,{method:"POST",body:JSON.stringify({body:message.trim()})});setMessage("");await loadMeta()}catch(e){setStatus(liveErrorText(e))}}
 async function react(emoji){try{await liveApi(`/api/live/${id}/reactions`,{method:"POST",body:JSON.stringify({reaction:emoji})});setReactions(list=>{const found=list.find(x=>x.reaction===emoji);return found?list.map(x=>x.reaction===emoji?{...x,count:Number(x.count)+1}:x):[...list,{reaction:emoji,count:1}]})}catch{}}
 return <main className="live-watch-page" dir="rtl"><section className="live-watch"><div className="live-watch-video"><video ref={videoRef} autoPlay playsInline controls={false}/><header><button type="button" onClick={()=>router.push("/live")} aria-label="ارجع"><Icon name="arrowRight"/></button><div><b><i/> LIVE</b><span><Icon name="users"/>{Number(live?.viewers_count||0)}</span></div></header>{!connected&&<div className="live-video-wait"><span>{live?.avatar_url?<img src={live.avatar_url} alt=""/>:String(live?.display_name||"م")[0]}</span><p>{status}</p></div>}<div className="live-watch-reactions">{["❤️","🔥","👏","😂","👍"].map(x=><button type="button" key={x} onClick={()=>react(x)}>{x}{Number(reactions.find(r=>r.reaction===x)?.count||0)>0&&<small>{reactions.find(r=>r.reaction===x)?.count}</small>}</button>)}</div></div><aside className="live-watch-chat"><header><div><b>{live?.title||"لايف مربوعة"}</b><small>{live?.display_name||""} {live?.username&&<><span>·</span> <bdi dir="ltr">@{live.username}</bdi></>}</small></div><button type="button" onClick={()=>router.push("/live")}>اطلع</button></header><div className="live-chat-stream">{messages.map(m=><p key={m.id}><b>{m.display_name||m.username}</b><span>{m.body}</span></p>)}</div><form onSubmit={sendMessage}><input value={message} onChange={e=>setMessage(e.target.value)} maxLength={500} placeholder="اكتب في الشات..."/><button aria-label="ابعث"><Icon name="send"/></button></form></aside></section></main>
}
