"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import Icon from "../Icon";
import "./engagement.css";

const token=()=>typeof window!=="undefined"?(localStorage.getItem("marbo3a_token")||sessionStorage.getItem("marbo3a_token")||""):"";
async function api(path,options={}){const t=token(),headers={...(options.headers||{})};if(t&&t!=="cookie")headers["x-marbo3a-session-mode"]="cookie";if(options.body)headers["content-type"]="application/json";const r=await fetch(path,{...options,headers,credentials:"same-origin",cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"REQUEST_FAILED");return d}
const emitEffect=type=>window.dispatchEvent(new CustomEvent("marbo3a:effect",{detail:{type}}));
function Avatar({u}){return u?.avatar_url?<img className="mn-avatar" src={u.avatar_url} alt=""/>:<span className="mn-avatar mn-fallback">{u?.display_name?.[0]||"م"}</span>}
function Card({title,icon,children,className=""}){return <section className={`mn-card ${className}`}><header><span>{icon}</span><h2>{title}</h2></header>{children}</section>}

export default function EngagementPage(){
 const[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState(""),[streak,setStreak]=useState(null),[trending,setTrending]=useState({posts:[],accounts:[],rooms:[],topics:[]}),[suggestions,setSuggestions]=useState([]),[polls,setPolls]=useState([]),[memories,setMemories]=useState([]),[collections,setCollections]=useState([]),[saved,setSaved]=useState([]),[analytics,setAnalytics]=useState({}),[prefs,setPrefs]=useState({sound_enabled:true,haptics_enabled:true,respect_reduced_motion:true}),[question,setQuestion]=useState(""),[options,setOptions]=useState(["",""]),[collectionName,setCollectionName]=useState(""),[selectedCollection,setSelectedCollection]=useState("");
 async function load(){if(!token()){location.href=`/?next=${encodeURIComponent("/engagement")}`;return}setLoading(true);setError("");const [a,b,c,d,e,f,g,h,i]=await Promise.allSettled([api("/api/engagement/streak"),api("/api/engagement/trending"),api("/api/engagement/suggestions"),api("/api/engagement/polls"),api("/api/engagement/memories"),api("/api/engagement/collections"),api("/api/engagement/analytics"),api("/api/experience/preferences"),api("/api/saved")]);if(a.status==="fulfilled")setStreak(a.value.streak);if(b.status==="fulfilled")setTrending(b.value);if(c.status==="fulfilled")setSuggestions(c.value.suggestions||[]);if(d.status==="fulfilled")setPolls(d.value.polls||[]);if(e.status==="fulfilled")setMemories(e.value.memories||[]);if(f.status==="fulfilled"){setCollections(f.value.collections||[]);if(!selectedCollection&&f.value.collections?.[0])setSelectedCollection(String(f.value.collections[0].id))}if(g.status==="fulfilled")setAnalytics(g.value.analytics||{});if(h.status==="fulfilled")setPrefs(h.value.preferences||prefs);if(i.status==="fulfilled")setSaved(i.value.posts||i.value.saved||[]);if([a,b,c,d,e,f,g,h].every(x=>x.status==="rejected"))setError("تعذر تحميل مركز التفاعل الآن");setLoading(false)}
 useEffect(()=>{load()},[]);
 const streakProgress=useMemo(()=>{if(!streak)return 0;return Math.min(100,Math.round((Number(streak.count||0)/Math.max(1,Number(streak.nextMilestone||3)))*100))},[streak]);
 async function friend(userId){try{await api("/api/friends/request",{method:"POST",body:JSON.stringify({userId})});setSuggestions(x=>x.filter(v=>String(v.id)!==String(userId)));setNotice("تم إرسال طلب الصداقة");emitEffect("send")}catch(e){setNotice(e.message==="RELATION_EXISTS"?"العلاقة موجودة بالفعل":"تعذر إرسال الطلب")}}
 async function vote(postId,optionId){try{const d=await api(`/api/engagement/polls/${postId}/vote`,{method:"PUT",body:JSON.stringify({optionId})});setPolls(x=>x.map(p=>String(p.post_id)===String(postId)?d.poll:p));emitEffect("like")}catch(e){setNotice(e.message==="POLL_CLOSED"?"انتهى التصويت":"تعذر تسجيل التصويت")}}
 async function createPoll(e){e.preventDefault();const cleanOptions=options.map(x=>x.trim()).filter(Boolean);if(!question.trim()||cleanOptions.length<2)return setNotice("اكتب السؤال وخيارين على الأقل");try{const d=await api("/api/engagement/polls",{method:"POST",body:JSON.stringify({question:question.trim(),options:cleanOptions})});setPolls(x=>[d.poll,...x]);setQuestion("");setOptions(["",""]);setNotice("تم نشر الاستطلاع");emitEffect("send")}catch(e){setNotice(e.message==="POLL_INVALID"?"راجع السؤال والخيارات":"تعذر إنشاء الاستطلاع")}}
 async function createCollection(e){e.preventDefault();if(!collectionName.trim())return;try{const d=await api("/api/engagement/collections",{method:"POST",body:JSON.stringify({name:collectionName.trim()})});setCollections(x=>[d.collection,...x]);setSelectedCollection(String(d.collection.id));setCollectionName("");setNotice("تم إنشاء المجموعة")}catch(e){setNotice(e.message==="COLLECTION_EXISTS"?"عندك مجموعة بنفس الاسم":"تعذر إنشاء المجموعة")}}
 async function addSaved(postId){if(!selectedCollection)return setNotice("اختار مجموعة أولًا");try{await api(`/api/engagement/collections/${selectedCollection}/posts/${postId}`,{method:"POST"});setCollections(x=>x.map(c=>String(c.id)===String(selectedCollection)?{...c,posts_count:Number(c.posts_count||0)+1}:c));setNotice("تمت إضافة المنشور للمجموعة");emitEffect("send")}catch{setNotice("تعذر إضافة المنشور")}}
 async function savePrefs(next){setPrefs(next);try{const d=await api("/api/experience/preferences",{method:"PATCH",body:JSON.stringify({soundEnabled:next.sound_enabled,hapticsEnabled:next.haptics_enabled,respectReducedMotion:next.respect_reduced_motion})});setPrefs(d.preferences);window.dispatchEvent(new CustomEvent("marbo3a:experience-preferences",{detail:d.preferences}));setNotice("تم حفظ إعدادات الصوت والاهتزاز")}catch{setNotice("تعذر حفظ الإعدادات")}}
 if(loading)return <main className="mn-page" dir="rtl"><div className="mn-shell"><div className="mn-loading">جاري تجهيز مركز التفاعل...</div></div></main>;
 return <main className="mn-page" dir="rtl"><div className="mn-shell">
  <header className="mn-hero"><div><small>GROUP M + N</small><h1>التفاعل في مربوعة</h1><p>سلسلة التفاعل، الشائع في ليبيا، اقتراحات الأصحاب، الاستطلاعات، الذكريات، المجموعات وإحصائياتك.</p></div><button type="button" onClick={load}><Icon name="refresh"/> تحديث</button></header>
  {error&&<div className="mn-notice danger">{error}</div>}{notice&&<button type="button" className="mn-notice" onClick={()=>setNotice("")}>{notice}</button>}
  <div className="mn-grid top">
   <Card title="سلسلة التفاعل" icon="🔥" className="streak"><div className="mn-streak"><strong>{streak?.count||0}</strong><span>يوم</span></div><p>{streak?.warning?"السلسلة مازالت قابلة للاستمرار — تفاعل ثنائي اليوم قبل ما تنقطع.":streak?.qualifiedToday?"تفاعل اليوم محسوب ✓":"ابدأ تفاعلًا حقيقيًا متبادلًا مع أحد أصحابك."}</p><div className="mn-progress"><i style={{width:`${streakProgress}%`}}/></div><small>الهدف الجاي: {streak?.nextMilestone||3} يوم {streak?.milestone100?"• وصلت إنجاز 100 🔥":""}</small></Card>
   <Card title="إحصائياتي — 30 يوم" icon="📊"><div className="mn-stats">{[["مشاهدات الملف",analytics.profileViews],["مشاهدات المنشورات",analytics.postViews],["مشاهدات القصص",analytics.storyViews],["نمو الأصحاب",analytics.friendGrowth],["التفاعل",analytics.engagement],["منشورات",analytics.posts]].map(([l,v])=><div key={l}><b>{Number(v||0)}</b><span>{l}</span></div>)}</div></Card>
  </div>
  <div className="mn-grid">
   <Card title="شائع في ليبيا" icon="📈" className="wide"><div className="mn-topics">{trending.topics?.length?trending.topics.map(t=><span key={t.topic}>#{t.topic} <b>{t.count}</b></span>):<span>مافيش مواضيع بارزة توا</span>}</div><div className="mn-trending-posts">{trending.posts?.slice(0,6).map(p=><article key={p.id}><Avatar u={p}/><div><Link href={`/u/${p.username}`}><b>{p.display_name}</b></Link><p>{p.body||"منشور وسائط"}</p><small>نقاط الشيوع {p.score}</small></div></article>)}</div><div className="mn-mini-list"><b>غرف نشطة</b>{trending.rooms?.slice(0,5).map(r=><Link key={r.id} href={`/room/${r.id}`}>{r.name}<small>{r.members} عضو • {r.recent_messages} رسالة حديثة</small></Link>)}</div></Card>
   <Card title="أصحاب مقترحين" icon="👥"><div className="mn-suggestions">{suggestions.length?suggestions.map(s=><article key={s.id}><Link href={`/u/${s.username}`}><Avatar u={s}/><span><b>{s.display_name}</b><small>{s.mutuals} مشترك • {s.room_overlap} غرف مشتركة</small></span></Link><button onClick={()=>friend(s.id)}>+ إضافة</button></article>):<p className="mn-empty">مافيش اقتراحات جديدة توا.</p>}</div></Card>
  </div>
  <div className="mn-grid">
   <Card title="استطلاع جديد" icon="🗳️"><form className="mn-form" onSubmit={createPoll}><textarea value={question} onChange={e=>setQuestion(e.target.value)} maxLength={280} placeholder="شن السؤال اللي تبي تسأله؟"/>{options.map((o,i)=><div className="mn-option-edit" key={i}><input value={o} onChange={e=>setOptions(x=>x.map((v,n)=>n===i?e.target.value:v))} maxLength={100} placeholder={`الخيار ${i+1}`}/>{options.length>2&&<button type="button" onClick={()=>setOptions(x=>x.filter((_,n)=>n!==i))}>×</button>}</div>)}{options.length<6&&<button type="button" className="ghost" onClick={()=>setOptions(x=>[...x,""])}>+ خيار</button>}<button className="primary">نشر الاستطلاع</button></form></Card>
   <Card title="استطلاعات المجتمع" icon="📮" className="wide"><div className="mn-polls">{polls.length?polls.map(p=><article key={p.poll_id}><div className="mn-poll-head"><Link href={`/u/${p.username}`}><Avatar u={p}/><b>{p.display_name}</b></Link><small>{p.total_votes} صوت</small></div><h3>{p.question}</h3><div className="mn-poll-options">{p.options?.map(o=>{const pct=p.total_votes?Math.round(o.votes*100/p.total_votes):0;return <button key={o.id} className={Number(p.my_option_id)===Number(o.id)?"selected":""} onClick={()=>vote(p.post_id,o.id)}><span>{o.label}</span><b>{pct}%</b><i style={{width:`${pct}%`}}/></button>})}</div></article>):<p className="mn-empty">مافيش استطلاعات حتى الآن.</p>}</div></Card>
  </div>
  <div className="mn-grid">
   <Card title="في مثل هذا اليوم" icon="🕰️"><div className="mn-memories">{memories.length?memories.map(m=><article key={m.id}><b>منذ {m.years_ago} سنة</b><p>{m.body||"ذكرى بصورة"}</p><small>{new Date(m.created_at).toLocaleDateString("ar-LY")}</small></article>):<p className="mn-empty">ما عندكش ذكرى في نفس تاريخ اليوم.</p>}</div></Card>
   <Card title="مجموعات المحفوظات" icon="🔖" className="wide"><form className="mn-inline-form" onSubmit={createCollection}><input value={collectionName} onChange={e=>setCollectionName(e.target.value)} maxLength={60} placeholder="اسم مجموعة جديدة"/><button>إنشاء</button></form><div className="mn-collections">{collections.map(c=><button key={c.id} className={String(selectedCollection)===String(c.id)?"active":""} onClick={()=>setSelectedCollection(String(c.id))}><b>{c.name}</b><span>{c.posts_count||0} منشور</span></button>)}</div>{saved.length>0&&<div className="mn-saved-pick"><h3>أضف من محفوظاتك</h3>{saved.slice(0,8).map(p=><article key={p.id}><p>{p.body||"منشور محفوظ"}</p><button onClick={()=>addSaved(p.id)}>إضافة للمجموعة</button></article>)}</div>}</Card>
  </div>
  <Card title="الأصوات والاهتزاز" icon="🔊"><div className="mn-settings"><label><span><b>الأصوات</b><small>Like، إرسال، إشعار، قبول صديق وتفاعل Story</small></span><input type="checkbox" checked={prefs.sound_enabled!==false} onChange={e=>savePrefs({...prefs,sound_enabled:e.target.checked})}/></label><label><span><b>الاهتزاز الخفيف</b><small>يستخدم Haptics المدعومة من الجهاز</small></span><input type="checkbox" checked={prefs.haptics_enabled!==false} onChange={e=>savePrefs({...prefs,haptics_enabled:e.target.checked})}/></label><label><span><b>احترام تقليل الحركة</b><small>يوقف الاهتزاز لما الجهاز يطلب تجربة أهدأ</small></span><input type="checkbox" checked={prefs.respect_reduced_motion!==false} onChange={e=>savePrefs({...prefs,respect_reduced_motion:e.target.checked})}/></label><div className="mn-effect-tests"><button onClick={()=>emitEffect("like")}>تجربة Like</button><button onClick={()=>emitEffect("send")}>تجربة إرسال</button><button onClick={()=>emitEffect("notification")}>تجربة إشعار</button><button onClick={()=>emitEffect("friendAccepted")}>تجربة قبول</button><button onClick={()=>emitEffect("story")}>تجربة Story</button></div></div></Card>
 </div></main>;
}
