"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import AppDialog from "../../AppDialog";
import styles from "./AdvancedAdmin.module.css";

const token=()=>localStorage.getItem("marbo3a_token")||sessionStorage.getItem("marbo3a_token")||"";
async function api(path,options={}){const t=token(),headers={...(options.headers||{}),...(t?{"x-marbo3a-session-mode":"cookie"}:{})};if(options.body)headers["content-type"]="application/json";const r=await fetch(path,{...options,headers,credentials:"same-origin",cache:"no-store"}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"REQUEST_FAILED");return d}
const nf=v=>Number(v||0).toLocaleString("en-US");
const dt=v=>v?new Date(v).toLocaleString("ar-LY"):"-";
const labels={
 registration_enabled:"التسجيل الجديد",login_rate_limit_15m:"محاولات الدخول / 15 دقيقة",captcha_escalation_enabled:"CAPTCHA عند الاشتباه",captcha_escalation_threshold:"عتبة CAPTCHA",new_account_restrictions_enabled:"قيود الحسابات الجديدة",reports_limit_per_hour:"البلاغات / ساعة",friend_requests_limit_per_hour:"طلبات الصداقة / ساعة",dm_limit_per_minute:"الرسائل الخاصة / دقيقة",
 post_limit_per_hour:"المنشورات / ساعة",comment_limit_per_hour:"التعليقات / ساعة",story_lifetime_hours:"عمر الستوري بالساعات",upload_max_mb:"حد الرفع العام MB",upload_max_image_mb:"حد الصور MB",upload_max_video_mb:"حد الفيديو MB",upload_max_audio_mb:"حد الصوت MB",allowed_media_types:"أنواع الوسائط المسموحة",pinned_post_limit:"حد المنشورات المثبتة",
 rooms_enabled:"الغرف",room_create_limit_per_day:"إنشاء الغرف / يوم",room_default_max_members:"السعة الافتراضية للغرفة",room_max_members_cap:"أقصى سعة للغرفة",room_invite_limit_per_hour:"دعوات الغرف / ساعة",voice_participant_max:"أقصى مشاركين بالصوت",
 live_create_limit_per_hour:"بدء Live / ساعة",live_max_viewers:"أقصى مشاهدي Live",live_default_slow_mode_seconds:"Slow mode الافتراضي بالثواني",
 maintenance_mode:"وضع الصيانة",maintenance_message:"رسالة الصيانة",maintenance_eta_minutes:"مدة الصيانة التقديرية بالدقائق",site_font:"خط الموقع",
 engagement:"التفاعل M/N",map:"الخريطة",calls:"المكالمات",live:"البث المباشر",voice_rooms:"الغرف الصوتية",guest_explore:"تصفح الزوار",push:"Push Notifications"
};
const groupLabels={security:"الأمان ومكافحة الإساءة",content:"المحتوى والرفع",rooms:"الغرف والصوت",realtime:"المكالمات والبث",platform:"المنصة والصيانة"};
const modLabels={posts:"المنشورات",images:"الصور",stories:"الستوريات",comments:"التعليقات",rooms:"الغرف",reports:"البلاغات",reported_messages:"الرسائل الخاصة المُبلّغ عنها"};
const anomalyLabels={registration_spike:"ارتفاع التسجيلات",error_spike:"ارتفاع الأخطاء",login_anomaly:"محاولات دخول غير طبيعية",room_spam:"إنشاء غرف بشكل غير طبيعي",abuse_reports:"بلاغات إساءة متكررة"};

export default function AdvancedAdmin(){
 const[tab,setTab]=useState("analytics"),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const[analytics,setAnalytics]=useState(null),[users,setUsers]=useState([]),[q,setQ]=useState("");
 const[modType,setModType]=useState("reports"),[modItems,setModItems]=useState([]),[settings,setSettings]=useState({}),[features,setFeatures]=useState([]),[schema,setSchema]=useState({}),[operations,setOperations]=useState(null),[controlReason,setControlReason]=useState("");
 const[audit,setAudit]=useState([]),[alerts,setAlerts]=useState([]),[dialog,setDialog]=useState(null),[dialogReason,setDialogReason]=useState(""),[messageContext,setMessageContext]=useState(null);
 const stats=useMemo(()=>analytics?[['تسجيلات اليوم',analytics.registrations?.today],['تسجيلات 7 أيام',analytics.registrations?.week],['تسجيلات 30 يوم',analytics.registrations?.month],['نشطون 30 يوم',analytics.users?.active],['غير نشطين',analytics.users?.inactive],['دخول اليوم',analytics.logins?.today],['منشورات اليوم',analytics.posts?.today],['رسائل اليوم',analytics.messages?.today],['غرف جديدة اليوم',analytics.rooms?.today],['تفاعلات اليوم',analytics.reactions?.today],['مستخدمون عائدون',analytics.returningUsers],['متوسط الجلسة',`${Math.round(Number(analytics.averageSessionSeconds||0)/60)} د`]]:[],[analytics]);
 async function run(fn){setLoading(true);setError("");try{await fn()}catch(e){setError(e.message||"REQUEST_FAILED")}finally{setLoading(false)}}
 async function loadAnalytics(){setAnalytics((await api("/api/admin/advanced/analytics")).analytics)}
 async function loadUsers(){setUsers((await api(`/api/admin/advanced/users?q=${encodeURIComponent(q.trim())}`)).users||[])}
 async function loadModeration(){setModItems((await api(`/api/admin/advanced/moderation?type=${encodeURIComponent(modType)}&q=${encodeURIComponent(q.trim())}`)).items||[])}
 async function loadSettings(){const[d,o]=await Promise.all([api("/api/admin/advanced/settings"),api("/api/admin/operations")]);setSettings(d.settings||{});setFeatures(d.features||[]);setSchema(d.schema||{});setOperations(o.operations||null)}
 async function loadAudit(){setAudit((await api(`/api/admin/advanced/audit?q=${encodeURIComponent(q.trim())}&limit=150`)).audit||[])}
 async function loadAlerts(){setAlerts((await api("/api/admin/advanced/anomalies")).alerts||[])}
 async function refresh(){await run(async()=>{if(tab==="analytics")await loadAnalytics();if(tab==="users")await loadUsers();if(tab==="moderation")await loadModeration();if(tab==="controls")await loadSettings();if(tab==="audit")await loadAudit();if(tab==="alerts")await loadAlerts()})}
 useEffect(()=>{if(!token()){location.replace("/");return}refresh()},[tab,modType]);
 async function saveSetting(key,value){if(controlReason.trim().length<3){setError("اكتب سبب التعديل قبل الحفظ");return}await run(async()=>{await api("/api/admin/advanced/settings",{method:"PATCH",body:JSON.stringify({key,value,reason:controlReason.trim()})});if(key==="site_font")window.dispatchEvent(new CustomEvent("marbo3a:site-font",{detail:{font:value}}));await loadSettings()})}
 async function toggleFeature(feature){if(controlReason.trim().length<3){setError("اكتب سبب التعديل قبل تغيير Feature Flag");return}await run(async()=>{await api(`/api/admin/advanced/features/${feature.key}`,{method:"PATCH",body:JSON.stringify({enabled:!feature.enabled,reason:controlReason.trim()})});await loadSettings()})}
 function askModerate(type,item){setDialogReason("");setDialog({kind:"moderate",type,item})}
 function askMessage(item){setDialogReason("");setDialog({kind:"message",item})}
 function askAck(item){setDialogReason("");setDialog({kind:"ack",item})}
 async function confirmDialog(){if(dialogReason.trim().length<3){setError("السبب مطلوب للتدقيق");return}await run(async()=>{if(dialog.kind==="moderate"){const singular={posts:"post",images:"image",stories:"story",comments:"comment",rooms:"room"}[dialog.type];await api(`/api/admin/advanced/moderation/${singular}/${dialog.item.id}/action`,{method:"POST",body:JSON.stringify({reason:dialogReason.trim()})});setDialog(null);await loadModeration()}else if(dialog.kind==="message"){const d=await api(`/api/admin/advanced/reported-messages/${dialog.item.report_id}?reason=${encodeURIComponent(dialogReason.trim())}`);setMessageContext(d.context);setDialog(null)}else if(dialog.kind==="ack"){await api(`/api/admin/advanced/anomalies/${dialog.item.id}/ack`,{method:"POST",body:JSON.stringify({reason:dialogReason.trim()})});setDialog(null);await loadAlerts()}})}
 function settingEditor(key,item){
  const spec=schema[key]||{},value=item?.value;
  if(spec.type==="boolean"||typeof value==="boolean")return <button className={value?styles.on:styles.off} onClick={()=>saveSetting(key,!value)}>{value?"مفعّل":"متوقف"}</button>;
  if(spec.type==="enum")return <div className={styles.numberControl}><select key={`${key}-${value}`} defaultValue={value}>{(spec.values||[]).map(v=><option key={v} value={v}>{v}</option>)}</select><button onClick={e=>saveSetting(key,e.currentTarget.previousSibling.value)}>حفظ</button></div>;
  if(spec.type==="string_array")return <div className={styles.numberControl}><input key={`${key}-${JSON.stringify(value)}`} type="text" defaultValue={(Array.isArray(value)?value:[]).join(", ")} /><button onClick={e=>saveSetting(key,e.currentTarget.previousSibling.value.split(",").map(x=>x.trim()).filter(Boolean))}>حفظ</button></div>;
  if(spec.type==="string")return <div className={styles.numberControl}><input key={`${key}-${value}`} type="text" maxLength={spec.maxLength||240} defaultValue={value||""}/><button onClick={e=>saveSetting(key,e.currentTarget.previousSibling.value)}>حفظ</button></div>;
  return <div className={styles.numberControl}><input key={`${key}-${value}`} type="number" min={spec.min??0} max={spec.max??100000} defaultValue={Number(value??spec.default??0)} onKeyDown={e=>{if(e.key==="Enter")saveSetting(key,Number(e.currentTarget.value))}}/><button onClick={e=>saveSetting(key,Number(e.currentTarget.previousSibling.value))}>حفظ</button></div>;
 }
 const groupedSettings=Object.entries(settings).reduce((acc,[key,item])=>{const group=schema[key]?.group||"platform";(acc[group]||=[]).push([key,item]);return acc},{});
 const maxHour=Math.max(1,...(analytics?.peakHours||[]).map(x=>Number(x.views||0))),maxDay=Math.max(1,...(analytics?.topDays||[]).map(x=>Number(x.views||0)));
 return <main className={styles.page} dir="rtl">
  <header className={styles.header}><div><small>GROUP O · ADVANCED ADMIN</small><h1>الإدارة المتقدمة</h1><p>تحليلات، إشراف، مفاتيح تشغيل، سجل تغييرات وتنبيهات غير طبيعية — بدون تصفح عشوائي للرسائل الخاصة.</p></div><div className={styles.headerActions}><button onClick={refresh} disabled={loading}>تحديث</button><Link href="/admin">مركز الإدارة</Link><Link href="/home">مربوعة</Link></div></header>
  <nav className={styles.tabs}>{[["analytics","التحليلات"],["users","بحث المستخدمين"],["moderation","الإشراف"],["controls","التحكم"],["audit","Audit"],["alerts","التنبيهات"]].map(([k,l])=><button key={k} className={tab===k?styles.active:""} onClick={()=>{setQ("");setTab(k)}}>{l}</button>)}</nav>
  {error&&<div className={styles.error} role="alert">{error}</div>}{loading&&<div className={styles.loading}>جاري التحديث...</div>}
  {tab==="analytics"&&analytics&&<><section className={styles.stats}>{stats.map(([l,v])=><article key={l}><b>{typeof v==="string"?v:nf(v)}</b><span>{l}</span></article>)}</section><section className={styles.analyticsGrid}><article><h3>الجنس</h3><div className={styles.bigPair}><span><b>{nf(analytics.gender?.male)}</b> رجال</span><span><b>{nf(analytics.gender?.female)}</b> نساء</span></div></article><article><h3>إجمالي النشاط</h3><div className={styles.compactList}><span>المنشورات <b>{nf(analytics.posts?.total)}</b></span><span>الرسائل <b>{nf(analytics.messages?.total)}</b></span><span>الغرف <b>{nf(analytics.rooms?.total)}</b></span><span>التفاعلات <b>{nf(analytics.reactions?.total)}</b></span></div></article><article className={styles.wide}><h3>ساعات الذروة — آخر 30 يوم</h3><div className={styles.bars}>{(analytics.peakHours||[]).map(x=><div key={x.hour}><span>{String(x.hour).padStart(2,"0")}:00</span><i style={{width:`${Math.max(4,Number(x.views)*100/maxHour)}%`}}/><b>{nf(x.views)}</b></div>)}{!analytics.peakHours?.length&&<p>البيانات تبدأ تتجمع من هذه النسخة.</p>}</div></article><article className={styles.wide}><h3>أكثر الأيام نشاطًا</h3><div className={styles.bars}>{(analytics.topDays||[]).map(x=><div key={x.day}><span>{String(x.day).slice(0,10)}</span><i style={{width:`${Math.max(4,Number(x.views)*100/maxDay)}%`}}/><b>{nf(x.views)}</b></div>)}{!analytics.topDays?.length&&<p>لا توجد بيانات كافية بعد.</p>}</div></article><article className={styles.wide}><h3>أكثر الصفحات زيارة</h3><div className={styles.table}>{(analytics.topPages||[]).map(x=><div key={x.path}><code>{x.path}</code><span>{nf(x.views)} مشاهدة</span><small>{nf(x.sessions)} جلسة</small></div>)}{!analytics.topPages?.length&&<p>القياس يبدأ من نشر Group O.</p>}</div></article></section></>}
  {tab==="users"&&<><div className={styles.toolbar}><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&run(loadUsers)} placeholder="الاسم، @username، ID أو البريد"/><button onClick={()=>run(loadUsers)}>بحث</button></div><section className={styles.list}>{users.map(u=><article key={u.id}><div><b>{u.display_name||u.username}</b><span>@{u.username} · ID {u.id}</span><small>{u.email} · {u.gender} · آخر ظهور {dt(u.last_seen_at)}</small></div><div><span className={styles.pill}>{u.role}</span><span className={styles.pill}>{u.account_status}</span></div></article>)}{!users.length&&<p>لا توجد نتائج.</p>}</section></>}
  {tab==="moderation"&&<><div className={styles.toolbar}><select value={modType} onChange={e=>setModType(e.target.value)}>{Object.entries(modLabels).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select><input value={q} onChange={e=>setQ(e.target.value)} placeholder="بحث داخل القسم" onKeyDown={e=>e.key==="Enter"&&run(loadModeration)}/><button onClick={()=>run(loadModeration)}>بحث</button></div>{modType==="reported_messages"&&<div className={styles.policy}>سياسة الخصوصية: لا توجد قائمة بكل الرسائل الخاصة. يظهر فقط ما تم الإبلاغ عنه، وفتح محتوى الرسالة يحتاج سببًا ويُسجل في Audit.</div>}<section className={styles.list}>{modItems.map((x,i)=><article key={x.id||x.report_id||i}><div><b>{x.name||x.display_name||x.username||x.reason||x.body?.slice(0,80)||x.text_body?.slice(0,80)||`#${x.id||x.report_id}`}</b><span>{x.username?`@${x.username}`:x.owner_username?`@${x.owner_username}`:x.sender_username?`@${x.sender_username}`:""} {x.status?`· ${x.status}`:""}</span><small>{dt(x.created_at||x.message_created_at)} {x.deleted_at?"· محذوف":""}</small>{x.image_url&&<a href={x.image_url} target="_blank" rel="noreferrer">فتح الصورة</a>}</div>{["posts","images","stories","comments","rooms"].includes(modType)&&<button className={styles.danger} onClick={()=>askModerate(modType,x)}>إزالة/تقييد</button>}{modType==="reported_messages"&&<button onClick={()=>askMessage(x)}>فتح سياق البلاغ</button>}</article>)}{!modItems.length&&<p>لا توجد عناصر.</p>}</section>{messageContext&&<section className={styles.privateContext}><div><h3>سياق رسالة مُبلّغ عنها</h3><button onClick={()=>setMessageContext(null)}>إغلاق</button></div><p>{messageContext.body||"رسالة محذوفة"}</p><small>Report #{messageContext.report_id} · Message #{messageContext.message_id} · Sender @{messageContext.sender_username||messageContext.sender_id}</small></section>}</>}
  {tab==="controls"&&<><div className={styles.policy}><b>كل تغيير هنا يُسجل Before / After / Admin / Time / Reason، والحدود تتحقق في الـBackend.</b><input value={controlReason} onChange={e=>setControlReason(e.target.value)} placeholder="سبب التغيير — مطلوب"/></div>{operations&&<section className={styles.stats}><article><b>{operations.database?.ok?"OK":"FAIL"}</b><span>Database</span></article><article><b>{operations.redis?.ok?"OK":"FAIL"}</b><span>Redis</span></article><article><b>{operations.turn?.status||"unknown"}</b><span>TURN</span></article><article><b>{operations.storage?.driver||"unknown"}</b><span>Storage</span></article><article><b>{operations.backup?.lastSuccessAt?dt(operations.backup.lastSuccessAt):"غير موثق"}</b><span>آخر Backup ناجح</span></article><article><b>{operations.restore?.lastVerifiedAt?dt(operations.restore.lastVerifiedAt):"غير موثق"}</b><span>آخر Restore تحقق</span></article><article><b>{operations.release?.known?String(operations.release.sha).slice(0,12):"unknown"}</b><span>Release SHA</span></article></section>}<section className={styles.controls}>{Object.entries(groupedSettings).map(([group,items])=><div key={group}><h2>{groupLabels[group]||group}</h2>{items.map(([key,item])=><article key={key}><div><b>{labels[key]||key}</b><small>{item.description}</small></div>{settingEditor(key,item)}</article>)}</div>)}<h2>Feature Flags</h2>{features.map(f=><article key={f.key}><div><b>{labels[f.key]||f.key}</b><small>{f.description}</small></div><button className={f.enabled?styles.on:styles.off} onClick={()=>toggleFeature(f)}>{f.enabled?"ON":"OFF"}</button></article>)}</section></>}
  {tab==="audit"&&<><div className={styles.toolbar}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="الإجراء، السبب، المستخدم أو ID" onKeyDown={e=>e.key==="Enter"&&run(loadAudit)}/><button onClick={()=>run(loadAudit)}>بحث</button></div><section className={styles.audit}>{audit.map(a=><article key={a.id}><div><b>{a.action}</b><span>{a.entity_type} {a.entity_id?`#${a.entity_id}`:""}</span><small>@{a.admin_username||"system"} · {dt(a.created_at)}</small><p>{a.reason||"بدون سبب"}</p></div><details><summary>Before / After</summary><pre>{JSON.stringify({before:a.before_state,after:a.after_state},null,2)}</pre></details></article>)}{!audit.length&&<p>لا توجد تغييرات مسجلة.</p>}</section></>}
  {tab==="alerts"&&<section className={styles.alerts}>{alerts.map(a=><article key={a.id} className={a.severity==="critical"?styles.critical:""}><div><b>{anomalyLabels[a.alert_type]||a.alert_type}</b><span>{a.status} · {a.severity}</span><small>{dt(a.detected_at)}</small><p>القيمة {nf(a.metric_value)} · العتبة {nf(a.threshold_value)}</p></div>{a.status==="open"&&<button onClick={()=>askAck(a)}>تمت المراجعة</button>}</article>)}{!alerts.length&&<p>لا توجد تنبيهات غير طبيعية حاليًا.</p>}</section>}
  <AppDialog open={Boolean(dialog)} title={dialog?.kind==="moderate"?"تأكيد إجراء الإشراف":dialog?.kind==="message"?"فتح رسالة خاصة مُبلّغ عنها":"تأكيد مراجعة التنبيه"} description={dialog?.kind==="message"?"لن يتم فتح الرسالة إلا ضمن البلاغ المحدد، وسيتم تسجيل سبب الوصول في Audit.":"اكتب سببًا واضحًا؛ سيُحفظ مع الإجراء."} input value={dialogReason} onValueChange={setDialogReason} danger={dialog?.kind==="moderate"} confirmLabel={dialog?.kind==="message"?"فتح السياق":"تأكيد"} onClose={()=>setDialog(null)} onConfirm={confirmDialog}/>
 </main>
}
