"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import Icon from "../../Icon";
import {uploadMedia} from "../../imageTools";
const token=()=>localStorage.getItem("marbo3a_token")||sessionStorage.getItem("marbo3a_token")||"";
async function api(path,options={}){const headers={authorization:`Bearer ${token()}`,...(options.headers||{})};if(options.body&&!(options.body instanceof FormData))headers["content-type"]="application/json";const r=await fetch(path,{...options,headers});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"REQUEST_FAILED");return d;}
const human=e=>({FILE_TOO_LARGE:"الصورة ما زالت كبيرة جدًا بعد الضغط",UNSUPPORTED_FILE:"نوع الصورة غير مدعوم",HEIC_DECODE_FAILED:"تعذر تجهيز صورة الآيفون. جرّب حفظها كـ JPG أو لقطة شاشة.",IMAGE_PROCESS_FAILED:"تعذر تجهيز الصورة قبل الرفع",UPLOAD_FAILED:"تعذر رفع الصورة",REQUEST_FAILED:"تعذر تنفيذ العملية"}[e]||e);
export default function EditProfile(){const router=useRouter(),[form,setForm]=useState({bio:"",avatarUrl:"",coverUrl:"",city:"",sharePrecise:false,latitude:null,longitude:null}),[status,setStatus]=useState(""),[uploading,setUploading]=useState("");useEffect(()=>{api("/api/profile/extended").then(d=>setForm({bio:d.user.bio||"",avatarUrl:d.user.avatar_url||"",coverUrl:d.user.cover_url||"",city:d.location?.city||"",sharePrecise:Boolean(d.location?.share_precise),latitude:d.location?.latitude??null,longitude:d.location?.longitude??null})).catch(e=>setStatus(human(e.message)))},[]);async function upload(file,field){if(!file)return;setUploading(field);setStatus("جاري تجهيز الصورة...");try{const d=await uploadMedia(file,token(),{compress:true,onState:s=>setStatus(s==="processing"?"جاري ضغط الصورة بجودة عالية...":s==="uploading"?"جاري رفع الصورة...":"تم تجهيز الصورة")});setForm(f=>({...f,[field]:d.file.url}));setStatus("تم رفع الصورة بنجاح") }catch(e){setStatus(human(e.message))}finally{setUploading("")}}function locate(){if(!navigator.geolocation)return setStatus("تحديد الموقع غير مدعوم على هذا الجهاز");setStatus("جاري تحديد موقعك...");navigator.geolocation.getCurrentPosition(p=>{setForm(f=>({...f,sharePrecise:true,latitude:p.coords.latitude,longitude:p.coords.longitude}));setStatus("تم حفظ الموقع في النموذج. اضغط حفظ لتأكيده.")},()=>setStatus("لم نقدر نوصل للموقع. تأكد من إعطاء الإذن."),{enableHighAccuracy:true,timeout:12000,maximumAge:60000})}async function save(e){e.preventDefault();try{await api("/api/profile/extended",{method:"PATCH",body:JSON.stringify(form)});setStatus("تم حفظ الملف الشخصي") }catch(e){setStatus(human(e.message))}}function goBack(){if(window.history.length>1)router.back();else router.push("/home")}
return <main className="social-page" dir="rtl"><div className="social-shell"><header className="sf-top"><a href="/home" className="sf-brand"><img src="/logo.svg" alt="مربوعة"/><span><b>تعديل الملف</b><small>MARBO3A</small></span></a><button type="button" className="map-home" onClick={goBack} aria-label="رجوع"><Icon name="arrowRight"/></button></header><section className="feature-page"><section className="feature-card">{status&&<div className="settings-status" role="status">{status}</div>}<form className="feature-grid" onSubmit={save}><div className="feature-block upload-box"><h3>الصورة الشخصية</h3>{form.avatarUrl?<img src={form.avatarUrl} alt="الصورة الشخصية الحالية" style={{width:90,height:90,borderRadius:24,objectFit:"cover"}}/>:<div className="profile-media-empty"><Icon name="user"/><span>ما فيش صورة شخصية</span></div>}<label className="profile-file-label"><Icon name="image"/> {uploading==="avatarUrl"?"جاري الرفع...":"اختيار صورة"}<input type="file" hidden accept="image/*" disabled={Boolean(uploading)} onChange={e=>{const f=e.target.files?.[0];e.target.value="";upload(f,"avatarUrl")}}/></label><h3>صورة الغلاف</h3>{form.coverUrl?<img src={form.coverUrl} alt="صورة الغلاف الحالية" style={{width:"100%",height:120,borderRadius:16,objectFit:"cover"}}/>:<div className="profile-cover-empty"><Icon name="image"/><span>ما فيش صورة غلاف</span></div>}<label className="profile-file-label"><Icon name="image"/> {uploading==="coverUrl"?"جاري الرفع...":"اختيار غلاف"}<input type="file" hidden accept="image/*" disabled={Boolean(uploading)} onChange={e=>{const f=e.target.files?.[0];e.target.value="";upload(f,"coverUrl")}}/></label><small className="profile-upload-note">الصور الكبيرة وصور الآيفون يتم تحويلها وضغطها تلقائيًا قبل الرفع.</small></div><div className="feature-block"><h3>البيانات</h3><label className="profile-field-label">نبذة عنك<textarea value={form.bio} onChange={e=>setForm({...form,bio:e.target.value})} maxLength={160} placeholder="اكتب نبذة قصيرة عنك"/></label><label className="profile-field-label">المدينة<input value={form.city} onChange={e=>setForm({...form,city:e.target.value})} maxLength={80} placeholder="مثال: طرابلس"/></label><div className="location-choice"><label><span>الظهور بموقع أدق على خريطة مربوعة</span><input aria-label="مشاركة الموقع الدقيق" type="checkbox" checked={form.sharePrecise} onChange={e=>setForm({...form,sharePrecise:e.target.checked})}/></label><button type="button" onClick={locate}><Icon name="map"/> استخدام موقعي الحالي</button><small>{form.sharePrecise&&form.latitude?"الموقع الدقيق محفوظ بإذنك. تقدر تلغي الخيار في أي وقت.":"بدون هذا الخيار نظهرك بشكل تقريبي داخل مدينتك فقط."}</small></div><button type="submit">حفظ</button></div></form></section></section></div></main>}
