"use client";
import {useEffect,useMemo,useState} from "react";
import Icon from "../Icon";
const token=()=>localStorage.getItem("marbo3a_token")||sessionStorage.getItem("marbo3a_token")||"";
async function api(path,options={}){const headers={authorization:`Bearer ${token()}`,...(options.headers||{})};const r=await fetch(path,{...options,headers,cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"REQUEST_FAILED");return d}
const when=v=>{const t=new Date(v).getTime();if(!Number.isFinite(t))return"";const s=Math.max(0,Math.floor((Date.now()-t)/1000));if(s<60)return"الآن";if(s<3600)return`${Math.floor(s/60)} د`;if(s<86400)return`${Math.floor(s/3600)} س`;if(s<172800)return"أمس";if(s<604800)return`${Math.floor(s/86400)} ي`;const d=new Date(t);return`${d.getDate()}/${d.getMonth()+1}`};
export default function Messages(){
  const[chats,setChats]=useState([]),[error,setError]=useState(""),[loading,setLoading]=useState(true),[q,setQ]=useState("");
  async function load(silent=false){try{const d=await api("/api/chats");setChats(d.chats||[]);setError("")}catch{if(!silent)setError("تعذر تحميل المحادثات")}finally{if(!silent)setLoading(false)}}
  useEffect(()=>{if(!token()){location.href="/";return}let busy=false;const refresh=async(silent=true)=>{if(busy||document.visibilityState!=="visible")return;busy=true;try{await load(silent)}finally{busy=false}};refresh(false);const timer=setInterval(()=>refresh(true),7000);const onVisible=()=>document.visibilityState==="visible"&&refresh(true);document.addEventListener("visibilitychange",onVisible);return()=>{clearInterval(timer);document.removeEventListener("visibilitychange",onVisible)}},[]);
  const visible=useMemo(()=>{const needle=q.trim().toLowerCase();if(!needle)return chats;return chats.filter(c=>`${c.display_name||""} ${c.username||""} ${c.last_message||""}`.toLowerCase().includes(needle))},[chats,q]);
  const unread=chats.reduce((n,c)=>n+Number(c.unread_count||0),0);
  return <main className="social-page" dir="rtl"><div className="social-shell"><header className="sf-top"><a className="sf-brand" href="/home"><img src="/logo.svg" alt="مربوعة"/><span><b>الرسائل</b><small>{unread?`${unread} غير مقروء`:"MARBO3A"}</small></span></a><a href="/home" className="sf-back" aria-label="الرئيسية"><Icon name="home"/></a></header><section className="sf-layout"><aside className="sf-side"><nav><a href="/home"><Icon name="home"/>الرئيسية</a><a className="active" href="/messages"><Icon name="message"/>الرسائل</a><a href="/friends"><Icon name="users"/>الأصحاب</a><a href="/rooms"><Icon name="hash"/>الغرف</a><a href="/search"><Icon name="search"/>البحث</a></nav></aside><section className="sf-main"><div className="sf-panel sf-inbox"><div className="sf-inbox-title"><div><h2>محادثاتك</h2><small>{chats.length} محادثة{unread?` • ${unread} غير مقروء`:""}</small></div><a href="/friends" className="sf-new-chat"><Icon name="users"/>محادثة جديدة</a></div><div className="sf-search sf-inbox-search"><Icon name="search"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث في المحادثات..."/></div>{error&&<div className="sf-alert" onClick={()=>load()}>{error} — اضغط لإعادة المحاولة</div>}{loading&&<div className="sf-skeleton">جاري تحميل المحادثات...</div>}{!loading&&!visible.length&&!error&&<div className="sf-empty"><Icon name="message"/><h2>{q?"ما لقيناش محادثة":"ما عندكش محادثات توا"}</h2><p>{q?"جرّب اسم أو كلمة ثانية.":"ابدأ من قائمة الأصحاب."}</p></div>}{visible.map(c=><a className={`sf-chat-row ${Number(c.unread_count||0)>0?"unread":""}`} key={c.id} href={`/chat/${c.id}`}>{c.avatar_url?<img className="sf-avatar" src={c.avatar_url} alt=""/>:<div className="sf-avatar sf-avatar-fallback">{c.display_name?.[0]||"م"}</div>}<div><div className="sf-chat-row-head"><b>{c.display_name}</b><time title={c.last_message_at?new Date(c.last_message_at).toLocaleString("ar-LY"):""}>{when(c.last_message_at||c.updated_at)}</time></div><small>@{c.username}</small><p>{c.last_message||"ابدأ المحادثة"}</p></div>{Number(c.unread_count||0)>0?<span className="chat-unread-badge">{Number(c.unread_count)}</span>:<Icon name="message"/>}</a>)}</div></section></section></div></main>;
}
